### ISSUE TITLE
Time left in book will show already listened to duration. 

### ISSUE THREAD

**Issue by ChiefMedicalOfficer** [advplyr/audiobookshelf-app#100]
### Steps to reproduce

1. Pause book
2. Close app 
3. Open app

### Expected behaviour
- Tell us what should happen

'time left' should show actual time left in book

### Actual behaviour
- Tell us what happens

'time left' shows the duration on the book that has been listened to already if no speed up has been applied. 

Example: if I have played 1 hour of a book at 1.5 the 'time left' will briefly show 1:30:00 then show the actual time I have left in a book -5:00:00 (for instance). (I'll try and add a screenshot). 

### Environment data

Audiobookshelf Version:

- [0.9.40-beta] Android App? But has happened on last couple of versions at least. 

#### Android Issue
Android version: 8

Device model: Galaxy S7

Stock or customized system:

Stock

**Comment by ChiefMedicalOfficer** [comment]
Example image.

![20220208_190804.jpg](https://user-images.githubusercontent.com/11256455/153058565-1b4c7b7a-e4c5-4f44-8bea-452c8eb8956b.jpg)

**Comment by advplyr** [comment]
I'm not sure what you mean, what are you expecting to see in the screenshot?

**Comment by ChiefMedicalOfficer** [comment]
The screenshot was to show the issue because it was hard to explain. It has been resolved now.
