### ISSUE TITLE
Connect to server failed:  java.security.cert.CertPathValidatorExeption

### ISSUE THREAD

**Issue by swedishstyle** [advplyr/audiobookshelf-app#1001]
### Steps to reproduce

1. Attempt to connect to audiobookshelf server that was working yesterday
2. ??

### Expected behaviour
- I should be able to connect

### Actual behaviour
- "Failed to contact server (Error: java.security.cert.CertPathValidatorExeption)
Trust anchor for certification path not found

Note: This only occurs when attempting to connect to the server via a reverse proxy address behind NGINX. This worked as of yesterday, and no updates to the server have been made since then. I can still access it without issue on the web using the reverse proxy.

### Environment data

Audiobookshelf Version:

- [ X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.70-beta

Device model:
Samsung S20FE

Stock or customized system:
Stock

#### iOS Issue
iOS Version:
N/A

iPhone model:
N/A

**Comment by DieselTech** [comment]
Something went wrong with your reverse proxy. You can try using a SSL checking service like SSL Labs to see if there is an underlying issue with your setup / RP

https://www.ssllabs.com/ssltest/index.html

**Comment by swedishstyle** [comment]
> Something went wrong with your reverse proxy. You can try using a SSL checking service like SSL Labs to see if there is an underlying issue with your setup / RP
> 
> https://www.ssllabs.com/ssltest/index.html


![image](https://github.com/advplyr/audiobookshelf-app/assets/32089115/4df9696f-e27f-423c-a3cd-3e8cb5119850)

I'm not sure where to look exactly, but nothing jumps out as obviously wrong for my proxy site. If you can tell me which section I should look at, I'd be happy to check it out

**Comment by dziurka** [comment]
Unfortunately I have the same problem. SSL works without any problems in the browser, but in the application it throws the same error.

**Comment by advplyr** [comment]
Is this resolved? I'm not sure how this is a bug with Abs

**Comment by swedishstyle** [comment]
Oh apologies, yes it was a misconfiguration on my end! Bloody DNS :)

**Comment by ociaw** [comment]
I just encountered this issue myself. I would get this error on the android app, but in Firefox it worked fine. The server is behind an nginx reverse proxy, with a certificate from Let's Encrypt. I believe this was caused by missing intermediate certificates (AFAIK Firefox has its own certificate store, so would not necessarily need to have the intermediate certificates provided by nginx).

I solved my issue by changing the `ssl certificate` directive in nginx from just `cert.pem` to `fullchain.pem`.

**Comment by pjones112000** [comment]
> Oh apologies, yes it was a misconfiguration on my end! Bloody DNS :)

What was the solution?  I'm suddenly having problems with the Android client with this error and as far as I know nothing changed.

**Comment by swedishstyle** [comment]
> > Oh apologies, yes it was a misconfiguration on my end! Bloody DNS :)
> 
> What was the solution? I'm suddenly having problems with the Android client with this error and as far as I know nothing changed.

Sorry, I can't remember exactly, but mine was pretty distinct. I think I had some sort of weird loop setup with my DNS from memory. Wish I could be of more help!
