### ISSUE TITLE
Show tags on audiobook view

### ISSUE THREAD

**Issue by PulsarFTW** [advplyr/audiobookshelf-app#1014]
It would be great to see the tags underneath the genres on the book page like they do on the website:

![Screenshot 2023-12-28 at 00 14 41](https://github.com/advplyr/audiobookshelf-app/assets/115924048/cb08169c-47d1-47e4-be3b-2d91fc0c05ad)

I am not sure if they display on android as I only have iOS to test on. 

Thanks!

**Comment by advplyr** [comment]
Added in [v0.9.71-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.71-beta)
