### ISSUE TITLE
Add option for epub ereader to use single page on tablets

### ISSUE THREAD

**Issue by darthrater78** [advplyr/audiobookshelf-app#1018]
### Steps to reproduce

1. Open app on Android tablet
2. Open ebook ![PXL_20231231_234546519.jpg](https://github.com/advplyr/audiobookshelf-app/assets/94141126/29f6a696-1ed7-41ef-b2e9-f63dad49b236)

### Expected behaviour
- one page should display 

### Actual behaviour
- two pages display split in half 

### Environment data

Audiobookshelf Version: 2.7.1

- [ x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 970 beta

Device model: Lenovo P11

**Comment by advplyr** [comment]
Added in [v0.9.71-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.71-beta)

There is now a setting that you can enable that will switch to single page view
