### ISSUE TITLE
[Bug] Incorrect spacing around commas for genre

### ISSUE THREAD

**Issue by update-freak** [advplyr/audiobookshelf-app#1020]
### Problem
Wrong spacing around commas for genre

### Steps to reproduce

1. Add e.g. "Besser Leben" podcast
2. Check the information in the genre

### Expected behaviour
First the comma and then the space

### Actual behaviour
First the space and then the comma

### Environment data
Audiobookshelf Version: v0.9.70-beta
Android App

#### Android Issue
Android version: 14
Device model: Samsung Galaxy S23
Stock or customized system: Stock ROM

![Screenshot_20240101_111900_Audiobookshelf](https://github.com/advplyr/audiobookshelf-app/assets/40196995/38fde8e8-66c4-45bb-a27d-814eb8b8cb30)

Same as https://github.com/advplyr/audiobookshelf-app/issues/777
Was solved in the past but now the issue is present again for me.

**Comment by advplyr** [comment]
Thanks I fixed this again for the upcoming release

**Comment by advplyr** [comment]
Fixed in [v0.9.71-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.71-beta)
