### ISSUE TITLE
Button touch area too large

### ISSUE THREAD

**Issue by gh0sti** [advplyr/audiobookshelf-app#1021]
### Steps to reproduce

1. Go to settings of ABS on iOS
2. Tap anywhere in the yellow area that I highlighted in screenshots
3. Buttons are toggled when the area of touch should be closer or on the actual button

### Expected behaviour
The buttons should be the only touch area for toggling. 

![image](https://github.com/advplyr/audiobookshelf-app/assets/4202657/b01fbca6-2199-4c57-a5d5-5718fa25bea6)

### Actual behaviour
Any of the area highlighted in the screenshot toggles the buttons

![image](https://github.com/advplyr/audiobookshelf-app/assets/4202657/05f810fd-a323-436b-a4ea-8b08c6867632)

### Environment data

Audiobookshelf Version: 0.9.70/ ABS Server 2.7.1

- [x] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 17.2.1

iPhone model: 15 Pro Max

**Comment by gh0sti** [comment]
@advplyr  thanks for looking at this!

**Comment by advplyr** [comment]
Fixed in [0.9.72-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.72-beta)
