### ISSUE TITLE
Download stuck at various percentages on android app

### ISSUE THREAD

**Issue by dkomljenovic2502** [advplyr/audiobookshelf-app#1024]
### Steps to reproduce

1. Point to audiobookshelf via reverse proxy, or directly
2. Try to download the audio book
3. Infinite stuck on download on different percentages
4. restart the phone or app, same behavior it gets to e.g. 5% total and stops again

### Expected behaviour
- It should download the book

### Actual behaviour
- Gets stuck at random percentages 

### Environment data

Audiobookshelf Version:

- [x] Android App 0.9.71-beta

#### Android Issue
Android version:
13
Device model:
Honor 90 - REA-NX9
Samsung S23 ultra
Stock or customized system:
stock

### Additional info

Streaming works normally

#### From docker log from audiobookshelf container:
[2024-01-03 12:21:24.369] INFO: [LibraryItemController] User "dkomljenovic2502" requested file download at "/audiobooks/Dune - Audiobook Collection 2015/01 - Dune Saga/03. Children of Dune.m4b"
[2024-01-03 12:21:24.370] INFO: [LibraryItemController] User "dkomljenovic2502" requested file download at "/audiobooks/Dune - Audiobook Collection 2015/01 - Dune Saga/01. Dune.m4b"
[2024-01-03 12:21:24.379] INFO: [LibraryItemController] User "dkomljenovic2502" requested file download at "/audiobooks/Dune - Audiobook Collection 2015/01 - Dune Saga/02. Dune Messiah.m4b"

**Comment by dkomljenovic2502** [comment]
didn't modify anything at all with the app storage. 
I managed to download some books, but after multiple retries, reboots of server and client... 
Not sure how can i change the folder? and where is the data downloaded? didn't find that option

**Comment by dkomljenovic2502** [comment]
Ok, created a new folder, added permission for usage, it said success, but same behavior even to external storage

**Comment by nichwall** [comment]
It should be going to Internal App Storage if you didn't set anything up. Internal App Storage tends to cause less issues, but doesn't let the data downloaded media be available to other apps.

https://www.audiobookshelf.org/guides/android_app_shared_storage

**Comment by nichwall** [comment]
How big is the book you're downloading? Does it work with smaller files?

Looks like you're downloading multiple Dune books, or at least they're showing up as the same library item (not sure if it's an omnibus or something)

**Comment by advplyr** [comment]
If you don't use the reverse proxy do you still have the issue? Have you tried with other books, maybe some smaller ones?

**Comment by dkomljenovic2502** [comment]
Tried with and without reverse proxy, same behaviour
Now i am trying directly to http://IP:13378, which is directly the exposed audiobookshelf without reverse proxy 

The books are:
![image](https://github.com/advplyr/audiobookshelf-app/assets/44649134/a2750667-90a5-48e6-b105-54fb3c74716c)

Now i tried this
![image](https://github.com/advplyr/audiobookshelf-app/assets/44649134/f516f948-758b-4efe-a2f7-00c80c9419ad)
and this downloaded

**Comment by nichwall** [comment]
How much free space is on your device?

**Comment by dkomljenovic2502** [comment]
180GB free space left...

**Comment by dkomljenovic2502** [comment]
i would say this is not app connected. 
After playing, updating kernel, docker and stuff i would say it is an issue with either the server in docker or my pc...
Other containers don't do stuff like this one. 

When downloading an image the server docker seems to "kill my ethernet"  for few seconds, then continue.. 

The dmesg doesn't have any info when this happens i just realized that my ssh connection hangs, and other stuff which the pc  does stop working for few seconds.
And this only happens when i am downloading from audiobookshelf container, e.g. plex container for streaming which uses more cpu, and bandwidth doesn't do "kill the ethernet"

**Comment by kirarpit** [comment]
I have the same issue here. Downloading keeps hanging at arbitrary percentages. 
I am using a raspberry pi for running the ABS docker container, with my MacBook's hard drive mounted to it where all the audiobooks reside. The setup does work for streaming just fine and I have managed to download some books after repeated tries. But overall it's quite painful.
Is the downloading meant to work in the background once the app is minimized? With my setup it immediately hangs if I minimize the app.

**Comment by kirarpit** [comment]
Sometimes most files download but the other ones are stuck. I think it's socket disconnecting intermittently that causing the issue. But it would be great to have a way to retry the unfinished downloads. I am happy to contribute to this project because it's a great project overall and I really appreciate it. If you could provide some pointers on how we could support such a functionality that'd be great! Cheers!
![Screenshot_20241001-085216](https://github.com/user-attachments/assets/206e31a9-43fc-45ab-a5e0-e4a07c05098a)

**Comment by Astorsoft** [comment]
Any update on the above? I have the exact same issue (audiobookshelf in a container using cosmos cloud on a home server, Android app as well). I usually end up succeeding after some attempts but this is extremely frustrating. Having a way to resume a partial download instead of restarting from scratch would be ideal.

**Comment by kirarpit** [comment]
I moved away from Raspberry Pi to a more powerful system and that resolved the issue for me. It still won't run in background if I minimize the app or resume when I open it back up. However, it doesn't get stuck midway anymore if the screen is kept on.

**Comment by Astorsoft** [comment]
Thanks for the feedback, I don't think performance is the issue here, at least not the only possible cause as my server is quite beefy (corei7, 12gb ram and running on an ssd).

**Comment by ThePrankMonkey** [comment]
I have this issue happen randomly for me. Here's the steps that work for me:

1. I'll restart the container (`docker compose pull && docker compose up -d`)
1. I'll restart the android app.
1. I'll download a different audiobook.
1. I'll download the original audiobook that was failing.

**Comment by stefanroels** [comment]
I also ran into this problem today. For me, the cause of the aborted connection isn't even the main concern. It is the fact that the (android) app does not seem to detect that the connection is disrupted and does not restart/resume the download. 

For me, the abort happens at random moments, so a restart of the download would solve the problem. I can imagine that you would put a limit on the retries, but even retrying the download once (automatically) would help. Additionally, it would also help to retain the downloaded parts so a manual restart of the download would be possible.

**Comment by Vinnecent** [comment]
Facing the same problem. For me it happens every time I put the app in the background for download. If I go in the android settings und force close the app and reset the cache I can start the download again. I just leave the app open when I download something now. Still annoying though as my parents are not tech savy enough to do this on their own.

**Comment by jango** [comment]
> i would say this is not app connected. After playing, updating kernel, docker and stuff i would say it is an issue with either the server in docker or my pc... Other containers don't do stuff like this one.
> 
> When downloading an image the server docker seems to "kill my ethernet" for few seconds, then continue..
> 
> The dmesg doesn't have any info when this happens i just realized that my ssh connection hangs, and other stuff which the pc does stop working for few seconds. And this only happens when i am downloading from audiobookshelf container, e.g. plex container for streaming which uses more cpu, and bandwidth doesn't do "kill the ethernet"

@dkomljenovic2502 do you, by chance host and access audiobookshelf across VLANs? I have experienced the "kill the ethernet" issue after download gets stuck if I run it for a few times and it only happens in a situation where my container is on one VLAN and my client is on a separate VLAN. Seems like there is some sort of flooding issue happening. However, the moment I put them on the same VLAN I am able to download the books with no issues.

**Comment by dkomljenovic2502** [comment]
hi, no wlan in  my case. It is pure "stupid" lan network. upload from pc is 1gbps, and download was from wlan which was max 400mbps, so it shouldn't have bottle necked 
But i changed my mobile phone from honor 90 to samsung s25 ultra and i didn't have problems then.. not sure if something updated or the mobile phone change helped

**Comment by paprika27** [comment]
I have actually been able to reliably get my downloads stuck by adding another book to the queue. So I can download one book at a time and if I wait for it to finish before starting the next, the preparation whatever is running undisturbed until at some point the book is marked as available. but if I start a second book before the first book is completely downloaded (even if it isn't yet prepared), the app reliably gives up with no button to retry or restart.

**Comment by saucedge** [comment]
I also seem to be able to trigger this issue by letting the app lose focus.  If I keep the screen on and the app open, no issues.

**Comment by Weedalf** [comment]
I have the same issue. 
If the display turns off the file that is downloading right now stops. 

Please add functionality to start and restart download of single files. And keep files stored even if not all files are completed. This would fix or work around the problem

**Comment by Tsamsiyu1** [comment]
yeah I have this a lot of times. it happens when you let the app lose focuse or your network has a hickup. if the connection is away for just a millisecond it cancles the download of the file and stays on this percentage. and instead of either contiuing or resetting it to zero and start over with the file it just stops at that percent and does not go any further. only way i know to fix it is close the entire app, open again and try again. but if you have large  audiobooks it is almost impossible to download them over the internet. 
the stream is probably UDP. so the server has no knowlede about how much the client has received. maybe this could be fixed in a future release.

**Comment by andersonimes** [comment]
I have this trouble when I foolishly try to download a book on a questionable connection or close the app during a download. It seems to put the app in a state where it won't download anything anymore. To fix this, I clear the app's cache and storage and re-login. This fixes it. Hope this helps someone. I realize this kind of difficult to reproduce bug is hard to fix, but it is pretty irritating so hoping someone has a breakthrough on it soon!

**Comment by derringer08** [comment]
Running into this whenever I try to queue more than a single book. If I try to download a full series it hangs after downloading one book. The server logs also only show that single book being requested.

**Comment by leogaggl** [comment]
I can not download any book unless the app is in the foreground and the screensaver does not kick in (the app is definitely allowed to run in the background). 

As soon as the screensaver activates or I switch to another app, the download stops.

This behaviour is consistent!

**Comment by jenoe** [comment]
> I can not download any book unless the app is in the foreground and the screensaver does not kick in (the app is definitely allowed to run in the background).
> 
> As soon as the screensaver activates or I switch to another app, the download stops.
> 
> This behaviour is consistent!

I can confirm this behavior unfortunately.

**Comment by The-Nusbaum** [comment]
Just an FYI, allowing unrestricted battery usage  in the background seems to help

**Comment by piwicode** [comment]
I think we should reopen this issue. I can help with investigation if needed.
The service is running in a container behind caddy proxy.

I reproduced the issue from a clean install, it blocks on every attempt after 10 files or so, it is impossible to resume, and if I restart the app the progress is lost.

Server logs:
```
026-01-28 20:52:20.828] INFO: [SocketAuthority] Socket d_HwN8k1kVopMz5lAAAb disconnected from client "admin" after 184686ms (Reason: transport close)                                                             │
026-01-28 21:03:25.318] INFO: [SocketAuthority] Socket Connected to /socket.io oFQ8pYJrbYD3O-JxAAAd 
```

App logs:
```
01/28/2026 21:48:46.946 [INFO] load: AbsLogger plugin initialized
01/28/2026 21:48:47.472 [INFO] mounted: initializing first load (android v0.11.0-beta)
01/28/2026 21:48:47.748 [INFO] mounted: Server not connected, attempt connection
01/28/2026 21:48:47.760 [INFO] attemptConnection: No last server config set
01/28/2026 21:48:47.763 [INFO] mounted: fully initialized
01/28/2026 21:49:18.544 [INFO] mounted: initializing first load (android v0.11.0-beta)
01/28/2026 21:49:18.553 [INFO] mounted: Server connected, init libraries (https://[SERVER_ADDRESS] (admin))
01/28/2026 21:49:18.587 [INFO] initLibraries loading library Livres Audio
01/28/2026 21:49:18.671 [INFO] Calling syncLocalSessions
01/28/2026 21:49:18.674 [INFO] [ApiHandler] syncLocalMediaProgressForUser: Server connection https://[SERVER_ADDRESS] (admin)
01/28/2026 21:49:18.675 [INFO] [ApiHandler] syncLocalMediaProgressForUser: No local media progress to sync
01/28/2026 21:49:18.676 [INFO] syncLocalSessionsWithServer: No saved local playback sessions to send to server.
01/28/2026 21:49:18.681 [INFO] mounted: fully initialized
```

**Comment by ursoos** [comment]
Same thing happens for me. The most frustrating part, the download never resumes.
I delete partially finished download, they again, it gets stuck eventually.

Also it probably leads to different issue: app crashing.
https://github.com/advplyr/audiobookshelf-app/issues/1802

**Comment by dirkson** [comment]
I also have this issue. I can download single books just fine, but the moment it's multiple, the download freezes after the first.

**Comment by breakid** [comment]
> I have this trouble when I foolishly try to download a book on a questionable connection or close the app during a download. It seems to put the app in a state where it won't download anything anymore. To fix this, I clear the app's cache and storage and re-login. This fixes it.

I lost cellular connection while downloading a book, and this fixed it for me. Thanks for sharing!

**Comment by scottp** [comment]
I can't download any books. Gets to 38% and stops. Deleting app and reinstall allows start download again but then fails about same space. My server is on unraid and latest docker and latest Android app. Streaming works great.

**Comment by mattalxndr** [comment]
This is still happening for me. 

- Server: v2.34.0
- Client: v0.12.0-beta

I just tried to download an audiobook so I could play it offline. I left the phone sitting there overnight, downloading, with the app focused. In the morning, there were a couple of MP3s of the list that were stuck at 99% and one that was at a lower percentage. 

My workaround is to use the Create M4B tool and then download that.

**Comment by weardj** [comment]
I'm having the same issue, though I think a drop in connection to the server caused it to get stuck. I wish there was a way of cancelling the downloads to get them to restart.
