### ISSUE TITLE
tile of Authors to small -> name is truncated / ability to change between tile-view and list-view

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf-app#1026]
### Steps to reproduce

1. goto register "Authors" 

### Expected behaviour
- enlarge tile to see more of the author name, it has enough space
- add new view like under Library
![image](https://github.com/advplyr/audiobookshelf-app/assets/72630160/b4798514-e63e-466d-a2e2-71be567b5365)
- Filter "Author without Image 

### Actual behaviour
- name of author is truncated
![image](https://github.com/advplyr/audiobookshelf-app/assets/72630160/52ad273b-4b23-4157-b9e2-fe8317112852)

### Environment data

Audiobookshelf Version:

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Huawei P30

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Updated in [0.9.72-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.72-beta) to show 2 per row and fill the width
