### ISSUE TITLE
Display current position (time) as a constant regardless of playback speed

### ISSUE THREAD

**Issue by gazpachoking** [advplyr/audiobookshelf-app#1028]
### Is your feature request related to a problem? Please describe.
Knowing where I am in a chapter, and translating that to other players (e.g. my Garmin watch) is difficult, as the current position is scaled with the playback speed.

### Describe the solution you'd like
Display the current position in the book/chapter as if the playback speed was 1X. 

### Describe alternatives you've considered
Guess what my position is based on the current playback speed. Change the playback speed to 1X to see the current position, then put it back.

### Additional context
Smart Audiobook Player on Android has this as the default behavior, and I find it to be optimal. I think the remaining time in the book/chapter could still be scaled based on the playback speed so you know how long in realtime is left at the current rate. (That is also how SABP handles it.)

**Comment by advplyr** [comment]
This is how I originally had it but after discussing it in GH and Discord the popular opinion was to have them all scale by playback speed.

Some discussion is here https://github.com/advplyr/audiobookshelf-app/issues/549 where I commented what I still think is true:
> I think in the end it makes more sense to adjust to the current time with the playback speed even though it isn't as functionally useful.

For this reason I think a player setting makes sense so I added one. The default will still be to scale it but you can optionally choose not to. It will scale both elapsed time values on the total and chapter track.

![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/f2d4aa53-0e49-444f-93b0-4d3a557695e0)

**Comment by gazpachoking** [comment]
Oh, excellent. That sounds perfect! Thank you!

**Comment by advplyr** [comment]
Added in [0.9.72-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.72-beta)
