### ISSUE TITLE
Server UI

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf-app#103]
i use this app every day on home and outdoor but change the server from in to out is ... 

its possible to get an UI for changing the server adress? 

if iam at home i dont need to use the external server address and its a little bit faster to use the internal network ip ... and if i have problems on the internet provider > i cant use the app ... on the other way: if iam outdoor i need to use the external server adress ....

**Comment by Budlyte** [comment]
I think you're going to need to be more clear on what you want here. I understand that you are accessing your server externally, probably through port forwarding, and prefer the local address when on the same network. What are you changing when switching networks?

Your router should be doing the hairpin thing and routing back to your LAN if you're straight requesting your internet IP address, but if you're using some DDNS thing then yeah that'll slow you down a tad.

You can do what I used to do, keep separate shortcuts for "LOCAL" & "AWAY" that point to your different addresses.

**Comment by Budlyte** [comment]
I understand now, and suggest changing the title to something like "Remember Previous Connections" or similar. And I agree, this would be a nice feature.

**Comment by benonymity** [comment]
I think this was implemented in the latest release, if you click logout in the app you're presented with a list of servers and you can change among them.

**Comment by advplyr** [comment]
Multiple server configs is in [v0.9.41-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.41-beta)

I also like the idea of setting a home network config that will be automatically switched to when entering your home network, but we can put this in another feature request.
