### ISSUE TITLE
Bug Report: Last played automatically resumes when re-opening the app [iOS]

### ISSUE THREAD

**Issue by b3nd1k** [advplyr/audiobookshelf-app#1030]
After I am done listening to an audiobook, I click the pause button and minimize the app. When I later re-open the app, the last played audiobook starts playing automatically once I open the app. This is is without initiating a play session. Not sure if anyone else has ran into this, but I thought I would report it.

**Comment by nichwall** [comment]
Duplicate of #973

**Comment by b3nd1k** [comment]
Closing this. Duplicate of #973
