### ISSUE TITLE
[Enhancement]: add new setting Option "show Track-Title"

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf-app#1034]
today the App show the name of the file. But I have a lot of "Life Act" from comedian. These filename contains the name of the album and an  incrementing Track number. Each track as its own Title  as you can see in next picture:

![image](https://github.com/advplyr/audiobookshelf-app/assets/72630160/35c2f0ff-3d99-4730-9916-68d94f746d7a)

It would be very use to have an setting option to choose or flag what to show:
- File name
- Track title
- Disk no - Track no

**Comment by advplyr** [comment]
Show this where?

**Comment by Gru0810** [comment]
show on the player under Cover:
next Pic "Title is truncated -> no number visible:
![image](https://github.com/advplyr/audiobookshelf-app/assets/72630160/1b54120a-fbf3-4fa7-b4dd-7af2f554ce0b)

next Pic : name of album is not so long -> see Track Number:
![image](https://github.com/advplyr/audiobookshelf-app/assets/72630160/17e2591a-2577-4065-873e-9d6fed159716)


If the user can choose of flag what to show its open.

**Comment by advplyr** [comment]
This is actually showing the chapter and not the name of the audio track. The scanner will use the title ID3 tag as the chapter title and if that is not found it will use the filename. More here https://github.com/advplyr/audiobookshelf/issues/679
