### ISSUE TITLE
Android Auto Crashes Randomly

### ISSUE THREAD

**Issue by MrBearedJoe** [advplyr/audiobookshelf-app#1040]
My coworker is reporting randomly while using ABS the app will crash. Before he would use is on double display mode, where he can see the map on the left and ABS app on the right. And he found if he only had other open by it self, it wouldn't crash. He had just the ABS app open and it crashes too. Seems to be fairly random, maybe 20min+ before it would crash.

Also he said it has been happening for about a month, which would be the last 3 versions or so on the Phone app. Also we did upgrade form 2.3.3 to 2.70 (debian) in December too.

### Environment data
Audiobookshelf Version: From v0.9.69 to v0.9.71-beta
- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13
Samsung OneUI: 5.1
Android Auto Version: 10.9.634644
Device model: Samsung A23
Stock or customized system: Stock

**Comment by Jerk-Solutions** [comment]
Experiencing crashes pretty frequently on android Samsung S23 Ultra. No errors in the server log

**Comment by SlothDev353** [comment]
It usually crashes on start up on my Samsung S21 Ultra the first time I try to open the app. Then on the second it opens fine.

**Comment by advplyr** [comment]
I'm pretty sure this is from https://github.com/anggrayudi/SimpleStorage/issues/133 and will be fixed in the next release.

It isn't specific to android auto though.

**Comment by JBlond** [comment]
@advplyr Thank you for the new release. it fixed the crashes for me (Android).

**Comment by SlothDev353** [comment]
@advplyr thank you, this has worked for me too. Appreciate all your work <3

**Comment by joshaconnor** [comment]
Updating to the most recent version did not fix the problem for me. I'm on 0.9.72-beta, Pixel 7 with android 14. It's every time I try to play anything over android auto, and it's so bad it crashed my whole android auto app and forced me to reconnect my phone to the car once.
