### ISSUE TITLE
OIDC Authentication fails with "state parameter mismatch"

### ISSUE THREAD

**Issue by k8ieone** [advplyr/audiobookshelf-app#1041]
### Steps to reproduce

1. Use Authentik OIDC for authentication
2. Try logging in with the mobile app
3. "State parameter mismatch"

### Expected behaviour
The user should be logged in.

### Actual behaviour
The login fails and the web browser ends up on this page:
![Screenshot_20240110-134039.png](https://github.com/advplyr/audiobookshelf-app/assets/28711937/b4cdc05f-f647-475b-a2a1-78d4d95ed33f)

(up in the left corner)

![ResizedImage_2024-01-10_13-41-43_1209.png](https://github.com/advplyr/audiobookshelf-app/assets/28711937/e3a509a5-1f89-4226-94d2-f7a6e59a9fd1)

Logging in to the web interface through OIDC works as expected. That's why I'm reporting this here.

### Environment data

Audiobookshelf Version:

- Android App `0.9.71-beta`

#### Android Issue
Android version: 13

Device model: Wingtech T-Phone

Stock or customized system: Stock (pretty much vanilla Android)

**Comment by advplyr** [comment]
What is the version of the server?

**Comment by k8ieone** [comment]
@advplyr 2.7.1, brand new deployment.

**Comment by k8ieone** [comment]
Update: I managed to log in today.

I still ended up on the "state parameter mismatch" page, but after tapping on "open", the app proceeded to log in.

Previous attempts resulted in the app either freezing or crashing.

I did not change anything about my setup, so I'm not sure why it works now.

**Comment by advplyr** [comment]
I'm not sure either. Are you still having odd behavior?

**Comment by Sapd** [comment]
> Update: I managed to log in today.
> 
> I still ended up on the "state parameter mismatch" page, but after tapping on "open", the app proceeded to log in.
> 
> Previous attempts resulted in the app either freezing or crashing.
> 
> I did not change anything about my setup, so I'm not sure why it works now.

Thats weird. I suspect its something with the Browser on your Android because if you get the screen "Open in another App" it means the auth was successful. Maybe your browser reloads the page for a second time or so AND shows "Open in another app", which would lead to that kind of message you see in the background.

**Comment by k8ieone** [comment]
@Sapd That could be it. Just for the record - the browser used here is [Fennec](https://f-droid.org/packages/org.mozilla.fennec_fdroid/).

I just tested again today. The "state parameter mismatch" page still loads, but the login succeeds after pressing "open".

**Comment by advplyr** [comment]
Have you tested with another browser?

**Comment by k8ieone** [comment]
@advplyr No, but I can try. Which browsers should I test?

**Comment by Sapd** [comment]
@k8ieone  You can just try any on the device. Chrome or Firefox for example.

**Comment by k8ieone** [comment]
@Sapd I tested with Firefox and Chrome. Firefox has the same behavior.

Chrome went right back to the app after signing in to my IDP. This is how I think it should look.

So it looks like this is a Firefox-only issue (Fennec is a fork).

**Comment by advplyr** [comment]
I'm not sure if there is anything we can do about this. We aren't doing anything special but a redirect

**Comment by k8ieone** [comment]
Since logging in works I think we can close this.
