### ISSUE TITLE
[Android] sound reduced to 0 on low voicelines

### ISSUE THREAD

**Issue by MrDaft** [advplyr/audiobookshelf-app#1045]
### Steps to reproduce

1. Play Any audiobook with some pauses between sentences
2.
3.

### Expected behaviour
- sound plays perfectly fine as intended 

### Actual behaviour
- when there is any pause between words/sentences sound reduced to 0 like it some kind of of noise cancellation . sometimes I lose first 1-1,5 words of the sentence and than sound appeared again.
- no such issue on desktop or in mobile browser (chrome/firefox).
- definitely an issue for last 2 releases of app 

### Environment data

Audiobookshelf Version: 2.7.1

- [+] Android App
- [ ] iOS App?

#### Android Issue
Android version:
0.9.71 beta
Device model:
Pixel 8 pro
Stock or customized system:
Stock

**Comment by nichwall** [comment]
I haven't experienced that behavior at all using a Pixel 6a, on either the phone speaker or over Bluetooth.

Is this happening for all files?
On phone speaker or Bluetooth?
Downloaded or streamed?
What playback speed are you using?

**Comment by friki67** [comment]
Hello. This same thing is happening to me. Only in bluetooth. It works ok for the phone speaker or a cable headset. I'm losing the begining or the fist word for almost every paragraph. I've tried same file using Voice (https://github.com/PaulWoitaschek/Voice) and same thing is happening. It is a m4b file. Some m4b files play ok, and some other make this silence-at-the-begging-of-paragraph fail.
So this isn't a problem with Audiobookshelf, but a problem with certain files and/or bluetooth devices, and maybe only with certain devices, I don't know.  JFYI
Greap app and server! Keep on!
