### ISSUE TITLE
Swipe Up to Expand the View on Android App

### ISSUE THREAD

**Issue by doctordarko** [advplyr/audiobookshelf-app#1046]
While searching for a way to set the manual timer on the Android app, it took me longer than I care to admit (haha) to actually click onto the play bar in order to expand the view. I was expecting a swipe up/down to expand and minimise the play screen like it is implemented on all the audio player apps. 

Annoyingly, once expanded, swipe down seems to work but only in the upper portion of the screen. It would be amazing if the app mimicked You Tube Music swipe up/down mechanism.

Also, while nitpicking, when the now playing bar is minimised, there should be a little up arrow (^) hinting that view can be expanded. There is already a down arrow (V) on the expanded view.

**Comment by advplyr** [comment]
Looking at this I don't see much room for an up arrow. If we move over the play button then there isn't much room for the title. It would also look strange on the right side I think.

**Comment by doctordarko** [comment]
![Screenshot_20240202-101736~2](https://github.com/advplyr/audiobookshelf-app/assets/57649463/2ef63dd7-e018-4c16-ac55-4c1ea6ed7b8c)
This is a screenshot from Pixel 7 Pro and the gap between the progress and the white bar looks like to have enough space for a little up arrow (^) nicely centred. 

Then again, I have zero clue what it takes to implement this or how it looks on other phones so I'll let the experts decide. 😁

**Comment by advplyr** [comment]
I don't think an arrow will look right down there and I'm not sure if the bottom could be cutoff on certain devices. We could add a message there in the center "swipe up for fullscreen" or show an animation above the player when it first gets opened but I think it will be unnecessary once swipe up is released.
As you said in your original comment you did try swiping up and that will be in the next release

**Comment by doctordarko** [comment]
Agree, let's not complicate it with extra visual candy. Swipe up should do
the trick. Thanks for the amazing work.

**Comment by advplyr** [comment]
Updated in [v0.9.72-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.72-beta)
