### ISSUE TITLE
German Localization

### ISSUE THREAD

**Issue by bloodscript** [advplyr/audiobookshelf-app#1051]
### Is your feature request related to a problem? Please describe.
I recognized the German localization can be improved.

### Describe the solution you'd like
I would check all German localization strings by a native or good speaker. I assume the strings are shared for iOS and android but I will only assign it to iOS as I am not sure yet.

### Describe alternatives you've considered
Alternative solution would be to translate with help of a translation software like deepl

**Comment by nichwall** [comment]
Strings are located here and are shared between iOS and Android.
https://github.com/advplyr/audiobookshelf-app/blob/master/strings%2Fde.json
