### ISSUE TITLE
Contribution Improvement

### ISSUE THREAD

**Issue by bloodscript** [advplyr/audiobookshelf-app#1053]
### Is your feature request related to a problem? Please describe.
I wanted to contribute, so since no description of the expected workflow was described, I just cloned the repo, created a branch locally, did some changes and upon comitting and trying to push I realized that this workflow is not allowed.

### Describe the solution you'd like
A description of the expected workflow for contributions shall be added to the contribution section.

### Describe alternatives you've considered
Dont change the contribution section. Some contributors may not read or understand that they are not allowed to push a branch to the repo and therefore may stop contributing

**Comment by nichwall** [comment]
You will need to make a fork and open a PR to this repository. You can add a new a remote to your locally cloned repository (which is your fork), push your changes to a branch there, and then open a PR to this repository. You could also make the fork, clone your fork, and then copy your changes.

In general, you should always make a fork and open a PR to the parent repository when contributing to an open source project, both for security and management reasons. Many projects operate that way.
