### ISSUE TITLE
Cant connect to server after building the app

### ISSUE THREAD

**Issue by izyspania** [advplyr/audiobookshelf-app#1056]
Im getting the next error when building on Windows , i can start the app but i cant connect to the server , the server works because i can connect with the app from playstore.

PS C:\Users\me\Desktop\audiobookshelf-app-master>  npm run dev

> audiobookshelf-app@0.9.71-beta dev
> nuxt --hostname 0.0.0.0 --port 1337

ℹ Using default Tailwind CSS file                                                           nuxt:tailwindcss 02:45:32
ℹ Module @nuxtjs/tailwindcss took 120.74ms to setup.                                                         02:45:32
ℹ Tailwind Viewer: http://192.168.100.2:1337/_tailwind/                                     nuxt:tailwindcss 02:45:32

   ╭───────────────────────────────────────────╮
   │                                           │
   │   Nuxt @ v2.17.3                          │
   │                                           │
   │   ▸ Environment: development              │
   │   ▸ Rendering:   client-side              │
   │   ▸ Target:      static                   │
   │                                           │
   │   Listening: http://192.168.100.2:1337/   │
   │                                           │
   ╰───────────────────────────────────────────╯

ℹ Preparing project for development                                                                          02:45:33
ℹ Initial build may take a while                                                                             02:45:33

 ERROR  Nuxt compatibility issues found:                                                                      02:45:33
 - [bridge] Nuxt bridge is required

  - [bridge] Nuxt bridge is required
  at assertNuxtCompatibility (/C:/Users/me/Desktop/audiobookshelf-app-master/node_modules/@nuxt/kit/dist/index.mjs:76:11)

i Discovered Components: .nuxt/components/readme.md                                                           02:45:33
✔ Builder initialized                                                                                        02:45:33
✔ Nuxt files generated                                                                                       02:45:33

 √ Client
   Compiled successfully in 6.98s

ℹ Waiting for file changes                                                                                   02:45:41
ℹ Memory usage: 657 MB (RSS: 794 MB)                                                                         02:45:41
ℹ Listening on: http://192.168.100.2:1337/

![image](https://github.com/advplyr/audiobookshelf-app/assets/93366907/fdb5eafe-54b4-4662-aa18-c1874793e584)

**Comment by advplyr** [comment]
Are you trying to connect to a production server from the browser? If you check the console logs this is probably a cors error

**Comment by izyspania** [comment]
> Are you trying to connect to a production server from the browser? If you check the console logs this is probably a cors error

The server is on the same computer as the app, i was trying to modify some code and i want real time updates (im used with react-native not sure how this works yet) in android studio i prob have to rebuild the app after each change.
I can connect with the app on my local server running in android studio (or from google play from my phone) but the live WEB version doesnt want to connect, i am not sure what im doing wrong.

**Comment by advplyr** [comment]
Did you open up the browser console and confirm that you are getting a CORS error?

**Comment by advplyr** [comment]
Unless you are running the server in development then cors is blocked. I recommend you spin up a local development server if you want to develop in the browser.

https://github.com/advplyr/audiobookshelf/blob/b9ec4068ee50a3ac54f64d53f8ed0bd13bd101e9/server/Server.js#L152-L166

**Comment by izyspania** [comment]
![image](https://github.com/advplyr/audiobookshelf-app/assets/93366907/4ccb3cf5-0b20-40ed-9d46-e5f83a027248)
