### ISSUE TITLE
Continiously playback

### ISSUE THREAD

**Issue by groetg** [advplyr/audiobookshelf-app#1062]
When I listen to a podcasts and the podcasts ends, audio bookshelf stops playback. Other podcast app Antennapod keeps playing the next podcast automaticly. What am I doing wrong?

**Comment by groetg** [comment]
When I listen to a podcasts and the podcasts ends, audio bookshelf stops playback. Other podcast app Antennapod keeps playing the next podcast automaticly. What am I doing wrong?

**Comment by advplyr** [comment]
Duplicate of #416
