### ISSUE TITLE
When casting from mobile to another device, speed can only be 1x

### ISSUE THREAD

**Issue by billyhelms24** [advplyr/audiobookshelf-app#1065]
### Steps to reproduce

1. Begin stream
2. Cast to another device via 'Cast'
3. Change speed

### Expected behaviour
- playback speed changes to reflect selection

### Actual behaviour
- playback speed stayed at 1x

### Environment data

Audiobookshelf Version: 0.9.71-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 14, OneUI 6

Device model: Samsung S23 Ultra

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Does it work if you set the speed before casting?

**Comment by JakobTischler** [comment]
AFAIK, and as long as I can remember, Google's cast eco-system has never supported variable playback speeds. If this has changed, I'd be happy to be corrected, though.

**Comment by billyhelms24** [comment]
It seems you are correct. I just read through their Google Dev Audio Cast Guide and it made no mention of speed controls or variable playback in the guide or the API docs. Bit of a bummer, hopefully that will change in the future.

**Comment by advplyr** [comment]
Ah okay that's interesting since the exoplayer casting part of the library has an option to pass in playback speed which I am doing
