### ISSUE TITLE
[Android] App crashes when trying to play from SD Card

### ISSUE THREAD

**Issue by timrychta** [advplyr/audiobookshelf-app#1067]
### Steps to reproduce

1. Create Download folder on SD Card
2. Download book to said folder
3. Close the App (it works before closing the app for the first time)
4. Open the App and try to play book

### Expected behaviour
- The book should play

### Actual behaviour
- The app crashes and closes immediately

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: Android 14, OneUI 6

Device model: Galaxy A54

Stock or customized system: Stock

**Comment by nichwall** [comment]
Probably the SimpleStorage bug which is fixed for next release

https://github.com/advplyr/audiobookshelf-app/commit/c9fb98f033e5ae78772454d29adb620d4d798ebe

**Comment by advplyr** [comment]
The crash should be fixed now in [v0.9.72-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.72-beta) but let me know if you are still getting crashes
