### ISSUE TITLE
[Enhancement]: Link to web client in app sidebar

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf-app#1079]
### Is your feature request related to a problem? Please describe.
There has been some more recent discussion around adding custom functionality (recommendation forms, server management, other custom buttons) to the clients here in GH and on Discord. Instead of requiring people to make and distribute custom mobile clients, a quicker way to get to the web client (or correct page?) would help with some of these requests. That allows for quicker server management or adding custom buttons/functionality without requiring a big change to the mobile apps.

### Describe the solution you'd like
An additional button in the app sidebar, such as below "Switch Server/User" like "Go to Web Client" which just opens the web client at the library home page.

Bonus points if there's an option to go to the current item (such as a book or author page) or Library view so it's easier to manage the existing item if that's what someone is going for. If that's done, I think that should be a separate button of "Go to Item on Server" or something. Not sure on the best way to do that part of the interface, maybe just always going to the item is better.

### Describe alternatives you've considered
Having links in the 3 dot menu for every item, which may be nice too, but is more clicks to go through the More Information for something that shouldn't be used a ton in the main interface.

### Additional context
Some issues and discussions that could be mitigated:
https://github.com/advplyr/audiobookshelf/issues/2603
https://github.com/advplyr/audiobookshelf/discussions/2592
https://github.com/advplyr/audiobookshelf-app/issues/1063
https://github.com/advplyr/audiobookshelf-app/issues/710

**Comment by advplyr** [comment]
I restricted this to only show for admin users. I'm not sure if it is necessary to show this to regular users.

For the button in the side drawer I have it open the current library home page. We could expand this in the future to open the matching page in the web client but it seemed like overkill mapping all those pages.

I added the button to the item more menu also and I think it looks good. That will open to the item in the web client.

![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/140df078-ef9a-4ea2-9f38-136647d4c1da)

![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/34324d30-1f3b-404f-a6c3-d76a1354022e)

**Comment by nichwall** [comment]
Looks good!

Is there a specific reason to not make the buttons available for normal users?

I think at least the side menu button (goes to home page) could be shown to regular users, specifically for the use case where people are wanting to add a recommendation form button or other functionality to their server.

**Comment by advplyr** [comment]
I couldn't think of a use-case for a normal user to jump to the web app. I'm not sure what you mean with recommendation form button?

**Comment by nichwall** [comment]
The "request form" is from discussion https://github.com/advplyr/audiobookshelf/discussions/2592 (this discussion also links to a Discord discussion about it).

Basically some server owners have added a button with a link to a 3rd party recommendation form to the web client so their users can more easily request books (instead of needing to remember the link for the form, or texting). There could be other modifications individual server owners make to the web client because that is much easier than compiling and distributing the app themselves.

My reasoning for normal users to have the button is so a user could get to the web client more easily if they mostly just use the app so they can just hit a button instead of needing to bookmark/remember the domain for the web client.

**Comment by advplyr** [comment]
That works for me!

**Comment by advplyr** [comment]
Added in [v0.9.74-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.74-beta)
