### ISSUE TITLE
Add ability to download & view EPISODE image for Podcasts

### ISSUE THREAD

**Issue by rxbrad** [advplyr/audiobookshelf-app#1087]
Currently, a given podcast displays the same ```<channel> // <image>``` podcast art for all episodes.

Would be nice if ABS also downloaded each individual episode's ```<channel> //  <item> // <image>``` art (if it exists), and made this available to display in clients.

**Comment by advplyr** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1573
