### ISSUE TITLE
Ability to share links from Android app

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf-app#1090]
### Is your feature request related to a problem? Please describe.
I would like to be able to be able to copy/share a url for a book on my abs server from the android app.  In particular, this would come in handy dealing with (https://github.com/advplyr/audiobookshelf-app/issues/1063) insofar as all I would have to do is use the link to go directly to the book in an Android browser window.  

### Describe the solution you'd like
A share icon somewhere in ABS which does the normal Android share functions so I can either copy or text the link to the book I'm browsing in ABS/Android

### Describe alternatives you've considered
X

### Additional context
X

**Comment by nichwall** [comment]
Related issues:
- Link to web browser from side bar https://github.com/advplyr/audiobookshelf-app/issues/1079
- "Open With" button https://github.com/advplyr/audiobookshelf-app/issues/1050

**Comment by advplyr** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1768

**Comment by advplyr** [comment]
This is for a link to open in a browser
