### ISSUE TITLE
Press and drag chapter progress slider bar

### ISSUE THREAD

**Issue by elementalest** [advplyr/audiobookshelf-app#110]
### Is your feature request related to a problem? Please describe.

I am unable to precicely skip/seek to the position I want using the chapter progress bar. Currently I can press a location on the progress bar and the player will skip/seek to it, but the accuracy is not great and around the edges of the screen its even harder.

### Describe the solution you'd like

I would like to be able to press and drag the progress slider bar to precicely seek to the exact second, then release to actually seek, similar to the Audible app.

### Describe alternatives you've considered

It is possible to roughly seek to where you want and then skip forward/back 10s using the buttons, but for chapters that are very long (i.e. 1.5hrs) this can mean spamming the skip buttons 20+ times.

### Additional context

The Audible app has a good solution and is a good reference.

### Feedback

Just discovered this last weekend and have been testing it out. I really like it and so far its the best solution I have found!

**Comment by advplyr** [comment]
Added in [v0.9.47-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.47-beta)

I haven't checked how Audible did it. I'm sure there is a better way to make it more precise in the future
