### ISSUE TITLE
Cellular network connection allways failed when use app in android.

### ISSUE THREAD

**Issue by 65786113** [advplyr/audiobookshelf-app#1102]
### Steps to reproduce

1.First noticed server version is 2.72 ,and version 2.80 didnot fix it.
2.
3.

- My server is synology DSM 7.2.1-69057 Update 3.
- I use android app version0.9.72,,the release version is 2.8.0.
- when enjoying in the local area network,all is well,responds very mooth；But in the Cellular networks，it is seldom to play the audio.usually I had to try 1 min or more to success view the audioplay.Even the mainpage showed up,I tapped the coutinue-play,it showed failing"server play request failed."

### Environment data
![微信图片_20240225223332](https://github.com/advplyr/audiobookshelf-app/assets/134789512/399cf09a-7e65-483e-9155-14100fac8783)

Audiobookshelf Version:

- [ ] Android App 0.9.72

#### Android Issue
Android version:0.9.72

Device model:

Stock or customized system:DSM 7.2.1-69057 Update 3.

**Comment by advplyr** [comment]
Check your server logs. This is reporting an error on the server side.

**Comment by 65786113** [comment]
2024-02-25 14:32:22.081

DEBUG

[SocketAuthority] User Offline root

2024-02-25 14:32:22.084

INFO

[SocketAuthority] Socket XuIDxdsEAReJ6O8jAADC disconnected from client "root" after 27543ms (Reason: transport close)

2024-02-25 14:32:23.144

INFO

[STREAM-CHECK] Check Files 38220 of 184836 20.68% Furthest Segment: 130040

2024-02-25 14:32:25.153

INFO

[STREAM-CHECK] Check Files 38426 of 184836 20.79% Furthest Segment: 130246

2024-02-25 14:32:27.145

INFO

[STREAM-CHECK] Check Files 38622 of 184836 20.90% Furthest Segment: 130442

2024-02-25 14:32:29.140

INFO

[STREAM-CHECK] Check Files 38826 of 184836 21.01% Furthest Segment: 130646

2024-02-25 14:32:31.143

INFO

[STREAM-CHECK] Check Files 39029 of 184836 21.12% Furthest Segment: 130849

2024-02-25 14:32:33.143

INFO

[STREAM-CHECK] Check Files 39231 of 184836 21.22% Furthest Segment: 131051

2024-02-25 14:32:35.148

INFO

[STREAM-CHECK] Check Files 39434 of 184836 21.33% Furthest Segment: 131254

2024-02-25 14:32:37.164

INFO

[STREAM-CHECK] Check Files 39630 of 184836 21.44% Furthest Segment: 131450

2024-02-25 14:32:39.150

INFO

[STREAM-CHECK] Check Files 39825 of 184836 21.55% Furthest Segment: 131645

2024-02-25 14:32:41.153

INFO

[STREAM-CHECK] Check Files 40024 of 184836 21.65% Furthest Segment: 131844

2024-02-25 14:32:43.154

INFO

[STREAM-CHECK] Check Files 40231 of 184836 21.77% Furthest Segment: 132051

2024-02-25 14:32:45.154

INFO

[STREAM-CHECK] Check Files 40429 of 184836 21.87% Furthest Segment: 132249

2024-02-25 14:32:47.157

INFO

[STREAM-CHECK] Check Files 40625 of 184836 21.98% Furthest Segment: 132445

2024-02-25 14:32:49.152

INFO

[STREAM-CHECK] Check Files 40816 of 184836 22.08% Furthest Segment: 132636

2024-02-25 14:32:51.159

INFO

[STREAM-CHECK] Check Files 41007 of 184836 22.19% Furthest Segment: 132827

2024-02-25 14:32:53.159

INFO

[STREAM-CHECK] Check Files 41199 of 184836 22.29% Furthest Segment: 133019

2024-02-25 14:32:55.165

INFO

[STREAM-CHECK] Check Files 41392 of 184836 22.39% Furthest Segment: 133212

2024-02-25 14:32:57.164

INFO

[STREAM-CHECK] Check Files 41583 of 184836 22.50% Furthest Segment: 133403

2024-02-25 14:32:59.163

INFO

[STREAM-CHECK] Check Files 41778 of 184836 22.60% Furthest Segment: 133598

2024-02-25 14:33:00.761

DEBUG

[ApiCacheManager] count: 4 size: 148946

2024-02-25 14:33:00.762

DEBUG

[ApiCacheManager] Cache hit: {"user":"root","url":"/libraries/37dd663f-8d42-4f80-b542-a25a9959aaa0/items?sort=addedAt&desc=1&collapseseries=1&limit=20&page=0&minified=1&include=rssfeed,numEpisodesIncomplete"}

2024-02-25 14:33:01.167

INFO

[STREAM-CHECK] Check Files 41977 of 184836 22.71% Furthest Segment: 133797

2024-02-25 14:33:02.837

DEBUG

[ApiCacheManager] Object.afterBulkUpdate: Clearing cache

2024-02-25 14:33:02.838

DEBUG

[PlaybackSessionManager] startSessionRequest for device 23049RAD8C SDK 33 / v13

2024-02-25 14:33:02.838

INFO

[PlaybackSessionManager] startSession: Closing open session "太平洋战争.青梅煮酒.演播现代军吧.2020.AAC.96~128kbps-RL" for user "root" (Device: 23049RAD8C SDK 33 / v13)

2024-02-25 14:33:02.839

DEBUG

[PlaybackSessionManager] closeSession "a8fd1717-7669-472a-8ee1-8d5e7cb5f019"

2024-02-25 14:33:02.841

INFO

Closing Stream a8fd1717-7669-472a-8ee1-8d5e7cb5f019

2024-02-25 14:33:02.874

INFO

[FFMPEG] Transcode Killed

2024-02-25 14:33:04.086

INFO

Deleted session data /metadata/streams/a8fd1717-7669-472a-8ee1-8d5e7cb5f019

2024-02-25 14:33:04.086

DEBUG

[PlaybackSessionManager] Stream closed for session "a8fd1717-7669-472a-8ee1-8d5e7cb5f019" (Device: 23049RAD8C SDK 33 / v13)

2024-02-25 14:33:04.087

DEBUG

[PlaybackSessionManager] Removed session "a8fd1717-7669-472a-8ee1-8d5e7cb5f019"

2024-02-25 14:33:04.088

DEBUG

[PlaybackSessionManager] "root" starting direct play session for item "a07ad03a-b990-42eb-8ba5-8c2594061cc7" with id 6b773f0f-9ff6-4bfb-b822-065e03a1b70e (Device: 23049RAD8C SDK 33 / v13)

2024-02-25 14:33:06.225

DEBUG

[ApiCacheManager] count: 0 size: 0

2024-02-25 14:33:06.506

DEBUG

Loaded 20 of 558 items for libary page in 0.28s

2024-02-25 14:33:06.518

DEBUG

[ApiCacheManager] Cache miss: {"user":"root","url":"/libraries/37dd663f-8d42-4f80-b542-a25a9959aaa0/items?sort=addedAt&desc=1&collapseseries=1&limit=20&page=0&minified=1&include=rssfeed,numEpisodesIncomplete"}

2024-02-25 14:35:00.990

DEBUG

[ApiCacheManager] count: 1 size: 32251

2024-02-25 14:35:01.171

DEBUG

Loaded 10 of 18 items for "Continue Listening/Reading" in 0.18s

2024-02-25 14:35:01.254

DEBUG

Loaded 1 of 1 items for "Continue Series" in 0.08s

2024-02-25 14:35:02.466

DEBUG

Loaded 10 of 36 items for "Recently Added" in 1.21s

2024-02-25 14:35:02.508

DEBUG

Loaded 4 of 4 series for "Recent Series" in 0.04s

2024-02-25 14:35:02.756

DEBUG

Loaded 10 of 535 items for "Discover" in 0.25s

2024-02-25 14:35:02.876

DEBUG

Loaded 10 of 10 items for "Listen/Read Again" in 0.12s

2024-02-25 14:35:02.893

DEBUG

Loaded 10 of 39 authors for "Newest Authors" in 0.02s

2024-02-25 14:35:02.894

DEBUG

Loaded 7 personalized shelves in 1.90s

2024-02-25 14:35:02.895

DEBUG

[ApiCacheManager] Cache miss: {"user":"root","url":"/libraries/37dd663f-8d42-4f80-b542-a25a9959aaa0/personalized?minified=1&include=rssfeed,numEpisodesIncomplete"}

2024-02-25 14:35:02.895

DEBUG

[ApiCacheManager] Caching with 1800000 ms TTL

2024-02-25 14:35:21.304

DEBUG

[ApiCacheManager] count: 2 size: 123415

2024-02-25 14:35:21.305

DEBUG

[ApiCacheManager] Cache hit: {"user":"root","url":"/libraries/37dd663f-8d42-4f80-b542-a25a9959aaa0/items?sort=addedAt&desc=1&collapseseries=1&limit=20&page=0&minified=1&include=rssfeed,numEpisodesIncomplete"}

2024-02-25 14:35:31.955

INFO

[SocketAuthority] Socket Connected xE4QlHRLxYHvC-E5AADE

2024-02-25 14:35:32.099

DEBUG

[SocketAuthority] User Online root

2024-02-25 14:36:15.899

DEBUG

[SocketAuthority] User Offline root

2024-02-25 14:36:15.908

INFO

[SocketAuthority] Socket xE4QlHRLxYHvC-E5AADE disconnected from client "root" after 43953ms (Reason: transport close)

2024-02-25 14:36:57.074

DEBUG

[ApiCacheManager] count: 2 size: 123415

2024-02-25 14:36:57.074

DEBUG

[ApiCacheManager] Cache hit: {"user":"root","url":"/libraries/37dd663f-8d42-4f80-b542-a25a9959aaa0/personalized?minified=1&include=rssfeed,numEpisodesIncomplete"}

2024-02-25 14:37:13.712

DEBUG

[ApiCacheManager] count: 2 size: 123415

2024-02-25 14:37:13.713

DEBUG

[ApiCacheManager] Cache hit: {"user":"root","url":"/libraries/37dd663f-8d42-4f80-b542-a25a9959aaa0/items?sort=addedAt&desc=1&collapseseries=1&limit=20&page=0&minified=1&include=rssfeed,numEpisodesIncomplete"}

2024-02-25 14:37:15.756

INFO

[SocketAuthority] Socket Connected DwExvU9k-4ry-fFjAADG

2024-02-25 14:37:15.938

DEBUG

[SocketAuthority] User Online root

2024-02-25 14:37:16.760

DEBUG

[ApiCacheManager] count: 2 size: 123415

2024-02-25 14:37:16.761

DEBUG

[ApiCacheManager] Cache hit: {"user":"root","url":"/libraries/37dd663f-8d42-4f80-b542-a25a9959aaa0/items?sort=addedAt&desc=1&collapseseries=1&limit=20&page=0&minified=1&include=rssfeed,numEpisodesIncomp

**Comment by advplyr** [comment]
Can you share information about the audio file(s)? I suspect something is wrong with the audio file that is making Abs have to transcode it. You can go into the web client and select "More Info" on the audio track

**Comment by 65786113** [comment]
I had check the log by myself,I found **Cache miss** always means a unseccess attempted

**Comment by 65786113** [comment]
> Can you share information about the audio file(s)? I suspect something is wrong with the audio file that is making Abs have to transcode it. You can go into the web client and select "More Info" on the audio track

{
  "programs": [],
  "streams": [
    {
      "index": 0,
      "codec_name": "aac",
      "codec_long_name": "AAC (Advanced Audio Coding)",
      "profile": "HE-AACv2",
      "codec_type": "audio",
      "codec_tag_string": "mp4a",
      "codec_tag": "0x6134706d",
      "sample_fmt": "fltp",
      "sample_rate": "44100",
      "channels": 2,
      "channel_layout": "stereo",
      "bits_per_sample": 0,
      "initial_padding": 0,
      "id": "0x1",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/44100",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 30548732,
      "duration": "692.715011",
      "bit_rate": "96001",
      "nb_frames": "14920",
      "extradata_size": 7,
      "disposition": {
        "default": 1,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0,
        "non_diegetic": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      },
      "tags": {
        "language": "und",
        "handler_name": "SoundHandler",
        "vendor_id": "[0][0][0][0]"
      }
    }
  ],
  "chapters": [],
  "format": {
    "filename": "/volume3/AudioNovel/太平洋战争.青梅煮酒.演播现代军吧.2020.AAC.96~128kbps-RL/1.001第一辑｜黑船来航.m4a",
    "nb_streams": 1,
    "nb_programs": 0,
    "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
    "format_long_name": "QuickTime / MOV",
    "start_time": "0.000000",
    "duration": "692.715011",
    "size": "8375131",
    "bit_rate": "96722",
    "probe_score": 100,
    "tags": {
      "major_brand": "M4A ",
      "minor_version": "512",
      "compatible_brands": "M4A isomiso2",
      "encoder": "Lavf58.45.100"
    }
  }
}

**Comment by 65786113** [comment]
2024-02-25 14:48:35.591

DEBUG

[ApiCacheManager] Cache hit: {"user":"root","url":"/libraries/37dd663f-8d42-4f80-b542-a25a9959aaa0/personalized?minified=1&include=rssfeed,numEpisodesIncomplete"}

2024-02-25 14:48:46.333

DEBUG

[ApiCacheManager] count: 6 size: 313949

2024-02-25 14:48:46.333

DEBUG

[ApiCacheManager] Cache hit: {"user":"root","url":"/libraries/37dd663f-8d42-4f80-b542-a25a9959aaa0?include=filterdata"}

2024-02-25 14:48:46.488

DEBUG

[ApiCacheManager] count: 6 size: 313949

2024-02-25 14:48:46.488

DEBUG

[ApiCacheManager] Cache hit: {"user":"root","url":"/libraries/37dd663f-8d42-4f80-b542-a25a9959aaa0/personalized?include=rssfeed,numEpisodesIncomplete"}

2024-02-25 14:48:50.024

DEBUG

[PlaybackSessionManager] startSessionRequest for device Windows 10 / Edge

2024-02-25 14:48:50.027

DEBUG

[PlaybackSessionManager] "root" starting direct play session for item "a07ad03a-b990-42eb-8ba5-8c2594061cc7" with id dd4b34e1-c8b0-46e4-a9fe-c2c0327b920b (Device: Windows 10 / Edge)

2024-02-25 14:49:12.054

DEBUG

[PlaybackSessionManager] syncSession "dd4b34e1-c8b0-46e4-a9fe-c2c0327b920b" (Device: Windows 10 / Edge) | Total Time Listened: 20

2024-02-25 14:49:12.096

DEBUG

[ApiCacheManager] Array.afterUpsert: Clearing cache

2024-02-25 14:49:12.117

DEBUG

[ApiCacheManager] playbackSession.afterCreate: Clearing cache

2024-02-25 14:49:18.244

DEBUG

[SocketAuthority] User Offline root

2024-02-25 14:49:18.269

INFO

[SocketAuthority] Socket 2_jOHKx2u_DwX3q_AADQ disconnected from client "root" after 47404ms (Reason: transport close)

2024-02-25 14:49:22.019

DEBUG

[PlaybackSessionManager] syncSession "dd4b34e1-c8b0-46e4-a9fe-c2c0327b920b" (Device: Windows 10 / Edge) | Total Time Listened: 30

2024-02-25 14:49:22.044

DEBUG

[ApiCacheManager] Array.afterUpsert: Clearing cache

2024-02-25 14:49:22.059

DEBUG

[ApiCacheManager] Object.afterBulkUpdate: Clearing cache

2024-02-25 14:49:25.091

INFO

[SocketAuthority] Socket Connected Ka4yOb-LUPuumwo0AADS

2024-02-25 14:49:25.111

DEBUG

[SocketAuthority] User Online root

2024-02-25 14:49:31.583

DEBUG

[SocketAuthority] User Offline root

2024-02-25 14:49:31.604

INFO

[SocketAuthority] Socket Ka4yOb-LUPuumwo0AADS disconnected from client "root" after 6513ms (Reason: transport close)

2024-02-25 14:49:31.704

DEBUG

[PlaybackSessionManager] syncSession "dd4b34e1-c8b0-46e4-a9fe-c2c0327b920b" (Device: Windows 10 / Edge) | Total Time Listened: 40

2024-02-25 14:49:31.728

DEBUG

[ApiCacheManager] Array.afterUpsert: Clearing cache

2024-02-25 14:49:31.747

DEBUG

[ApiCacheManager] Object.afterBulkUpdate: Clearing cache

If I use web client in local network,it works well.
so I think maybe the format of the file is not the cause .

**Comment by advplyr** [comment]
Does this happen with other books or is this a specific book?

**Comment by 65786113** [comment]
> Does this happen with other books or is this a specific book?

I have try on other books,still the same problem.

**Comment by advplyr** [comment]
Are you still seeing this issue with v2.8.1 and mobile app release v0.9.73-beta?

**Comment by 65786113** [comment]
> Are you still seeing this issue with v2.8.1 and mobile app release v0.9.73-beta?

with all the update,the issue looks like a bit better respond,but still not smooth as in the lan wan.
