### ISSUE TITLE
Local media item page long titles overflowing screen pushing play & more menu button offscreen

### ISSUE THREAD

**Issue by bloodscript** [advplyr/audiobookshelf-app#1103]
### Steps to reproduce

1. Download a book with a name long enough to for the name not fitting in one line (e.g Stephen.Hawking.-.Eine.kurze.Geschichte.der.Zeit on iPhone 12)
2. maneuver to manage local files
3. Try to find the 3 dots for options to delete the local files

### Expected behaviour
- The option menu should either have a fixed position and the name of the book is broken into multiple lines, even if the title consists of only one long word
OR
- the name shall be sidescrollable to reveal the option menu

### Actual behaviour
- The name of the book is cut off and the 3 dots menu is not findable

### Environment data

Audiobookshelf Version: 0.9.71-beta

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 17.3.1

iPhone model: iPhone 12

**Comment by bloodscript** [comment]
I checked other books with long titles - if the title contains multiple words, a linebreak is inserted. 

![image](https://github.com/advplyr/audiobookshelf-app/assets/18524350/40e7af99-51b7-4d27-9e46-b1c12c479cae)

![image](https://github.com/advplyr/audiobookshelf-app/assets/18524350/c5fb7f44-401f-45e0-95fa-dd3fe246f2e0)

**Comment by bloodscript** [comment]
Tested also with 0.9.72-beta and issue is reproducible.

**Comment by advplyr** [comment]
Fixed in [v0.9.73-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.73-beta)
