### ISSUE TITLE
No playback in iOS app

### ISSUE THREAD

**Issue by norseghost** [advplyr/audiobookshelf-app#111]
### Steps to reproduce

1. Launch app
2. Select book
3. Attempt playback 

### Expected behaviour
Audiobook plays

### Actual behaviour
The play/pause icon and other UI indicate playback; but nothing is passed on to iOS.

server logs show a stream is created, and playback through the web interface works

### Environment data

Audiobookshelf Version: 0.9.40

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 15.0.2

iPhone model: XS max

**Comment by norseghost** [comment]
Updated iOS to latest 15.3.2 — still nothing. Are there logs from the app I can check somewhere?

**Comment by chrisruffalo** [comment]
I am experiencing the same behavior. Works fine in the browser. I see streams and things created in the logs. No audio comes through to iOS, the time doesn't even go up, no progress appears to be made.

**Comment by benonymity** [comment]
Has this been fixed with the new release?

**Comment by norseghost** [comment]
Obligatory works for me :)

closing this issue.
