### ISSUE TITLE
[Bug] Sleep Timer "Custom time" sub-menu does not reset to top level when exiting without using "Set Timer"

### ISSUE THREAD

**Issue by DavidPesticcio** [advplyr/audiobookshelf-app#1112]
### Steps to reproduce

1. Select "Sleep Timer"
2. Select "Custom time"
3. Exit sub-menu, either by closing with "X" or touching outside pop-up
4. Re-enter "Sleep Timer"
5. "Custom time" sub-menu is still active, i.e. was not reset to top level upon exit at step 3

### Expected behaviour
- Sub-menu state should reset to "Sleep Timer" top-level menu

### Actual behaviour
- Sub-menu state not reset to "Sleep Timer" top-level menu

### Environment data

Audiobookshelf Version: 0.9.72-beta

- [ ] Android App?
- [X] iOS App?

#### Android Issue
Android version: 12

Device model: Pixel 6 Pro

Stock or customized system: Stock

**Comment by advplyr** [comment]
Interesting, I didn't know having "close #1112" in the commit message would close the issue

**Comment by DavidPesticcio** [comment]
I wonder if "open #1112" will create/re-open an/the issue too! lol

Maybe a hyphen or colon will stop it being interpreted incorrectly... :smile: :+1:

**Comment by advplyr** [comment]
Fixed in [v0.9.74-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.74-beta)
