### ISSUE TITLE
playlists don't play when casting 

### ISSUE THREAD

**Issue by localhorse** [advplyr/audiobookshelf-app#1116]
### Steps to reproduce

1. fire up abs
2. try to make a play list 
3. now try to cast to your google cast and watch it stop after the first item in the list 

### Expected behaviour
- I think I've pretty much summed it up 

### Actual behaviour
- Tell us what happens

### Environment data

Audiobookshelf Version ..
idk how to find it 
- [ ] Android App...
- [ ] I'm sorry I've deleted the other questions (on my phone) but will be willing to provide any information required

**Comment by nichwall** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/416

Auto playing the next item in a playlist has not been implemented in the mobile apps yet.

**Comment by advplyr** [comment]
Duplicate of #416
