### ISSUE TITLE
Local Download Hangs?

### ISSUE THREAD

**Issue by colvdv** [advplyr/audiobookshelf-app#1117]
I've noticed that some of my downloads (saving audiobook to local device) hang and never move past a certain percentage.
In some cases exiting the app and then re-opening and trying again works. In other cases it never makes it past a certain percent. I notice that a large single-file mp3 gets stuck at 61% every time I try.

Is this a known issue? Should I attempt to transcode the file and re-upload it to the server? In this case it was an mp3 pulled from YouTube using JDownloader2.

Phone Model: Google Pixel 6
OS: GrapheneOS, version 2024030300
Android Version: 14

**Comment by advplyr** [comment]
That's not a known issue. Have you tried downloaded using local ip as a test?

**Comment by colvdv** [comment]
> Have you tried downloaded using local ip as a test?

How do I go about doing that?

**Comment by colvdv** [comment]
UPDATE: I tried again and it worked this time, weird. I wonder if it has something to do with my HDD. I'm feeling to replace it soon. Thanks!
