### ISSUE TITLE
Show downloaded books in continue listening shelf on home page

### ISSUE THREAD

**Issue by jt196** [advplyr/audiobookshelf-app#112]
### Steps to reproduce

1. Play downloaded book (Android device)
2. Close app
3. Try to resume listening
4. Can't find last listened book

### Expected behaviour

- Book last listened should show up in Continue Reading section. instead, have to search for it again, or go to downloaded section. 
- Have tested this for non downloaded books and it works fine. 
- Playback progress seems to sync correctly

### Actual behaviour

- Recently played books don't show up in this section

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Pixel3

Stock or customized system: CalyxOS

**Comment by tvories** [comment]
I have experienced this exact same bug, so +1

**Comment by feerlessleadr** [comment]
As have I.

**Comment by advplyr** [comment]
Continue listening shelf implemented when offline in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
