### ISSUE TITLE
iOS attempt to stream fails

### ISSUE THREAD

**Issue by Fut1l3** [advplyr/audiobookshelf-app#1128]
Book is The Making of the Atomic Bomb.

iPhone 13 Pro - iOS version 17.4
audio bookshelf version 0.9.73-beta
connects to docker audio bookshelf v 2.8.0

Attempted several times to stream this book through the app, however following pressing the stream button the app gets stuck animation of loading.

The book is listed in the app as 1GB in size.

Workaround:  Connect to audio bookshelf via the web browser.  Select Play.
![IMG_0377](https://github.com/advplyr/audiobookshelf-app/assets/110137437/4f5a7474-64e0-4219-b2f1-83d73eed276e)

**Comment by advplyr** [comment]
I would need the audio file to reproduce the issue. Generally if it is a one-off audio file causing a problem I suggest re-encoding the file because most of the time it is a poorly encoded audio file.
