### ISSUE TITLE
[Bug]: Android Audiobook Playback Resumes a Few Moments After Last Session

### ISSUE THREAD

**Issue by LordNyrox** [advplyr/audiobookshelf-app#1129]
### Describe the issue

When using the android app, there is a bug that causes playback to resume a few moments after where the last session ended when the user stops and wants to continue listening later. Instead, the playback should resume exactly from the point where the user left off.

### Steps to reproduce the issue

1.Open the audiobook app and start listening to an audiobook.
2.Listen to the audiobook for a while, then pause or stop playback.
3.Close the app or switch to another task.
4.Return to the app later and attempt to resume playback.

### Audiobookshelf version

v.2.8.0

### How are you running audiobookshelf?

Windows Tray App

**Comment by advplyr** [comment]
Have you tested the setting that @nichwall pointed out? Is this issue resolved?
