### ISSUE TITLE
Material Design/You styling

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf-app#113]
### Is your feature request related to a problem? Please describe.
More material design styling. But the biggest thing for me at the moment is option to remove wood backgrounds.

**Comment by advplyr** [comment]
New release has a list view. Still need to come up with an alternative design for the home page that shows the shelf labels.

**Comment by advplyr** [comment]
[v0.9.41-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.41-beta) includes a list view that persists.

Still waiting on a better design for the home page.

**Comment by SenorSmartyPants** [comment]
List view is nice. But the option to disable wood everywhere would be wonderful. 

Thanks for a great app.

**Comment by advplyr** [comment]
Getting there!

**Comment by advplyr** [comment]
As of [v0.9.55-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.55-beta) you can now use alternative bookshelf view
