### ISSUE TITLE
automatically download podcast episodes

### ISSUE THREAD

**Issue by theballdredge** [advplyr/audiobookshelf-app#1132]
### Describe the solution you'd like
It would be great if the app would automatically download new episodes from the server instance automatically when it syncs.

### Describe alternatives you've considered
Doing it manually is kind of a pain.

**Comment by nichwall** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/613

**Comment by advplyr** [comment]
Duplicate of #613
