### ISSUE TITLE
Unable to pause audiobook from iOS control center or Lock Screen.

### ISSUE THREAD

**Issue by sevenlayercookie** [advplyr/audiobookshelf-app#1134]
### Steps to reproduce

1. Play a book.
2. Swipe open control center or lock iPhone.
3. Attempt to pause from the control center or Lock Screen. 

### Expected behaviour
- should allow pausing of currently playing audiobook

### Actual behaviour
-pause button is grayed out and does not respond to touch

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [x] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 17

iPhone model: 13 Pro

**Comment by advplyr** [comment]
What version of the app are you using?

Is this happening for a specific book or multiple books? Are these downloaded books or books you are streaming?
