### ISSUE TITLE
Podcast playlist screen says x Podcasts instead of Playlists

### ISSUE THREAD

**Issue by politas** [advplyr/audiobookshelf-app#1135]
### Steps to reproduce

1. Switch to playlists tab 
2. Look at top of window

### Expected behaviour
- Should say _n_ Playlists

### Actual behaviour
- Says _n_ Podcasts

### Environment data

Audiobookshelf Version: 2.8.0 (0.9.73-beta app) 

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 11 (11.1.2.2) 

Device model: oneplus 6

Stock or customized system: stock
![Screenshot_20240315-205509.jpg](https://github.com/advplyr/audiobookshelf-app/assets/2109967/637a2207-fd4a-4d41-a2d2-e67c5c393c9e)

**Comment by politas** [comment]
Note, I have 26 podcasts and 2 playlists.

**Comment by advplyr** [comment]
Fixed in [v0.9.74-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.74-beta)
