### ISSUE TITLE
Separate Speed Controls 

### ISSUE THREAD

**Issue by darthrater78** [advplyr/audiobookshelf-app#1138]
It would be great to have separate speed settings for podcasts versus audiobooks. I tend to listen to audiobooks at a slower rate, and having to adjust back and forth is a bit tedious.

**Comment by nichwall** [comment]
Duplicate of: https://github.com/advplyr/audiobookshelf/issues/1785

Related to:
https://github.com/advplyr/audiobookshelf/issues/1173
https://github.com/advplyr/audiobookshelf-app/issues/1039

**Comment by advplyr** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1785
