### ISSUE TITLE
Pause not working from notification card.

### ISSUE THREAD

**Issue by Mssol94** [advplyr/audiobookshelf-app#1141]
### Steps to reproduce

1. Have a audiobook playing
2. Go to settings
3. Change jump back interval 
4. Use pause audiobook from notification card or use AirPods to play/pause

### Expected behaviour
- The audiobook should pause.

### Actual behaviour
- The audiobook jumps back a couple of seconds and continue playing. To pause the audiobook I have to use the controls in the app.
- If I force close the app and open it again play/pause works as expected.

### Environment data

Audiobookshelf Version: 2.7.1

- [x]  iOS App

#### iOS Issue
iOS Version: iOS 17.4

iPhone model: iPhone 14 Pro Max

**Comment by nichwall** [comment]
Related to https://github.com/advplyr/audiobookshelf-app/issues/1134 ?

**Comment by pgrosslicht** [comment]
I've also experienced the same issue. It seems to only occur when the jump back or forward interval has been changed this restart. I've attached a video of it happening. Until 0:30 you can see pausing works on the lock screen, then I change the jump forward interval 10 -> 5 -> 10, play again and when I try pausing again it looks paused, but the audio actually jumps back a bit and starts playing again. Further pausing/unpausing on the lockscreen just make playback start over and over from that point.
Here's the application logs during the video: https://gist.github.com/pgrosslicht/71e2db7d61a186ec402893012a3de6e8

https://github.com/advplyr/audiobookshelf-app/assets/1881000/9b4596f9-24e8-4bae-8a7e-56e10befb12d
(Video has sound so you can hear the playback as well)

I hope that helps a bit!

**Comment by indiefan** [comment]
I'm able to reproduce this issue and am starting to look into it.

**Comment by indiefan** [comment]
Debugger captures this as the result of multiple calls to the `commandCenter.pauseCommand` target we define in `AudioPlayer` (despite only pressing the pause button once).

So what's happening is that it successfully pauses only to immediately call the target again, which then unpauses. Still looking into root cause (seems we're probably calling `setupRemoteTransportControls` too many times?)

**Comment by advplyr** [comment]
Fixed in [v0.9.74-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.74-beta)
