### ISSUE TITLE
Bookshelf Empty

### ISSUE THREAD

**Issue by zahroc** [advplyr/audiobookshelf-app#1144]
### Steps to reproduce

1. Every time I open the app, it states "Bookshelf empty"
2. Select any other tab, it loads with books
3. Come back to the home tab and it populates

### Expected behaviour
- Home screen should populate on loading the app

### Actual behaviour
- show bookshelf empty

### Environment data
ABS IOS Version 0.9.73-beta
ABS Server Version 2.8.1 (Docker version running on Synology)

Audiobookshelf Version:

- [ ] Android App?
- [x ] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 17.4

iPhone model: 14 Pro

**Comment by zahroc** [comment]
yes, every time

**Comment by zahroc** [comment]
I am using the app connecting to my server via a URL and not the internal IP, so no, it would not be over a local network. I am sitting on the same network with my wifi connections but not connecting directly to the server IP.

**Comment by advplyr** [comment]
Are you able to test that?

**Comment by zahroc** [comment]
changing it to local IP and using it on the wireless, it works every time. I went back to public URL and it fails until I select a different tab, must have something to do with latency as you said????

**Comment by advplyr** [comment]
It may have to do with your server rejecting the request. If it works with the local ip address it suggests that this isn't an issue with the app so unless we can get more information I'm not sure what can be done
