### ISSUE TITLE
Allow self-signed certificates for https connections to locally deployed services

### ISSUE THREAD

**Issue by schloege** [advplyr/audiobookshelf-app#1152]
### Steps to reproduce

1. deploy audiobookshelf-app in home network (docker, reverse proxy traefik etc,, internal DNS)
2. use self-signed certificate for https
3. connect to service within local network from android app

### Expected behaviour
- Connect to server as indented

### Actual behaviour
- Error: Failed to contact server. (ERROR: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.)

### Environment data

Audiobookshelf Version:
0.9.73-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version:
9

Device model:
Galaxy S8

Stock or customized system:
Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
What is needed for this? I'm not aware of anything to change in the app for this. I thought that these self-signed certs were something you registered on the device and is not associated with a particular app.

**Comment by schloege** [comment]
Hi @advplyr, sorry for not responding earlier and thanks for getting back to me so quickly ;) I really like the app and have started hosting and using it regularly. However I need o use http to connect to my server as the self signed certificate I added to my phone does not help in connecting. The issue could be me being too dumb to set this up correctly but I am kind of out of ideas. Do you have any experience with this?

**Comment by peterahunt** [comment]
I can reproduce this, the app needs to be able to connect to http for local connections, or have a way to verify self-signed certificates.

**Comment by TheLordDuck** [comment]
> You need to add the self-signed root CA to your devices. At least on iOS, multi-step process where after adding it, you have to install it under Settings → General → VPN & Device Management. Then, you have to go under Settings → General → About → Certificate Trust Settings and enable full trust for the newly added root CA.
> 
> Details here: https://support.apple.com/en-us/102390

Not enough to make it work in the app, even changed compose file of traefik to accept certificate but not validate it, like this works, but the moment it has to validate it doesnt work.

**Comment by danielnegreiros** [comment]
Why not making available an option to disable tls verification on the client?
