### ISSUE TITLE
[IOS] After Downloading Podcast shows 100% when trying to play.

### ISSUE THREAD

**Issue by drice000** [advplyr/audiobookshelf-app#1159]
### Steps to reproduce

1. Go into podcast library
2. Go to podcast
3. In the list of episodes of that podcast hit the download button / or go into the episode itself hit download there
4. Once episode downloads and turns to play instead of stream, hit the play
5. Episode acts like it fully play and progress shows 100%

### Expected behaviour
- Downloaded Episode should play like how a stream of the podcast would

### Actual behaviour
- Acts like podcast fully played and shows 100% progress, stream from server behavior works fine.

### Environment data

Audiobookshelf Version: Server 2.8.1

- [ ] Android App?
- [X] iOS App?

#### iOS Issue
App Ver: 0.9.73-beta

iOS Version: 17.3.1

iPhone model: 14 Pro

**Comment by advplyr** [comment]
Does the podcast episode you are downloading have progress already or is marked as finished before downloading?

Have you reproduced this with other episodes?

**Comment by drice000** [comment]
These are podcast episodes that only downloaded to the server, no progress on them. They don't get mark as finished until I attempt to listen, so I will hit the download button let it download and then once finished I will attempt to play. The milisecond after I hit play it will go to 100 percent progress. If I try to use the progress bar and go back to the beginning it will just spin. It happens with multiple episodes, but the podcasts it happens on is random. Some podcast episodes will work and some will have this issue but it always the same podcasts.

**Comment by advplyr** [comment]
Is the actual audio file that is downloaded playable? Does the duration look correct if you press "More Info" on the library file?

![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/c367dc51-4b72-4c8e-83ac-bf46cdfefdbd)
