### ISSUE TITLE
Podcast - Add to Queue/Play Next

### ISSUE THREAD

**Issue by Eschguy** [advplyr/audiobookshelf-app#1164]
### Describe the solution you'd like
This essentially would replicate a feature from Google Podcasts (R.I.P). You could be listening to a Podcast, double tap any episode of any podcast, and it would play that one after the current one ended. 

My thoughts is an easy to manage queue (or a default playlist maybe) for that listening session/day. 

### Describe alternatives you've considered
Having a persistent playlist running works, but isn't as convenient as a temporary queue. 

### Additional context
I know it might not be the highest priority feature, but one my wife missed today (her first day using ABS!).

**Comment by nichwall** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/416

**Comment by Eschguy** [comment]
> Duplicate of #416

Nuts, I searched and didn't see it. You're correct.
