### ISSUE TITLE
iOS Audiobook plays automatically at night without any user interaction

### ISSUE THREAD

**Issue by neilasiii** [advplyr/audiobookshelf-app#1165]
### Steps to reproduce

1. Listen to ABS during the day. 
2. Stop book and close the app
2. iPhone plugged into charger next to bed
3. Around 0200+- audiobook starts playing with phone locked and inactive for 4+ hours. 
5. Lock Screen widget doesn't work to stop the book. 
6. Only way to stop the book if force close the app. 

### Expected behaviour
- book should only play with user interaction. 

### Actual behaviour
- book plays most nights around 0200 after hours of non use without user interaction. Only way to stop it from playing is to force close the app. 

- For a while I suspected there was something weird happening after Proxmox runs backups of my VM (hosting ABS). Backup occurs at 0100. But I had the same issue while I had backups turned off. 

### Environment data

Audiobookshelf Version: docker v2.8.1 on Ubuntu 22.04

- [ ] Android App?
- [x] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 17.3.1

iPhone model: 12

**Comment by neilasiii** [comment]
Upon further inspection, two sessions show up in the Listening sessions section for this event:

![image](https://github.com/advplyr/audiobookshelf-app/assets/17012908/72e7470a-6b2a-42e9-85a8-096c69c05d77)

**Comment by advplyr** [comment]
This is only for downloaded books?

**Comment by neilasiii** [comment]
> This is only for downloaded books?

I think so, it's only the last played downloaded book

**Comment by advplyr** [comment]
Is this resolved now on the latest release?

**Comment by neilasiii** [comment]
I believe so. I haven’t noticed it happening again. ThanksSent from my iPhoneOn Jun 17, 2024, at 17:47, advplyr ***@***.***> wrote:﻿
Is this resolved now on the latest release?
