### ISSUE TITLE
Allow streaming/downloads from WiFi connections only, disable streaming/downloads from mobile connections

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf-app#1166]
### Is your feature request related to a problem? Please describe.
For one of my friends, they have a very limited mobile data plan on their mobile device, thus streaming/downloading should be avoided when they are not connected to WiFi

### Describe the solution you'd like
A toggle in Settings that says "Connect to WiFi only". When enabled, any attempt to stream/download book will result in a error message.

**Comment by nichwall** [comment]
Related to https://github.com/advplyr/audiobookshelf-app/issues/247

They may want to look at NetGuard (no root firewall) on Android. It allows you to control data connections by app based on whether you are connected to WiFi or mobile data. However, this would prevent their phone from syncing on mobile data if they block ABS.

I use NetGuard to block a lot of apps when on mobile data for the same reason.

**Comment by ZLoth** [comment]
> Related to #247
> 
> They may want to look at NetGuard (no root firewall) on Android. It allows you to control data connections by app based on whether you are connected to WiFi or mobile data. However, this would prevent their phone from syncing on mobile data if they block ABS.
> 
> I use NetGuard to block a lot of apps when on mobile data for the same reason.

The syncing of the book status is very low in the bandwidth compared to streaming/downloading the media. Thus, completely blocking traffic isn't a good idea here.

**Comment by mfcar** [comment]
I've been checking other apps that offer options to limit streaming/download over mobile networks, and I've found the following implementations:

-----
**Overcast:** Provides an option to allow downloads only over Wifi or both Wifi and Cellular. If you attempt to download an episode over a mobile network, the app will ask if you want to permit that episode to be downloaded over the cellular network.

<img width="395" alt="image" src="https://github.com/advplyr/audiobookshelf-app/assets/814828/f7b49537-ac99-4190-b3e7-f251e684ae3d">

---

**Apple Podcast:** Very similar to Overcast, but it also has an option to block downloads if they exceed a specific size.

<img width="395" alt="image" src="https://github.com/advplyr/audiobookshelf-app/assets/814828/8a891ed5-4eab-438b-981d-334c45dae214">

---

**Pocket Cast:** Offers options to allow downloads only over wifi, and an option to warn if streaming is being done over cellular.

<img width="395" alt="image" src="https://github.com/advplyr/audiobookshelf-app/assets/814828/3b150388-7616-4801-ab6d-28fd805106e3">

---

**Audible:** Provides an option to allow streaming and downloading only from wifi.

![IMG_1654](https://github.com/advplyr/audiobookshelf-app/assets/814828/3d3bca0b-7895-4f2f-921f-d738dc833f6f)

---

**Castro Box:** Similar to Pocket Cast. It has an option to allow downloads over cellular and an option to warn if streaming over cellular or only play.

<img width="395" alt="image" src="https://github.com/advplyr/audiobookshelf-app/assets/814828/d47baa95-9df1-431e-bebe-f7a67ba28399">

---

**Spotify:** This app provides an option to allow downloads using cellular data.

![IMG_1662](https://github.com/advplyr/audiobookshelf-app/assets/814828/e24d0d63-93a7-4aab-ad76-5961cfffb6b2)

---

**Prologue:** This app offers an option to always allow downloads via cellular, or to turn it off, or to require confirmation.

<img width="395" alt="image" src="https://github.com/advplyr/audiobookshelf-app/assets/814828/72bed5fc-d7b2-455d-8856-17ad40d7ac3f">

---

**Podbean:** This app provides options to allow cellular downloads and cellular streaming.

![IMG_1658](https://github.com/advplyr/audiobookshelf-app/assets/814828/170e732d-696f-44ae-b8cd-f1d22eb784a4)

---

All of these applications have very similar options.
In general, I think a good implementation could be:
 - Allow cellular downloads (on, off, require confirmation)
 - Allow cellular streaming (on, off, require confirmation)

**Comment by ZLoth** [comment]
> I've been checking other apps that offer options to limit streaming/download over mobile networks, and I've found the following implementations:

Very detailed. Thank you. 

> All of these applications have very similar options. In general, I think a good implementation could be:
> 
> * Allow cellular downloads (on, off, require confirmation)
> * Allow cellular streaming (on, off, require confirmation)

Agreed. I'm very fortunate that I have unlimited data for streaming, but will still prefer to do the downloads on a WiFi network.

**Comment by mfcar** [comment]
I have started working on a prototype for this new setting. Feedback is appreciated.
#1210

**Comment by Maxklos** [comment]
I think it's an great Idea. If you build an APK for me, I can test it on Android 14

**Comment by mfcar** [comment]
> #1210

Sorry for the delay. I'm not familiar with the Android ecosystem and was trying to set up the development environment on my machine.  #But, I found that the APKs are built automatically. 
Here is the APK for the PR:
https://github.com/advplyr/audiobookshelf-app/actions/runs/9246204920

**Comment by ZLoth** [comment]
Thank you!
