### ISSUE TITLE
Continuously switch to the previous song

### ISSUE THREAD

**Issue by gsh456** [advplyr/audiobookshelf-app#1172]
### Steps to reproduce

1. when i play audio
2. Dropdown notification bar
3. the player auto  Continuously switch to the previous song

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data

Audiobookshelf Version: 0.9.73-beta

- [ ] Android App?

#### Android Issue
Android version: android 14 

Device model: xiaomi14

Stock or customized system: xiaomi hyperOs 1.0.35.0 

https://github.com/advplyr/audiobookshelf-app/assets/23634685/f592c77f-5558-4c3c-9668-3088caf63c98

**Comment by advplyr** [comment]
Is this with many audio files or a specific one? What file format is this? mp3 or m4b?

**Comment by gsh456** [comment]
All folders have this problem. I suspect that the button in the notification bar is not compatible with the system.

**Comment by wiyin** [comment]
> Is there more information you can provide about the type of media or anything that can help narrow this down a bit?
> 
> Just to confirm, every audiobook you have has the same issue, even single file audiobooks?

similar issue here.    single file audiobooks (both mp3 & m4a) works fine, multi-files audiobooks (both mp3 and m4a)has same issue as video

Android version: android 14
Device model: xiaomi14
Stock or customized system: xiaomi hyperOs 1.0.45.0
app version:  0.9.76-beta
