### ISSUE TITLE
Add 1.7x Playback Speed Shortcut

### ISSUE THREAD

**Issue by indiefan** [advplyr/audiobookshelf-app#1180]
### Is your feature request related to a problem? Please describe.
I frequently change playback speed between 2x and 1.7x (Sonos gets a little choppy at 2x). Not having a shortcut means more UI interactions and more changes in playback speed along the way. It also means I can't set the speed directly from carplay.

### Describe the solution you'd like
I'd like there to be a shortcut to directly set the playback speed to 1.7x (either replacing 3x or in addition to it)

### Describe alternatives you've considered
Letting users customize their playback speed shortcuts. But seems like probably overkill?

### Additional context
I don't have a direct data-driven argument to support, but I do have an implicit one. Audible provides a direct shortcut for 1.7x playback speed. Given their size, I suspect they've done UX research into these options (and possibly even run A/B experiments).

**Comment by advplyr** [comment]
Are you referring to this menu?
![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/994d1dbe-55ca-4459-a8f8-843a8fa56725)

**Comment by indiefan** [comment]
Yes, thanks!

**Comment by advplyr** [comment]
Added in [v0.9.74-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.74-beta)
