### ISSUE TITLE
Add Explicit Marker

### ISSUE THREAD

**Issue by MrBearedJoe** [advplyr/audiobookshelf-app#1181]
Add Explicit Marker next to the title of the book, just like the client version.

**Comment by ZLoth** [comment]
I agree. From the server:

![image](https://github.com/advplyr/audiobookshelf-app/assets/6700159/b95c62c8-10aa-4f25-967e-bc865557e386)
![image](https://github.com/advplyr/audiobookshelf-app/assets/6700159/35faf34c-0659-4913-b523-f51177816b68)

From the Android app:
![Screenshot_20240428-054258](https://github.com/advplyr/audiobookshelf-app/assets/6700159/d3fc9eb5-8b62-4b13-8dc9-15b884ec7ea0)
![Screenshot_20240428-054312](https://github.com/advplyr/audiobookshelf-app/assets/6700159/9d52b6b8-b33e-4ddf-b16e-62ca2a75594c)

**Comment by advplyr** [comment]
Added in [v0.9.74-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.74-beta)

**Comment by ZLoth** [comment]
> Added in [v0.9.74-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.74-beta)

Thank you. Looking forward to the release.
