### ISSUE TITLE
iOS app does not sync listening statistics to server

### ISSUE THREAD

**Issue by benonymity** [advplyr/audiobookshelf-app#119]
### Steps to reproduce

1. Check "Your Stats" page on server
2. Play audiobook on iOS app for any amount of time
3. Check "Your Stats" again, no time has been recorded

### Expected behaviour
- Listening to audiobook on mobile iOS app should sync progress and listening activity to the server.

### Actual behaviour
- Any time spent listening on the app does not appear in the statistics page of the server, so the listening isn't being reported somehow? When using web browser to listen, even on mobile, statistics do get reported and synced to the server, but not when using the app.

### Environment data

Audiobookshelf Version:

iOS App 0.9.40-beta

I don't have an android device to test, but I'd imagine the issue would also manifest itself there as that section of the codebase is probably shared, right? Can anyone confirm that?

#### iOS Issue
iOS Version: 15.4.1

iPhone model: iPhone SE 2020

**Comment by rasmuslos** [comment]
This is a known bug. We are currently rewriting the native audio players to handle the syncing themselves

**Comment by benonymity** [comment]
Seems to have been implemented in the latest iOS player commits. Thanks!
