### ISSUE TITLE
Connect to existing server from dev mobile-app

### ISSUE THREAD

**Issue by DenniLa2** [advplyr/audiobookshelf-app#1191]
I have an audiobookshelf server running on my local network. I can access it through both the web interface and the mobile app.

Today, I deployed the audiobookshelf-app project and ran `npm run dev`. I enter the server address in the browser, but I cannot connect.

web-app:
![image](https://github.com/advplyr/audiobookshelf-app/assets/9018493/f186cc5e-0b82-4d4d-9d52-45907831ea1e)

mobile-app interface in browser:
![image](https://github.com/advplyr/audiobookshelf-app/assets/9018493/10225839-d99d-4bb2-a9c3-6a4581b18410)

Browser console:
![image](https://github.com/advplyr/audiobookshelf-app/assets/9018493/86bb3c50-9b27-438d-af52-7e5856b50403)

Can you please provide me with the instructions for connecting to the server?

**Comment by advplyr** [comment]
You have to run a server in development so that CORS is disabled. You will be able to connect to servers in development from the browser. You can also test on a mobile device that won't have CORS issues.
We could had an env variable to disable CORS on production servers I guess
