### ISSUE TITLE
cant open on tablet A14 / page not found

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf-app#1192]
### Steps to reproduce

1. open any location (continue listening, recently added, ...) > no action

### Expected behaviour
- open any media

### Actual behaviour
- not open any media
- recent series > this page could not be found - also in series tab
- newest author > open library > open any media > home
- collections tab > open any collection > home
- playlists > cant open any entry

### Environment data

Audiobookshelf Version:
server: v2.9.0
app: 0.9.66-beta

#### Android Issue
Android version:
Android 11

Device model: 
SM-T725

Stock or customized system:
Stock

**Comment by nichwall** [comment]
Can you try with a newer version of the app? The newest app version is 0.9.73-beta.

The server version at the time of 0.9.66-beta was 2.4.3 and there have been a number of "page not found" issues since then and not sure if that old or an app version is supported with the server.

**Comment by skyzuma** [comment]
0.9.73-beta installed and all ok but thats strange: this version was only visible today, i look every day for any updates ... and if i see this correct, this version is from 3.3.2024? and today is the 27.04.2024 ...

**Comment by advplyr** [comment]
All the releases are here https://github.com/advplyr/audiobookshelf-app/releases where you can see the dates.

0.9.66 is too old to work with an up-to-date server
