### ISSUE TITLE
Downloads section does not scroll

### ISSUE THREAD

**Issue by stefanop1** [advplyr/audiobookshelf-app#120]
### Steps to reproduce

1. Download some audiobooks (5 or 6)
2. Visit the downloads section (any of the tabs)
3. Try to scroll

### Expected behaviour
- The list must scroll

### Actual behaviour
- The list is blocked

### Environment data

Audiobookshelf Version:  0.9.40-beta

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model: Xiaomi MI 10

Stock or customized system: Stock

**Comment by advplyr** [comment]
That page was removed in the latest release v0.9.41-beta
