### ISSUE TITLE
[Bug]: Certificate regression bug in Android 0.9.74b 

### ISSUE THREAD

**Issue by hydrian** [advplyr/audiobookshelf-app#1209]
### What was the Problem?

After upgrading to Android client 0.9.74, the client will not connect to the ABS server anymore. 

If you are logged in already, the client will just look like it is in offline mode. 

If you are not logged in, the client shows a TLS certificate error. 

### Steps to Reproduce the Issue

1. Logout of ABS server with client. 
2. Install 0.9.74b android client
3. Try to login with to ABS server with android client
4. Recieve TLS certificate error. 

### What was Expected?

Redirect for OIDC login 

### Phone Model

Moto G Stylus G5 2023

### Phone OS

Android  13 (stock)

### Audiobookshelf App Version

Android App - 0.9.63

### Installation Source

Google Play Store

### Additional Notes

My ABS server setup has been working fine for months. Only the android client broke after the 0.9.74 update which released 3 days ago. Rolling back to 0.9.73 is a viable workaround to 'fix' this issue. I made sure to test that my  android device can get to my ABS server and OIDC without any TLS errors in a browser and it could.

**Comment by advplyr** [comment]
This release did not change anything with authentication and no dependencies were updated.

https://github.com/advplyr/audiobookshelf-app/compare/v0.9.73-beta...v0.9.74-beta

No clue

**Comment by hydrian** [comment]
Looks like it may have been an app configuration corruption/migration issue. Deleting the app config and reinstalling the app resolved the issue. Closing the ticket.
