### ISSUE TITLE
Android progress not saving

### ISSUE THREAD

**Issue by droidile** [advplyr/audiobookshelf-app#121]
When playing on Android from the background the app does not save progress. When paused/resumed from the media controls, progress is preserved, but as soon as the app is brought to the foreground, all progress is lost.

**Comment by advplyr** [comment]
An update is coming soon that will fix this.

**Comment by advplyr** [comment]
Fixed in [v0.9.41-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.41-beta)
