### ISSUE TITLE
Call prepareLibraryItem when app starts

### ISSUE THREAD

**Issue by rasmuslos** [advplyr/audiobookshelf-app#122]
### Is your feature request related to a problem? Please describe.
The last playback session is not resumed when starting the new app

### Describe the solution you'd like
Resume the last playback session when the app starts

### Describe alternatives you've considered
Save the last session in the local DB and resume it

### Additional context
Occurs on both android and ios with the new players

**Comment by ronaldheft** [comment]
This will be implemented on iOS when PR #277 is merged.
