### ISSUE TITLE
[Bug]: Sleep Timer modal defaults to "Custom Time" only during first access after app start

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf-app#1224]
### What was the Problem?

The sleep timer in the mobile app defaults to "Custom Time" mode the first time the modal is opened after the app has been opened. After the sleep timer modal has been closed (either using back button or clicking out of modal) the Sleep Timer modal will default to the preset time view until the app is restarted.

Looks like this is due to https://github.com/advplyr/audiobookshelf-app/commit/8201f3c9a6c93d3a82c9345a2ee1def14eebf27f defaulting to `true` instead of `false`.

### Steps to Reproduce the Issue

1. Open ABS app after having app completely closed
2. Press sleep timer (observe sleep timer defaults to 1 minute of "custom time")
3. Press back button or click out of modal to close
4. Press sleep timer (observe defaults to "preset time" list until app is completely closed again)

### What was Expected?

Sleep timer should default to "preset list" every time.

### Phone Model

Pixel 6a

### Phone OS

Android 14, stock

### Audiobookshelf App Version

Android App - 0.9.74

### Installation Source

Google Play Store

**Comment by m0veax** [comment]
It is the same on iOS

Version 0.97.4-Beta
iOS 17.5.1
iPhone 13

If I can provide any more infos, let me know
