### ISSUE TITLE
[Enhancement]: Download all books by author or series

### ISSUE THREAD

**Issue by MadBobUK** [advplyr/audiobookshelf-app#1226]
### Describe the Feature/Enhancement

a bit faffy downloading 1 book at a time, Download all books by author or series

### Why would this be helpful?

android app for booksonic has this and i use all the time

### Future Implementation (Screenshot)

under ellipsis menu

### Audiobookshelf App Version

Android App - 0.9.74

**Comment by nichwall** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/188
