### ISSUE TITLE
[Bug]: chapter track not saved after 3 min mark iphone

### ISSUE THREAD

**Issue by radhoo2k10** [advplyr/audiobookshelf-app#1236]
### What was the Problem?

If I start listening a chapter and stops the playback and start again the playback, it starts the playback at 3:26. Even if I stopped at 10 min mark. This does not occur in the Android app, but it occur in the plappa app as well. 

### Steps to Reproduce the Issue

Start listening at the start of a chapter and pause playback at 5 min mark and start again. 

### What was Expected?

Start playing where I stopped. 

### Phone Model

iPhone 13 pro

### Phone OS

17.4.1 ios

### Audiobookshelf App Version

iOS App - 0.9.74

### Installation Source

Testflight

**Comment by nichwall** [comment]
Does this happen with all books or only that specific book?

**Comment by radhoo2k10** [comment]
Seems like it is just this book.

**Comment by nichwall** [comment]
It is probably an issue with the audio file itself and how seeking happens on iOS. You could also try using your mobile browser on iOS to see if it also has the issue, or look at the server Debug logs to see if sync events are showing up on the server (sync events should happen every 60 seconds).

You will likely want to re-encode the file.
