### ISSUE TITLE
[Bug]: iOS client app is unavailable

### ISSUE THREAD

**Issue by t0maz** [advplyr/audiobookshelf-app#1275]
### What was the Problem?

After clicking link to audiobookshelf in app store the page says "This beta is full."

### Steps to Reproduce the Issue

1. Navigate to https://www.audiobookshelf.org/ web page
2. Click/tap on "[Download on the App Store](https://testflight.apple.com/join/wiic7QIW)"

### What was Expected?

To be able to download/install iOS client app.

### Phone Model

iPhone 13 Mini

### Phone OS

iOS 17.5.1

### Audiobookshelf App Version

iOS App - 0.9.74

### Installation Source

Testflight

**Comment by nichwall** [comment]
The iOS is still in beta.

https://www.audiobookshelf.org/faq/app#how-do-i-get-an-invite-to-testflightthe-ios-beta-is-full
