### ISSUE TITLE
[Bug]: Downloaded Audiobook - Playback failed Source error

### ISSUE THREAD

**Issue by Klar** [advplyr/audiobookshelf-app#1277]
### What was the Problem?

Download Audiobook for offline listening mode. In offline mode i.e no Wif I see the book and start play, it gives me a loading animation and fails with the error:  `Playback failed Source error`

Other Audiobooks work. I did delete the files and re-downloaded the files with the same error.

### Steps to Reproduce the Issue

Download Audiobook and press play while in offline mode

### What was Expected?

Audiobook plays in offline mode

### Phone Model

GT-I9505

### Phone OS

Android 11 - Lineage OS

### Audiobookshelf App Version

Android App - 0.9.74

### Installation Source

SideStore

### Additional Notes

If I open the downloaded .mp3 files with VLC the file plays correct.

Audibook Server version is 2.11.0

**Comment by Klar** [comment]
streaming works, in the player menu on middle top it says direct, so I assume it is direct.

is there a helpful command in linux / ffmpeg to convert to a format which should be better? or command to give an output of the file for debug information.

**Comment by nichwall** [comment]
You could try running ffprobe on the file https://www.audiobookshelf.org/guides/ffprobe/#inspecting-an-audio-file or running the file through ffmpeg with the `copy` argument to recreate metadata on the file. Ffmpeg should provide more information while doing the copy if it finds problems with the file

**Comment by Klar** [comment]
Thanks for your help. I re coded the mp3 files and now it is working
