### ISSUE TITLE
[Enhancement]: Send Ebook to... on iOS app

### ISSUE THREAD

**Issue by drewjohnston13** [advplyr/audiobookshelf-app#1280]
### Describe the Feature/Enhancement

On the website there is an option "Send Ebook to..." to send and ebook to an E-reader, which I love. It would be excellent if this were extended to the iOS mobile app (and Android if it's not already supported).

### Why would this be helpful?

The experience of sending a book to my kindle right from the app is much more streamlined than navigating back to the site on a browser and signing in again just to click the Send Ebook to... button. 

### Future Implementation (Screenshot)

It could be exactly like the site version--just an option in the 3-dots drop down. Or if you wanted to make a dedicated button as has been done with Download. 

### Audiobookshelf App Version

iOS App - 0.9.74

**Comment by advplyr** [comment]
This is already supported using the 3-dot menu on the book page. Unless you are referring to something else?

**Comment by drewjohnston13** [comment]
Nope, that’s exactly what I’m referring to. I swear it didn’t show up on the app when I made this issue! haha I kept trying to do it in app and then had to go to the browser when I couldn’t. But now I see it right there in the drop down! Apologies for wasting your time.

**Comment by advplyr** [comment]
Yeah that is probably why. It only shows when you have a device setup and that information is loaded on app launch.
