### ISSUE TITLE
[Bug]: App crashes on playback VERSION 0.9.75

### ISSUE THREAD

**Issue by cordlord** [advplyr/audiobookshelf-app#1287]
### What was the Problem?

When trying to stream audio for audiobooks or podcasts, the app crashes.

### Steps to Reproduce the Issue

1. Find an audio source to stream.
2. Press play.
3. App crashes.

### What was Expected?

The audio will stream

### Phone Model

Samsung Galaxy S24 Ultra

### Phone OS

Android 14

### Audiobookshelf App Version

Android App - 0.9.74

### Installation Source

Other (List in "Additional Notes")

### Additional Notes

Installed through Aurora Store. Rolled back to version 0.9.74 and everything works perfect again.

**Comment by nichwall** [comment]
Can you try 0.9.76 from a few hours ago?

**Comment by derekcentrico** [comment]
Confirmed.  Mine also was crashing on .75.  Just updated to .76 and no longer crashes.

**Comment by cordlord** [comment]
Yep, updated and that fixed it!
