### ISSUE TITLE
[Enhancement]: Show playback in Media Output "drawer"

### ISSUE THREAD

**Issue by gavinorland** [advplyr/audiobookshelf-app#1289]
### Describe the Feature/Enhancement

For all other media apps that I use, a panel is shown at the top of the phone when you swipe down showing that that app is currently active and offering essential playback controls, and a seek control if it is further expanded. This panel, or "drawer", can be slid sideways to show other recently active media apps. I just noticed that ABS doesn't show up in here. I don't know if it does for anyone else, but it might be nice to have it do so. The particular example here is of Plexamp:

<img src="https://github.com/user-attachments/assets/38efa82e-887e-427c-a650-85fc49a98fef" width="250">

### Why would this be helpful?

Provides quick access to controls even if app is not in foreground.

### Future Implementation (Screenshot)

Just like the screenshot but it would show the book cover.

### Audiobookshelf App Version

Android App - 0.9.76

**Comment by nichwall** [comment]
Same as https://github.com/advplyr/audiobookshelf-app/issues/768

**Comment by gavinorland** [comment]
Hm, yes, I suppose so, though I think the dscription there is slightly confused/confusing:

- That issue is entitled "Keep audiobook playing in background when android app is closed". The audiobook _does_ in fact keep playing when the app is "closed" (i.e. not in foreground, though not - of course - when the app is completely stopped).
- The issue of a media drawer doesn't pertain only to background apps. That panel is added even when the app is only ever in the foreground. In the case of ABS, it seems it is never added.

I'll leave this to be picked up under that one anyway.

**Comment by gavinorland** [comment]
Duplicate of #768

**Comment by gavinorland** [comment]
fyi @advplyr I'm not sure if there has been an update, but with regard to this specific issue of ABS's playback not appearing in the "media drawer" on Android, I'm pleased to report it _is_ now appearing for me, just like other media apps.
