### ISSUE TITLE
Library empty and can't log out of Android App

### ISSUE THREAD

**Issue by brandonhowlett** [advplyr/audiobookshelf-app#129]
After the most recent Android app update, 0.9.41-beta, series and collections still exist but my library is empty. I'm also unable to log out. Once clicked the logout button turns grey but nothing happens.

**Comment by Thovi98** [comment]
Did you upgrade your server to v2.0.0 ?
This new update doesn't work with server < 2.0.0

**Comment by advplyr** [comment]
There was a bug introduced in the server release last night, that is fixed now so please patch your server again.

**Comment by brandonhowlett** [comment]
The most recent server release solved both problems. That's what I get for
updating anything away from the lab. Strong work folks!
