### ISSUE TITLE
[Bug]: Audiobookshelf has expired - iOS

### ISSUE THREAD

**Issue by listy-bit** [advplyr/audiobookshelf-app#1293]
### What was the Problem?

Can’t open app. Message as in headline. 

### Steps to Reproduce the Issue

Press on app icon

### What was Expected?

App would open

### Phone Model

iPhone 11

### Phone OS

iOS 17.2.1

### Audiobookshelf App Version

iOS App - 0.9.76

### Installation Source

Testflight

**Comment by nichwall** [comment]
Did you update to 0.9.76 in Testflight? New spots will be released today or tomorrow (depending on when they are actually released by Apple)

**Comment by listy-bit** [comment]
iOS auto-offload took TestFlight off because it wasn’t frequently “used”, so no update notification for ABS. Silly Apple. Resolved.
