### ISSUE TITLE
No authorization for download folder

### ISSUE THREAD

**Issue by Maximilian85** [advplyr/audiobookshelf-app#13]
I can't select a folder to download. I always get the message access denied. The system asks whether the access should be allowed and even a manual assignment of rights in the app settings do not help. 

System:
Xiaomi 9 lite
Android 10 
MIUI 12.0.10 

Good work from server and app keep it up !

Edit: 
I can only select the "Download" system folder. But then the app hangs when trying to download. 
Good work from server and app keep it up !

**Comment by leonbroadbent** [comment]
I am seeing this same issue. I have also tried internal and SD storage.

System:
Sony Xperia (H8296)
Android 10

![Screenshot_20211015-141341](https://user-images.githubusercontent.com/44085448/137416938-33fad9c4-3d23-4978-ad88-511b00505efc.png)
![Screenshot_20211015-141426](https://user-images.githubusercontent.com/44085448/137416940-78e99f62-b119-42d7-8958-624588504ff8.png)

**Comment by advplyr** [comment]
I wasn't able to emulate your exact devices, but when testing on a Pixel 2 w/ Android 10 I did find a bug.

I could only download to the public download folder, and even then the download was hanging like @Maximilian85 mentioned.

I was able to fix the hanging issue and have successful downloads to the download directory, but I wasn't able to resolve the issue of choosing different folders.
The update will be live in an hour or so, I will follow up.

**Comment by Maximilian85** [comment]
The new version was available yesterday (0.9.5). I have deleted all old versions but unfortunately the error is unchanged with me. I can't set a folder as download target. It always follows the error message access denied. The app asks for the permission which I also give and also manually assigned.

**Comment by Maximilian85** [comment]
Yes, in the previous version I was able to select the download folder, but in the current version this is no longer possible.

**Comment by Maximilian85** [comment]
I'm sorry it was my mistake, I opened the download folder from the system storage and that doesn't work. You have to select the direct download folder from the app. 

Xiaomi 9 lite: Download folder can be selected, but when trying to download an audio book, the app just closes without further notification. 

Samsung S8: Download folder can be selected and the download also works.

**Comment by Maximilian85** [comment]
Xiaomi 9 lite: Android 10
Samsung S8: Android 9 (no longer receives official update)

Since my programming skills are limited. 
I am glad that I can help the project at least in another way.

**Comment by advplyr** [comment]
The issue @leonbroadbent is having isn't a crash, it appears to be the same issue I identified earlier.

I found 2 more bugs with the download that I fixed and released `v0.9.8-beta`, which will be live in the google play store soon.
One of the bugs had to do with Android 10 not detecting downloaded audiobooks after closing and re-opening the app.
The other one was unnecessary thread pool getting used.

**Comment by Maximilian85** [comment]
v0.9.15-beta

The new functions work for me but still only if I use the direct download folder without subdirectories. The download is done in a new subfolder that is created by the APP. 

If I select another folder, there is the following error message and the app closes directly. 

![IMG_20211101_115410](https://user-images.githubusercontent.com/76774860/139662069-4f52dd1d-bc2b-40bf-ae85-4fc2675d02f9.jpg)

**Comment by Maximilian85** [comment]
Here I wanted to give you an update. I can now select all orders in the download area, including subfolders. For other storage areas, the app says that I do not have permission. I am asked if I allow access, but even if I agree, the app reports this.

**Comment by wtanksleyjr** [comment]
I can confirm I see at least one version of this issue on my Android 10 device (Moto Power 2021): when I download a book, I'm asked to choose a folder (using the standard system UI), it allows me to pick any folder, pops up a "do you want to grant permissions" system dialog, and then the app displays a red message saying that no permissions were granted.

I do have one detail I don't see above: first time I got this message, I went to the app's details page, and found that sure enough, the app wasn't granted Storage permissions. I manually granted that ... but with or without permissions the same process happens every time, exactly as described above.

**Comment by jparrish88** [comment]
Samsung Galaxy Note 9
Android 10

Hi, (Really appreciate everything that this app and the self hosted software do) , I just wanted to report that I was seeing the same issue with the permissions problem. 

In this case, I had already downloaded a book, read it locally (not streamed). The reading went well, no problem. Then I read another book, it was pretty much all at once. I then erased both books and left the app for a good 16 hours or so. I just reopened it, looking to download another audiobook locally.  This time it told me I didn't have the correct permissions. So I pressed the "click here" Nothing happened for awhile, but it popped up the same file directory structure it had before and I asked if I would give it permission. I did. However, nothing happened. I clicked again nothing happened. I double checked that I had given the app permissions similar to what other published above. I checked the app again, and suddenly it was working again. I was able to download a book again and am listening to it now. 

If I see it again, I'll try to take screenshots and record my actions more accurately. Is there anything I can do for a "provide you more debug information" the next time (if) it happens again?

**Comment by advplyr** [comment]
Please try again with the latest release v0.9.43-beta

**Comment by wtanksleyjr** [comment]
0.9.43-beta (also upgraded the Docker container while I'm at it) shows the
same permission denied that all the other versions I've tried have. I also
tried again on both Download folders just in case something had changed. So
no downloading still, unfortunately.

moto g power (2021) Android 10 (October 1 patch)

-Wm

**Comment by advplyr** [comment]
@wtanksleyjr  please try the workaround here: https://github.com/advplyr/audiobookshelf-app/issues/115#issuecomment-1114308743
There are a few issues open now for download permissions so I'm going to close this one.
