### ISSUE TITLE
Author images missing in android app

### ISSUE THREAD

**Issue by TK3D** [advplyr/audiobookshelf-app#131]
### Expected behaviour
- Display of author pictures on the Home tab.

### Actual behaviour
- Authors images are missing in the mobile app, while being present in the web app.
Screenshot of issue: [[imgur link]](https://imgur.com/a/cePWIBT)

### Environment data

Audiobookshelf Version: v2.0.1 on Ubuntu 21.04 (docker)
App Version: 0.9.41-beta (android)

#### Android Issue
Android version: 12

Device model: Samsung S22 Ultra

Stock or customized system: Stock

**Comment by TK3D** [comment]
Confirming that [b72aba3](https://github.com/advplyr/audiobookshelf-app/commit/b72aba36b821084cbf33a173e8f541d31d3a0ba0) fixed it for me

**Comment by advplyr** [comment]
Are you building from source? Google hasn't approved the latest release yet.

**Comment by TK3D** [comment]
Yes, I built from source
