### ISSUE TITLE
proxy no longer works after update to server 2.0.1 and app 0.9.41-beta

### ISSUE THREAD

**Issue by bobnvic** [advplyr/audiobookshelf-app#133]
### Steps to reproduce

1. Update server to 2.0.1
2. Update android app to 0.9.41-beta
3. Use same proxy address audiobooks.example.com for server as used prior to update

### Expected behaviour
- Request username and password

### Actual behaviour
- error message "Failed to ping server"

### Environment data

Audiobookshelf Version: 2.0.1

- [X ] Android App? version 0.9.41-beta
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Pixel 3XL

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

Other notes:
Apache proxy config based on example in audiobookshelf docs. Worked fine prior to update. Works if URL and port is used. Proxy works for web gui just fine.

**Comment by advplyr** [comment]
Were you the one in discord that resolved this issue?
I don't believe this is a bug with audiobookshelf.

**Comment by bobnvic** [comment]
My apologies, it was my proxy setup. It wasn't that the proxy was setup incorrectly, but that I needed to use https and had only used http in the address. User error. Sorry for the noise and any wasted time!
