### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Gadgetroch** [advplyr/audiobookshelf-app#1333]
### What was the Problem?

For now, in background, this app use a large amount of battery.

Even if the minuteur is finished, battery is always used.

### Steps to Reproduce the Issue

Use this app in backgroup

### What was Expected?

Use less battery

### Phone Model

Redmi note 13 pro

### Phone OS

Xiaomi Hyper OS

### Audiobookshelf App Version

Android App - 0.9.76

### Installation Source

Google Play Store

**Comment by nichwall** [comment]
Can you define a "large amount of battery", like share screenshots of battery usage for the app?
