### ISSUE TITLE
[Enhancement]: manage and download audio tracks separatly

### ISSUE THREAD

**Issue by takov751** [advplyr/audiobookshelf-app#1337]
### Describe the Feature/Enhancement

A feature similar to the web interface to download and manage Audio Tracks / Library Files of a  specific audiobook. That includes deleting them as well especially after listening. To have an option to download only remaining audio tracks only when you are in the middle of an audiobook would be a boon .

### Why would this be helpful?

In my case I have an audiobook, where each Audio Track/ Library File is a book from the series 17GB all together. And it causing issues storing all of them, instead of the ones i am still listening to.  

### Future Implementation (Screenshot)

The option to partially download book automatically the remaining audio tracks, could be asked when you are press download on a audiobook that had been started. `Would you like to download every/specific tracks?  [All ] [ Remaining ] [Cancel ]`

Local Item section: should be a subfolder when you click on a book that includes library files. Where it can be removed separately.  If library file unavailable it should be streamed. 

### Audiobookshelf App Version

Android App - 0.9.76, iOS App - 0.9.76

### Current Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/208676f7-4dc1-4cfe-999f-749e752574b2)

**Comment by Daemonias** [comment]
+1

**Comment by nichwall** [comment]
I can see the benefit for this, but you could also just split the series up into individual books by moving each file to its own folder so each book is a manageable size.

**Comment by takov751** [comment]
> I can see the benefit for this, but you could also just split the series up into individual books by moving each file to its own folder so each book is a manageable size.

Not going to lie. That is a perfectly reasonable solution, which i have ignored out of sheer laziness. 👍👍👍
