### ISSUE TITLE
Square covers on android

### ISSUE THREAD

**Issue by kaldigo** [advplyr/audiobookshelf-app#136]
### Steps to reproduce

1.Turn off square covers
2.Open android app
3.

### Expected behaviour
- covers to follow the server toggle

### Actual behaviour
- in the android app the toggle only changed the library tab. On the homepage it uses the generated square cover. On the book page and the player the cover is stretched to be square.

### Environment data

Audiobookshelf Version:

- [ x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Pixel 6

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by feerlessleadr** [comment]
Same issue here

**Comment by advplyr** [comment]
This was fixed in v0.9.42-beta
