### ISSUE TITLE
Unable to add bookmarks

### ISSUE THREAD

**Issue by kaldigo** [advplyr/audiobookshelf-app#137]
### Steps to reproduce

1. Try to add bookmark
2.
3.

### Expected behaviour
- The popup with bookmarks should show up and give the option to add one.

### Actual behaviour
- when I press the bookmark button I get the popup telling me there are no bookmarks but I don't get the option to add one (as if there is no connection to the server)

### Environment data

Audiobookshelf Version:

- [ x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Pixel 6

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by kaldigo** [comment]
So I dug into this a bit more and I do have the option if I close the stream and re open it. If the connection to the server drops for a second I can still listen as it seems to re connect but I can no longer add bookmarks and my progress is no longer saved from the moment the connection dropped.

**Comment by ChiefMedicalOfficer** [comment]
I get the option to add one but when I tap 'Create' nothing happens.
! [Screenshot_20220423-090835_audiobookshelf.jpg](https://user-images.githubusercontent.com/11256455/164886368-169bf21e-79c8-4d5e-aaf6-d6c2f59bba35.jpg)

**Comment by advplyr** [comment]
Ah yeah I forgot to move this over. Bookmarks no longer use the web socket, we have an API for bookmarks now.
Will include this fix in the update later today

**Comment by advplyr** [comment]
This was fixed in v0.9.42-beta
