### ISSUE TITLE
Audiobooks play at 1x when starting stream, regardless of playback speed setting previously set

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf-app#138]
### Steps to reproduce

1. Set playback speed on book to greater than 1x
2. Close stream
3. Open same book to start a new stream
5. Although playback speed is still set in the app according to step 1, actual playback speed is 1x

### Expected behaviour
- Playback speed should persist across stream sessions

### Actual behaviour
- App remembers playback speed setting, but actual playback speed of the book is 1x. To fix, I need to re-adjust the playback speed each time I open a stream. 

### Environment data

Audiobookshelf Version: v 2.0.1

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: v0.9.41-beta 

Device model: OnePlus 8T

Stock or customized system: Stock

**Comment by advplyr** [comment]
This was resolved in v0.9.42-beta
