### ISSUE TITLE
[Bug]: Item does not play on android app, web fine

### ISSUE THREAD

**Issue by sharinganthief** [advplyr/audiobookshelf-app#1389]
### What happened?

When attempting to play a book i see the loading circle forever and nothing plays

### What did you expect to happen?

for the item to play

### Steps to reproduce the issue

1. go to the book in the app and play it, not sure what the issue is so not sure how y'all can repro

### Audiobookshelf version

v2.17.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
2024-11-18 06:20:46.367 DEBUG [PlaybackSessionManager] startSessionRequest for device Pixel 7 SDK 35 / v0.9.76-beta

2024-11-18 06:20:46.367 INFO [PlaybackSessionManager] startSession: Closing open session "Solo Leveling, Vol. 07" for user "admin" (Device: Pixel 7 SDK 35 / v0.9.76-beta)

2024-11-18 06:20:46.368 DEBUG [PlaybackSessionManager] closeSession "0cbc02d7-b99a-4301-af38-29723fa11c63"

2024-11-18 06:20:46.369 DEBUG [PlaybackSessionManager] Removed session "0cbc02d7-b99a-4301-af38-29723fa11c63"

2024-11-18 06:20:46.369 DEBUG [PlaybackSessionManager] "admin" starting direct play session for item "45d6f248-78e2-462c-b8ec-e7c45dae5d0a" with id 3e0c7adc-879f-4f2c-bd42-343dc9adadb4 (Device: Pixel 7 SDK 35 / v0.9.76-beta)
```

### Additional Notes

Mostly looking for advice/info for more logging, android specific quirks maybe?

Books are the seventh and eighth in a series and I process all the media to have the same container, codec, bitrate, etc. The first 6 have worked fine so no idea why the last

Media Info for a working (left) and issue (right) file - both play in VLC just fine and both stream on the web app

![image](https://github.com/user-attachments/assets/a22f3c48-9cdd-43df-9f47-9bf5910e022f)

**Comment by sharinganthief** [comment]
[ApiCacheManager] Object.afterBulkUpdate: Clearing cache

2024-11-25 04:58:02.693

DEBUG

[PlaybackSessionManager] closeSession "10c61134-8fb9-4643-9191-ccaa5a96de5f"

2024-11-25 04:58:02.695

DEBUG

[PlaybackSessionManager] Removed session "10c61134-8fb9-4643-9191-ccaa5a96de5f"

2024-11-25 04:58:02.696

DEBUG

[PlaybackSessionManager] "admin" starting direct play session for item "4bbf90da-7e07-417b-8e16-0e2b9f48b6f4" with id eec7c7bb-63ed-46d9-bcfa-945a04a35959 (Device: Pixel 7 SDK 35 / v0.9.76-beta)

2024-11-25 04:58:27.383

DEBUG

**[SocketAuthority] User Offline admin**

2024-11-25 04:58:27.385

INFO

[SocketAuthority] Socket orjDq3ZmjVAqnx7CAACp disconnected from client "admin" after 117365ms (Reason: transport close)

2024-11-25 04:58:27.967

INFO

[SocketAuthority] Socket Connected rQaRQbuFSrfXJBBWAACr

2024-11-25 04:58:28.026

DEBUG

[ApiCacheManager] count: 0 size: 0

**Comment by sharinganthief** [comment]
uninstalled google play version and pulled latest release form github, i think i see the User Offline admin from socket authority each time it fails, not sure if that is relevant or not

**Comment by sharinganthief** [comment]
copied and renamed a working file and no dice. 
pulled down lissen latest and it plays just fine.  
starting to think it's explicitly the app since web and lissen work and working file copied in doesn't. 
can I build the app with like more logging calls or something?

**Comment by nichwall** [comment]
What do you mean by "copied and renamed"? So you just renamed a file which was working the ABS mobile app and now it is not working?

Are you streaming or using a downloaded file?

**Comment by sharinganthief** [comment]
like 5 was working so copied it to 7s dir and renamed to 7 to rule out file issues

**Comment by sharinganthief** [comment]
pulled down the app, fought android studio to get it working and break pointed the hell out of it. in the jaon deserialization there was an error, digging into the payload there was an ebook with Chinese characters abs didn't like so it had question marks. deleted the offending file, rescanned, all good now.

tempted to say since that can be an issue we should open a bug on abs proper to either replace bad chars, ignore bad files or at least ignore specific ones per book or something. 

weird bug
