### ISSUE TITLE
Add "play" button to play latest podcast episode

### ISSUE THREAD

**Issue by rasmuslos** [advplyr/audiobookshelf-app#139]
### Is your feature request related to a problem? Please describe.
You have to scroll for a long time to resume a podcast

### Describe the solution you'd like
Add the "play" button present in the web app

### Additional context
![IMG_94CF5483F552-1](https://user-images.githubusercontent.com/49640416/164916512-94d67293-f858-4669-8685-3eefb941480f.jpeg)

**Comment by advplyr** [comment]
Added in [v0.9.56-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.56-beta)
