### ISSUE TITLE
[Enhancement]: If only one Collection/Playlist exists, go straight to the Collection/Playlist

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf-app#1395]
### Describe the Feature/Enhancement

In the App interface, if only one Collection/Playlist exists, then the Web page should go straight to that collection/playlist without selecting the list first.

### Why would this be helpful?

This is to improve the user experience and reduce needless screen touches. 

### Future Implementation (Screenshot)

No screenshot. 

### Audiobookshelf App Version

Android App - 0.9.77

### Current Implementation (Screenshot)

Screen recording. 

https://github.com/user-attachments/assets/710bb7b8-bfa1-4e8a-8349-4e627e66cf69

**Comment by ZLoth** [comment]
Similar to the Web Interface feature request https://github.com/advplyr/audiobookshelf/issues/3660

**Comment by advplyr** [comment]
See https://github.com/advplyr/audiobookshelf/issues/3660#issuecomment-2503927458
