### ISSUE TITLE
[Bug]: downloaded the audiobook  to my phone,  it prompted a playback error and source error

### ISSUE THREAD

**Issue by diyuzhousi** [advplyr/audiobookshelf-app#1405]
### What was the Problem?

I downloaded the audiobook stored in the NAS to my phone, but when playing it locally, it prompted a playback error and source error

### Steps to Reproduce the Issue

1. Download audiobooks
2. Local playback

### What was Expected?

The expectation is that after downloading, it can be directly played locally on the phone

### Phone Model

Honor Magic VS2

### Phone OS

 Android14 Custom System

### Audiobookshelf App Version

Android App - 0.9.77

### Installation Source

Google Play Store

**Comment by nichwall** [comment]
What file format and codec is the book? Does the book work for streaming, and if so does it say "Direct" or "Transcode" at the top of the player?

**Comment by diyuzhousi** [comment]
I just looked at the other questions and I think I understand. I have an Android phone and my audiobook is in WMV format, so... It should be due to this reason
