### ISSUE TITLE
[Enhancement]: request apk package

### ISSUE THREAD

**Issue by Chenghao999** [advplyr/audiobookshelf-app#1409]
### Describe the Feature/Enhancement

Hi!
Could you pls pack the app and put it on the release page? 

### Why would this be helpful?

because most China edition Android can not install the Google Play Store. 

### Future Implementation (Screenshot)

aaaaaaaaaaaaaaa

### Audiobookshelf App Version

Android App - 0.9.77, Android App - 0.9.76

### Current Implementation (Screenshot)

aaaaaaaaaaaa

**Comment by advplyr** [comment]
It is there under assets https://github.com/advplyr/audiobookshelf-app/releases
