### ISSUE TITLE
Search term is lost when selecting an item

### ISSUE THREAD

**Issue by cassieesposito** [advplyr/audiobookshelf-app#142]
### Steps to reproduce

1. Open app
2. Select magnifying glass icon
3. Search for something
4. Select a book
5. Select back icon

### Expected behaviour
Search should be pre-populated with previous search term

### Actual behaviour
Search is empty

### Environment data
Audiobookshelf Version: 2.0.2
Android version: 0.9.42-beta / 0.9.41-beta
Device model: Moto G7+ / Motorola One 5G Ace
Stock or customized system: Custom (Android 11, Lineage OS 18.1) / Stock (Android 10)

**Comment by advplyr** [comment]
Good call

**Comment by advplyr** [comment]
This is updated in [v0.9.43-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.43-beta)
