### ISSUE TITLE
[Bug]: Can't get ABS running again, after two weeks offline

### ISSUE THREAD

**Issue by m0veax** [advplyr/audiobookshelf-app#1421]
### What was the Problem?

Hi,

we had some Issues in our house and i shutdown my whole setup to avoid damage to the Hardware itself. The issues got solved and I tried to get all working again.

I use a ABS Server as a Docker Container on my Synology. I tried connecting the Android Clients of my Kids and ran in a lot of Syncing for local PlaybackSessions. I thought this could be the bottleneck, because I downloaded audiobooks to the phones so my kids could listen to them, while my Setup is offline.

To solve those issues, i deleted their users and created new ones. The log said, that the PlaybackEntries had the user id removed.

I can not start playing audio books. The Log does not give me any Errors, but says that the session got closed.

An update to the latest ABS docker version did not helped

### Steps to Reproduce the Issue

Blackout your setup for 2 weeks and listen to localy saved audiobooks a lot.

### What was Expected?

I expected to start my Setup again, sync and start listening again.

### Phone Model

Samsung Galaxy A51

### Phone OS

Android 12

### Audiobookshelf App Version

Android App - 0.9.77

### Installation Source

Google Play Store

**Comment by m0veax** [comment]
If you need further informations or something, leave me a note and i will give you everthing you need :)

**Comment by nichwall** [comment]
Where did you delete their users? On the server or on the phone?

What server version are you using? Is the server itself working and there was just an issue with syncing everything, or is the server crashing?

**Comment by m0veax** [comment]
Hey,

I deleted the Users in the webinterface with my Admin User Account.

I'm on the latest Docker Image. The Server itself does Not crash. I just can't play anything anymore

**Comment by nichwall** [comment]
Can you not play anything in the admin account through the web interface either? If so, did you delete the accounts on the phone and create new connections? Even if you create accounts with the same username and password, they have a different user ID, so nothing should be working (you also shouldn't even be able to log in, but might have some weird caching going on)

If you can't play anything even on the admin web interface, your media is likely not visible to ABS.

Did you set up your docker mounts correctly and is your media present in the file system? If the media is on an external drive, is the drive properly mounted before the docker container starts?

If you did not set up the docker mounts and used the web uploader in ABS, your media would have been stored in the old container, which is deleted and replaced when you update.

**Comment by m0veax** [comment]
Playback through the admin Account on the webinterface works like a charm.

After deleting the Accounts, i deleted AppData on the Phone, removed the Apps and did a fresh install to get a proper start. I just checked the docker mounts to be sure, and they are correctly setted up and the webinterface even shows fresh audiobooks after doing a partial scan.

I use docker mounts and store data in the folders directly. After that i do a partial scan and check if the metadata is right ect.

**Comment by nichwall** [comment]
Does playback work in the app if you sign in as the admin?

**Comment by m0veax** [comment]
I don't know what to say. After trying the things you mentioned, it all started working again. Maybe the Server Application had some stuff to do or something.

The audiobooks are working again, with the newly created Accounts.

I wonder what changed that, I tried everything the first time yesterday evening and it did not get resolved over night.

Do you want to investigate here further? I'm willing to deliver everything you need to do that.

Otherwise I want to say "thank you" for your great work and the fast responding time! Really love audiobookshelf and use it since 2y now :)

**Comment by nichwall** [comment]
I think it is most likely due to a caching issue, having a large amount of listening sessions to sync, and deleting the user accounts from the server but not resetting them in the app as well. If you want to share the log from the server from when it was not working, that could be helpful but I'm not really sure what to be looking for.

Glad you got it working!

**Comment by m0veax** [comment]
Just got a message from my synology, that the disk checkup is now finished and i should have full performance again.

I checked the logs, they are only have lines like this, no errors:

```
2024/12/29 16:50:17	stdout	[2024-12-29 15:50:17.086] INFO: [PlaybackSessionManager] startSession: Closing open session "AUDIOBOOKNAME A" for user "KID-A" (Device: SM-A515F SDK 31 / v0.9.76-beta)
2024/12/29 16:50:07	stdout	[2024-12-29 15:50:07.683] INFO: Received ping
2024/12/29 16:50:05	stdout	[2024-12-29 15:50:05.538] INFO: [PlaybackSessionManager] startSession: Closing open session "AUDIBOOKNAME B" for user "KID-B" (Device: SM-A515F SDK 31 / v0.9.76-beta)
2024/12/29 16:49:59	stdout	[2024-12-29 15:49:59.273] INFO: [SocketAuthority] Socket Connected to /socket.io nIONismJtcIS_6kkAAAt
2024/12/29 16:48:57	stdout	[2024-12-29 15:48:57.912] INFO: [PlaybackSessionManager] startSession: Closing open session "AUDIOBOOKNAME C" for user "KID-A" (Device: SM-A515F SDK 33 / v0.9.76-beta)
2024/12/29 16:48:50	stdout	[2024-12-29 15:48:50.633] INFO: Received ping
2024/12/29 16:48:50	stdout	[2024-12-29 15:48:50.030] INFO: [PlaybackSessionManager] startSession: Closing open session "AUDIOBOOKNAME D" for user "KID-B" (Device: SM-A515F SDK 33 / v0.9.76-beta)
2024/12/29 16:48:45	stdout	[2024-12-29 15:48:45.377] INFO: [SocketAuthority] Socket Connected to /socket.io MTRHlkmOElNFJxhdAAAr
2024/12/29 16:48:45	stdout	[2024-12-29 15:48:45.028] INFO: [Auth] User "KID-B" logged in from ip ::ffff:172.27.0.1 
```

(I redacted the names of my Kids and Audiobooks)

I had no notification, that my Synology is doing a full RAID Checkup and guess that this was a performance Issue because the HDDs had some other things to do. 

Thanks for your Support :)
