### ISSUE TITLE
bug: download audiobooks work but when I play local it starts from zero regardless of synced position and plays at 1X

### ISSUE THREAD

**Issue by zombiehoffa** [advplyr/audiobookshelf-app#145]
### Steps to reproduce

1.install latest app from android store (0.9.42 I believe), install 2.0.3 server. 
2. login on app and choose download on a partially listened to audio book
3. hit play local and watch it start from the beginning at 1X instead of from the saved position and saved playback speed
4. cry when you realize it wrote your new track position back to the server so you have to scroll through trying to remember where you were  with only a rough recollection from looking at the screen before you hit play.
5.  Note the book cover is missing still, although I think there is a stand alone bug for this.

### Expected behaviour
- when I hit play local it should start playing from the position saved on the server, at the speed that was already set with the book cover that already exists on the server and in the streaming version.

### Actual behaviour
- see steps to reproduce

### Environment data
lineageos 18.1 with  microg, 2.0.3 server, l
Audiobookshelf Version: 0.9.42 beta (latest on android store as of this morning).

- [ X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: lineagos 18.1 microg edition.

Device model:

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
This will be fixed in the next release and will require a server update as well.

**Comment by advplyr** [comment]
Fixed in [v0.9.43-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.43-beta) and server v2.0.7
