### ISSUE TITLE
Sleep time cannot be properly changed

### ISSUE THREAD

**Issue by HStep20** [advplyr/audiobookshelf-app#147]
### Steps to reproduce

1. Begin playing a book, and start a sleep timer
2. After letting it play for a moment, make note of the time and cancel the timer
3. Create a new sleep timer for another time, and it will set a sleep timer to the noted time.

### Expected behaviour
The sleep timer should be cleared of time when it is cancelled, and new sleep timers/time edits should set the actual sleep timer time

### Actual behaviour
There is some incredibly odd behavior related to the sleep timer. Even when the timer is cancelled, it seems to continue counting down in the background, and shutting off after X minutes even when the sleep timer is cancelled. The +/- buttons also don't work for quick changes, with the + completely unable to up the sleep timer time, and the - removing one minute, then putting it down to negative two hours, and an odd number of minutes and seconds.

### Environment data

Audiobookshelf Version: v2.0.3
Android App Version: v0.9.42-beta

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: Android 12

Device model: Google Pixel 4a 5g

Stock or customized system: Stock

**Comment by advplyr** [comment]
I think these issues are fixed in [v0.9.43-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.43-beta), please let me know
