### ISSUE TITLE
Download doesnt acutally download anything

### ISSUE THREAD

**Issue by Thoroslives** [advplyr/audiobookshelf-app#15]
Running most v0.9.8-beta hit download choose my folder, it doesn't actually download anything, the status bar shows download unsuccessful. I've checked the app permissions and it does have media access. 

Running on Galaxy Fold 3 btw

Update: I reinstalled and now it downloads the cover but he actual audio file still fails

**Comment by orangebrush72** [comment]
Hi @advplyr  - I am experience the issue @Thoroslives has documented above. 
Relevant details:
>Pixel 6 Pro
>Android 12
>App version 0.9.54-beta
>Server version (Docker) - I'll need to check (not in front of the server atm)
>File name - 1990 - Four Past Midnight (4 novellas).mp3 (single file) 304.2MB
>Local directory - Internal storage/Audiobooks (I have also tried Downloads)

The folder of the book is created and the cover is downloaded and I get the message : "Item download complete but failed to create library item"

I have tried other audiobooks and get the same result.

This had been working before. 

Thanks
Tim
