### ISSUE TITLE
App crashes to home screen right away after launch (v0.9.40-beta is last working release that works)

### ISSUE THREAD

**Issue by galaxyfar** [advplyr/audiobookshelf-app#153]
### Steps to reproduce

1. Wipe clean any older installation of ABS
2. Install any release v0.9.41-beta through v0.9.43-beta (tried both Google Play and Github .apk
3. App would ask for folder access permission - press "Yes"
4. App crashes right away on first and any subsequent launches
5. Last know version that does not crash for me is the v0.9.40-beta 

### Expected behaviour
- App should launch and preset login screen

### Actual behaviour
- Crashes to home /desktop screen

### Environment data

Audiobookshelf Version: v0.9.41-beta, v0.9.42-beta & v0.9.43-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: Android 11, Android 10 and Android 9

Device model: OnePlus 8T, Nvidia Shield 2019, Galaxy S9+

Stock or customized system: LineageOS + Stock Android on Nvidia Shield

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Please test again with the latest release. v0.9.43-beta

**Comment by rwa96** [comment]
I have the same issue with the latest release (v0.9.43-beta). The app worked on OxygenOS but crashes with LineageOS. Does this app require Google Services/Libraries? Maybe thats the issue here.

**Comment by rwa96** [comment]
After setting up a development environment and running the app using AndroidStudio I get the following exception:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.audiobookshelf.app, PID: 10734
    java.lang.RuntimeException: com.google.android.gms.cast.framework.zzat: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
...
```

I am not an android developer but it seems like, the missing Google Play Services are the issue here. 

@galaxyfar can you confirm that your installation has no Google Services either?

**Comment by advplyr** [comment]
Ah yes, thanks for the log. That makes sense since the app looks for a valid chromecast receiver on launch. We can fix that.

**Comment by galaxyfar** [comment]
> After setting up a development environment and running the app using AndroidStudio I get the following exception:
> 
> ```
> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.audiobookshelf.app, PID: 10734
>     java.lang.RuntimeException: com.google.android.gms.cast.framework.zzat: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
> ...
> ```
> 
> I am not an android developer but it seems like, the missing Google Play Services are the issue here.
> 
> @galaxyfar can you confirm that your installation has no Google Services either?

@rwa96 you hit the nail in the head. I'm indeed not using play Google Services. Thanks for taking time to debug this.

**Comment by advplyr** [comment]
Thanks for confirming. We will use #158 as the main thread for this issue.

**Comment by galaxyfar** [comment]
> Ah yes, thanks for the log. That makes sense since the app looks for a valid chromecast receiver on launch. We can fix that.

Thanks @advplyr you guys are awesome. Congrats on building JF/Plex equivalent for audiobooks world.
