### ISSUE TITLE
Sleep-Timer can't be set, while Audiobook is playing

### ISSUE THREAD

**Issue by Pewidot** [advplyr/audiobookshelf-app#155]
**Steps to reproduce**
Start an audiobook, set the sleep timer to x Minutes while the Audiobook is playing.

**Expected behaviour**
Sleeptimer should start and trigger in x minutes.

**Actual behaviour**
Audio playback stops right away and Audiobooks is paused when you select any "X Minutes" Button.  When continuing the audiobook manually after setting the sleeptimer, the sleeptimer does not trigger at any time in the future.

**Environment data**
Audiobookshelf Version: v2.0.3
Android App Version: v0.9.42-beta

**Android Issue**
Android version: Android 11

Device model: Xiaomi Mi 9t

Stock or customized system: Stock

**Comment by Pewidot** [comment]
I would like to add that I have seen the same problem on my iPhone 11 with iOS 15, here the sleeptimer simply doesn't trigger at all

**Comment by advplyr** [comment]
Please check again in the latest release for android [v0.9.43-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.43-beta)
