### ISSUE TITLE
feature request: ability to link local files to server items

### ISSUE THREAD

**Issue by zombiehoffa** [advplyr/audiobookshelf-app#157]
### Is your feature request related to a problem? Please describe.
I am running into problems getting downloads of books with a large number of files to register in audiobookshelf even though the download finishes, so it would be nice to be able to link the item to the server item manually, or at least have it try to do that automagically on a local file rescan (i.e. if it's the same number of files, same size as something on the server link it to that. You could get even fancier and compare file hashes)

**Comment by advplyr** [comment]
Definitely. This has been the plan but just has a lot of little details to figure out.

**Comment by advplyr** [comment]
Local files were removed in v0.9.67-beta so there is no more scanning. All media has to be downloaded from a server and will always be linked. Scanning and managing local files made things too complicated and not worth the added instability
