### ISSUE TITLE
Crash when initializing chromecast on device with no Google Services

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf-app#158]
After setting up a development environment and running the app using AndroidStudio I get the following exception:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.audiobookshelf.app, PID: 10734
    java.lang.RuntimeException: com.google.android.gms.cast.framework.zzat: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
...
```

I am not an android developer but it seems like, the missing Google Play Services are the issue here. 

@galaxyfar can you confirm that your installation has no Google Services either?

_Originally posted by @rwa96 in https://github.com/advplyr/audiobookshelf-app/issues/153#issuecomment-1114008083_

**Comment by rwa96** [comment]
@advplyr You can reproduce this but easily by using the sdk emulator with a system image that doesn't include Google services btw. I don't know if this is obvious but I thought I'd mention it here since it might help you with debugging and avoiding this error in the future.

**Comment by galaxyfar** [comment]
@advplyr can confirm v0.9.44-beta release has fixed this issue. Thanks a lot.

**Comment by advplyr** [comment]
Great! Release notes: [v0.9.44-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.44-beta)
