### ISSUE TITLE
[Bug]:  Android app not logging in

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf-app#160]
### Describe the issue

Fresh install of the app, installed from Play Store, and opening it on a Samsung SM-T580 tablet. Android version 8

I dont get any prompt for server info, it just asks for files permission (which i grant) then it goes to a blank screen. Hamburger menu does not respond / accept clicks.

![Screenshot_20220501-090242_audiobookshelf](https://user-images.githubusercontent.com/101836977/166137537-1e7ab977-de2b-4d92-8cc0-8323343a77fa.jpg)
 

### Steps to reproduce the issue

1. 

### Audiobookshelf version

0.9.43-beta

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
What version of server are you using?

**Comment by barelylit** [comment]
v2.0.7

Not that it matters, i never get prompted for the server info so its not connected to anything.

**Comment by barelylit** [comment]
I suspect this was to do with the version of Android.

I have upgraded the rom on the tablet to an Android 10 one and its working fine now.  I'll leave this open FYI but feel free to close once you've seen, I'll not be able to reproduce the issue now.

**Comment by barelylit** [comment]
It was the stock Samsung A10.1 2018 Android 8, in case you want to know.

Now on Bliss Roms Bliss-12.11 (Android 10)

**Comment by advplyr** [comment]
The app should support android 8, but I haven't tested on android 8 yet so will need others to confirm

**Comment by barelylit** [comment]
I have an old Samsung S6 which im trying to setup just as an audiobook player for my kid, that I've tried various roms on in the last 24h, and it just will not give a prompt for server info on Android 8

**Comment by advplyr** [comment]
Does this still persist in the latest version?

**Comment by rmkjr** [comment]
Seeing this as well.  App version 0.9.49-beta.  Device is a Hiby RS6 running Android 9.

**Comment by advplyr** [comment]
> Seeing this as well. App version 0.9.49-beta. Device is a Hiby RS6 running Android 9.

You are seeing the same issue with a blank home page?

**Comment by rmkjr** [comment]
Correct.  Exactly the same as the OP's screenshot.  Tabs are clickable, but the hamburger menu is not.  Unlike on iOS, after install, there is no Connect button appearing on the home tab, it is completely blank.

**Comment by rmkjr** [comment]
I also have another Android device.  An iBasso DX300.  Same processor and also Android 9.  Really the only main difference from an app perspective that I can think of is it has a much taller screen.  Interestingly, on that device, the connect button appears after install and open.

**Comment by sandreas** [comment]
Ok, same here. I use an LG G5 H850, Android 8.0.0, App Version 0.9.49-beta 
- App opens up, not responding to any tap
- Restarting the app (normally) does not help

Somehow I fixed it by one of the following actions:

- Long tap on the app icon, App Info, Force stop
- Reboot phone completely
- Logging in on the web interface, clearing ALL issues
- Disabling always on display (that should not be an option on all devices, so I think you can skip this)
- Starting the app again

After these steps, I had a `Connect` button that worked.

**Comment by rmkjr** [comment]
No such luck on this side reproducing a workaround with the above steps.

**Comment by advplyr** [comment]
Please try again with the latest release

**Comment by rmkjr** [comment]
No changes on this side with that Hiby RS6 device.  Did a fresh install of 0.9.50-beta to be sure everything was a clean as possible.  After first open I get a permission prompt, but then a blank screen with no way to enter server details.

https://imgur.com/a/ysb3rvr

**Comment by advplyr** [comment]
Please try again with the latest release 0.9.52-beta. I fixed some things that may have been causing this
