### ISSUE TITLE
[Android] Download Manager does not not remove finished Items

### ISSUE THREAD

**Issue by Sacerdoss** [advplyr/audiobookshelf-app#161]
### Steps to reproduce

1. Download Any Audiobook

### Expected behaviour
- Downloadmanager Notification pops up while downloading
- Notifications for finished downloads get removed

### Actual behaviour
-  Downloadmanager Notification pops up while downloading
- Notification for finished downloads stay active

The problem is that there is one notification for every file of the audiobook and you cannot remove the notifications for finished downloads all at once. You have to swipe every single notification to get rid of it which is tideous for possibly hundreds of files.
This [Stackoverflow Thread](https://stackoverflow.com/questions/14443536/android-downloadmanager-notification-sticking) might be related and could guide to the solution. (i.e. call downloadManager.remove(download_id) for finished downloads)

### Environment data

Audiobookshelf Version: [v0.9.43-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.43-beta)

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model: Galaxy S10

Stock or customized system: LineageOs

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Fixed in [v0.9.44-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.44-beta)
