### ISSUE TITLE
Playing locally downloaded books causes loop requiring restart (Sony Xperia 1)

### ISSUE THREAD

**Issue by carlocgc** [advplyr/audiobookshelf-app#164]
Similar issue #35 

Ticket raised for visibility of reproduction on Sony device, other issue is for different device.

Appreciate this might be closed as dupe.

### Steps to reproduce

1. Download audio book locally
2. Play Audiobook
3. See black screen flicker and only way to resolve is restarting phone

### Expected behaviour
- Book should play without issue

### Actual behaviour
- Black screen flicker and no responsive phone

### Environment data

Audiobookshelf Version:

- [ 0.9.43-beta] Android App?

#### Android Issue
Android version: 11

Device model: Sony Xperia 1

Stock or customized system: Stock

**Comment by advplyr** [comment]
It's the same issue as the OnePlus one which is due to the cover image. Removing the cover image solves the issue.
At first I thought it was specific to OnePlus

**Comment by TDderpy** [comment]
> It's the same issue as the OnePlus one which is due to the cover image. Removing the cover image solves the issue. At first I thought it was specific to OnePlus

The same issue is happening on OnePlus 7 Pro. Is there any solution in the works? As admittly easy deleting the cover for each book isn't ideal.

**Comment by advplyr** [comment]
I remain stumped on this issue. I may just add a flag for you to set that will just not set the cover image in the notification, that is the reason for the crash.

**Comment by TDderpy** [comment]
> I remain stumped on this issue. I may just add a flag for you to set that will just not set the cover image in the notification, that is the reason for the crash.

Honestly that sounds like the best idea, just a toggle that switch the cover off or to like a default one (if that's doable without the issue repeating)
If i can help with troubleshooting or testing this let me know.

**Comment by advplyr** [comment]
I'm hoping this attempt will fix it in [v0.9.44-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.44-beta) on the play store. Let me know!

**Comment by advplyr** [comment]
This is fixed in [v0.9.45-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.45-beta)!
