### ISSUE TITLE
When starting download multi-track m4b audiobook the App disconnect from socket

### ISSUE THREAD

**Issue by LordKolonas** [advplyr/audiobookshelf-app#168]
### Steps to reproduce

1. Start App
2. Choos Audiobook
3. Start Download
4. Confirm: Start download with 321 AudioTracks to Folder.
5. Confirm-Window closed, wait 10sec. 
6. App Closed

### Expected behaviour
- App should start Downloads
### Actual behaviour
- App closes by itself/ Crashes

### Environment data

Audiobookshelf Server-Version: 2.0.9
Audiobookshelf App-Version:0.9.43-beta

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version:
11 RP1A.200720.011
Device model:
M2003J15SG
Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Once you start the download you can see that they begin downloading?
What do you mean by confirm window closed wait 10 seconds?

Were any audio files downloaded?

**Comment by LordKolonas** [comment]
After i pressed the Download-Button and confirmed the Download. Nothing Happens. No Downloads. Just the Folder gets created.

**Comment by LordKolonas** [comment]
After manual Download the .apk Version 0.9.43-beta and Install the Download started. 322 in an orange circle in the right upper Corner. App Crashed 10sec after the Download started. Download continues a few sec and Stopps. Com.android.providers.download stopped working.
Download-Folder is emty. Not evan a Folder was created.
When Open the App again. Nothing Happens.

**Comment by advplyr** [comment]
I am thinking this has to due with the quantity of tracks being downloaded. Can you confirm that you are able to successfully download other audiobooks with less tracks?

**Comment by advplyr** [comment]
Please try again with the latest update 0.9.44-beta updates were made to the downloader.
