### ISSUE TITLE
Cast downloaded media

### ISSUE THREAD

**Issue by claabs** [advplyr/audiobookshelf-app#170]
### Is your feature request related to a problem? Please describe.
Currently, if you download media locally and try to cast it, you get the warning: "Cannot cast downloaded media items. Confirm to close cast and play on your device". The only way to cast the audio is to delete the local copy, or to connect to Bluetooth (if capable) and play from your phone.

### Describe the solution you'd like
I'd expect downloading media wouldn't disable a feature like casting. Other apps like PocketCasts are able to cast audio of downloaded podcasts.

I don't expect the audio stream to actually come from the phone, but it should at least play the stream from the server.

### Describe alternatives you've considered
Currently I just connect to my smart speaker over Bluetooth, but not all casting devices have Bluetooth, and it restricts playback to be within Bluetooth range of the phone.

### Additional context
There's also a minor bug where tapping the cast button while the playback bar for downloaded media is shown causes nothing to happen. I'd at least expect an error message.

**Comment by advplyr** [comment]
In [v0.9.44-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.44-beta) if you are connected to the server that the downloaded local item was downloaded from then you will be able to cast. It will just change the player over to a stream from the server.

This may need a bit more tweaking to get right so let me know

**Comment by claabs** [comment]
Amazing turnaround. Thanks so much!
