### ISSUE TITLE
Mark as complete from App

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf-app#174]
There seems to be no way to mark something as completed in the app, there isnt the mark read button there is on the web interface.

This was especially annoying as i listend to a local copy but the streamed copy was still showing 67% complete after totally finishing the local copy.

**Comment by advplyr** [comment]
What version of the app are you using?

**Comment by barelylit** [comment]
Hah! 0.9.43

Updated and there it is. Get out of my head! Lol

Great job. Cheers.
