### ISSUE TITLE
[Android] Timestamps don't line up between android app and web app

### ISSUE THREAD

**Issue by jmt-gh** [advplyr/audiobookshelf-app#176]
### Steps to reproduce

1. Choose a chapter in the web app on an mp3, and notice what is being spoken
2. Chose a chapter in the android app on an mp3, and notice it is not the same place in the audio

### Expected behaviour
- I would expect these to be the same

- ### Actual behaviour
- They are at different points in the book

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model: OnePlus 6

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by jmt-gh** [comment]
Noting that this only seems to occur with MP3 files. If I convert the MP3 to an M4B, it seems to be synced appropriately.

**Comment by advplyr** [comment]
Was this issue reproducible? I remember discussing this in discord also but don't recall the conclusion.
