### ISSUE TITLE
[iOS] Will it be possible to download on the iOS app?

### ISSUE THREAD

**Issue by njakes** [advplyr/audiobookshelf-app#178]
From what I can see there is no option to download an audiobook on iOS. I just switched over from android and am not seeing that option. Perhaps I am missing something or is that feature not implemented?

**Comment by jparrish88** [comment]
Not an answer, as I thought I was just missing something too, but the dev answered this just a few days ago: https://github.com/advplyr/audiobookshelf-app/discussions/60#discussioncomment-2622201

**Comment by advplyr** [comment]
iOS is still a bit behind android, but it is in the works.

**Comment by njakes** [comment]
Thank you both for the response. I wish I could help but have no experience in coding.

**Comment by rovashan** [comment]
Nice project. 
Is there any ETA on download ability on iOS?

**Comment by advplyr** [comment]
No ETA, but we are looking for help!

**Comment by rovashan** [comment]
I don't mind taking a look. Do you have a remote Mac instance that I can use?

**Comment by advplyr** [comment]
Nope, we don't have anything cool like that setup yet.

**Comment by rovashan** [comment]
I'm running Windows but I will see if I can do something.

**Comment by genebean** [comment]
Looks like this project might be able to access Mac hardware for free: https://www.macstadium.com/opensource

**Comment by ronaldheft** [comment]
Planning to work on this over the upcoming weekend. Some notes for myself as I start the progress:

- [ ] Track down the UI component the Android app uses for downloading
	- [ ] Is the component disabled on iOS?
	- [ ] What needs to be done to enable?
- [ ] How does the Android app keep track of files that are downloaded?
	- [ ] What records are updated in a database?
	- [ ] Edge case: What happens when a download starts when playing?
	- [ ] Edge case: What happens if not all files are downloaded?
	- [ ] How are files deleted?
- [ ] Is there an interface that abstracts files to the Android player so it doesn't care if it's local or server?
	- [ ] This should be in the shared library as iOS will want the same functionality
- [ ] Where do we want to download on iOS?
	- [ ] Stubbed code shows downloading into the documents directory
	- [ ] Will this backup to iCloud? (We want to avoid this)
- [ ] Does `AVQueuePlayer` and local files work with AirPlay?
- [ ] How is the offline progress synced back to the server?
	- [ ] This includes the reverse, server progress when offline?
	- [ ] Who wins out if different progress was made? The furthest? Most recent?
