### ISSUE TITLE
UI - Library List View Scrolling - Improper Indexing

### ISSUE THREAD

**Issue by r1aven** [advplyr/audiobookshelf-app#179]
### Steps to reproduce

1. Open Android Audiobookshelf App
2. Go to Library tab
3. Scroll down list through 20+ books

### Expected behaviour
- Proper display of all visible audiobooks at current scrolling index position

### Actual behaviour
- When scrolling through list of available books in library tab in list view (not the default cover view), the available audiobooks to do not properly display on the visible screen space.  The reserved area for a cover and book title are present above the current index but nothing populates and you are unable to interact with that index.  See attached screen capture.

### Environment data

Audiobookshelf Version:

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version:  0.9.44-beta

Device model:  Pixel 6

Stock or customized system:  Stock

![Audiobookshelf_android_library_listview_scrolling](https://user-images.githubusercontent.com/6191252/167920889-2c6aae12-3194-4b7f-8cac-4697dc390a1f.png)

**Comment by advplyr** [comment]
This is fixed in [v0.9.45-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.45-beta)!
