### ISSUE TITLE
Progress not synced when switching between cast streaming and regular streaming playback

### ISSUE THREAD

**Issue by tzw9373** [advplyr/audiobookshelf-app#180]
### Steps to reproduce

1. Select Cast Option and choose device, wait for successful connection
2. Select play stream, listen until ready to stop
3. Pause playback and disconnect cast option

### Expected behaviour
- Tell us what should happen
- Current play position should remain and be synced to server

### Actual behaviour
- Tell us what happens 
- Play position reverts to previous noncast play position, unless app is immediately closed and reopened

### Environment data

Audiobookshelf Version: 2.0.13

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: Android 12, app version 0.9.44

Device model: Google Pixel 6

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
I found the issue causing this it will be fixed in the next release

**Comment by advplyr** [comment]
This is fixed in the latest release
