### ISSUE TITLE
[Android] Make a click sound while navigating audiobook

### ISSUE THREAD

**Issue by cobalt027** [advplyr/audiobookshelf-app#181]
Can the app make a click when I skip forward or backward?

Often times I glance away (while working out or walking for example) while navigating the audiobook and I have no feedback that I tapped in the right area to skip back or forward. I might have the book paused, or I might have skipped to a silent portion of the book from a silent portion.

**Comment by advplyr** [comment]
Do you know of any other audio players that does this?

**Comment by cobalt027** [comment]
Both Smart AudioBook Player (on Android) and the Audible app do it.

**Comment by advplyr** [comment]
Are you talking about navigating the audiobook from bluetooth?

I don't hear this happening on smart audiobook player unless there is a setting I'm missing.

**Comment by cobalt027** [comment]
Nothing to do with bluetooth, No headset connected at all. Just listening on the phone itself. I couldn't find a setting (in Smart) to enable or disable it (I looked). I wonder if its part of the overall Android setting "System Sound/vibration control" - > Touch Interactions. Disabling it in Android settings disables it in both Smart and Audible. Turning it back on in settings makes Smart and Audible click.

**Comment by advplyr** [comment]
I don't have that setting, but I have "Touch Sounds" which is enabled and I don't think I've ever heard any touch sounds.

**Comment by cobalt027** [comment]
I'm running a Samsung Galaxy S20 5G. Android 12. One UI version 4.0

![image](https://user-images.githubusercontent.com/164455/168430814-e41f881c-cd2e-4cce-82b0-1928c0d74f5a.png)

**Comment by advplyr** [comment]
As of now this isn't going to be supported, I think this is something with the device because I see no way to enable this and haven't heard it before.
