### ISSUE TITLE
After phone pauses from sleep timer, sound volume doesn't reset when... 

### ISSUE THREAD

**Issue by JamesDean3** [advplyr/audiobookshelf-app#182]
### Steps to reproduce

1. Set sleep timer. 
2. Wait for sleep timer to turn down and pause. 
3. Use the notification to resume. 

### Expected behaviour
- Tell us what should happen
Expected to resume at full volume. 

### Actual behaviour
- Tell us what happens
Resumes at reduced volume. *Also starts sleep timer back up to the original time set in the sleep timer. Pausing and unpausing from notification again won't fix it either. 

However when pressing play inside the app to resume, it starts at full volume and the sleep timer shows as off, which I assume is what it was meant to do.

*Auto starting the sleep timer bit actually reminds me of a feature I like in listen audiobook player app, you are able to set a range of time every day that it would automatically turn on the sleep timer, it had the same shake to keep awake feature as you have, except it had different levels of sensitivity and it would reset the timer back to the original set time at any point the phone shook at the set sensitivity  level during the countdown ( instead of the last minute or so, which I believe audiobook shelf does ). Making it is the only way it would actually sleep was if you stopped moving for the set amount of time. 

### Environment data
Audiobookshelf Version: 0.9.44-beta

- [x] Android App?
- [ ] iOS App?

Pixel 4a (5G) 
Android version: 12 
Stock

Kernel Version: 4.19.220-gadc60de00e3a-ab8172795
#1 Thu Feb 10 21:46:05 UTC 2022

Build Version: SP2A.220405.003

**Comment by advplyr** [comment]
Fixed in [0.9.46](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.46-beta)
