### ISSUE TITLE
[iOS] Sleeptimer counts down too fast

### ISSUE THREAD

**Issue by Pewidot** [advplyr/audiobookshelf-app#184]
Steps to reproduce
Start an audiobook, set the sleep timer to x minutes.

Expected behaviour
Sleeptimer should count down one second in one real second

Actual behaviour
Sleeptimer is counting down 4 seconds in one real second

Environment data
Audiobookshelf Version: v2.0.13
Android App Version: v0.9.45-beta

#### iOS Issue
iOS Version: iOS 15.4

Device model: iPhone 12

I have a Screenrecording showing whats happening just request if needed

**Comment by advplyr** [comment]
Are you able to reproduce this in the latest version?
I just tested this and wasn't able to reproduce it.
