### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ChickenCasual** [advplyr/audiobookshelf-app#185]
### Describe the issue

For a while I have not been able to log into audibookshelf. and I have no idea what is wrong.

I use abs android app just like my gf. She is able to login via the app. I am not I just get a "unknown error"
We use the root user. But I have same issue is I make a dedicated user. 
It works if I login from Unraid and everything else beside my phone. 
Best regards
CS

### Steps to reproduce the issue

1. Trying to log in

### Audiobookshelf version

0.9.45-beta

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
What version is the server?
What is the device model and android version of both of your phones?

**Comment by ChickenCasual** [comment]
> What version is the server? What is the device model and android version of both of your phones?

Unraid / docker Version v2.0.14 
app version android 0.9.45-beta and prior version also
Phone with issue: Huawei P20 pro / android version: 10 also 10 EMUI version
Phone that works: xiaomi mi 10 pro also android 10.

**Comment by advplyr** [comment]
are you connecting via your local network using an ip address like 192.168.x.x? Or have you setup a reverse proxy?

**Comment by ChickenCasual** [comment]
Local 192.168.x.x:13378. Reverse proxy not setup yet.

**Comment by ChickenCasual** [comment]
I get ping when i put in ip on app. But user/pass dont. Even i just tried also in browser and it works fine. on app it just says unknown error. 
I did try to uninstall app and install again.

**Comment by advplyr** [comment]
I don't have any suggestions, it appears this is an issue with your device/network. I would just recommend joining the discord and asking in there.

**Comment by nirurin** [comment]
I'm having the same issue. No help on discord. I can log into the server fine via browser, but the app just throws an 'unknown error' when entering login details. Same thing happens whether I use local ip or my reverse proxy.
