### ISSUE TITLE
Android eBook Download

### ISSUE THREAD

**Issue by projx** [advplyr/audiobookshelf-app#187]
### Is your feature request related to a problem? Please describe.
When viewing an audiobook, a download link is shown, this does not appear for eBooks.

### Describe the solution you'd like
Could you add a download button for eBooks.

**Comment by mogorman** [comment]
I would really appreciate this as well

**Comment by ambarnes2** [comment]
I am in the same boat, i do not want to expose this server to the public internet and would like to read books while not on my home network.

**Comment by advplyr** [comment]
Added in [v0.9.64-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.64-beta)

**Comment by advplyr** [comment]
Note also that offline reading is supported on Android and progress is saved for epubs.
