### ISSUE TITLE
[iOS]: resume playback results in concurrent audio streams

### ISSUE THREAD

**Issue by norseghost** [advplyr/audiobookshelf-app#190]
### Steps to reproduce
haven't been able to pin it down completely, but sometimes:
1. play audiobook through airpods
2. audio gets interrupted -- siri reads a notification, i get a phonecall etc
3. audiobook does not resume (a separate bug)
4. I press airpods to restart audio 

### Expected behaviour
audiobook should resume from before interruption

### Actual behaviour
audiobook resumes from point of interruption *and* from previous saved location (from when app was last restarted? maybe?)

### Environment data

Audiobookshelf Version: 2.0.13

- [ ] Android App?
- [X] iOS App?

#### iOS Issue
iOS Version: 15.4.1

iPhone model: XS max

**Comment by advplyr** [comment]
I'm not sure how to debug this. Let me know if you can get reproducible steps or join the discord and we can discuss.

**Comment by thu3n** [comment]
I have the exact same ”issue”.

When i listend to anything in the app via my airpods. 
Iphone have that siri could read a recieved notification. When siri reads is, the audio gets to pause and wont resume when siri are finished.

How it happens.
1. Listend to anything via airpods etc.
2. Get notification from Facebook messanger etc
3. Siri will read the notification for you, and the audio will be paused.
4. Siri are finished reading.
5. Audiobook still remain paused.

expected behaivior are like when listend to spotify, spotify will still run, but the volume goes down to like 5% and the notification will be red. When notification are finished. Spotify will go back to the volume you where at.
Or expected are like the ts mentioned. The audio should be paused and resumed once the notification have been red.

**Comment by advplyr** [comment]
Yours is slightly different from the OPs. The OPs issue was actually resolved in the last iOS app I believe but was brought up recently here https://github.com/advplyr/audiobookshelf-app/issues/283 as well

Having the audio resume again after a notification is another issue and was brought up here #191
