### ISSUE TITLE
[iOS]]: audio interruption does not resume payback

### ISSUE THREAD

**Issue by norseghost** [advplyr/audiobookshelf-app#191]
### Steps to reproduce

1. play audiobook
2. system interrupts playback (a notification,  a phone call)

### Expected behaviour
playback should resume

### Actual behaviour
nothing happens

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [X] iOS App?:

#### iOS Issue
iOS Version: 15.4.1

iPhone model: XS max

**Comment by BCNelson** [comment]
I have this problem as well

**Comment by advplyr** [comment]
Please follow up if this issue still persists in the latest version [v0.9.57-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.57-beta)

**Comment by BCNelson** [comment]
It is still happening

**Comment by advplyr** [comment]
Is this still happening in v0.9.60? I see an update was made for this in [v0.9.58-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.58-beta)

**Comment by advplyr** [comment]
Awesome!
