### ISSUE TITLE
Unable to download books with TITLE which have non-english letters.

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf-app#192]
### Steps to reproduce

1. Create Book with non-english letters ("Ciałość")
2. Try to download Book
3. Downloading will crash at 100% . Folder is created  "Ciałość", , and all files are downlaoded.

superpawko — Yesterday at 8:38 PM
I have found what breaks it. 
what fixed it:  Removing polish letters from title.
It creates later folder also with polish lettes. So i think this is what breakes it.
I'm testing now filenames.
give me few minutes.
it takes a lot of time to re-scan one book.
Also saving audioobook only by title could be problematic in the future, if you have same title but different authors, or different narrators.
it works with non-polish title, polish letters in filenames.  I will lastly check if it is only re-edit of medata what fixed it. So I Will go back to polish letters inserted from hand.
Going back to polish letters in title , crashes again download manager at 100%.
I will create ticket tomorrow.
advplyr — Yesterday at 9:23 PM
Can you create a folder manually yourself with polish letters?
superpawko — Yesterday at 9:42 PM
yes, ABS also creates folder with polish letters, download everything, but while SCANING something is wrong and it crashes
So even I have files, and folder, I can not Re-Scan it. Because it will crash.

### Expected behaviour
- Book should be downloaded

### Actual behaviour
-   Downloading will crash at 100% . Folder is created  "Ciałość", , and all files are downlaoded.

### Environment data

Audiobookshelf Version:

- [ X ] Android App?
- [ ] iOS App?

#### Android Issue
Android version:
12
Device model:
Oneplus 9 pro
Stock or customized system:
STOCK
#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
I just tested this and had no problems downloading a book with that title. Tested on Android 12 with Google Pixel 6.

**Comment by superpawko** [comment]
I still can't. I checked other book with title "igła"  and it was downloaded successfully. I tried book with word "Śmierć" and it faield. May I send you this audiobook? Maybe the problem is in .opf file and metadata from it ? I will check more audiobooks tomorrow.

**Comment by advplyr** [comment]
Are they all mp3 or all m4b?

I don't think this has to do with the characters in the book title or filenames.

**Comment by superpawko** [comment]
Only .mp3

**# Example 01**
I tried changing title to : 
Ciałość   - Works: No
Ciałosc   - Works: Yes
Ciałośc   - Works: No
Cialosc   - Works: Yes

Works: NO   - > Crash after 10-15 seconds when all files are downloaded already at 100%

**# Example 02**
I tried different book:
Igrzyska Śmierci - it didnt work. IT crashed in first second of downloading. I investigated what could be a problem with MP3Tag, and 
1. In ID3 tag there was some strange strings in the comment:  like \00FF00 .
2.  I changed it to something normal.  like "text"
3. I performed a re-scan of this book
4. I did download audiobook
5. It was okay this time. So book with Ś was okay this time.


**# Example 03**
Świat bez końca Część 01 :  does not work
Swiat bez konca Czesc 01 : After changing title and pressing save, download was possible
Świat bez końca Część 1 : does not work (here I tested if only reloading title can help)

**# Example 04**

I have found another book which crash just after pressing download, This time I noticed that the cover is not 1:1. I have 3 books with this title and author:
1.  1:1 cover , works 
2.  ~ebook cover  does not work  ( crash in 1st second)
2.  ~ebook cover  does not work  ( crash in 1st second)

I have deleted cover for 2nd book and it works.  Other problem is, that you cant downlaod 3 books with the same title, You get error about not able to create library item. I will make new issue.


What I can do to help is:
Send you a archive of few books which works and not, with .opf files, so you only need to create new library and scan folder.


What maybe you could do:
Save somekind of log file into a download folder for example:
Cialosc-{Timestamp}.log
Maybe it is something with encoding of ID3tag? 

Questions:

1. What happens in the end of downloading a book, after file are downloaded , what ABS is checking?
2. How removing few polish letters from title helps me download a book.

**Comment by advplyr** [comment]
The files are initially downloaded into the /downloads folder or similar on your device then transferred to the folder you selected them to be in.
Make sure there are no other folders with a similar name on your mobile device when you download, maybe there is already a folder with that name and it is causing a problem.

If there are some audiobooks that can use the polish characters and others that cannot then I don't think it is the polish characters.

What you should check is where the audio files end up. Are they in the final destination? Or are they in your /downloads directory?

**Comment by superpawko** [comment]
So I have Created fresh new DB. 

DB: 5 books
I have tested with metadata from opf files and from id3 tags.
Ciałość  works every single time but  **Świat bez końca Część 01** does not for both libraries.

I have sent you url with mini version of this DB. with only 1 mp3 file.
ALL Files are downloaded but it crashes app and book does not appear in the library.

What suprise me is that I can't download the same book on my Big Library... (Ciałość)

**Comment by superpawko** [comment]
**I did not removed polish characters**. You used **Folder Names**, which does not have polish letters (and have CalibreID) so Indeed it will work because **it does not have polish letters**.  Metadata in **ID3** tags are from **goodreads**, and .**opf** is from **lubimyczytac**.

Could You please use .opf or  prefer audio metadata. Thank you!

I tested letter by letter Ciałość  and in BIG library it crashes in few instances.  In fresh DB with only 5 books it works. 

Ciałość - Works: No  , In fresh DB with only 5 book it works.  But removing polish letters in big library helps.
Ciałosc - Works: Yes
Ciałośc - Works: No
Cialosc - Works: Yes


**"Świat bez końca Część 01" Does not work in both DB.**
Świat bez końca Czesc 01 - Works: No
Świat bez konca Czesc 01 - Works: No
Swiat bez konca Czesc 01 - Works: **Yes**, without polish letters

I tested it in so many ways I'm in 95% sure that it is something with encoding and how you check if this title is in ABS base. 

If I have 3 audiobooks with the same title , and I download all of them, How ABS know which version do I have?

**Comment by superpawko** [comment]
SUPER!  Thank you! I will keep testing after new release.

**Comment by advplyr** [comment]
Fixed in [v0.9.47-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.47-beta)
