### ISSUE TITLE
Persist scroll position for bookshelves (similar to web UI)

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf-app#196]
Similar to the recent change to the web ui added in server 2.0.15 (Persist scroll position for bookshelves, https://github.com/advplyr/audiobookshelf/issues/604) it'd be nice to have the library in the mobile app also return to the section of the library one was viewing before opening a library item to view the details.

From that issue submission: If I'm browsing the library and click to view the details of an Audiobook, when I click the 'back' button, I'd like to be returned to the previous place in the library.

If I have a large collection and wish to browse titles for an interesting book to listen to, then continually being returned to the top of the library is very frustrating.

**Comment by advplyr** [comment]
Fixed in [0.9.46](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.46-beta)
