### ISSUE TITLE
Request: Android Auto

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf-app#2]
Please.

^_^

From the way Plex works, it seems there are a lot of options that can go into the way an AA app works, so I understand if this is going to take awhile. I'll manually play from my phone screen until then.

**Comment by advplyr** [comment]
I played around with this and got some baseline support added. Release `v0.9.1-beta` should recognize the app in android auto, however the audiobooks will not load unless you have opened the app first (as opposed to only launching from android auto).

I think it is going to be difficult to have the audiobooks load when launching the app from android auto, but right now I have little understanding of AA.

Unfortunately there is a bug with Pixel 3 and my car so I could only test this using an emulator. I could use your help on testing this out on your system. 

1. Launching the app from android auto, then opening the app manually to see if the audiobooks load.
2. Launching the app manually, then launching from android auto.

**Comment by Budlyte** [comment]
Once the update shows available on the play store, will do.

**Comment by advplyr** [comment]
The update just got approved on the play store. It took longer I guess because I added the app as android auto compatible.

**Comment by advplyr** [comment]
I forgot to mention here that I had to remove the AA support. The google play store has additional requirements for android auto apps that the app did not meet, so this feature is still pending development.

**Comment by danmed** [comment]
Just to add to this, AA support is the killer feature for me as the only time i listen to my books is in the car.. if you can make this work then it automagically becomes a direct replacement for booksonic-air.

**Comment by cillin89** [comment]
> Just to add to this, AA support is the killer feature for me as the only time i listen to my books is in the car.. if you can make this work then it automagically becomes a direct replacement for booksonic-air.

I second this.

**Comment by rubbo898** [comment]
Quote, a must have feature in my case

**Comment by advplyr** [comment]
I have a release of the android app with android auto support currently in review.
It is my second attempt at getting it approved for android auto and it takes a few days so I just wanted to post an update here.

**Comment by advplyr** [comment]
After a few more rejections I added a "Local Audio" section in the android auto app so that the google testers could verify it was working, and it got approved. So if you see that category you'll know why it is there.

`v0.9.21-beta` should work with android auto. I have only tested on an emulator until my new phone comes next week.

**Comment by rubbo898** [comment]
I'm going OT: anyone is experiencing strange behaviors when playing audiobooks in Android (not only Andriod Auto)?

With the players I've tested (all the available in play store) I have the following "issues":

- Within AA the track sometimes stop for 1/2 secs and suddenly move forward of 10/20/30 secs.
- Even if I've disabled the options, when pause/notifications/calls the tracks auto-rewind of a random amount of secs, sometimes even forward!

I have a Oneplus 8, latest official firmware (11.0.9.9)

**Comment by feerlessleadr** [comment]
@rubbo898 I use the app pretty much daily (both via bluetooth as well as via Android Auto). I am using a 1+8T on latest firmware. 

I have noticed 2 things related to android auto behavior however so @advplyr if you want me to open separate issues I can:

1. When I am listening to music through my regular music app through AA and then switch to audiobookshelf app, the current book I'm listening too will refuse to load, and I need to select if from the list. Once I select it, my playback speed settings are not respected (I listen to my books at 1.5x), and instead it seems like it plays back at 1X or slower. As soon as I unlock my phone and select the audiobookshelf app on my phone, everything works as expected using AA. 
2. Similar to [this issue](https://github.com/advplyr/audiobookshelf-app/issues/40) the remaining time isn't adjusted based on the playback speed selected in the app when using AA. 

Other than these 2 items (as well as the app randomly jumping back about 5-10 minutes when resuming a book), this ecosystem has been absolutely awesome. thanks!

**Comment by felixbro** [comment]
Just tested the 0.9.34-beta in my Car, here are the things i noticed:

- First time it only showed me my audiobooks after i manually startet the app. After that i could open it from AA. 
- The books startet at the correct timestamp. after playing like 5 min, i continued listeing at the app and it startet at the original timestamp (so now sync, from that was played in AA)
- the second time i connected to AA it only showed me 2 recend played books (i had 4) and the other as 100% red and they are listed ar "read again".
- it would be nice to the have a playlist with all chapters or audiofiles. now i can only the a x hour long progress bar. so it would very hard to navigate in the timeline. ;-)

im using the app on a pixel 6 pro with Android 12

**Comment by advplyr** [comment]
`v0.9.35-beta` was just released and will keep your progress when streaming from AA, this should address one of your bullets hopefully. Progress already worked but only when you had the app open on your device already. This is a fix for when opening the app from your cars AA.
I think you're right about the playlist of chapters, it would be easier to navigate that way.

**Comment by mediacowboy** [comment]
One feature I wish AA had was the ability to auto start playing when I connect. Right now I have to launch the app and select the book. 

If I am missing something please point me in the right direction.

**Comment by advplyr** [comment]
The android auto feature is stable now. I just pushed an update that should fix some crashing.
There is still a lot more to be improved, here are the relevant AA tickets still open
#79 #141 #167 #229

This was the first feature request btw! We've come a long way, thanks for everyone testing this feature over the last ~10 months.
