### ISSUE TITLE
Android Auto - Blank Screen

### ISSUE THREAD

**Issue by andonevris** [advplyr/audiobookshelf-app#201]
Using latest version of server and app (2.0.14 & 0.9.45 beta)

When starting audiobookshelf from within android auto I get a black screen, I expect there should  be a book list or something there.

If I start a book playing on the phone a pink/purple circle appears on the android auto interface and if I click on that I can get into the book that is playing.

### Steps to reproduce
1. Plug phone into car when audiobookshelf is not playing anything.
2. Click on audiobookshelf icon on android auto
3. Get black screen

### Expected behaviour
1. Plug phone into car when audiobookshelf is not playing anything.
2. Click on audiobookshelf icon on android auto
3. Be presented with a book list or some controls

### Actual behaviour
Black screen with spinning circle no controls available until I start playing a book on the phone, then I can see the book playing on Android Auto

### Environment data

Audiobookshelf Version:
0.9.45 beta
- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version:10

Device model: Galaxy S10

Stock or customized system: Stock system Rooted

**Comment by mediacowboy** [comment]
Seeing similar behavior. Plug phone in click abs. Select a book. Then sits at "Getting your selection...". 

App: 0.9.46-beta
OS: Andriod 12
Server: 2.0.15

**Comment by duplaja** [comment]
Seeing the same as mediacowboy . 

App: 0.9.46-beta
OS: Android 10
Server: v2.0.17

**Comment by advplyr** [comment]
Made some adjustments to android auto in [v0.9.47-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.47-beta)
Let me know how that goes! Requires server 2.0.19

**Comment by andonevris** [comment]
Have done lots of driving today, in and out of the car, connected fine every time.  

Seems resolved to me

**Comment by advplyr** [comment]
Nice! Thanks for testing
