### ISSUE TITLE
Stats in the app (maybe "My Account" page?)

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf-app#206]
Right now I believe the only way to view stats is from the browser.

I think it would be nice to be able to view my stats from within the mobile app. It might make sense to make them visible under the "My Account" tab in the app. Right now that screen just tells you what server and username you're using.

Thinking it through, it might make sense simply beneath the server stuff, or it might make sense to make the pages nested. Like, tapping my account opens a list (just two items for now): Server Connection, and My Stats, then tap either one to open a page with that info. Maybe the link to GitHub can be on the list page as well.

**Comment by advplyr** [comment]
Agreed! If you can think of a specific design that would be great. The more specific the better!

**Comment by hobesman** [comment]
![image](https://user-images.githubusercontent.com/29721765/171551356-6ff62218-3bd0-450a-946f-4f3a3f32e366.png)

![image](https://user-images.githubusercontent.com/29721765/171551016-fa7ddc56-3de2-4e65-9dad-e5438fd8d1b8.png)
Here's one proposal for the "Account" page.

**Comment by hobesman** [comment]
Or you break it up into two pages. Like this:
![image](https://user-images.githubusercontent.com/29721765/171551761-1c348869-89e7-4b1b-8afe-840c2ca474e9.png)

**Comment by hobesman** [comment]
Or maybe separate the session history like this (and make "log out" easily accessible too):

![image](https://user-images.githubusercontent.com/29721765/171552118-5b03eafe-1b79-47f8-aa8d-dc110b3982fa.png)

**Comment by advplyr** [comment]
Added in [v0.9.56-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.56-beta)
