### ISSUE TITLE
Show chapter progress

### ISSUE THREAD

**Issue by gvarph** [advplyr/audiobookshelf-app#208]
I'm used to both total progress and chapter progress being shown in the *playing section*

Show both chapter and total progress like the attached screenshot

If you think that would take up too much space, turn it into an option

![image](https://user-images.githubusercontent.com/17300137/170532965-954bd933-256d-4bfa-8a99-32beb8c4ca8f.png)

**Comment by advplyr** [comment]
This is already an option see #46
