### ISSUE TITLE
Pressing forward 30sec multiple times causes player to jump to the end of the book

### ISSUE THREAD

**Issue by itsamenathan** [advplyr/audiobookshelf-app#210]
### Steps to reproduce

1. Jump forward 30 sec multiple times
2. See the player jump to the end of the book

### Expected behaviour
- You keep jumping forward 30secs

### Actual behaviour
- Jumps to the end of the book

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.46-beta

Device model: Samsun Galaxy s21

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
I just tested this and was not able to replicate on both streaming and playing a downloaded audiobook.

**Comment by advplyr** [comment]
I wasn't able to reproduce this. Let me know if you find a pattern or something to go off of.
