### ISSUE TITLE
Android app not connecting to server using a Tailscale address

### ISSUE THREAD

**Issue by Koliera** [advplyr/audiobookshelf-app#217]
### Steps to reproduce

1. Setup Tailscale on server and Phone
2. Use app as usual and try to log in pointing to the server 
3.

### Expected behaviour
- I sign in to the server using the Tailscale address (100.xxx.xx.xx:1337)

### Actual behaviour
- The app sees that the server is there and gives me a chance to log in, but when adding the password/username it throws an "Unknown error". **Going to the same address on a browser works fine.** 

### Environment data

Audiobookshelf Version:

- [ x] Android App?
- [ ] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
I'm not able to replicate this issue. Maybe check in the discord if someone has come across this but doesn't appear to be a bug with the mobile app.
