### ISSUE TITLE
Progress bar and play buttons don't show current state when playing downloaded books on Android

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf-app#218]
### Steps to reproduce

1. Download book to phone
2. Play downloaded book
3. Watch progress bar and time stay frozen, and play button plays/pauses but doesn't change to reflect what it's doing.

### Expected behaviour
- The progress bar should move, the playback time should refresh, and the play buttons should reflect the current state.

### Actual behaviour
- 
progress bar and time stay frozen, and play button plays/pauses but doesn't change to reflect what it's doing.
### Environment data

Audiobookshelf Version: Server 2.0.19 and app 0.9.47-beta

Note: problem began at same time as #219 and may be related

- [ x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 9

Device model: LG G7 Thinq

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by raviwarrier** [comment]
Example:

https://user-images.githubusercontent.com/42061703/172066632-5ab64cf1-279e-4754-bdf8-43249381a12e.mp4

**Comment by advplyr** [comment]
Yeah I see this also

**Comment by raviwarrier** [comment]
I moved back to the previous version for now... am sure you guys will fix it soon.

**Comment by hobesman** [comment]
To make it work did you have to revert the app, the server, or both?

**Comment by advplyr** [comment]
Fixed in [v0.9.49-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.49-beta)

**Comment by raviwarrier** [comment]
Only the app. will check out the new beta and report back.
