### ISSUE TITLE
Downloaded books don't save progress on Android

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf-app#219]
### Steps to reproduce

1. Download book to device
2. Listen to book
3. Close app or listen to a different book
4. Go back to first book and press play. 

### Expected behaviour
- it should resume where you left off

### Actual behaviour
- it resumes where it was as if your previous session never occurred.

### Environment data

Audiobookshelf Version: Server 2.0.19 and app 0.9.47-beta

Note: problem began at same time as #218 and may be related

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 9

Device model: LG G7 Thinq

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Fixed in [v0.9.49-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.49-beta)
