### ISSUE TITLE
Log-out button on Account page doesn't work on Android

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf-app#222]
### Steps to reproduce

1. Tap the hamburger menu button
2. Tap Account
3. Tap Log out

### Expected behaviour
- It logs you out.

### Actual behaviour
- Nothing happens.

### Environment data

Audiobookshelf Version: Server 2.0.20, app version 0.9.48-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 9

Device model: Lg G7 Thinq

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Fixed in [v0.9.49-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.49-beta)
