### ISSUE TITLE
download books to local

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf-app#223]
### Steps to reproduce

1. tap download button on any book
2. 1st time tap dl > dont see the circle with the count of files inside and the "Download" (x%) under stream button
    2nd time (re-download) > all is showing but this is random 
    >>> dl on P10 > i see the circle and all other
    >>> dl on my sm-t725 (android 11) > i dont see any circle and other things ... if i tap the dl button again there is a popup that says: 
    "already dl on this media" (this info is missing on P10 android 9 )
3. book with 2 files > ok
   book with over 100 files (~400) > dl > app crash (idk android and available crash log locations) > dl in background > open app and after few time (dl in background) it stops dl ...
4. re-open app > cant dl anything > i see the circle with a jumping count number and the Download! text (0%) anytime ...

after reboot server and restart app, there is no dl possible > i see the circle with a jumping count number and the Download! text (0%) anytime ...

### Environment data

Audiobookshelf Version: 2.0.20

- [x ] Android App? 0.9.48-beta

#### Android Issue
Android version: 9

Device model: Huawei P10

Stock or customized system: Stock

**Comment by advplyr** [comment]
Downloads in progress will not persist when you restart the app. Are you sure you completely closed out of the app and re-opened it?

**Comment by skyzuma** [comment]
i close the app with ... idk how is named ... task manager?

**Comment by skyzuma** [comment]
btw, its possible to make an download-page ? maybe under the circle with any detailed informations?

**Comment by advplyr** [comment]
Yes my original idea was that clicking the circle would take you to a page with a list of the items downloading and their progress.
I'm not sure what this issue you came across is though.

**Comment by skyzuma** [comment]
after restart the smartphone the dl manager goes crazy and downloaded all files ... problem with the dl-manager on android 9?

**Comment by skyzuma** [comment]
i switch to the tablet (android 11)

**Comment by advplyr** [comment]
Are you able to reproduce this on the latest?

**Comment by skyzuma** [comment]
i cant test it on huawei p10 (android 9) ... create a local book folder with access rights > error: permission denied
