### ISSUE TITLE
Click/tap cover image to view larger

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf-app#224]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
Sometimes I want to get a closer look at the cover image but the largest size in most views is just a thumbnail

### Describe the solution you'd like
I'd like to be able to tap on the cover art in the book details page (and maybe the now playing page) and have it open a large, maybe full screen, version of the image.

**Comment by advplyr** [comment]
Added in [0.9.50-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.50-beta)
