### ISSUE TITLE
Allow adding / importing podcasts via app

### ISSUE THREAD

**Issue by genebean** [advplyr/audiobookshelf-app#225]
### Is your feature request related to a problem? Please describe.

Im frustrated I can’t add podcasts via the app

### Describe the solution you'd like

I would like to add podcast rss feeds and opml files from the mobile app. I’d also like to be able to share an opml from a podcast app that exporting it into Audiobookshelf via the iOS share menu (all 3rd party podcast apps I’ve used support importing via this method).

### Describe alternatives you've considered

I tried adding via the mobile web interface but discovered https://github.com/advplyr/audiobookshelf/issues/693

The mobile web method is still suboptimal, especially when it comes to importing opml files.

**Comment by advplyr** [comment]
Are you expecting the podcast episodes to download locally on your mobile device or download on the server?

It's important to note that abs is not comparable to other podcast apps because abs is serving content from your server primarily. This makes building the interface challenging because it is then confusing about where will these episodes get auto-downloaded too? Will they be available on my server?
There is a lot that goes into a feature like this for the mobile app that doesn't need to be considered for regular podcast apps.

**Comment by genebean** [comment]
I’m expecting them to be on the server. My use case for this is to easily copy subscriptions from my mobile listening app to ABS where I’ll archive select episodes.

**Comment by siopao** [comment]
Echoing the above as a new user, I thought the app would mirror the website functionality with the ability to search and add new podcasts (to the server). I was pretty confused as to why the "search" in the app via the magnifying glass was different than the "search" option in the website. 

Opening the website back up today, I realized these are two different search options and the search "to add new podcasts" is missing from the app.

**Comment by advplyr** [comment]
It can be confusing, we need a UI/UX designer to help us out

**Comment by mattague** [comment]
Just chiming in to say I would love to be able to add podcasts to the server from mobile. My main use case is my partner and I adding podcasts with long back catalogues for each other to listen to, and I would like my own backup of these in case any are ever archived by the makers.

**Comment by advplyr** [comment]
We're going to have to add new user permissions to the server that are specific to managing podcasts.
Until that is added this will be available only to admin users.

**Comment by advplyr** [comment]
Added in [v0.9.60-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.60-beta)

Currently restricted to admin users. Also no editing of podcast details or episode details.
