### ISSUE TITLE
Custom Playback Speed Rounded to Nearest "preset" Value

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf-app#226]
### Steps to reproduce

1. Set playback speed to 1.7x (or any speed that isn't one of the default options of 1, 1.2, 1.5, etc.)
2. Force close ABS app, then reopen and then start playing a book (tested on both local and streaming books)
3. Playback speed is reset to 1.5 instead of staying at 1.7x

### Expected behaviour
- App should remember playback speed

### Actual behaviour
- App defaults to a pre-set speed instead.

This has been an issue for quite some time, I've just not had the time to report until today. I know a bunch of updates we're pushed in the last day or so, didn't want you think think this relates to those. 

### Environment data

Audiobookshelf Version: 0.9.49-beta and running server version 2.0.20.

- [x] Android App?

#### Android Issue
Android version: 11

Device model: OnePlus 8T

Stock or customized system: stock

**Comment by advplyr** [comment]
Fixed in [0.9.50-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.50-beta)
