### ISSUE TITLE
Headset only has stop button

### ISSUE THREAD

**Issue by puregreen59** [advplyr/audiobookshelf-app#228]
Hi there, not a issue so much with the software, well I'm pretty sure it's my hands free thats causing the problem 

I have a cardo pack talk bold for my motorcycle helmet, and using the android app. 

when I hit what I thought was the pause button it completely stops it, when I press the play button again it won't play, I have to pull over and open the app too manually start the audiobook. 

Turns out going through the manual for my cardo, it has a play button and a stop button among other buttons, so pause button! 😭

 any other way of getting this to work?

Cheers guys keep up the great work!

**Comment by advplyr** [comment]
I would assume this would be similar to bluetooth controls where the play button acts as a play/pause button.
If you press play when it is playing it doesn't pause?

**Comment by puregreen59** [comment]
Unfortunately not 😭 tapping it again skips forward

**Comment by advplyr** [comment]
Have you tried a long press? Hold for over 2 seconds?

So far this sounds like a bug with their software. Maybe they have a forum board or a contact form you can ask about a play/pause button.

**Comment by puregreen59** [comment]
Hands down, i think where just dealing with a very strange implementation!


https://www.cardosystems.com/wp-content/uploads/guides/pocket/en/packtalkBold-mobile.pdf
