### ISSUE TITLE
Android Auto Ignoring Playback Speed

### ISSUE THREAD

**Issue by andonevris** [advplyr/audiobookshelf-app#229]
### Steps to reproduce

1. Start stream on android auto with AB not running on phone
2. Playback starts at 1.0x even though playback speed is set on phone as 1.2x
3. Open AB on phone while still connected to AA
4. Playback instantly speeds up to 1.2x
5.

### Expected behaviour
- Tell us what should happen
- AA playback should use the speed set on the phone even if AB is not running on phone

### Actual behaviour
- Tell us what happens
- Playback is at 1.0x unless you open the app on the phone which updates AA with the correct speed

### Environment data

Audiobookshelf Version: v2.0.20

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.49

Device model: Galaxy S10

Stock or customized system: 
Stock Android 10 (rooted)

#### iOS Issue
iOS Version:

iPhone model:

**Comment by barelylit** [comment]
This is also happening on unpause from android app 

Server: v2.0.18
App: 0.9.49-beta

**Comment by advplyr** [comment]
Added in [v0.9.52-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.52-beta)
