### ISSUE TITLE
[Android] audio skips back 5s on notification

### ISSUE THREAD

**Issue by jt196** [advplyr/audiobookshelf-app#230]
### Steps to reproduce

1. Play something on Android app
2. Receive notification

### Expected behaviour
- I'd prefer the app to pause on notification sound, then resume when the sound is finished. Currently, a one off sound is ok, but if I get a few in short period of time, the skipping back is really annoying. 

### Actual behaviour
- Audio skips back ~5 seconds on receipt of a notification. 

### Environment data

Audiobookshelf Version:

- [x] Android App - most recent as of June 08 2022. 

#### Android Issue
Android version: 12

Device model: Pixel 3

Stock or customized system: CalyxOS

**Comment by DDriggs00** [comment]
Perhaps the auto-rewind function could be adjusted to have a minimum time before rewinding, maybe 3 seconds?

**Comment by jt196** [comment]
Any control would be useful! Unless I'm missing something, the app doesn't really have settings to control local stuff. Guess that's a Vue/Android thing.

**Comment by advplyr** [comment]
Ah yeah I just mentioned this in #244
I was using android auto on a road trip and the auto-rewind was really irritating when also using navigation.
Adding user config to adjust this is something planned, but first we should define a good default.

**Comment by jt196** [comment]
My figure is the least intrusive would be the best. Either pause between start and end of notification, or no pause at all, probably the former.

**Comment by jt196** [comment]
@advplyr I think this is resolved on the most recent app release, right?

**Comment by advplyr** [comment]
Correct this is resolved. Auto-rewind only happens now after a 10s pause and can also be disabled entirely in settings.

Here is the breakdown
```js
    if (time < 10000) seekback = 0 // 10s or less = no seekback
    else if (time < 60000) seekback = 3000 // 10s to 1m = jump back 3s
    else if (time < 300000) seekback = 10000 // 1m to 5m = jump back 10s
    else if (time < 1800000) seekback = 20000 // 5m to 30m = jump back 20s
    else seekback = 29500 // 30m and up = jump back 30s
```
