### ISSUE TITLE
Item details stay in view after clicking back from library item screen

### ISSUE THREAD

**Issue by kymahi** [advplyr/audiobookshelf-app#231]
### Steps to reproduce

1. Tap on any book in your library
2. Tap the ellipses menu in the top right corner
3. Tap View Details
4. Observe the item details appear
5. Tap the Android back button
6. Observe the screen returns to the library
7. Observe the item details still remain on the screen
8. Tap the X close button
9. Observe the item details still remain on the screen

### Expected behaviour
- Either:
- The item details close and the user remains on the item screen or
- The item details close and the user is sent back to the library and
- Tapping the close button should always dismiss the item details view

### Actual behaviour
- The user is sent back to the library, but the item details remain on the screen and unclosable

### Environment data

Audiobookshelf Version: v2.0.20

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: Android 11

Device model: Sony Xperia 1 III

Stock or customized system: Stock

**Comment by kymahi** [comment]
My apologies. I did attempt to fix this issue, but I have no idea what I'm doing in Vue, and my attempt made my local build much worse 😅

**Comment by advplyr** [comment]
I tagged the wrong issue in the commit https://github.com/advplyr/audiobookshelf-app/commit/b4bb6bf81bc478c7d1458a680ee4ebadfaa7b4aa

**Comment by advplyr** [comment]
Fixed in [0.9.51-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.51-beta)
