### ISSUE TITLE
FYI: playbooks lite

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf-app#232]
### Is your feature request related to a problem? Please describe.
Just in case you weren't aware of this app. https://github.com/Goodwy/PlayBooks 

It has a nice clean player UI. The dev is not the greatest at keeping the source updated on github.

https://play.google.com/store/apps/details?id=com.goodwy.audiobooklite

https://play-lh.googleusercontent.com/cyPuGUDvCyog-tbaPD8E6O6WTy8ffEU18b5xf-Cm3B2628Tqcrs97mOg6YVVU6N6xXo=w2560-h1440-rw

**Comment by advplyr** [comment]
I am, thanks. It may be better to put these in Discord or if you have something specific you like in the app that you want to be implemented that would be a good feature request.
