### ISSUE TITLE
Now playing page in landscape mode in Android app is jumbled

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf-app#234]
### Steps to reproduce

1. Play a book
2. Rotate device to landscape mode
3. Observe

### Expected behaviour
Things should move and resize to fit together

### Actual behaviour
Things overlap, get cut off, etc.
![Screenshot_20220608-133928](https://user-images.githubusercontent.com/29721765/172978913-f3e1544d-3005-48de-9c12-fbc8b460b51d.png)

### Environment data

Audiobookshelf Version: 2.0.21

- [x] Android App? 0.9.49-beta
- [ ] iOS App?

#### Android Issue
Android version: 9

Device model:

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Fixed in [0.9.50-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.50-beta)
