### ISSUE TITLE
Server version displayed in mobile app

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#235]
### Is your feature request related to a problem? Please describe.
When using the mobile app, if I need to check/see the server version number, I have to log on to the web app, go to settings just to check one number. This is, sometimes an hinderance when seeking quick help from the devs. Additionally, it's even more problematic for users who do not have access to the server (like end-users - friends, family, etc.) and have to rely on the server admin to respond with (often with delay) the info they need in order to get help.

### Describe the solution you'd like
In the side menu panel, along with the app version, display the server version as well.

### Describe alternatives you've considered
None. The side menu panel is the best place to display the server version number.

**Comment by jmt-gh** [comment]
This was merged in https://github.com/advplyr/audiobookshelf-app/pull/233 and will be available in the next release!

**Comment by raviwarrier** [comment]
Awesome. Thanks. :)

**Comment by advplyr** [comment]
This was included in the latest release
