### ISSUE TITLE
[Enhancement]: Display play-time for books in collection view

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#240]
### Is your feature request related to a problem? Please describe.
Sometimes, you just have limited time in a specific period and you want to select a book from a playlist/collection that you know you can finish within that period. But, in the mobile app, the length of the book (as time) is not displayed which makes me open each book view to see if it's something I should start reading. 

![tempFileForShare_20220614-183051](https://user-images.githubusercontent.com/42061703/173584219-b9dd3ab1-10df-47e7-b86b-e16ca18b99ba.jpg)

### Describe the solution you'd like
Just a simple label indicating total playback time in the list will do. Below the author's name seems like a place it would fit.

### Describe alternatives you've considered
None.

### Additional context
NA

**Comment by advplyr** [comment]
This was added in [v0.9.51-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.51-beta)
I also cleaned up that UI a bit and truncated the long titles.
