### ISSUE TITLE
[Bug]: E-reader cut-off by playback bar

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#242]
### Steps to reproduce

1. While playing an audiobook, open the accompanying EPUB
2. See image attached.
3. NA

### Expected behaviour
- Tell us what should happen
All the lines of the page should be visible/readable.

### Actual behaviour
- Tell us what happens

The last line of the e-reader is hidden behind the playback bar and hence obscuring the text on that line.
![tempFileForShare_20220616-161336](https://user-images.githubusercontent.com/42061703/174054225-ad25a9b2-5229-4452-89f9-d52f33aac3d0.jpg)

### Environment data

Audiobookshelf Version:

- [ ] Android App? 0.9.46
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model: Samsung M30s

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by raviwarrier** [comment]
Sometimes it's two lines:

![tempFileForShare_20220616-162537](https://user-images.githubusercontent.com/42061703/174055918-572a707f-d8c8-461e-b51a-68b44f1df7a9.jpg)

**Comment by advplyr** [comment]
This was fixed in a previous version I just missed this issue.
