### ISSUE TITLE
E-book reader doesn't save last location

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#243]
### Steps to reproduce

1. Open an ebook, go to any page.
2. Close the reader.
3. Open the book again.

### Expected behaviour
- Tell us what should happen
Should open up the page that was last open in the reader.

https://user-images.githubusercontent.com/42061703/174057872-3af14ba9-7f83-4303-b229-4c4c6e443b8b.mp4

### Actual behaviour
- Tell us what happens
Jumps back to the first page/cover instead. See attached screengrab.

### Environment data

Audiobookshelf Version: 0.9.46

- [ ] Android App? Yes
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model: Samsung M30s

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by raviwarrier** [comment]
In the meanwhile, what could help your users is that when they click the download button, instead of downloading just the audio files and cover, the app could download the epub as well. This way the user can get the book without switching applications and then read it locally with another app (until your feature is ready).

![Screenshot_20220617-064201_audiobookshelf.png](https://user-images.githubusercontent.com/42061703/174203042-f7039a5c-d39f-4938-bfc1-760836d82da2.png)

This book folder has 2 files - m4b and epub, but the prompt asks about downloading only the audio file.

**Comment by raviwarrier** [comment]
Another solution is to let users read the ebook using their preferred/default, locally installed app directly when they click the read button.

Some may tell you that this is a bad product design/business decision (making users go away/out of your app), but it's actually not. From the users point of view, you are creating a seamless experience (which is more important). When your e-reader is ready, you can turn off "open with [app]" and turn on your reader.

Trust me, your users will appreciate that you were thinking of their experience.

**Comment by DDriggs00** [comment]
> Another solution is to let users read the ebook using their preferred/default, locally installed app directly when they click the read button.

While I 100% agree with this, I think that there should be a basic ebook reader in the app (to look up spellings of names and places, etc.), with the option to either open internally in the basic ereader, or externally in a proper ereader (e.g. if intending to actually read the book).

**Comment by ambarnes2** [comment]
I agree with the previous users, without the ability to remember the last page, reading ebooks in this app is not really feasible.

**Comment by advplyr** [comment]
Added in [v0.9.64-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.64-beta)

Note this is only for epub ebooks right now. This will work on Android/iOS when connected to your server. On Android you can now download the ebook and read offline. It will sync with the server next to you open the app. There is some improvements on ebook syncing that will need to be made down the road.
