### ISSUE TITLE
Rollback not going past Chapter markers

### ISSUE THREAD

**Issue by SkippyTheMonkeyKeeper** [advplyr/audiobookshelf-app#244]
Currently the app automatically rolls back 30 seconds after resuming playback. That is fine when you are somewhere halfway in a story, but not when you just finished a Chapter and stop playback just after the start of a new Chapter. It's usually not very useful or desirable to hear the last 30 seconds of a Chapter.

That's why I am proposing that the rollback doesn't go past Chapter markers. So if a new chapter started within the rollback time it doesn't fully rollback but instead starts playback at the Chapter marker.

**Comment by advplyr** [comment]
I think this makes sense. The auto-rewind is also too sensitive. On a road trip and using navigation if the directions being announced is longer than a few seconds it triggers the rewind, which happens frequently back-to-back.
I think we need to re-define the auto-rewind functionality.

**Comment by advplyr** [comment]
Added in [0.9.50-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.50-beta)
