### ISSUE TITLE
User is unable to delete podcast episodes in Android app 

### ISSUE THREAD

**Issue by akshara-tg** [advplyr/audiobookshelf-app#245]
### Steps to reproduce

Even though "Can Delete" flag is enabled, user is not seeing the option to delete the podcast episodes in Android app.

The same user can see the option to delete the episodes in web app.

### Expected behaviour
User shall be able to delete the podcast episodes 

### Actual behaviour
User is not able to delete the podcast episodes

### Environment data

Audiobookshelf Version: 2.0.21

- [ ] Android App

#### Android Issue
Android version: 0.9.49 beta

Device model: Samsung Galaxy F62

**Comment by advplyr** [comment]
I may be misunderstanding what you are saying here but there is no option to remove any media on your server from the mobile app. We will probably add the ability to manage your server media from the mobile app eventually, but there are some design complications with the mobile app that don't exist with the web app.
The mobile app allows downloaded media so we need to differentiate what we mean by "Remove" if the user has downloaded the media item.
