### ISSUE TITLE
Way to get to book description from the player

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#246]
### Is your feature request related to a problem? Please describe.
Sometimes, whole reading a book, I want to go back and read the description - to get more info like published date, etc.

Currently, the only way to do that is to back out to the library and then tap on the book again to see the description.

### Describe the solution you'd like
A button on the player that would bring up the description that can be closed after reading and return to the player would be ideal.

### Describe alternatives you've considered
If not a button on the screen, perhaps in the menu.

(This might require a separate feature request, but I'm too lazy. The menu or the player screen can also have an action item/button to open the e-book directly from the player)

**Comment by jmt-gh** [comment]
we should probably just duplicate what we do on web and have tapping the cover art or title handle this this

**Comment by advplyr** [comment]
Added in [0.9.50-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.50-beta)
