### ISSUE TITLE
Time delay for 'listen again' section

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#248]
### Is your feature request related to a problem? Please describe.
![tempFileForShare_20220618-085704.jpg](https://user-images.githubusercontent.com/42061703/174421148-d243fe09-305a-4aa0-974a-3f6e396bdcd6.jpg)

I finished reading this book 3 hours back and it's on my 'Listen Again' shelf. This would make sense for music where someone might want to listen to songs again and again shortly after listening to it before, but for books, it makes less sense. It might even make sense for podcasts but since i don't listen to them I'll let someone who does validate that.

### Describe the solution you'd like
Keep a time delay of weeks/months before suggesting to listen again. And once the rating system is brought in it might make sense - if they rated it high, suggest again in a few months but ignore books that weren't liked/rated high.

As of now, for books, this is a moot feature.

### Describe alternatives you've considered
Suggested books might make more sense. For example, if I read a book on Quantum Physics (or a spy novel), suggest books on similar subjects/genres from the library (simple genre/tag matching), especially:

1. If the user indicates liking the book (high rating)
2. Books from other authors to encourage users to explore outside their preferences.

**Comment by JamesDean3** [comment]
Another option that could be added to this is if a new book in a series shows up, have the previous books in the series show up in the listen again list, but if the user gets a few hours into the new book, have it remove the previous ones from that list, generally I know within the first hour if a re-listen of the last book or possibly the entire series is necessary before continuing on.

**Comment by advplyr** [comment]
I don't think the complexity of that is worth it. The goal was to have those home page shelves configurable in which case you would eventually be able to disable the shelf if you wanted.
That shelf is basically a "Recently finished" also
