### ISSUE TITLE
Buffer indicator on chapter seekbar exceeds right border

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#250]
### Steps to reproduce

1. Turn on chapter seek bar
2. Let the book reach the end of the chapter
3. Observe that the buffer bar (light gray) pushes beyond the chapter seek bar

### Expected behaviour
- the buffer seek bar should end/right align with the chapter seek bar

### Actual behaviour
- See attached images
![tempFileForShare_20220620-073904.jpg](https://user-images.githubusercontent.com/42061703/174513519-9c3d78d0-7479-487a-98b5-294aa7c0b9b6.jpg)
![tempFileForShare_20220620-073933.jpg](https://user-images.githubusercontent.com/42061703/174513533-c258fc40-5a0d-427e-a8f9-3600c22ca829.jpg)

### Environment data

Audiobookshelf Version:

- [ ] Android App? 0.9.49-beta
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model: Samsung M30s

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Fixed in [v0.9.52-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.52-beta)
