### ISSUE TITLE
A download status/progress view

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#251]
### Is your feature request related to a problem? Please describe.
Once you start the download and back away from the item page, the only way (within the app) to check the progress is to go back to the item page.

It's partially okay if you just have one book downloading, but when you have multiple books being downloaded, going to reach book's item page to check download progress is cumbersome.

A page when you click on the downloading progress icon (see image below with (1) on the top) may be a better way to see/check up on all your ongoing downloads.
![tempFileForShare_20220620-204638.jpg](https://user-images.githubusercontent.com/42061703/174633964-153afae0-83ab-441c-a7e4-4de88598a103.jpg)

### Describe the solution you'd like
Sorry, put everything in the section above.

### Describe alternatives you've considered

None.

**Comment by raviwarrier** [comment]
Yes, one can look at the notification of the download manager, but that doesn't show the status of individual books. See screen grab below.https://user-images.githubusercontent.com/42061703/174634238-6409b761-6539-4f41-bacf-469bc6128c44.mp4

**Comment by advplyr** [comment]
Downloader has been re-written for the next release. You will be able to click on the icon and go to a page that shows the list of currently downloading files.

**Comment by advplyr** [comment]
Added in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
