### ISSUE TITLE
View all downloaded books

### ISSUE THREAD

**Issue by schrodingerskat** [advplyr/audiobookshelf-app#252]
### Is your feature request related to a problem? Please describe.
I like to batch-download books I plan to listen to soon, but there's not a great way to see books that I've downloaded but haven't started listening to yet. Is there a way to see books by download status? If not, I'd love to have a way to see just my downloaded books in the app.

### Describe the solution you'd like
I'm open to however you'd like to implement this, but my ideal solution has two parts:
- List downloaded books in a section on the Home tab (a new section, or include them in the existing Local Books section)
- Add a "Download Status" filter in the Library view

UX-wise, the two parts are independent, and I'd be happy with either one on its own. But the home sections are better for quickly finding something interesting, and the library view is nicer for considering all the options, so it'd be lovely to have both.

### Describe alternatives you've considered
I've tried a couple workarounds with existing features:
- Start playing everything I download, so it shows up in "Continue Listening." This is what I'm currently doing, but it means my Continue Listening section is full of things that I'm not actively listening to yet.
- Creating an "Up Next" collection through the web interface, then download those books through the app. This also works, but it means switching back and forth between the app and the web version to manage the collection, and requires manually keeping the list up to date. I'd prefer something that stays up-to-date automatically and that doesn't require switching back to the wb interface to manage.

**Comment by advplyr** [comment]
Your downloaded media should be showing in the "Local Books" or "Local Podcasts" shelf on the home page. Local books/podcasts will also show media you may have already had on your phone not connected to your server.

We should add the downloaded filter.

**Comment by schrodingerskat** [comment]
Aha, thanks for clarifying. The "Local Books" section hadn't been showing the books I downloaded from the server, just the ones I'd loaded separately onto my phone; I'd assumed that was by design. I just forced a rescan of the local folder, and now the books downloaded from my server are included there, too. Thanks!
