### ISSUE TITLE
No way to dismiss/remove the player permanent notification

### ISSUE THREAD

**Issue by madiele** [advplyr/audiobookshelf-app#255]
### Steps to reproduce
1. start playback
2. no way to remove the notification without force stopping the app

### Expected behaviour
- when no playback is active the notification should be dismissable

### Actual behaviour
- The notification is never dismissable, even by closing the app

### Environment data

Audiobookshelf Version: v2.0.22 - docker

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.49-beta

Device model: Pocopone F1 and Lenovo Tab M10 FHD plus

Stock or customized system: non stock LineageOS 16.0 (android 9) and Stock android 10

### Possible fix
add a x (close) button to gracefully close the player (this method is also used by the stock youtube app, and many other apps with a player). Or allow to dismiss the notification on no playback like the spotify app.

**Comment by advplyr** [comment]
We can look into adding an X, I'm not sure how they did that. However, the notification does go away when you close the app. Maybe you are just putting the app in the background and not actually closing it?

**Comment by madiele** [comment]
I tested it, you right it does go away if you close the app from the active app list! But it does not go away if you exit the app "the proper way" using the back button in the app or by manually choosing to close the player inside the app which is what I was doing.

**Comment by advplyr** [comment]
Fixed the issue where closing the player in the app wasn't removing the notification. Updated the notification to include the stop button in [0.9.50-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.50-beta)
