### ISSUE TITLE
Same cover style for collections as that of series

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#257]
### Is your feature request related to a problem? Please describe.
The cover style for collections is different that of the series. Even though a collection may have more than 2 books, the cover shows only the first two books on the list. See images below.

![tempFileForShare_20220626-082213.jpg](https://user-images.githubusercontent.com/42061703/175797466-a788dc9f-1cd7-4f99-8282-5ced81377bd9.jpg)
June 2022 cover (ignore July 2022 - it has only one)

![tempFileForShare_20220626-082131.jpg](https://user-images.githubusercontent.com/42061703/175797472-b5a14159-2384-4ad0-838e-8887c1797588.jpg)
But it has more than 2 books

![tempFileForShare_20220626-082332.jpg](https://user-images.githubusercontent.com/42061703/175797482-55c506a3-6d79-4f91-8766-9772d6a597c9.jpg)
The series' covers

### Describe the solution you'd like
Why not have the same cover style that you have for series for collections as well - cascaded, stacked book covers to indicate multiple books in the collection.

### Describe alternatives you've considered
NA

**Comment by advplyr** [comment]
One of the original ideas with collections is the cover image of the collection would be able to be set. I like that collections are displayed differently then series but I'm not sure. We'll see if anyone else has thoughts on this.

**Comment by raviwarrier** [comment]
TBH, I am a little confused between series and collections considering I was used to Plex for the last year. The way I see it (and I could be wrong) is Plex's collection = ABS' series and Plex's playlist = ABS' collection and that's how I use it. One can set a cover image for collections in Plex (and I have those for Harry Potter and The Witcher books), but for Plex playlists, I like that it shows covers of books inside (albeit only 4). 

The only reason I requested it is because the collections look incomplete with only cover images of the first 2 books and I love the way my series look... it looks, for the lack of better terms - grand, curated, collectibles. I just wanted those qualities for my collections/playlists as well.

You could ask people on discord about what their view is on this request and then will leave it to your call. :)

**Comment by advplyr** [comment]
I'm going to leave collections how they are for now unless someone comes with unique UI/UX design and functionality
