### ISSUE TITLE
Add longer skip button

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf-app#263]
### Is your feature request related to a problem? Please describe.
It's annoying to try and skip back to somewhere if you got interrupted or side tracked, when you can only do it in 10 second intervals. Especially if you're listening at 3x speed as this means you're only going back 3 seconds of real time. 

### Describe the solution you'd like
A second button, to skip back a minute. Or even better, a long and a short skip button with setting to configure the duration of each to be set by the user.

**Comment by advplyr** [comment]
How long of a skip button would you want?

**Comment by advplyr** [comment]
The jump forward/backward times are now adjustable in the latest release. Only up to 30 seconds though since those icons already existed.
