### ISSUE TITLE
Back on player doesn't exit to the main app

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#267]
### Steps to reproduce

1. Open app
2. Start player
3. Press back on Android navbar (the bottom portion with home button)

### Expected behaviour
- Should minimize the player and go back to the last screen/library view.

### Actual behaviour
- Prompts to exit the app instead. Can't upload screen grab here, will post it on discord.

### Environment data

Audiobookshelf Version: 0.9.50-beta

- [ ] Android App? Yes
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model: Samsung M30s

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Added in [0.9.51-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.51-beta)
