### ISSUE TITLE
Error ... Cannot POST //login

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf-app#269]
### Steps to reproduce

1. login to an server (webversion is functional)
2. https://gyazo.com/c2b45c137d4a572ab026d147c945ea43

### Environment data

Audiobookshelf Version: 0.9.50 beta

- [x] Android App?

#### Android Issue
Android version: 12 (One UI 4.1)

Device model: SM-G975F

Stock or customized system: Stock

**Comment by advplyr** [comment]
I'm unable to replicate this

**Comment by skyzuma** [comment]
idk where is the problem but there no login possible ... any password tested (long, short, simple, ...) ... w/ passwordmanager ... manual ... no login ... anytime this error ... (on my phone (Huawei P10) i can login this user)

maybe any logs on the phone? u know where i can find it?

**Comment by advplyr** [comment]
What is the version of the app you are using?

Pulling logs from the phone isn't easy

**Comment by skyzuma** [comment]
server: 2.0.23
app: 0.9.50 beta

**Comment by advplyr** [comment]
When you are entering your server URL are adding a slash at the end?
like this "https://yourserver.com/"

That's what it looks like from the error. Try removing the slash.

**Comment by skyzuma** [comment]
yes, was with a / ... without > login possible :) now login is OK

**Comment by advplyr** [comment]
That's weird because in my testing I was not able to add a "/".

Glad it is fixed though
