### ISSUE TITLE
Forward/reverse controls are not scaled by playback speed

### ISSUE THREAD

**Issue by GeorgeHahn** [advplyr/audiobookshelf-app#271]
### Steps to reproduce

1. Set playback speed above 1x
2. Use the forward or reverse 10s button
3. Notice that the time skipped is some fraction of 10s depending on the playback speed

### Expected behaviour
- The time skipped should be 10s at the current playback speed

### Actual behaviour
- The time skipped is relative to 1x playback. For example, these controls skip by 5s when listening at 2x speed.

### Environment data

Audiobookshelf Version: 0.9.49-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Pixel 4a

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
This must have been fixed at some point because this does not happen for me.

For testing I set the playback speed to 2x and paused the audiobook to see the time jump easier. Pressed jump forward/backward 10s.
