### ISSUE TITLE
after dl > abs crashed

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf-app#273]
i downloaded an book (any file (~ 200) > 1 sound from DL manager but i thinks its an android problem) and after its shows 100% the app crashed (no logs on server) ... after restart, there are no local files (only after i scan the local folder (every time)) ... and this book is not linked to an server item ...

ive tryed "logcat | grep audiobookshelf" on the phone but idk if this can help ... and idk if there any private data in there ...

- [x] Android App?

Audiobookshelf Version: 2.0.23
Audiobookshelf-app Version: 0.9.51-beta

#### Android Issue
Android version: 9

Device model: Huawei P10

Stock or customized system: Stock

**Comment by advplyr** [comment]
Are you able to reproduce this every time?
This isn't enough information to troubleshoot anything. Make sure to update to the latest app 0.9.52

**Comment by skyzuma** [comment]
(Huawei P10 / Android 9)

yes ... download a book (no informations like "Downloading! (%)" / indications like the ring on the top) ... after few seconds dl > the app is crashing ... after restart abs, no media on local media ... scanning local folder (local / sd-card) 112/170 files are found but no linked with the server and the last file with 0 sec and no cover ...

after phone restart > dl manager +60 files ...

after start app and scan local folder again > folder scan complete after 1 sec / 1 removed ... after force re-scan > folder scan complete after 1 sec with no updates

all "new" 60 files stored in /storage/emulated/0/Android/data/com.audiobookshelf.app/files/Download/ and will never be deleted if this no recognize

i think this is an phone problem ... not an ABS problem but idk ...

(SM-T725 / Android 11)

dl a book all ok, take a long time with no other informations like "Downloading! (%)" and after few minutes local book created but with "no internet" on the connection status but i can play non local books

**Comment by advplyr** [comment]
Downloader was re-written in 0.9.61-beta but let me know if this persists.
