### ISSUE TITLE
enhancement: more info after download

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf-app#274]
now i understand hopefully how it work ...

if i correct: go to an book > tap the download icon and wait to end download but thats all ... here is more info missing ... ive seen it on my phone with "logcat | grep audiobookshelf" ...

download all files > deleting files in "/Android/data/com.audiobookshelf.app/files/Download/" and i think moved to the own created download location AND after a whilte it comes a popup with "successfully" and the "stream" button change to "play" button ...

ater download and switch to "play" button ... there is no other informations ... only the 100% under the stream button ...

may be we need an onfo like: "plz wait up to the stream button change to play button" or any similar

**Comment by advplyr** [comment]
For the next release I've removed the ffprobe after downloads so there should only be a small delay between 100% downloaded.

**Comment by advplyr** [comment]
Updated in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
