### ISSUE TITLE
Uneven / non-alignment of list items in local media view


### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#279]
### Steps to reproduce

1. Go to local media view of the mobile app. See image below.
2. Observe the unevenness of the list items' alignment.
3. Na

![tempFileForShare_20220712-185622.jpg](https://user-images.githubusercontent.com/42061703/178501238-86d0bc7a-b6cf-47c1-a19e-dba4ad0230bc.jpg)

### Expected behaviour
- cover images' dimension needs to be standardized

### Actual behaviour
- the different sizes of cover images causes list to be mis-aligned

### Environment data

Audiobookshelf Version: 0.9.51-beta 

- [x] Android App? Yes
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model: Samsung M30s

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
This is fixed in [0.9.54-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.54-beta)
