### ISSUE TITLE
Seeking backwards loops around and therefore gets you to end of book and marks it as read

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf-app#280]
### Steps to reproduce

1. Start playing a book
2. Try to skip back using the skip back 10s (or whatever configured) button
3. get to below skip back duration ( 7 seconds on 10 second click) and press it one more time

### Expected behaviour
- Stop at zero, dont loop around to the end of the book

### Actual behaviour
- Time seek skips back to end of book, looping around

### Environment data

Audiobookshelf Version: v2.0.23

- Android App

#### Android Issue
Android version:  0.9.51

Device model: Pixel 6 Pro

Stock or customized system: Stock

**Comment by advplyr** [comment]
I just tested this on the latest release 0.9.52 and wasn't able to reproduce.
Can you try this again with the latest release?

**Comment by barelylit** [comment]
Afraid this one has re-surfaced. 0.9.57-beta app

**Comment by barelylit** [comment]
https://www.dropbox.com/s/re6rr3rmjunnz26/2022_09_18_08_32_19.mp4?dl=0

**Comment by advplyr** [comment]
Are you able to replicate this on every book every time?

**Comment by barelylit** [comment]
Just tried it on 5 books, 3 it didn't happen on, 2 it did.

3 that it didnt happen on were single m4b files, 2 that i did were multiple files (one multiple mp3, one multiple m4b)

**Comment by advplyr** [comment]
This has probably been long fixed. I haven't had any other reports of this.

If you can reproduce this on `0.9.62-beta` and server `2.2.15` let me know and we can re-open.
