### ISSUE TITLE
Aspect ratio of ABS icon on app loading screen is not correct

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf-app#281]
### Steps to reproduce

1. close app (swipe away or force close)
2. open app
3. view loading screen with ABS circular icon, but it is a tall oval.

### Expected behaviour
- icon should be circular. Like in the app header bar after the app has loaded. Couldn't get a screenshot, disappears too fast.

### Actual behaviour
- icon is squished on loading screen.
- 
### Environment data

Audiobookshelf Version: 0.9.51-beta

- [ X] Android App?

#### Android Issue
Android version: 10

Device model: Moto G7

Stock or customized system: Stock

**Comment by advplyr** [comment]
That old splash screen was removed a while ago but let me know if you still have a bad splash screen in the latest app release.
