### ISSUE TITLE
View details on a local audiobook marks it as started playing

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf-app#282]
### Steps to reproduce

1. Download a audiobook locally
2. tap version on "Local Books" shelf
3. AB now displays in Continue listen, progess 0%. Book was never played.

### Expected behaviour
- AB should not be put on continue listen until played.

### Actual behaviour
- AB displays on continue listen only when details viewed.

### Environment data

Audiobookshelf Version: 0.9.51-beta

[X] Android App?
Android Issue
Android version: 10

Device model: Moto G7

Stock or customized system: Stock

**Comment by advplyr** [comment]
I'm not able to reproduce this. Are you sure the audiobook didn't have progress already on the server?

Are you able to reproduce this every time? Can you try again on the latest release?
