### ISSUE TITLE
After Pausing, Disconnecting a Bluetooth device, and Reconnecting and Listening, the App Plays Two Audio Streams

### ISSUE THREAD

**Issue by ShiromMakkad** [advplyr/audiobookshelf-app#283]
### Steps to reproduce

I like to use my Airpods to listen to books. I was listening with them and I put them away, disconnecting the bluetooth. Then I went back to listen to the audiobook, so I opened my airpods and reconnected to my phone. Once I did,  it played two audio streams from two different parts of the book. 

### Expected behaviour
It should play the audio from the place I last left off

### Actual behaviour
It plays two audio streams, it literally sounds like two people are talking at once. One audio stream is from a few hours later in the book, and one is the correct one from when I left off. The bar at the bottom flickers between showing the later stream position and the actual one, but if you pause it, it goes to the later stream position and completely loses your spot in the book. It's very frustrating. 

### Environment data

Audiobookshelf Version:

- [? ] Android App?
- [ X] iOS App?

#### iOS Issue
iOS Version:
15

iPhone model:
iPhone 13

**Comment by ShiromMakkad** [comment]
This is a major issue for me and I'm running into it after one day of use. I'd love to help fix this, but I don't have any Vue or Capacitor experience. I do have React, React Native, and a lot of web experience, so I think I could figure things out with a few pointers. Thanks!

**Comment by ShiromMakkad** [comment]
It happens when I pause and resume while connected to a bluetooth device

**Comment by ronaldheft** [comment]
I fixed a number of issues in playback on iOS with PR #277. When we get that merged and released, I’d be curious if you can still reproduce.

**Comment by advplyr** [comment]
Please follow up if this issue still persists in the latest version [v0.9.57-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.57-beta)

**Comment by ronaldheft** [comment]
Confident this issue has been fixed, especially after #386
