### ISSUE TITLE
Android Auto not showing all started items in 'continue listening'

### ISSUE THREAD

**Issue by andonevris** [advplyr/audiobookshelf-app#285]
### Steps to reproduce

1. Start an audiobook
2. Start a podcast
3. Android auto only displays the audiobook in 'continue listening'

### Expected behaviour
- Tell us what should happen
- Continue Listening should list all currently started items

### Actual behaviour
- Tell us what happens
Only 1 item was listed in continue listening (audiobook)

### Environment data

Audiobookshelf Version:
2.0.23

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version:
v0.9.51-beta 

Device model:
samsusng galaxy s10

Stock or customized system: 
stock, rooted

**Comment by advplyr** [comment]
This is a limitation right now. The continue listening section is pulling the continue listening shelf of your first library.

I'm not yet sure how best to design android auto but I think we will need to create a new API endpoint to fetch all currently listening items across all libraries.

**Comment by advplyr** [comment]
Added in [v0.9.57-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.57-beta)
Requires server v2.1.4 and up.
