### ISSUE TITLE
Freeze at "connecting socket" message on android app

### ISSUE THREAD

**Issue by Koliera** [advplyr/audiobookshelf-app#29]
Unsure if it's something I did but I'm trying to log in via android and I get frozen on Login Success" Connecting socket.." message. The log on the server just says that a ping has been received.  v1.6.8 on server and can play books directly through browser.

**Comment by advplyr** [comment]
I found an issue that I resolved in `v0.9.18-beta` with the app. It will be available to update on the google play store in an hour or so.
You can work around the issue right now but closing and re-opening the app after logging in. It was just an issue re-establishing the socket connection.

**Comment by advplyr** [comment]
This is live on the play store.
