### ISSUE TITLE
[iOS] Sleep Timer for end of chapter doesn't account for playback speed

### ISSUE THREAD

**Issue by dacmcbibs** [advplyr/audiobookshelf-app#291]
### Steps to reproduce

1. Start a chapter 
2. Set playback speed to 2x
3. Set sleep timer to End of Chapter

### Expected behaviour
- App should stop playback when the chapter ends regardless of playback speed , even if the speed changes after setting the timer (should look for end of chapter marker) 

### Actual behaviour
- App sets sleep timer to match however much time is left if the chapter was playing at 1x speed

### Environment data

Audiobookshelf Version: 

- [ ] Android App? Yes   0.9.52-beta 
- [ ] iOS App?  Yes   0.9.51-beta 

#### Android Issue
Android version: 12 

Device model: Pixel 6 Pro

Stock or customized system: Stock

#### iOS Issue
iOS Version:  15.5

iPhone model: iPad Air 2

**Comment by advplyr** [comment]
Fixed in [v0.9.56-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.56-beta)
