### ISSUE TITLE
Server (play) request failed

### ISSUE THREAD

**Issue by Niun1992** [advplyr/audiobookshelf-app#297]
### Steps to reproduce

1. Install Server via docker version 2.1.0
2. Use nginx reverse proxy configuration as provided in readme (including letsencrypt certs)
3. Install Android APP V0.9.52beta

### Expected behaviour
- Play Stream or Download files

### Actual behaviour
- Library shows up as expected but playing and downloading doesnt work: Server request failed. Socket Connection is green.
- App works when using internal LAN IP instead of domain name (nginx target). Even if domain name resolves to LAN IP (nginx target) it doesnt start playback.
- Playback via firefox works fine

In conclusion: It seems something is wrong with the nginx reverse settings provided in the readme.

### Environment data

Audiobookshelf Version: 2.1.0, APP: V0.9.52beta

- [ ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Xiaomi Mi A1 (LOS Android 12), Xiaomi Poco F3(CrDroid Android 11), Huawei Mediatab M8 (LOS Android 10)

Stock or customized system:
Custom Roms, LOS and CrDroid

Nginx config:

```
server
{
        listen 443 ssl;
        server_name my.domain.de;
        access_log /var/log/nginx/bookshelf.access.log;
        error_log /var/log/nginx/bookshelf.error.log;
        include certs.conf;
        location / {
                     proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
                     proxy_set_header  X-Forwarded-Proto $scheme;
                     proxy_set_header  Host              $host;
                     proxy_set_header Upgrade            $http_upgrade;
                     proxy_set_header Connection         "upgrade";
                     proxy_http_version                  1.1;
                     proxy_pass                          http://127.0.0.1:13378;
                     proxy_redirect                      http:// https://;
                   }
}
```

**Comment by advplyr** [comment]
Reverse proxy works for many users so I don't think this is a bug with Abs. I'm not sure about your nginx config, the best place to get help with reverse proxy is in the discord.

Unless you have anything else indicating this is a bug with Abs?

**Comment by Niun1992** [comment]
Only the fact that firefox is working fine...
Is there a way to turn on some logging in the android app?

**Comment by Niun1992** [comment]
My bad... I had OCSP stapling active, looks like the app dont like it.

```
ssl_stapling on;
ssl_trusted_certificate XXXXXX;
ssl_stapling_verify on;
ssl_stapling_file XXXXX;
```

**Comment by advplyr** [comment]
That's great, glad you got it resolved.
