### ISSUE TITLE
Request: select download location

### ISSUE THREAD

**Issue by Amitheous** [advplyr/audiobookshelf-app#3]
I believe I saw somewhere that you are working on this but android storage is definitely a pain. But if it would be possible to have the ability to store on SD card that would be awesome.

**Comment by advplyr** [comment]
Just added download location selection in `v0.9.0-beta`

Just a heads up, if you have a bunch of previously downloaded audiobooks you should delete them and re-install. The file system is quite a bit different now and saves the audiobooks in folders with the book title.

I didn't test an actual SD card, so I will leave this open in case there are still issues there.
