### ISSUE TITLE
Failure to ping server using domain instead of IP on local network on iOS Testflight

### ISSUE THREAD

**Issue by jsaltzman** [advplyr/audiobookshelf-app#300]
### Steps to reproduce

1. Try and add new server. Enter audiobookshelf.mydomain.com. This works on my web browser on my local network.
2. I get an error that there was a failure to ping the server
3. When I turn off WiFi, I can add the server.
4. When I turn wifi back on, I cannot connect to server

### Expected behaviour
I should be able to add the server.

### Actual behaviour
I get an error

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [X ] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: ios 16 

iPhone model: iPhone 12 Pro Max

**Comment by advplyr** [comment]
Are you sure this is a bug with abs? Many users connect to their server with the iOS app

**Comment by jsaltzman** [comment]
Happy to troubleshoot, how can I help?

**Comment by advplyr** [comment]
I'm not sure how to troubleshoot your network. There are users in the discord server more knowledgeable than me about networking so I think you're best bet is to ask in there.

As of now I don't believe this is a bug with Abs but we can re-open this if we find something that suggests it is.

**Comment by jsaltzman** [comment]
FYI I resolved this by changing http to https in the url.
