### ISSUE TITLE
Local books shelf only shows ten books

### ISSUE THREAD

**Issue by GeorgeHahn** [advplyr/audiobookshelf-app#301]
### Steps to reproduce

1. Download more than ten books
2. Note that local books shelf only shows ten books

### Expected behaviour
- All local books should be shown, or local books should be shown in the library view 

### Actual behaviour
- Many local books are not displayed

### Environment data

Audiobookshelf Version: 2.0.24

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version:  0.9.54-beta

Device model: pixel 4a

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Fixed in [v0.9.56-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.56-beta)

Eventually the local items should be shown on the library tab just haven't figured that part out yet.
