### ISSUE TITLE
[Enhancement] Local Book Shelf should be sorted by unread and then read books

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#302]
### Is your feature request related to a problem? Please describe.
Scrolling around to find the unread books that I want to start listening to. Currently the shelf is sorted by 'downloaded date/time'.

### Describe the solution you'd like
If all the unread books are upfront, it would minimize the scrolling/searching required. Additionally, the unread books could also be sub-sorted by 'downloaded date' if possible.

### Describe alternatives you've considered
NA

### Additional context
See screen grab

https://user-images.githubusercontent.com/42061703/182054999-fc9ec0d4-e318-486e-a84c-037e2422921f.mp4

**Comment by advplyr** [comment]
Added in [v0.9.56-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.56-beta)
