### ISSUE TITLE
[Enhancement] Total playtime for a collection

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#303]
### Is your feature request related to a problem? Please describe.
Can we have a total playtime for a collection (and series and playlist [when it is developed])? Displayed as dd days, hh hours mm minutes. Maybe on the top-right corner of the table header?
![image](https://user-images.githubusercontent.com/42061703/182064633-3cd8c6a1-76c7-4cd3-8ebb-c5a92a1f55e7.png)

**Comment by advplyr** [comment]
Added in [v0.9.56-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.56-beta)

also added in web ui
