### ISSUE TITLE
[Enhancement] Make the whole row in collections tappable

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#305]
### Is your feature request related to a problem? Please describe.
Since the names of the books are left-aligned, anyone tapping with their right thumb on a relatively large-screen phone will not be able to reach the name of the book to select it (see screen grab below).

### Describe the solution you'd like
Make the whole row tappable.

### Additional context

https://user-images.githubusercontent.com/42061703/182410010-135707f9-9c6f-4e3c-9fef-01f5866658e1.mp4

**Comment by advplyr** [comment]
Updated in [v0.9.57-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.57-beta)
