### ISSUE TITLE
The counter in the collections view is not aligned in the center of the circle

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#306]
### Steps to reproduce

1. In collections view
2.
3.

### Expected behaviour
- In the image below, the number 15 should be evenly centered in the gray circle that is encompassing it.

![tempFileForShare_20220802-204702](https://user-images.githubusercontent.com/42061703/182410741-3ed91708-9ff9-48d4-bd52-a0205b3f7db4.jpg)

### Actual behaviour
- Tell us what happens

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model:

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Fixed in [v0.9.56-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.56-beta)

It's not perfect, there is something weird with font sizing on android but it is better.
