### ISSUE TITLE
[Enhancement] Home screen widgets on Android

### ISSUE THREAD

**Issue by lerndmina** [advplyr/audiobookshelf-app#307]
It would be nice to be able to quickly pause and play audiobooks from the home screen of your phone. And get some basic information about the book that you're listening to, such as title and author and have the art as the background. 

I would like to be able to add a resizable widget to the home screen of my Android phone to pause, play and skip a few seconds for the most recent audiobook I've listened to. 

The notification shade is a fairly decent way to quickly interact with your currently listening audiobook but a home screen widget would be nice too

Could look similar to this one by smart audiobook player. ![Screenshot_20220803-065615.png](https://user-images.githubusercontent.com/10632157/182534844-5d2923c2-082c-4b80-8270-cc294d74bbbb.png)

**Comment by tes5884** [comment]
Would love this as well! Loving the app on Android!

**Comment by MikeBishop** [comment]
Yes, the SAP widget is one of the nicest around, in my opinion. Good cover art support and such.

**Comment by advplyr** [comment]
Added in [v0.9.63-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.63-beta)
