### ISSUE TITLE
Android Auto - Opening podcast section displays audiobooks

### ISSUE THREAD

**Issue by andonevris** [advplyr/audiobookshelf-app#309]
### Steps to reproduce

1.Open AB and click podcasts
2.Audiobooks are displayed instead of podcasts
3.Backing out into audiobook section then back into podcasts displays podcasts correctly (sometimes need to do this multiple times)

### Expected behaviour
- Tell us what should happen
Podcast section should display podcasts

### Actual behaviour
- Tell us what happens
- Podcast section displays audiobooks on first load, backing out and back in a few times finally displays podcasts

### Environment data

Audiobookshelf Version:
2.1.1

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 10

Device model: Samsung galaxy s10

Stock or customized system: stock system, rooted

**Comment by advplyr** [comment]
I was able to resolve this for the next release.
I want to note that the continue listening section is still only showing the first libraries in progress items. Still not sure if we should mix all libraries for continue listening but thinking we will.

**Comment by andonevris** [comment]
I think we should definitely mix the libraries for continue listening, again stealing a cue from plex, the continue watching section has TV shows and movies in one place and is very useful to get back to watching without lots of navigating.

**Comment by advplyr** [comment]
Fixed in [v0.9.56-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.56-beta)
