### ISSUE TITLE
Language filter in mobile app

### ISSUE THREAD

**Issue by NotSafarad** [advplyr/audiobookshelf-app#312]
I'd be awesome to have the same language filter in the app as in the web interface.

**Comment by advplyr** [comment]
Added in [v0.9.56-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.56-beta)

**Comment by gianmarcomurru** [comment]
Can this filter be added to the user profile settings as well?

I am considering the case you have the same audiobook in multiple languages. As a user, I would like to configure a permanent filter to select only the languages I speak.

There is a similar setting in [Calibre-Web](https://github.com/janeczku/calibre-web):

<img width="1010" alt="Screenshot 2024-01-11 at 10 41 35" src="https://github.com/advplyr/audiobookshelf-app/assets/48201852/020ca3e4-dd1c-4ed1-9e54-5dc771687743">

**Comment by lockheed** [comment]
I have the same question. I don't want to create a separate library for someone how does not understand English.
