### ISSUE TITLE
Accidental skipping when closing the app or using the notification widget 

### ISSUE THREAD

**Issue by NotSafarad** [advplyr/audiobookshelf-app#313]
###Is your feature request related to a problem? Please describe.

When trying to close the mobile app I sometimes accidentally press on the timeline. This can also occure when trying to interact with the notification widget. In both cases I am somtimes unable to find my previous spot in the book, which can be really annoying. 

###Describe the solution you'd like

A button to undo the last skip action.

###Describe alternatives you've considered

A Setting to lock the timeline in the widget and the app. Booth features would be the best longterm, but one of those will suffice for time beeing. I have an example of in app locking attatched.

![photo_2022-08-08_10-57-12](https://user-images.githubusercontent.com/88512718/183381421-96d06975-a8ba-4603-bd31-db2334e8fba1.jpg)
![photo_2022-08-08_10-57-25](https://user-images.githubusercontent.com/88512718/183381425-b7066738-448b-485b-b81e-a7695768f5cd.jpg)

**Comment by advplyr** [comment]
Added in [v0.9.57-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.57-beta) but put inside of the more options menu.
I wasn't ready to redesign the UI to put this above the track bar but maybe it will be moved there in the future.
