### ISSUE TITLE
Podcast library tab episode counter only show incomplete # of episodes

### ISSUE THREAD

**Issue by Euromancer** [advplyr/audiobookshelf-app#315]
In the library view, it would be nice to be able to filter on complete and incomplete podcasts.
You can do that om a singe podcast, but not on the overview.

**Comment by advplyr** [comment]
Do you mean podcast episodes on the podcast page? Or complete podcasts which would be every episode inside the podcast is complete?

Can you elaborate?

**Comment by Euromancer** [comment]
I will try :-)
On this page: 
![image](https://user-images.githubusercontent.com/38189605/183866541-1905d76d-65cc-4387-822c-10df8c891952.png)
It would be nice to be able to filter the completed episodes, so it dont add up in the episode counter in the trop right on each podcast.. 
And if the podcast dont have any incomplete episodes it should be hidden.
This way its fast to see what episodes im missing to hear.

**Comment by mshuflin** [comment]
This would be a nice feature

**Comment by advplyr** [comment]
Updated in [v0.9.66-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.66-beta)
