### ISSUE TITLE
Disable "touch to seek" on minimized player progress bar [Feature Request]

### ISSUE THREAD

**Issue by Allastratou** [advplyr/audiobookshelf-app#32]
v0.9.18-beta

The progress bar on the minimized player/bar in the app is a bit too easy to tap accidentally and completely lose one's place. Maybe a toggle to dis/enable "seek on tap" for the minimized player? That way you still have the visual representation of progress, but you can't wildly lose your place. It'd be easy enough on the user to maximize the player and then tap the seekbar to jump around, if so desired.

**Comment by advplyr** [comment]
This was included in `v0.9.28-beta`, touching the track has no effect on the mini player.
