### ISSUE TITLE
Resuming playback of downloaded episodes from home screen plays back from server.

### ISSUE THREAD

**Issue by revilo951** [advplyr/audiobookshelf-app#324]
### Steps to reproduce

1. Download a podcast episode
2. Begin playing from the episode list, plays from local file
3. Come back to ABS later, select the episode from the Home screen, and it plays off the server.

### Expected behaviour
- Should play using local file

### Actual behaviour
- Plays from the server

### Environment data

Audiobookshelf Version:

- [x] Android App? 0.9.56-beta and older

#### Android Issue
Android version: 12

Device model: Galaxy S20 Plus

Stock or customized system: Stock

**Comment by advplyr** [comment]
Fixed in [v0.9.57-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.57-beta)
