### ISSUE TITLE
add auto rewind after notifications or loss of audio 

### ISSUE THREAD

**Issue by toxic0berliner** [advplyr/audiobookshelf-app#331]
On Android when a notification comes in it makes a sound that covers the audiobook and we miss a part of the sentence.

Autorewind should be configurable to also apply in this case.

Another case : start a for app that gives directions, start the audiobook in the background and set off driving. When the GPS app gives directions it covers the book. It should also be able to rewind there.

### Describe alternatives you've considered
Right now I download the audiobook locally and play it with "Smart Audiobook Reader" a paid app on Android that rewinds very nicely. That loses me the progress sync sadly.

In fact this reader has another great feature : when you star playing an audiobook to continue it, depending on how long ago you last listened to it, it will rewind 10s or 30secs or even 1mi  and up to 3min if it has been weeks since you have stopped listening to the same book.

Just an idea though, little comfort but makes a difference I believe

**Comment by advplyr** [comment]
The GPS shouldn't overlap the audiobook. For me the audiobook is paused until the directions are finished then the audiobook resumes.
When building the app there is a setting we pass in to let the device know that this audio should be paused while other audio is playing.

Can you provide the version of the app you are using, the device you are using, and the android version

**Comment by toxic0berliner** [comment]
I am using 0.9.55beta on Android 12 build 4.19.157 for OnePlus 8
What I actually get when using gps is that it pauses the audiobook but doesn't say the direction and never resumes by itself ^^
So that's actually a bug, might have happened today because I actually didn't start the audiobookshelf app instead connecting the Bluetooth from my car resumed the play of the book in the background automatically upon connection, I then opened Google Maps and asked it to take me somewhere. There the bug happened twice, I had to pause unpause with the Bluetooth remote and finally gave up after 2 roundabouts stopping the book and not giving any direction nor resuming the book after I left the roundabout.

But to come back to this feature request the idea is not only to pause but actively rewind a few seconds before resuming. And especially with notifications. The current behavior if I'm not mistaken is pause,"gling" from the notification, resume. When that happens mid-word it can be quite difficult to follow, if possible rewind 5 secs and resume will ensure no word is cut.

**Comment by toxic0berliner** [comment]
Just updated to 0.9.56beta but doubt it'll change. Will be more Up to date for the coming tests ;)

**Comment by advplyr** [comment]
Auto rewind is implemented already but it doesn't trigger unless the player has been paused for at least 10 seconds.

Originally it was 3 seconds but with directions it would trigger the rewind, then another map direction would be given right after which would trigger another rewind. This can happen 3 or 4 times in a row causing you to listen to the same sentence each time. This was happening so frequently on a road trip I was on that I increased the auto rewind to 10 seconds.

The bug you are encountering may be a bug with the OnePlus or some optimization setting on the device.

**Comment by toxic0berliner** [comment]
Just updated to 0.9.56beta Will be more Up to date for the coming tests ;)
With another car and the app properly started before the GPS the bug went away, probably a OnePlus "optimization " as you guessed.

Would it be possible to make this a bit more configurable? The 10 seconds of pause necessary to trigger rewind I understand why you could prefer it 10 seconds, but my gps is mostly set to only speak for alerts so it wouldn't be annoying and actually desirable for me to have it rewind as soon as it has been interrupted even is only for 1 sec.

The amount of the rewind too could be configurable and would be appreciated 👍

**Comment by advplyr** [comment]
Yes we will make it customizable, there is an issue open for that you can follow #205

**Comment by toxic0berliner** [comment]
Thx, a lot and sorry I didn't see #205 before
