### ISSUE TITLE
Add playback speed control in Android Auto

### ISSUE THREAD

**Issue by AwsomeFox** [advplyr/audiobookshelf-app#333]
### Is your feature request related to a problem? Please describe.
I'd like to be able to change playback speed from the android auto interface. When driving sometimes the reader changes or you change books or get to a complicated subject and you would like to speed up or slow down. 
### Describe the solution you'd like
Add a button that would cycle through speeds on the android auto interface. 
### Describe alternatives you've considered
In order to change speeds you would need to pull your phone out and open the app there.
### Additional context
I've implemented this in another app before before so I know it's possible. If I get time to get android studio setup again I may take a look at implementing this myself. [Link to pr in another repo](https://github.com/mattttvaughn/chronicle/pull/15)

**Comment by advplyr** [comment]
Awesome yeah I may get a chance to put this in this weekend before we push the next release. Are those drawables you used for the playback speeds in that PR something you made? I would implement it the same way you did in that PR if I get a chance to do it this weekend.

**Comment by AwsomeFox** [comment]
They were already part of the app for the regular player ui. I'm not sure where they came from.

**Comment by feerlessleadr** [comment]
I'd love this as well since I listen to my books sped up an my podcasts at 1x speed.

**Comment by advplyr** [comment]
Added in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)
