### ISSUE TITLE
Cannot specify local folder (Android LineageOS)

### ISSUE THREAD

**Issue by plague-doctor** [advplyr/audiobookshelf-app#336]
I am unable to specify Local Folder, so I can't download the books for offline use :-(

Steps:
1. Open application
2. Hamburger --> Local Media
3. Select "Books" (or "Podcasts") and tap on "New Folder" 
4. ... Nothing happens... :-(

The application has appropriate rights to media files.

Tested with versions: 0.9.56-beta and 0.9.57-beta

Mobiles: OnePlus 8 Pro and OnePlus 9 Pro
LineageOS: 18.1 and 19.1 respectfully.

**Comment by plague-doctor** [comment]
Ok. Figured out why.
I use MiXplorer exclusively and I disable "Files" app completely. When there is no "Files" app Audiobookshelf cannot call it to pick the local folder.

**Comment by advplyr** [comment]
Good to know thanks for following up
