### ISSUE TITLE
Streaming failed "File path does not exist /metadata/..."

### ISSUE THREAD

**Issue by esbenovich** [advplyr/audiobookshelf-app#337]
### Steps to reproduce
 
1. Jump to 1h36m mark of my current audiobook and streaming fails.

### Expected behaviour
- Plays the book. 

### Actual behaviour
- Stops streaming with the error "Playback failed: source error"
- Issue persists on another phone/user (same versions of android OS/ABS-app).
- The file is uncorrupted. It plays on any media player and on the web-interface.

### Environment data

Audiobookshelf Version:
0.9.56-beta (server v.2.1.4 (docker container))
- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version:
11 (Oxygen OS 11.0.18.EB13BA)

Device model:
One Plus Nord CE 5G

Stock or customized system:
Stock

I've tried purging the cache of the app, rebooting the phone and purging the cache on the server to no avail.
I've uploaded the log from the Audiobookshelf-server, but i don't comprehend the issue.
[ABS log](https://github.com/advplyr/audiobookshelf-app/files/9447125/ABS.log)

**Comment by advplyr** [comment]
Is this still an issue on the latest releases of the app and server?

The logs don't tell us anything special and the source error you are getting is from ExoPlayer.
