### ISSUE TITLE
Books cannot be selected in the "Continue Listening" section when not connected to the server

### ISSUE THREAD

**Issue by tboudreaux** [advplyr/audiobookshelf-app#346]
### Steps to reproduce

1. Disconnect app from server (I observe the behavior both in airplane mode and when I am away from WiFi + cellular)
2. Click on a book in the continue listening tab (which is locally downloaded of course)

### Expected behavior
- The book should open the details page, giving the option to continue playing

### Actual behavior
- The app does not respond to taps on the book in the currently playing shelf. I can tap on the same book in the locally downloaded section and everything works as expected.

### Environment data

Audiobookshelf Version: v2.1.4

- [x] Android App?

#### Android Issue
Android version: 0.9.56-beta

Device model: Samsung Galaxy S21 Ultra

Stock or customized system: Stock

**Comment by nichwall** [comment]
Also experienced this behavior on Android.
Server version: 2.1.1
Android version: 0.9.57-beta
Device model: Google Pixel 6a
Stock or customized system: Stock

**Comment by advplyr** [comment]
Now when you disconnect it should refresh the home page and only show the local download shelves (books or podcasts).

This will be fixed either way though once we implement the continue listening shelf for downloaded books.

For that we will track this issue in #112
