### ISSUE TITLE
Download notification on completion of ALL files

### ISSUE THREAD

**Issue by jt196** [advplyr/audiobookshelf-app#357]
This may just be an Android issue, in which case feel free to close!

### Steps to reproduce

1. Download multipart audiobooks

### Expected behaviour
- Notification on completion of all downloads

### Actual behaviour
- Each file gets a notification message and sound - this can get a bit annoying when you have an audiobook with dozens of audio files.

### Environment data

Audiobookshelf Version:

- [x] Android App?

#### Android Issue
Android version: 0.9.56

Device model: Pixel 3

**Comment by advplyr** [comment]
What version of android are you on? I know I updated this for Android 12 on Pixel 6 and others have confirmed as well.

**Comment by webbk18** [comment]
I am experiencing this too on my Moto Z4 Running Android 10.

**Comment by jt196** [comment]
This is Calyx 3.8 which is a modded version of Android 12.

**Comment by advplyr** [comment]
This was updated in a previous version I just missed this issue.
