### ISSUE TITLE
Bug: No books on main page, but can search for them

### ISSUE THREAD

**Issue by Tomaati** [advplyr/audiobookshelf-app#37]
Whenever I open the app it says that there are no audiobooks, but once I start searching it is able to find them and I can listen to them as well. I double checked the filters etc, but none are selected. The webapp works fine, it only occurs in the (android) app.

![Screenshot_2021-11-17-22-49-43-349_com audiobookshelf app](https://user-images.githubusercontent.com/31688938/142288586-d7a4beb8-0f01-4b6e-9ee7-a77166dea885.jpg)
![Screenshot_2021-11-17-22-49-38-295_com audiobookshelf app](https://user-images.githubusercontent.com/31688938/142288593-1a1bd037-cf96-4533-ab67-aa1ab5dfe51e.jpg)

**Comment by advplyr** [comment]
If you go to the account page and back to the library does it load then? Are you able to play audiobooks?

**Comment by Tomaati** [comment]
Nope moving from account to main page does not change anything. I can play audiobooks after searching.

**Comment by advplyr** [comment]
This is a new one. A new update was just released `v0.9.21-beta` with a new design, that is worth a try.

**Comment by Tomaati** [comment]
I've updated the app but unfortunately the issue still occurs. I've checked the webapp for different library names (maybe I changed it) but nothing...
![IMG_20211120_080415](https://user-images.githubusercontent.com/31688938/142717859-1e128ef8-23e7-4145-97a7-14d8c4355f8c.jpg)

**Comment by advplyr** [comment]
Do you have any other libraries? If not, you could try creating a new library and putting a book in there.

**Comment by Tomaati** [comment]
I do not have separate libraries, how do you create a new one?

**Comment by advplyr** [comment]
Only on the server config libraries page.

![image](https://user-images.githubusercontent.com/67830747/142730980-498e1e0b-27d1-4582-a730-cc1ff00e641e.png)

The + and if you are using docker you may need to map another volume.

**Comment by Tomaati** [comment]
Thanks, that seemed to have fixed the issue. Thank for the amazing app!
