### ISSUE TITLE
iOS Failed to create bookmark

### ISSUE THREAD

**Issue by BionicAlice** [advplyr/audiobookshelf-app#375]
### Steps to reproduce

1. at ~ 12 am tried to make a bookmark
2.
3.

### Expected behaviour
- Bookmark should have been made 

### Actual behaviour
- Got an error "Failed to create bookmark", I tried to change the name manually still same error. I tried a few times. Moving my placement in the book, closing and reopening the app. Same error. Gave up put app on a 30 min sleep timer.
- 
- In the morning I tried to re-create this it made a bookmark. I closed the app , tried again It worked again. (bookmark from last time showed) I then closed the app set my time to ~1:30am(went back ~8 hours) bookmark worked i saw the previous bookmark. Closed app retried worked again.
- I then closed the app set it to ~12:10am tried again and bookmark failed this time. Pervious bookmarks did not show now. 
- I fixed my time, bookmark failed. Closed the app, tried again and Bookmark fails again and not showing any bookmarks where ever made. 
- Before server showed nothing in logs this time it shows "WARN [User] Create Bookmark already exists for this time". I closed the app reopened the app. fast forwarded a few minutes, let it play. try to create a bookmark, get error , Again previous bookmarks are not showing.
- I probably broke it messing with my time and going back in time 8 then 9 hours. But it did naturally occur at a bit after 12am.
- Also should mention Web Browser version does still display my bookmarks that  where made , not the failed ones but the ones made this morning. and when I rolled back iOS time 8 hours.

### Environment data

Audiobookshelf Version: Docker:v2.1.5 . iOS 0.9.58

- [ ] Android App?
- [x ] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 16

iPhone model: Xs Max

**Comment by BionicAlice** [comment]
It might not have anything to do with time. It could be that I tried to create a bookmark when a bookmark existed. After it errors out once It will keep erroring out, along side hides the available bookmarks in the iOS app.

**Comment by mym0T** [comment]
I tried to re-create this error, but wasn’t able to. It let me add multiple bookmarks with the same, earlier, or later times without error. Clicking to create a bookmark while on the same time would give me a notification that the bookmark was added successfully, although it wouldn’t actually show a duplicate bookmark. I didn’t attempt to change the name of any of the bookmarks.
I tested with a streaming book, as the bookmark icon doesn’t show on downloaded books.
iOS app version: 0.9.58-beta
Server version: 2.1.5 running in docker on UnRaid
Device: iPhone 12 Pro on iOS 16.0 (20A362)

**Comment by BionicAlice** [comment]
Its been a few hour sense I tried adding bookmarks. Bookmarks started working again and it shows previous bookmarks. I am now getting same result as myM0T when trying to add a bookmark that already exists says added but server logs show already exists and it doesn't show up in the list. I then closed the app. Opened it up. Bookmark list is now empty. When I try to add a bookmark it gives me and error

**Comment by advplyr** [comment]
I was going to comment that the bookmarks should show up for downloaded books as long as you are connected to the server but I just tested and that appears to be broken. Fully offline bookmarks isn't implemented yet.

**Comment by advplyr** [comment]
Can you test this bookmark issue on the latest release 0.9.60?

I'm still not sure how to reproduce this since a lot of things are changing here. Is this a downloaded book?

**Comment by advplyr** [comment]
I'm making #163 as the main thread for offline bookmarks.
