### ISSUE TITLE
Podcast Sort Order options

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf-app#376]
### Steps to reproduce

1. Navigate to podcast library and select podcast (where there are a list of podcast episodes)
2. Attempt to click on the 'Pub Date' to change sort order
3. Nothing happens, the button is not clickable. 

### Expected behaviour
- The sort order should be able to be clickable to change order away from Pub Date

### Actual behaviour
- Nothing happens when clicking button

### Environment data

Audiobookshelf Version: v2.1.5 - Docker

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.57-beta

Device model: OnePlus 8t 5G

Stock or customized system: Stock

**Comment by advplyr** [comment]
Not a bug just hasn't been implemented yet. Only sort by pub date is in there now.

**Comment by feerlessleadr** [comment]
Got it, thanks!
