### ISSUE TITLE
Downloaded Audiobook with Multiple Files Plays out of order. 

### ISSUE THREAD

**Issue by ard0gg** [advplyr/audiobookshelf-app#380]
### Steps to reproduce

1. Find Audiobook containing multiple files
2. Download Audiobook to device.
3. 

### Expected behaviour
- When books are downloaded, Audiobookshelf will sort and play tracks based on filename order.

### Actual behaviour
- Audiobookshelf app will sort tracks, seemingly, in the order of files last modified date. I believe this results in the order of tracks being sorted when the download of individual files complete.  
- Attempting to sort the files manually by going to Local Media -> Selecting Local Folder -> Selecting Audiobook and manually re-sorting does not change the play order.

### Environment data

Audiobookshelf Version:
0.9.57-Beta
- [x] Android App?

#### Android Issue
Android version: 13
Device model: Pixel 6
Stock or customized system: Graphene OS Build TP1A.220905.004.2022090600

**Comment by wojtek1171** [comment]
Same with me. Checked on 2 devices:

Version: 0.9.57-Beta

Android version: 7
Device model: LG K9

Android version: 8
Device model: Unihertz Jelly Pro

Sometimes files order is correct right after the download is finished but then after scanning library the files order is changed, probably by file creation(download) time.
What is more, sometimes scanning removes the audiobook completely from the local media list in ABS even though the files are accessible in file manager.

**Comment by rwa96** [comment]
This is a dealbreaker for me because I can't use the app without using online streaming and therefore wasting mobile data. A workaround for this is, to use something like [AudioAnchor](https://github.com/flackbash/AudioAnchor) instead, pointing it to the download directory.

**Comment by advplyr** [comment]
This was fixed in 0.9.60-beta
