### ISSUE TITLE
[Bug]: Offline listening statistics are not being captured

### ISSUE THREAD

**Issue by ambarnes2** [advplyr/audiobookshelf-app#381]
### Describe the issue

When listening to audiobooks via the Audiobook Shelf Android app, the listening statistics are not being captured correctly. For example. I have been listening to a book on and off today (Over 2 hours) but the listening stats only show 5min.

### Steps to reproduce the issue

1. Listen to book on android app
2. Go to audiobookshelf docker page and review listening stats
3. Observe lack of proper stats

### Audiobookshelf version

2.1.4

### How are you running audiobookshelf?

Docker

**Comment by lostleonardo** [comment]
First things first, this is an exceptional piece of work. I jumped on the self-hosting bandwagon last year and one of the things I was really keen to find was a good audiobook player. When I found Audiobookshelf I practically fell in love. Something about the main page looking like an actual bookcase really grabbed me--and the overall design and UX are right up my street.

With that out of the way :-), I was just scrolling through the issue tracker to see if this exact issue had already been logged. Good to know that it's just a case of the feature not having been implemented yet.

If you're interested / amenable to somebody else picking this up, I could take a look. No guarantees, but if you could point me in the right direction, I'd be happy to go from there.

Possibly related (or possibly not), I was wondering if the app needs to keep trying to sync when the device does not have network access? As per the 'history' (another welcome addition), it is apparent that the app is tries to sync with the server roughly every 15 seconds, when a track is playing. That makes sense, I think. However, the app keeps trying to sync with the server in spite even when the app 'knows' (one of the icons changes) that the server is not accessible.

Thanks again,

LL

**Comment by advplyr** [comment]
That is great, I'm glad you are finding so much value in Abs.
This issue is something I'm hoping to make some progress on today actually. The code with this is a bit of a mess right now so it is probably not something you want to sift through.
The app does not need to keep trying to sync to the server when there is no connection. I must have just overlooked that.

**Comment by advplyr** [comment]
Fixed in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)
