### ISSUE TITLE
Will not login, throws 'unknown error'

### ISSUE THREAD

**Issue by nirurin** [advplyr/audiobookshelf-app#382]
### Steps to reproduce

1. Install 2.1.5 audiobookshelf server on docker
2. I have reverse proxy set up with Nginx Proxy Manager, however this issue also happens if I connect with local IP so the proxy doesn't seem to be related. 
3. Install current android app
4. Connect to server address (via url or local ip) (this seems to work, as it moves on to the login step)
5. Try and login - this does nothing, except says 'unknown error'

### Expected behaviour
IT should login. 

### Actual behaviour
It throws an 'unknown error'

### Environment data

Audiobookshelf Version: 2.1.5

- [Yes] Android App?

#### Android Issue
Android version:
12
Device model:
Z-Flip4
Stock or customized system:
Stock

**Comment by nirurin** [comment]
I found a solution - I needed to add http:// to the start of the ip or url.
If this is always needed on order to work, the app should have some logic
that assumes its always there (or adds it if it's missing). It's simple to
do. It didn't even occur to me that you might not have that in place
already.

**Comment by advplyr** [comment]
That is in place already. If your server entry does not start with "http" then "http://". See here https://github.com/advplyr/audiobookshelf-app/blob/master/components/connection/ServerConnectForm.vue#L256

I just tested entering my local ip without the protocol and it works. This won't work if you need to enter https:// since it will by default put in http://

**Comment by MattInternet** [comment]
I am experiencing this same issue. My server has ssl setup so I the server address starts with 'https'

I have tried it with and without the prefix. The server is running behind traefik

**Comment by advplyr** [comment]
@MattInternet I'm sure your issue is separate. There have been different issues posted here and in the main repo about traefik but I'm not familiar with it personally. I believe there are some active users in the discord server that run traefik.

**Comment by nirurin** [comment]
No it 8snt,because it -only- works if I manually add http:// to the start
of the server address. If you have it set up that it already adds that by
default, then you have it set up incorrectly.

**Comment by ravikiranj** [comment]
@advplyr I can actually reproduce this error on v2.3.3 (Docker on Windows) with latest Android app (0.0.65-beta). 

Probably worth adding a [placeholder](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder) to the server input element. Weirdly, the ping to the server succeeds but not the login.

![Audiobookshelf-Unknown-Error](https://github.com/advplyr/audiobookshelf-app/assets/389491/b5ee98d0-239c-4301-983b-e983246525a1)
