### ISSUE TITLE
[Enhancement]: Support web redirects for server url

### ISSUE THREAD

**Issue by kymahi** [advplyr/audiobookshelf-app#383]
### Is your feature request related to a problem? Please describe.
I have a dynamic DNS service set up to point to my home server IP. I have a web redirect to point a subdomain 
(e.g. audiobooks.[mydomain].com) to the correct port of my home server. Entering the url to connect to my 
server does not resolve to my home IP:port, but just says, "Failed to ping server".

### Describe the solution you'd like
I'd like the app to fully resolve the web redirect to whatever IP my dynamic DNS service points to, so if my 
home IP changes, I can always connect from my web redirected URL.

**Comment by advplyr** [comment]
I'm not really sure what you mean. The app just makes a request to the http address you enter, there isn't much to it.

It sounds like you may be setting up a reverse proxy in which case subdomains are not supported yet. See https://github.com/advplyr/audiobookshelf/issues/385

**Comment by hobesman** [comment]
Just to clarify: I think advplayer meant to say _subdirectories_ are not supported yet. _Subdomains_ should work fine so likely something else was going wrong.

**Comment by advplyr** [comment]
@hobesman Thank you! Fixed
