### ISSUE TITLE
[Bug] Android Auto: After download the app does not play the local content, it continues to stream the book.

### ISSUE THREAD

**Issue by jarrodCoombes** [advplyr/audiobookshelf-app#385]
### Steps to reproduce

1. Download a Book on Wifi
2. Play the book
3. Take note of mobile data usage during playback. 

### Expected behavior
The app should prioritize local content over streaming it, allowing people to download the book while on wifi, and play it in on cell data without using any actual data (well maybe a small bit of upload to report stats back to the server).

### Actual behavior
The app continues to stream the content, even though it has it locally cached.

### Environment data

Audiobookshelf Version: 0.9.57

- [x ] Android App?
- [ ] iOS App?

I use it primarily through Android Auto (so the screen in my car).

#### Android Issue
Android version: 13

Device model: Pixel 6

Stock or customized system: Stock

**Comment by advplyr** [comment]
Are you starting the playback from the continue listening tab in android auto? Or you are starting the playback from the downloads tab in android auto and it is still streaming?

**Comment by jarrodCoombes** [comment]
I believe I tried both, though it's unclear which one may or may not have caused data usage.  But given that I just hit play under the map, I'd guess it favored the "continue listening" tab. Oddly, at one point the progress on the "Continue listening" tab and "download" tab was different, but that seemed to resolve itself. 

I think the app should always favor the downloaded content, when a book is on the local device it should play the local files and merely send the usage data back to the server, and this should not matter where you start or resume from.

**Comment by jarrodCoombes** [comment]
It might be a good idea to add some sort of indicator that clearly shows that the playback is either streaming or local, for both on Android, and on Android Auto.

**Comment by advplyr** [comment]
> I think the app should always favor the downloaded content, when a book is on the local device it should play the local files and merely send the usage data back to the server, and this should not matter where you start or resume from.

Yes this is how it works everywhere except android auto right now. Android auto is a bit behind. Playing media from the download tab *should* play it locally.

I thought I had put this in the last release already but android auto allows you to put a flag indicating whether the media is downloaded. I couldn't find a screenshot of what it looks like but here is the docs for future reference: https://developer.android.com/training/cars/media#metadata-indicators

**Comment by Sp4rky001** [comment]
Hi, I was going to report high data usage, but finding this bug, I'm thinking this may be my problem.  I use Android auto as well and I found that the app uses a lot of foreground data as reported by my phone.  This is what I was originally going to post

> I'm on a limited mobile data plan and I use the Audiobookshelf Android client to listen on walks and drives. My phone reports that Audiobookshelf has high mobile data usage.
> 
> I make sure to always download the files locally and I make sure that the play button says "play" and not "stream"
> 
> Indeed, I'm 6 days into my new billing cycle and already, over 270MB of data has been transferred.
> 
> Is this because a socket connection is being used while on mobile? Does a socket connect keep a constant connection open that is always communicating?
> 
> Maybe an option for a data saver mode that increases the period of time between synchronization would be a good idea?

**Comment by advplyr** [comment]
Fixed in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
