### ISSUE TITLE
Notification image not updating

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf-app#388]
### Steps to reproduce

1. Start one book playing
2. Open a new book
3. Start playing the second book

### Expected behaviour
- Image in notification tray should be the image of the current book

### Actual behaviour
- Image in the notification tray is that of the previous book

### Environment data

Audiobookshelf Version:
v2.1.5 Docker
Android 0.9.57-beta

#### Android Issue
Android version: 13

Device model: Pixel 6 Pro

Stock or customized system: Stock

Example image
Previous book was Stephen King Airframe and has not been removed  when starting new book

![image](https://user-images.githubusercontent.com/101836977/190891115-3168a49f-46cc-4c05-97d8-2eb240321d6d.png)

**Comment by advplyr** [comment]
I just tested this with both streaming and locally downloaded books and was not able to reproduce.

Are you able to reproduce this every time with different books?

**Comment by barelylit** [comment]
Yeah, 3 in a row happened to each

![image](https://user-images.githubusercontent.com/101836977/190917938-337fc195-097e-43a7-ab23-7e8c1d208a37.png)

![image](https://user-images.githubusercontent.com/101836977/190917946-2f3c6556-8f6d-4f15-b041-683c58786763.png)

![image](https://user-images.githubusercontent.com/101836977/190917954-2a81f475-c1b7-4b34-88d5-498ee21751ce.png)

**Comment by advplyr** [comment]
Can you test this again in the latest release v0.9.60-beta?
I updated some things around cover images
