### ISSUE TITLE
Invalid Cover

### ISSUE THREAD

**Issue by Fenron-dev** [advplyr/audiobookshelf-app#39]
Instead of the correct cover, "Invalid Cover" is displayed. In browser mode, all covers are displayed correctly.

When I download the audiobook, the cover appears.

**Comment by advplyr** [comment]
Are you getting any errors in your server console? Are you updated to the latest version?

The way covers are stored on books has gone though so many evolutions, when you open up the "Covers" section in the edit modal does the cover path start with "/s/book/"?

![image](https://user-images.githubusercontent.com/67830747/143134007-9a38bb7e-eff4-4736-9f25-9e796234c9f4.png)

**Comment by Fenron-dev** [comment]
Indeed I get some error messages:

`[INFO] FFMPEG transcoding started with command: ffmpeg -seek_timestamp 1 -f concat -safe 0 -ss 12.9s -noaccurate_seek -i /metadata/streams/str_wqdefiq7sq0veimpl3/files.txt -y -loglevel error -map 0:a -c:a copy -f hls -copyts -avoid_negative_ts make_non_negative -max_delay 5000000 -max_muxing_queue_size 2048 -hls_time 6 -hls_segment_type mpegts -start_number 2 -hls_playlist_type vod -hls_list_size 0 -hls_allow_cache 0 -hls_segment_filename /metadata/streams/str_wqdefiq7sq0veimpl3/output-%d.ts /metadata/streams/str_wqdefiq7sq0veimpl3/final-output.m3u8`

2021-11-24 01:12:42 ERROR [BackupManager] Failed to load backups Error: Bad archive
2021-11-24 15:40:42 ERROR [ApiController] Audiobook not found for users progress undefined
2021-11-24 19:08:11 ERROR [ApiController] Audiobook not found for users progress undefined
2021-11-24 21:02:36 ERROR [ApiController] Audiobook not found for users progress undefined
2021-11-24 21:05:46 ERROR [BackupManager] Failed to load backups Error: Bad archive

![image](https://user-images.githubusercontent.com/56755865/143313947-0a01391d-bcf6-4fc1-97b7-f639a961396a.png)

**Comment by advplyr** [comment]
A new version of the app is released, can you check the new version?

The backup and user progress undefined error I haven't found the source of yet, but I don't think they are related to the cover issue you are having.

**Comment by feerlessleadr** [comment]
I'm not sure how to get logs from the server console, but I'm having the same issue as OP running app version 0.9.28-beta.

**Comment by Fenron-dev** [comment]
> A new version of the app is released, can you check the new version?
> 
> The backup and user progress undefined error I haven't found the source of yet, but I don't think they are related to the cover issue you are having.

I've tried it already but without success. I also tried to reinstall the Unraid docker but that didn't help too. When I remember correctly the Covers got lost with the first slumber update or one update sooner.

**Comment by Fenron-dev** [comment]
Just installed the new App Update. Sleep Timer seems to work now. :) 
Covers still not work but I noticed something this time. The Cover shows up in the Widget. 

![image](https://user-images.githubusercontent.com/56755865/143948390-ecf705a5-5210-49fa-bb19-2b2d2f8c8aa9.png)

I have problems with downloading Audiobooks too. It says finished but in the Download-Tab he is still at 0%. I have to restart the app and delete the "Download". Then I can stream it again. I had that error also in the last Version.

**Comment by Fenron-dev** [comment]
A small Update...I noticed that the covers are displayed when they are saved in the ".webp" format.

**Comment by TheBinaryLoop** [comment]
I have the same issue. My phone is the One Plus 8 Pro

**Comment by advplyr** [comment]
Are you all getting the error in your server logs about missing a user token?

**Comment by TheBinaryLoop** [comment]
I had to disable the hotlink-protection in cloudflare. Now it works for me. But thats not the best solution IMHO.

**Comment by advplyr** [comment]
Ah I didn't even think of that. Do you know how other software works around that?

**Comment by TheBinaryLoop** [comment]
Unfortunately not, but i don't know how you hande the images right now.

**Comment by advplyr** [comment]
I just realized the mobile app hasn't been updated to use the optimized cached images.. which are stored in `/metadata/cache/covers/`

You can still get any book cover from your server with the path 
`<SERVER URL>:<PORT>/api/books/<BOOK ID>/cover?token=<USER TOKEN>`
book id you can get from the URL of a book page
user token you can get by opening up developer console and going to application -> local storage you will see token.

**Comment by advplyr** [comment]
`v0.9.36-beta` is live and uses the new cached covers from the server. If this is not resolved you can re-open this.
