### ISSUE TITLE
[Enhancement] Make tapping the chapters' count pillbox show the table of contents/chapters list

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#399]
### Is your feature request related to a problem? Please describe.
![tempFileForShare_20220926-221353.jpg](https://user-images.githubusercontent.com/42061703/192334393-2b42896b-e78a-43e5-95a2-4bba58ce1570.jpg)

### Describe the solution you'd like
It would be nice to see the chapters list on the book info page.

The only way to see the list on the app right now is to start playing the book and then go to the chapters list view. But this requires people to start books which they may have no intention to start reading in the first place.

Pressing the pillbox (see image above) should open the same chapters list that one can see from the player view.

**Comment by stefanop1** [comment]
This option would be very useful

**Comment by sltvtr** [comment]
I agree, this is by far the only feature that I miss in this app :)
It would be also usefull for audiobooks that are for example sets of different failry tails.
Right now I have to start audiobook to choose what chapter I want to play.
Both thumbs up for this funcionality 👍 👍

**Comment by advplyr** [comment]
Chapters were added in a table on the book page in [v0.9.63-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.63-beta)
