### ISSUE TITLE
Force closing on Android 8

### ISSUE THREAD

**Issue by Helico-Pter** [advplyr/audiobookshelf-app#4]
I understand this is early access but I'd just like to know if anyone else is experiencing a force close on Android devices directly after opening?

Device: Samsung S7
Android: 8.0.0
App: Latest from play store

Great work on the server by the way, looks really promising.

**Comment by Amitheous** [comment]
I haven't had any issues with this. I'm on a galaxy note 9 running android 10. I do think they said there may be some issues with android versions earlier than 9.0 though

**Comment by Helico-Pter** [comment]
I thought this may be the case. I really should drag myself and devices into present day. 

Thanks.

**Comment by advplyr** [comment]
Yeah, this is a serious issue. Currently the app only supports about 40% of android devices running 10 or higher.
I would like to support at least Android 8 which would cover 80% of users, either way I need to update the play store listing to not allow earlier than Android 10 to install.

**Comment by Helico-Pter** [comment]
Thanks advplyr. Great job so far.

**Comment by advplyr** [comment]
Just published `v0.9.0-beta` which supports Android 8 and up.

The only difference is there is an extra permission step where Android 8 & 9 will be asked to accept to use the file system.

I only tested this on an emulator, so let me know if there are still issues.

**Comment by Helico-Pter** [comment]
I totally missed this post but just wanted to say the app is working well on my old device now. Thanks again.
