### ISSUE TITLE
Feature Request: Adjust Total Time & Time Remaining Based on Selected Playback Speed

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf-app#40]
Hi - I just installed the server and the android app, and I have to say that this is a really awesome program, great work and thank you!

One thing that my 'local' android audiobook player does that I really like is to adjust the total time of the audiobook as well as the time remaining (or in this case time played) of the current audio book, based upon the playback speed selected. So in my case, if I have an audiobook that is 10 hours long, and playback speed is 1x, then the total time reported by the app/server would be 10 hours. However if in the app I selected 2x playback speed, then the total time reported in the app/server would then be 5 hours. 

Thanks for your consideration!

**Comment by advplyr** [comment]
This was included in release `v0.9.28-beta`. You can re-open this if it isn't functioning how you thought.
