### ISSUE TITLE
[Bug] Streaming audio books chews up *way* more data than the actual file size(s). Maybe a bug, or maybe just my understanding is wrong?

### ISSUE THREAD

**Issue by jarrodCoombes** [advplyr/audiobookshelf-app#400]
So I use an app on my phone to track data usage (glass wire), and I couldn't help but notice the amount of data the app is using does not seem to match what I was expecting to stream a book. So I did some math.

The book is 16.25hrs long at a size of 2.18Gib (2,238Mib), which means it's around 137mib/hr in raw data size. But my phone is reporting me consuming data at nearly double that rate when I stream it (roughly 2.5 times that, or about 335.3mib/hr).

Why would this be? Is my reasoning flawed here? Is it a bug?

**Comment by advplyr** [comment]
I can't speak to exact numbers but every 5 second the mobile app sends a request to the server with the updated listening status. Right now this request is probably 2- 4 times bigger then it needs to be but if you are on a metered network then the requests are reduced to every 60s to save data.
See #238 for more details, we can use that as the main thread.
