### ISSUE TITLE
[Bug] 1.6:1 Book cover, covers the beginning of the seek bar

### ISSUE THREAD

**Issue by yourjelly** [advplyr/audiobookshelf-app#401]
### Steps to reproduce

1. Play a book in a library with standard sized book covers

![image](https://user-images.githubusercontent.com/26312697/192533502-7bb9d8eb-938a-471e-9976-fdb13742afda.png)

### Expected behaviour
- Book cover should be shrunk to not cover seek bar or should be layered behind it (could cause problems with light colored cover).

### Actual behaviour
- Book cover seems to be scaled based on width and allowed to flow over seek bar.

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: Pixel 4XL

Stock or customized system: Stock

![image](https://user-images.githubusercontent.com/26312697/192533502-7bb9d8eb-938a-471e-9976-fdb13742afda.png)

**Comment by advplyr** [comment]
Fixed in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
