### ISSUE TITLE
"Failed to ping server" in Android and iOS App

### ISSUE THREAD

**Issue by PlzSpamMeNot** [advplyr/audiobookshelf-app#403]
Hello

I freshly setup a ABS server on my synology nas and it works pretty fine over web.
But when I try to connect via app (both, Android and iOS) I will get the error massage "Failed to ping server".

On each device, i can reach the ABS server via browser. 
From the local netzwork and also from extern over internet.

### Steps to reproduce

1. setup fresh abs server  
2. install fresh iOS or Android app
3. try to connect via IP or dns name

### Expected behaviour
- establish connection

### Actual behaviour
- Error "Failed to ping server"

### Environment data

Audiobookshelf Version:

- [ x] Android App - latest version 
- [ x] iOS App - latest version

**Comment by Undergrid** [comment]
I have recently set up ABS and gained access from the Android app, so this is not an inherent issue with either the service or the app.

Can you access the synology device from your mobile using a webbrowser rather than any of the synology apps?

**Comment by PlzSpamMeNot** [comment]
Yes, I can access the Synology and its apps from everywhere. 
I also can access the specific ABS server over web from everywhere and every device.

**Comment by PlzSpamMeNot** [comment]
Maybe it is a timing problem. Could I extend ping timing on server site?

**Comment by nichwall** [comment]
Is it an issue with the ports? For example, only forwarding 80 or 443 from the internet so you need to make sure it's `http://books.example.com` vs `https://books.example.com` when filling out the connection information in the app? I block port 80 on my router to force people to connect via https (not the best solution, but it works for me) so sometimes people forget that.

**Comment by PlzSpamMeNot** [comment]
> Is it an issue with the ports? For example, only forwarding 80 or 443 from the internet so you need to make sure it's `http://books.example.com` vs `https://books.example.com` when filling out the connection information in the app? I block port 80 on my router to force people to connect via https (not the best solution, but it works for me) so sometimes people forget that.

I use the basic setting of ABS, port 80 to 13378 and forwarded this port to a random other port to the web.
When I login over the web browser (dosend matter if in LAN or over Internet) I only use HTTP (unfortunatly, HTTPS would be my preference)

In the app i tried the following connection string so far:
- http://book.example.com
- http://<externlP>:<forwardedPort> (e.g. http://81.221.123.45:12345)
- http://<internalIP>:13378 (e.g. http://192.168.0.10:13378

Over web browser, each of this URLs works, regardless wich device and in wich network. Only in the App it won't work.

**Comment by PlzSpamMeNot** [comment]
Figured out a workaround, if i use instead of the Subdomain the DynDNS URL with port, I could connect via App
