### ISSUE TITLE
User stats showing incorrect time (iOS and PC)

### ISSUE THREAD

**Issue by LynxCub** [advplyr/audiobookshelf-app#404]
### Steps to reproduce

1. Open up AudioBookShelf
2. click the three bars in upper right hand corner
3. Click on user stats
4. Time is not being displayed correctly

### Expected behaviour
- The correct amount of minutes for Week, Daily and Best should be displayed correctly

### Actual behaviour
- It appears that maybe milliseconds are being displayed vs minutes/hours

### Environment data

Audiobookshelf Version: 2.2.0

- [ ] Android App?
- [x] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 16.0.2 though it was happening on 15.x.x

iPhone model: 11 11 pro
![IMG_2769](https://user-images.githubusercontent.com/37588889/193488281-77cbc510-4fb8-4eb2-b53b-de4d687b22b3.PNG)

**Comment by LynxCub** [comment]
Issue also appears when just using a PC
![image](https://user-images.githubusercontent.com/37588889/193488716-d80ebf01-717f-485e-99ea-07f0b081a956.png)
 (Windows 10) + Brower to login.

**Comment by benonymity** [comment]
I'm experiencing this as well, but only on some accounts. I use the app all the time, but since the latest beta haven't noticed any issues with my own listening time--however, other people using my server are also on the latest beta, but they generate listening session that are thousands of hours long often. Maybe it's just coincidence, but it seems to only be happening to non-root users even on the latest iOS beta.

**Comment by copycatchiller** [comment]
<img width="788" alt="bug" src="https://user-images.githubusercontent.com/5833093/198511423-b35c0a1e-54f5-4b62-9ff1-022f9e156539.png">

experiencing this as well on iOS Beta

**Comment by grehund** [comment]
I'm also having this problem, even after deleting the App and reinstalling it.

**Environment data:**

Audiobookshelf Server Version: 2.2.6

Audiobookshelf App Version: 0.9.59

iOS Version: 16.1.1 though it was happening on 15.x.x

iPhone model: 10,3 and 12,8

**Comment by benonymity** [comment]
I'm been digging into this problem a bit and noticed that all the problematic listening sessions on my server are when the book is streamed. I've been downloading all my books and all of my listening stats are accurate, but other users that stream have listening sessions reported as thousands of hours long. I'm looking through the code, I bet that something is in milliseconds but is being reported as seconds on the logic for streamed sessions and we'll only need to divide one number by 1000. If I find the issue for sure I'll submit a PR!

**Comment by advplyr** [comment]
This should *hopefully* be fixed in [v0.9.60](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.60-beta)
