### ISSUE TITLE
After resuming from pause the book will jump forward by an unspecified amount of time. 

### ISSUE THREAD

**Issue by ChiefMedicalOfficer** [advplyr/audiobookshelf-app#405]
### Steps to reproduce

1. Play book at more than 1x speed (haven't tried at 1x speed but I will just now (occurring at 1x speed) 
2. Pause and disconnect bluetooth earphones (relevant?) 
3. Reconnect earphones and play

### Expected behaviour
- Tell us what should happen

Book should resume from where it was left off.

### Actual behaviour
- Tell us what happens

When the book is played it will start from a point further in the book. Just now I played a book, disconnected earphones (I'm not sure if that's relevant), started the book 5 minutes later and the time had jumped by 3 minutes. Sometimes the jump can be more than an hour if I'm further into a book. 

I stopped this book at 7 minutes and when I resumed it had moved to 10 minutes. 

This has definitely been happening since at least the last server version. 

Is occurring at 1x speed. 

### Environment data

Audiobookshelf Version: 2.2.0 (docker) 

- [X] Android App? 0.9.57-beta

#### Android Issue
Android version: 12

Device model: Samsung Galaxy S10

Stock or customized system: Stock

**Comment by ChiefMedicalOfficer** [comment]
The above is actually occurring at 1x speed too. I stopped my current book at 2h 15m and when I went to play again it jumped to 2h 28m.

**Comment by mefistos** [comment]
This is happening to me as well, started with the latest 2.2.0 server update. I am using Galaxy S22, but I have a feeling that it's a more of a server issue rather than the android app.

**Comment by ChiefMedicalOfficer** [comment]
> This is happening to me as well, started with the latest 2.2.0 server update. I am using Galaxy S22, but I have a feeling that it's a more of a server issue rather than the android app. 

Did you ever connect your phone to Android Auto?

I've just realised that my phone had been connected to my cars Android Auto and it's possible this only started from that point.

**Comment by advplyr** [comment]
Is this still happening?
If so, is this a downloaded audiobook or streaming from your server?

**Comment by mefistos** [comment]
> Is this still happening?
> If so, is this a downloaded audiobook or streaming from your server?

Hasn't happened in a long time. But it was happening when streaming from a server.

**Comment by ChiefMedicalOfficer** [comment]
> Is this still happening?
> If so, is this a downloaded audiobook or streaming from your server?

I'll try a book and let you know.

I commented that this only seemed to occur since my phone was connected to my car but I haven't been able to test that theory yet.

**Comment by ChiefMedicalOfficer** [comment]
> Is this still happening?
> If so, is this a downloaded audiobook or streaming from your server?

Completely disconnected from car and haven't noticed anything out of the Ordinary. Book has worked as expected for around 2 hours. 

A couple of weeks ago I removed Android Auto and it still occurred when only connected to the car through Bluetooth.

**Comment by advplyr** [comment]
Thanks for testing. Over the next week or 2 I'm trying to get to as many as these types of bugs as I can so let me know if it comes up.
