### ISSUE TITLE
[Bug]: series and collections tabs are empty except for "# of series" label on android app

### ISSUE THREAD

**Issue by yegods** [advplyr/audiobookshelf-app#406]
I did have some basic conversations and debugging of this in the discord general chat.

### Steps to reproduce

1.  create library with series and collections via web app, that uses abs docker
2.  attach to library via android app
3.  login as either root or another user (permissions don't seem to matter)
4. click the series tab

### Expected behaviour
- i should see the series or collections.
- 
### Actual behaviour
- blank page, except for # of series label

### Environment data
unraid docker of abs

Audiobookshelf Version:
2.2.0

- [ x] Android App?
- [ ] iOS App?

#### Android Issue
Android version:
12

Device model:
pixel 3 xl

Stock or customized system:
stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Is this still an issue?

**Comment by yegods** [comment]
It has apparently been fixed, since it works now :)  I looked at those tabs maybe a week or two ago, and they weren't working.  Anyhow... i'm closing this.  Thanks
