### ISSUE TITLE
IOS App switching interfere with the scrub bar

### ISSUE THREAD

**Issue by booleansmith** [advplyr/audiobookshelf-app#408]
### Is your feature request related to a problem? Please describe.
It is difficult for me to select the scrub bar [the progress bar that you can control location of playback in a book] without accidentally starting to switch apps.

### Describe the solution you'd like
I think a good solution could be to swap the location of the scrub bar with the bookmark/ playback speed/ sleep timer/ menu bar [see photo], but I'm sure someone else more creative than me could come up with a more creative solution. 

### Describe alternatives you've considered
The solution could also be to add a small amount of buffer between the bottom of the screen and the scrub bar, or even just to add some haptic feedback so I can tell when I have gotten ahold of the scrub bar. It could also help if the scrub bar was slightly larger. 

As always many thanks to the developers, this is an awesome project!

### Additional context
<img src="https://user-images.githubusercontent.com/32348565/194736524-efd5d5dc-8984-4df9-aef6-e5e7af6960b2.jpeg " width="200">

**Comment by advplyr** [comment]
Updated in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)

**Comment by booleansmith** [comment]
The new interface looks great!

**Comment by Piste** [comment]
Woohoo! Thanks a lot for the update. 👏
