### ISSUE TITLE
Make chapter names clickable/tapable to reveal details

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#412]
### Is your feature request related to a problem? Please describe.
Sometimes books have chapter titles that are really long. In the mobile app (Android) the label on the player or in the chapters' list is not wide enough to show the full title. See images below.

![tempFileForShare_20221015-230519.jpg](https://user-images.githubusercontent.com/42061703/196000392-8aae5a61-e1fb-4168-b706-a0bc33d2e018.jpg)

![tempFileForShare_20221015-230548.jpg](https://user-images.githubusercontent.com/42061703/196000400-4c95da3d-8b4e-41de-ace2-10f0ac56c8a6.jpg)

### Describe the solution you'd like
It would be nice if one could click/tap the label (on either or both screens) to see the full title.

### Describe alternatives you've considered
None

**Comment by advplyr** [comment]
We'll most likely make that text scrolling. I can't see how clicking would work
