### ISSUE TITLE
Are we open to alternative apps

### ISSUE THREAD

**Issue by Hackmodford** [advplyr/audiobookshelf-app#417]
Would it be okay if I made an alternative app that used Flutter instead?
Does audiobookshelf have an API?

**Comment by advplyr** [comment]
Absolutely. There is an API but it isn't documented yet. I started the documentation [here](https://api.audiobookshelf.org) but haven't gotten very far and some of those objects may be a little out-of-date.

You can find all the endpoints in the code here https://github.com/advplyr/audiobookshelf/blob/master/server/routers/ApiRouter.js#L56

The endpoints around syncing playback sessions and progress may change because right now that part is messy. Especially when it comes to downloaded library items.
The CRUD endpoints for libraries, library items, users, etc. are solid though.

**Comment by Hackmodford** [comment]
I might play around with this.
Does the app have to be open sourced? Is there a benefit to having an alternative in your mind?

**Comment by advplyr** [comment]
It doesn't have to be open source but since every other project for Abs is FOSS it would be preferred.
I'm not sure there is a direct benefit, but I think the more people interested in Abs the more contributors we will get and the better the software can become.

**Comment by Hackmodford** [comment]
I found the login endpoint and was able to get my api token. I was then able to request the libraries / items / item and post the play request. Seems like I can do what I need in a flutter app :)

**Comment by Manantra** [comment]
> I found the login endpoint and was able to get my api token. I was then able to request the libraries / items / item and post the play request. Seems like I can do what I need in a flutter app :)

will you then share your app for everyone else? are you open for ios and android too?
I would love the option to choose from different apps.

**Comment by Hackmodford** [comment]
> > I found the login endpoint and was able to get my api token. I was then able to request the libraries / items / item and post the play request. Seems like I can do what I need in a flutter app :)
> 
> will you then share your app for everyone else? are you open for ios and android too? I would love the option to choose from different apps.

I’m trying to decide if this should be v2 of my app, Undulib. Or just an open source project. Since I’m leaning towards Flutter it would definitely support iOS/Android. I’m also weighing if the current app is good enough.

I’m not a fan of using web tech for apps and prefer a more native experience. But then again Flutter isn’t exactly native either. I just believe it would be more performant.

**Comment by keaganhilliard** [comment]
I actually have a flutter app that works with Audiobookshelf... I could open source it haha. It only works for audiobooks but I use it all of the time to listen to audiobooks from ABS.

**Comment by Manantra** [comment]
> 

Undulib sounds nice. Would be nice to support it for  ABS. But sadly I can’t install it, because it’s not supported for German App Store. Could you fix that maybe?

**Comment by Manantra** [comment]
> I actually have a flutter app that works with Audiobookshelf (Emby and Plex too)... I could open source it haha. It only works for audiobooks but I use it all of the time to listen to audiobooks from ABS.

Would be also nice to check this app out and test it.

**Comment by Hackmodford** [comment]
Is the app available on the store?

**Comment by keaganhilliard** [comment]
No, I've been recently looking into actually publishing it, but I have not done so yet.

**Comment by k9withabone** [comment]
Hello all, its nice to see that other people are also interested in creating a Flutter app for audiobookshelf. I have been thinking about doing this myself for a bit now and would love to work with others in a open source manner. Perhaps we should move this to a discussion?

**Comment by keaganhilliard** [comment]
That makes sense, we could also talk about it on the discord server. I pushed up the current state of my app to this repo. https://github.com/keaganhilliard/audiobookly. Currently supports iOS, Android and Mac. Supporting Linux and windows should be more possible now that some audio libraries have surfaced.

**Comment by Hackmodford** [comment]
@keaganhilliard I just got your app to run in the simulator. It seems like a really good start. At a cursory glance the way you have architected the app seems similar to the way I would approach it. What license are you going with?

**Comment by k9withabone** [comment]
I was thinking using the discussion feature here on GitHub because then it would be easier for anyone else who finds this issue or the discussion and wants to help to see our initial thought processes. Anyway I've created a discussion (#428), but we can move to discord/matrix whenever.

**Comment by advplyr** [comment]
Discussion is better then issue, will close this one out
