### ISSUE TITLE
iOS app should respect safe area insets

### ISSUE THREAD

**Issue by Hackmodford** [advplyr/audiobookshelf-app#418]
### Steps to reproduce

This is particularly noticeable on the mini player.
The bottom of the view is too close to the app switch bar.

![image](https://user-images.githubusercontent.com/326668/196252926-434a61fd-a4c8-4037-b121-0604df2f07e7.png)
Ideally the mini player should add some bottom padding to account for the green area shown in the screenshot.

**Comment by Hackmodford** [comment]
This would also address this issue.
https://github.com/advplyr/audiobookshelf-app/issues/408

**Comment by benonymity** [comment]
Should be fixed in the latest release. See also #531.

**Comment by advplyr** [comment]
The audio player has been adjusted again for the next release, issue for that is #531

There was also an update to the modals to give more space at the top that will be in the next release.

We'll use #531 as the main thread for this and if there are specific things we need to adjust in the future they can be opened as separate issues.
