### ISSUE TITLE
[bug] weird behaviour when starting app without server connection vs losing access to server with app running

### ISSUE THREAD

**Issue by zombiehoffa** [advplyr/audiobookshelf-app#42]
If I start the app on my network and have a bunch of book wihth local copies then lose access to the server things work as expected mostly. My book list decreases to what is downloaded locally and things continue  basically as expected. If I start the app without access to the server I get 1 local book showing and that's it. even though I can scan and see the other downloaded books from within the app they do not show up to be played.

There is also still some weirdness sometimes around  when and which instance of playing a book is taken as the one to sync everywhere else  but I don't have that sorted out enough to comment authoritatively on what exactly is going on so I am just leaving it as a footnote on this bug.

**Comment by advplyr** [comment]
Sounds like the downloaded books didn't get stored in the DB correctly. When you connect to the server can you delete one of those downloads from the app and re-download it.

**Comment by zombiehoffa** [comment]
I tried one book so far and it seems to have worked unitil I  force stopped audiobookshelf-app to make sure it was actually stopped. Then when i started it again without connection to the server it did not have the one book I downloaded in it (It did show the second book I tried to download  that failed to download for an unrelated bug that I think relates to not having to transcode because that book was just 1 mp3 file already).

**Comment by advplyr** [comment]
A lot has changed since then and server sync and offline was completely re-done. If this persists please open a new issue.
