### ISSUE TITLE
[Enhancement]: Allow for PDF E-Reader support

### ISSUE THREAD

**Issue by st0r4ge** [advplyr/audiobookshelf-app#420]
This issue relates to feature request for the server application advplyr/audiobookshelf#1081

Maybe it's possible to make this work on the client app by allowing pdf-files in the already existing E-Reader?
Currently it supports everything but PDF-Files, as lined out in issue #14

![image](https://user-images.githubusercontent.com/69420383/197288732-1032e999-26ae-49fb-8b02-87a94fe5af63.png)

For addional context please look at advplyr/audiobookshelf#1081

**Comment by advplyr** [comment]
Added in [v0.9.60-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.60-beta)
