### ISSUE TITLE
Play stop not work on block screen

### ISSUE THREAD

**Issue by burghy86** [advplyr/audiobookshelf-app#427]
### Steps to reproduce

1.play a audiobook
2.shoutdown screen
3. Immediately  try to pause on lock screen command: work
4. Listen 5 minute with screen off
5. Try to pause on block screen not work
6. Unlock smartphone and pause on app work
7. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data

Audiobookshelf Version:

- [ ] Android App? Yes
- [ ] iOS App?

#### Android Issue
Android version:
10
Device model:
Samsung a6 2018
Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by hobesman** [comment]
I haven't noticed a difference with the delay, but mine also won't play/pause from the lock screen. Android app version 0.9.59. phone on Android 10 (stock Galaxy S9+)

**Comment by advplyr** [comment]
I just tested this Android 12 Pixel 6 and it is working.
The reproduction steps aren't clear so here is what I did.

1. Start playing an audiobook
2. Turn off screen
3. Pause from lock screen
4. Play from lock screen

@hobesman is this what you did?

**Comment by advplyr** [comment]
I made some updates in v0.9.60-beta that may have impacted this. Can you test this again?

**Comment by hobesman** [comment]
Still happening for me on 0.9.60-beta. It almost seems like the widget registered two taps. Sometimes when I tap it pauses for a few seconds and then resumes by itself, as if the "second tap" took a few seconds to process. Other times the audio just stutters a tiny bit when you tap it.

**Comment by advplyr** [comment]
I've just tested this on Pixel 5 Android 10 and still unable to reproduce the issue. Perhaps a Samsung bug?

**Comment by advplyr** [comment]
I think I figured this one out. The same solution as for #429

**Comment by advplyr** [comment]
This should be fixed in `0.9.62-beta` but let me know if it persists after you test

**Comment by Linden-Ryuujin** [comment]
0.9.62 did indeed fix this for me 👍 (Galaxy Note 9)

**Comment by advplyr** [comment]
Thanks for following up!
