### ISSUE TITLE
BUG: Android - Playing offline file - can't unlock phone

### ISSUE THREAD

**Issue by FlamingoDaBird** [advplyr/audiobookshelf-app#43]
Hi

Noticed a really weird issue. Installed the app on my android phone, connected to my selfhosted docker on Unraid, reverse proxy.

When I streamed it worked fine, then I decided to download the m4b audiobook to my \downloads\#AudioBooks\ folder
After a few seconds playing it offline made my phone go nuts. :)
I could unlock it, I couldn't see the display finger print reader, the screen only flashed to briefly show me a empty desktop...
pressing and holding the power button to display the power options to shut down/restart gave me an empty grey screen...

I had to hard reset the phone to be able to access it again. 

- I uninstalled the app and reinstalled it, same issue again.
- I then used another folder to save my audiobook, \Audiobooks instead of the one mentioned above, maybe there's an issue with the hashtag in foldernames? :)

I'm using a Oneplus Nord2, android v11.

Not a big deal since it seems to work now when I use a different foldername. 
Thank you.
Best regards
Peter Striberger

**Comment by advplyr** [comment]
I think this is the same issue in #35 and I haven't been able to reproduce this yet. It also isn't getting reported as a crash by google play so I can't see any error logs.
Hopefully I can reproduce or get some more info on this soon. Might be specific to the Oneplus.

**Comment by FlamingoDaBird** [comment]
I got the same issue again, with a downloaded audiobook, weird stuff. 
Could be that the oneplus is the culprit, my wifes workphone is another nord variant, could ask her to try it as well :)

Seems like its the same issue as #35 
Should we close this issue and add my stuff to the existing issue instead? 
Thanks.

**Comment by advplyr** [comment]
Yeah that is a good idea, thanks for helping to test. I'm not able to emulate that device.
