### ISSUE TITLE
Preset server URL and login

### ISSUE THREAD

**Issue by sanbroz** [advplyr/audiobookshelf-app#434]
I suggest to add a option to preset a server url and login user detail. This way users can use the app without entering server detail at first run

**Comment by advplyr** [comment]
I don't understand. How would can we preset a server url and user without knowing what it is'?

**Comment by sanbroz** [comment]
I think we should have a optional config to add a url and public view credentials at compilation. It's related to my public view comment.

BTY thanks for your nice project

**Comment by advplyr** [comment]
I still don't understand. The mobile app will be installed from an app store or side loaded. Once it is installed you will have to enter in a server address, there is no way around that.
