### ISSUE TITLE
Custom Download manager

### ISSUE THREAD

**Issue by Hyperion923** [advplyr/audiobookshelf-app#435]
### Is your feature request related to a problem? Please describe.
I currently have the problem that when I download (android 13) audiobooks with a lot of files, the download manager sends a lot of notifications. in addition, it is not possible to cancel a download once it has started. Furthermore, the app (0.9.59) currently crashes when I download an audio book with many files. The files are still downloaded but not imported by the app. it would therefore be nice to be able to pause and continue downloads.

### Describe the solution you'd like
For this issue i guess the best solution is a new or own download manager.

### Describe alternatives you've considered
as an alternative solution you could pack the files into a zip archive to reduce the number of downloads.

**Comment by advplyr** [comment]
The last release fixed the notifications. The upcoming release 0.9.62 will fix an issue with the UI hanging for a long time after downloads with many files is finished.
The ability to cancel downloads was brought up in #258
