### ISSUE TITLE
ENHANCEMENT: Sleep Timer

### ISSUE THREAD

**Issue by FlamingoDaBird** [advplyr/audiobookshelf-app#44]
Hi.
Love the application, comparing it to my go to audiobook player, android app: smart audiobook player.
But this has so much more potential  :) 

I really love the sleep timer options bundled in the smart audiobook player.. Yes there's a bunch of options regarding this...
The main thing every other application seems to not include is the option to use the sleep timer in bed, my point is:
If you're in bed you do not want to look into that bright sun of a display when you're trying to being all cozy in all that comfy darkness :)

When you set the sleep timer to X minutes the sound volume fades when reaching the end, say with 10 seconds left.
That's when you have the option to shake the phone to get another X minutes of that sleep timer.
Or as I prefer, use your ear buds or whatever function to pause/play and thus reset the timer, not being dependent to get hold of your phone.

The point is that you never run out of that sleeper timer, it is never reset to zero. 
Which makes it nice if you feel you can listen x minutes more.

Also it would be nice with a scheduler for setting up your sleep timer,

Thank you very much.
Best regards
Flamingo Da Bird

**Comment by advplyr** [comment]
I didn't know the sleep timer was such a popular feature, it has also been mentioned in #10 and #24 

Can you explain how the sleep timer works with the play/pause on your ear buds? When the sleep timer is running and you press pause this will reset the sleep timer?

Also, can you explain what you mean by a scheduler?

I've never used any sleep timer features so this is all new to me.

**Comment by FlamingoDaBird** [comment]
It seems like a very popular feature. Its nice to know that you don't miss way too much and can easily backtrack the amount of X minutes you set if you fall asleep. 

Yes, that's how it works indeed. If you press play/pause on your buds to pause the audiobook it will pause the book and the set timer will be reset to the original value of your timer. This will give you a new full timer again.
so if you set your timer to 10 minutes and you pause halfway through the timer (5 minutes left) it will reset directly to 10 minutes again. Might be difficult to know when it should reset during a pause perhaps? Or this particular programmer wanted it to be this way. Not sure either when the reset should apply, when the last 10 seconds within the fade out period? if you pause then it will reset the timer? Or one must wait for the audiobook to pause itself after the timer runs out?

Not sure, I guess that's a matter of choice, 

I would love to have the option to keep the timer running its course until it hits the amount of time entered. Even if you would pause during the timer it would keep the timer paused as well, and then continue to run the timer when playing.
An indication that the end of the timer is coming up would be nice (such as the volume fading?) so  one could play/pause during that limited time frame and get a timer reset to the original value once again to keep going.  Or simply press play on ones buds to get it going if the timer runs out. But at all times keep the same timer.

----

A schedule is just an easy setup to keep the above set to a time frame. Lets say I usually go to bed about 11pm (trying to use a 12h clock even though I'm not used to it ;)  )
If I set my scheduler to 11pm - 06am it would always set a sleep timer to say 10 minutes.
But during the day I do not want the timer to be active. So its more of a lazy thing... Not needing to set a sleep timer every night. Like having my phone alarm in the morning always set for a specific time when it's time go get going for work... So I don't forget to set it each night,

Thanks.
I hope that helps.. omg.. so much text. Let me know if you need further information.

**Comment by advplyr** [comment]
I released an update to the sleep timer. We can continue this discussion in the original sleep timer issue #10 
let me know what you think there
