### ISSUE TITLE
M4B Encoder Quality

### ISSUE THREAD

**Issue by dreaming-sparrow** [advplyr/audiobookshelf-app#440]
Hello,

I have a lot of large Audiobooks which are currently all split in multiple mp3 files.
Since there are still some issues when attemting to download large books on my android due to the problem metioned in #435 i decided to go for the option to convert my books to m4b files.
For me though it seems that when converted using the buildin M4B Encoder the quality is much lower than from the original files.
Sometimes the pitch tips over and is just a crackling noise.
Are there any options for the m4b encoder to set?
Is it just me?

Thanks for your time and help!

**Comment by advplyr** [comment]
There are currently no settings but I think there should be. I haven't dug into this deeply yet but there is an issue already open for this here https://github.com/advplyr/audiobookshelf/issues/1029

Follow that issue for updates on this
