### ISSUE TITLE
Ebook rendering missing last few lines while audiobook is playing 

### ISSUE THREAD

**Issue by joshuatly** [advplyr/audiobookshelf-app#442]
### Steps to reproduce

1.read an ebook
2.play an audiobook 
3.follow till the last few lines

### Expected behaviour
- mini player shouldn't obstruct last few lines of book page 

### Actual behaviour
- I can't find a way to read the last few lines of the page 

### Environment data

Audiobookshelf Version: 2.2.4 debian

- [ yes ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.59 beta

Device model: Pixel 6

Stock or customized system: stock

![Screenshot_20221117-213722](https://user-images.githubusercontent.com/8279975/202449372-99ab12b3-59e3-4554-a71a-e17a6818531b.png)

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Fixed in [v0.9.60-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.60-beta)
