### ISSUE TITLE
Stream Volume

### ISSUE THREAD

**Issue by dreaming-sparrow** [advplyr/audiobookshelf-app#446]
Hello,

it seems to be not possible to change the volume for steamed music from within the android application.
Currently i have to change it via the google home application.
Volume up and down buttons are mapped to the inbuild volume not the streaming volume while streaming.

**Comment by advplyr** [comment]
What is your Android version?

**Comment by dreaming-sparrow** [comment]
> What is your Android version?

10

**Comment by jamesbrindle** [comment]
I have the same issue. Android 12... Unable to change volume from phone when casting.

**Comment by advplyr** [comment]
Duplicate of #584

That issue is more specific
