### ISSUE TITLE
Multilingual app

### ISSUE THREAD

**Issue by burghy86** [advplyr/audiobookshelf-app#448]
just as a reminder.  I'm ready to help translate the mobile apps into Italian as well. An in a other language naturally..

**Comment by hellofaduck** [comment]
I can help with translation to russian if this option is available!

**Comment by advplyr** [comment]
This is available for the server/website already if you want to help translate that https://github.com/advplyr/audiobookshelf/issues/1103

We don't have any central localization system in place so it is just updated JSON files.

**Comment by burghy86** [comment]
any news?

**Comment by Uinsart** [comment]
I would love to help translate it to German!

**Comment by advplyr** [comment]
Mobile app is ready to be translated. Any of the matching strings already translated on the server have been moved over. There are a lot of new strings to translate.
https://github.com/advplyr/audiobookshelf-app/tree/master/strings

**Comment by Demian98** [comment]
Thank you a lot :)

**Comment by advplyr** [comment]
Added in [0.9.69-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.69-beta)
