### ISSUE TITLE
Allow for Orientation Lock in Audiobook Player

### ISSUE THREAD

**Issue by ambarnes2** [advplyr/audiobookshelf-app#449]
### Is your feature request related to a problem? Please describe.
No current issue, just a way to enhance user experience

### Describe the solution you'd like
Create a way to allow the end user to lock the orientation of the player, this will allow them to choose if they want the player in landscape or portrait mode. 

### Describe alternatives you've considered
The only option I found that works is to disable screen rotation in Android as a whole. Not a great user experience as there are other apps I want to be able to switch orientation. 

### Additional context
None

**Comment by advplyr** [comment]
Do you know of another app that offers this feature?

**Comment by ambarnes2** [comment]
Yes, SmartAudiobook Player has this functionality.

![Screenshot_20221126_230349_Smart AudioBook Player001 6659](https://user-images.githubusercontent.com/54408675/204118760-25653f12-0643-4873-882c-8dcb43c9ee34.jpg)

**Comment by advplyr** [comment]
Added in [v0.9.60-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.60-beta)

**Comment by nichwall** [comment]
> Is this available on iOS? I can’t find it. 

It is not currently on ios. https://github.com/advplyr/audiobookshelf-app/issues/1036
