### ISSUE TITLE
App crashes during audiobook download

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf-app#450]
### Steps to reproduce

1. Download audiobook "Ich Lebe"  by Series "Hamburg Sequence" from Thariot
2.
3.

### Expected behaviour
I just tried to save several audiobooks locally on my phone. The first audiobook worked. The second one didn't. Every time I try, the Audiobookshelf app shuts down on its own. This phenomenon occurs with all audiobooks from the "Hamburg Sequence" series. If I select any other audio book, it works again.... Do you have a solution for this?

### Actual behaviour
- Tell us what happens

### Environment data

Audiobookshelf Version:
2.2.6

- [ x ] Android App?
- [ - ] iOS App?

#### Android Issue
Android version:
11

Device model:
Android 

Stock or customized system:
Stock

**Comment by advplyr** [comment]
Can you check if there is XML inside the metadata?

**Comment by Hallo951** [comment]
Um, how do I do that?

**Comment by Hallo951** [comment]
I have looked at the audiobooks in question again but have not seen anything conspicuous. I looked at the metadata with the mp3tag tool, but I didn't see anything with xml or anything else.

Attached are a few screenshots.

Folder structure:
![IMG_20221201_080109_1](https://user-images.githubusercontent.com/40667862/204989921-2a7b5164-cab8-4b8d-918b-9343f42763f8.jpg)

Abs file:
![IMG_20221201_081037](https://user-images.githubusercontent.com/40667862/204990110-dee15258-7b1c-4dec-884d-91c6f274d596.jpg)

Mp3tag:
![IMG_20221201_081410](https://user-images.githubusercontent.com/40667862/204990222-27381540-b1d9-499a-981a-ece69a6572f1.jpg)

**Comment by Hallo951** [comment]
Ha, I have found the error. It was probably the file names. They had the following format: "I.Live..mp3". I changed this to the following: "I live.mp3" and lo and behold, the download works.

Maybe you should add a rotine that checks the file names for consistency or something....

**Comment by advplyr** [comment]
I don't think this is an issue anymore on newer versions since I can download a file with that name but let me know if this is still an issue for you
