### ISSUE TITLE
Filter by Progress:Not Finished Broken

### ISSUE THREAD

**Issue by tknorris** [advplyr/audiobookshelf-app#451]
Sometime between server version 2.2.4 and 2.2.7 Filter by Progress:Not Finished is broken in the Android App. Before it worked normally, now when I filter by that option in the Android App, I get 0 results. The filter still works properly in the Web App.

#### Android Issue
Android version: 12
App Version: 0.9.59-beta
Device model: Samsung S21+
Stock or customized system: Stock

**Comment by hobesman** [comment]
Actually I'm not able to filter by _any_ of the progress options on the mobile app.

**Comment by advplyr** [comment]
This is from https://github.com/advplyr/audiobookshelf/commit/4541e9ddc384ad83e2dffdc1f87b7ccacc127027
and the intro of localization. I forgot this would impact the mobile app. Easy fix though at least

**Comment by tknorris** [comment]
Glad it's not just me. I'll wait for the fix ;-)

**Comment by advplyr** [comment]
Fixed in [v0.9.60-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.60-beta)
