### ISSUE TITLE
Hold down marker to jump in track timeline

### ISSUE THREAD

**Issue by ceramicwhite** [advplyr/audiobookshelf-app#457]
### Is your feature request related to a problem? Please describe.
Currently if you click anywhere on the tracks timeline you will automatically jump the that point. This is really frustrating as you lose your spot and it's easy to by accidently click somewhere on the track line by accident.

### Describe the solution you'd like
Jumping to a certain spot on the track timeline should only be possible if you hold down on the circle where you currently are and then while holding it down it allows you to "scrub" back in the track to where you want to play from.

### Describe alternatives you've considered
Make this an option

### Additional context
![signal-2022-12-07-120121_002](https://user-images.githubusercontent.com/7660824/206283807-c87a1a9c-65b9-4569-8977-eb89ea614b2f.jpeg)

**Comment by advplyr** [comment]
Updated in [v0.9.63-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.63-beta)
