### ISSUE TITLE
REQUEST: Navigating the audio file

### ISSUE THREAD

**Issue by FlamingoDaBird** [advplyr/audiobookshelf-app#46]
Hi
Suggestions to enhance the audio navigation, I'm comparing it to an app I use very often to see if it is of interest for others as well? :)

I'm used to be able to skip 10 sec back and forth as this app has as well. But then simply also skipping 1 full minute, sometimes when I've fallen asleep to the audiobook I need to find my last position I remember listening to. So it's easier to skip by minutes instead of 10 seconds intervals.
 
There's some neat features I like displayed in the below picture.
I'm able to see the entire book and the current chapter playing.  To avoid cluttering the display with all symbols they've cleverly added a function (the padlock on the top right side) the padlock toggles the add-on buttons, so when its enabled (red) like in the last picture (1) both the touch side scroll (2) is gone and all extra buttons (3).  Only the comfortable play button is visible so that no accidental mistakes can be made

What I would like is the ability to ff or rewind 1 minute  or being able to slide the "touch ball"  (2) sideways to ff or rewind within a chapter quickly.  I do know that there's a lot going on in the picture below, kind of cluttered, The audiobook name appears more than once, but I believe I made some weird choice in my settings :). But being able to see the total time and the current chapter is kind of neat.
Thank you.

![image](https://user-images.githubusercontent.com/47981216/143720627-deacf822-7bd9-4e72-98e5-1c72569b8fa1.png)![image](https://user-images.githubusercontent.com/47981216/143720461-d59936e7-6611-4829-bbab-66c589101d10.png)

**Comment by advplyr** [comment]
In `v0.9.34-beta` I added an option to change the main track bar as a chapter track. This is a first attempt at capturing these features you outlined here without interrupting the current design.

If you check the checkbox in the dropdown you will see the main track is the duration of the current chapter, and a smaller track is shown above with the full audiobook progress.

![image](https://user-images.githubusercontent.com/67830747/146087957-0f678fca-523a-440b-9a4b-ad9c5dc60a4d.png)

Let me know if this makes sense and if this is close to what you were looking for. I also fixed the chapter next/prev buttons, they weren't working correctly before.

**Comment by FlamingoDaBird** [comment]
yes this makes sense :) it's moving along the path I was looking for. The rest might be hard to implement or could be seen as to intrusive from a end user perspective. Hard to say.

Nice that you only need to enable that tick box once and not per audio book. 
Thank you.
