### ISSUE TITLE
Progress Bar Resets after Android Auto disconnect 

### ISSUE THREAD

**Issue by tboudreaux** [advplyr/audiobookshelf-app#462]
### Steps to reproduce

1. Start listening session of a book while connected to Android Auto (version 8.6)
2. Pause playback while connected to android auto (In my case this amounts to turning the car off most times)
3. Check the progress of the book in the app

N.B That this does not seem to happen every time. Very long listening sessions in a car (on the order of hours) are not affected. I keep all of my books as mp3s split by chapter and the problem seems to be contained to listening sessions which start and end in the same file.

### Expected behavior
- The progress bar in the app should reflect the time listened while connected to Android Auto

### Actual behavior
- The progress bar in the app is where it would have been before the listening session with android auto. However, when I click on play in the app the progress bar will jump forward to where one would expect it to be. However, if I reconnect the phone to Android Auto and click play on the head unit then progress picks up from the incorrect location (the location in the book before the original listening session)

### Environment data

Audiobookshelf Version: 2.2.8

- [x] Android App?

#### Android Issue
Android version: 12

Device model: Samsung Galaxy S21 Ultra

Stock or customized system: Stock

**Comment by advplyr** [comment]
Can you get more specific on the reproduction steps? I just tested this and it is working well for me but some variables were left to open ended.

Is this a downloaded book or are you streaming?
Do you have the app open on your device before you connect to Android Auto?
If you have the app open and you are listening in Android Auto do you see the progress bar changing in real time?



> * However, if I reconnect the phone to Android Auto and click play on the head unit then progress picks up from the incorrect location (the location in the book before the original listening session)

I'm not sure if I'm understanding this part right. Android Auto is going back to the start time when you first started listening in Android Auto? Are you able to reproduce this without the step of opening the app and pressing play? Listen in Android Auto for a bit then disconnect and reconnect form Android Auto.

**Comment by tboudreaux** [comment]
- The book is downloaded
- The app is open in the background.
- If the app is opened and I’m listening on android auto the progress bar updates in real time as it should.


And you are correct, sorry I should have been more clear there. If I listen in android auto it seems to “forget” the previous android auto listening session.  It’s frustrating to try and report as I can’t get any of it to happen super reliably. I probably run into the issue about 50 % of the time. Its also possible it’s some weird edge case behavior with my specific head unit.

**Comment by advplyr** [comment]
In the latest release `0.9.62-beta` we are saving the local playback sessions and syncing them differently. Can you try to reproduce this in the latest app and server?
