### ISSUE TITLE
[Bug]: Download In Android App Does Not Work

### ISSUE THREAD

**Issue by weswitt** [advplyr/audiobookshelf-app#463]
### Describe the issue

I cannot download books in the Android app. Using the browser the downloads work just fine.  In the Android app I click on the download button and it does nothing. The progress just stays at 0%.  This could certainly be something I did with the config but i don't see it. 

### Steps to reproduce the issue

1. Try to download a book

### Audiobookshelf version

2.2.5

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
What device are you using and what version of Android?

Have you tried a small book or podcast episodes incase it is just going very slow?

Initially the downloads will go into the downloads folder on your device, can you check that folder to see if they are in there.

**Comment by weswitt** [comment]
i'm using a pixel 6 pro running android 13. and i see nothing is the device's download folder.

**Comment by weswitt** [comment]
i just reproduced the problem on a pixel 3xl running android 12. same exact problem.  is there anyway to collect logs are other diagnostics on the phone to see what is wrong?

**Comment by weswitt** [comment]
what i do see eventually is that the download fails

![image](https://user-images.githubusercontent.com/15125944/206877836-db274916-d6c5-49c4-b5eb-8c165552f809.png)

**Comment by advplyr** [comment]
That's good to know that it is not working on another device. This makes me think it is something with your server.
Are you connecting to your server through a local ip address or how is your server setup?

**Comment by weswitt** [comment]
my server is setup according to the instructions. i can access the library and all functions EXCEPT download.  i am accessing ab via an external URL and i'm using SSL.  are  there any issues using SSL and downloads??

**Comment by advplyr** [comment]
It is possible. If you can try this using your local ip address that would be helpful to determine if this has to do with SSL

**Comment by weswitt** [comment]
OK that is the issue. i just disabled SSL and now downloads work. 

this is a pretty serious bug because it means that the website/service has to be run unsecure. i really don't like sites to be unsecure like this. can this be fixed??

**Comment by advplyr** [comment]
Many people including myself run our server with SSL without this issue. This is likely to do with your network or how you have setup your server.
This does not appear to be an issue with Abs. I recommend joining the discord or matrix server since users are there with all types of setups using SSL.

**Comment by weswitt** [comment]
my config is very straight forward. using an nginx web server with the following site config:

server
{
        listen 443 ssl;
        server_name ab.mydomain;

        access_log /var/log/nginx/audiobookshelf.access.log;
        error_log /var/log/nginx/audiobookshelf.error.log;

        ssl_certificate      /etc/nginx/ssl.crt/mydomain.crt;
        ssl_certificate_key  /etc/nginx/ssl.crt/mydomain.key;

        location / {
                     proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
                     proxy_set_header  X-Forwarded-Proto $scheme;
                     proxy_set_header  Host              $host;
                     proxy_set_header Upgrade            $http_upgrade;
                     proxy_set_header Connection         "upgrade";

                     proxy_http_version                  1.1;

                     proxy_pass                          http://127.0.0.1:13378;
                     proxy_redirect                      http:// https://;
                   }
}

**Comment by Dob4115** [comment]
@weswitt , I had a similar problem: I would tap the download icon and nothing would happen. No progress, no indication of tap, nothing. I realized that I had created multiple local download folders (one for each library). When I removed all but one, local download (of podcasts) worked fine.

@advplyr Should I create a new issue for this? (multiple local download folders keep user from downloading)

**Comment by advplyr** [comment]
@Dob4115 I just tested this by creating multiple local folders and downloaded audiobooks to each one. It works on Pixel 6 Android 12. There are a few issues with the download that I have seen that you may be running into but I don't think it has to do with multiple folders.

Feel free to join the discord or matrix server to discuss your particular issue.

I'm closing this because the original issue is not a problem with Abs as far as I know.

**Comment by Dob4115** [comment]
No problem. Pixel 4a, Android 13 here.

**Comment by p6002** [comment]
Same here. The android app is buggy. If it doesn't download just restart it a few times. But it should work automatically, in addition there is no automatic download from the server, you can only download manually.
