### ISSUE TITLE
Playback progress display not updating until relaunching Android app

### ISSUE THREAD

**Issue by Skitals** [advplyr/audiobookshelf-app#464]
### Steps to reproduce

1. Listen to audio via bluetooth with app in the background
2. Fishing listening session with app still in background
3. Open the app and the playback progress does not reflect progress while app was in the background
4. Force close and relaunch the app. Playback progress is now accurate.

### Expected behaviour
- Playback progress displayed should update without having to relaunch the app

### Actual behaviour
- Playback progress that ends when the app is not visible are not displayed until the app is force closed and relaunched

### Environment data

Audiobookshelf Version:

- [ 0.9.59-beta ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13, December 5, 2022 security update

Device model: Pixel 7 Pro

Stock or customized system: Stock 

#### Thoughts
There are a number of bug reports specific to Android Auto. The bug here is not that playback is not being tracked, it's simply not being refreshed in the UI if the session ends while the app is not visible. In my case I am starting playback directly from the app, whether listening directly over bluetooth or while using Android Auto. If I finished a 30 minute podcast, when I reopen the app it might display only the first 5 minutes were played. If I force close the app and relaunch it now shows the entire episode was played.

**Comment by advplyr** [comment]
I'm not sure bluetooth matters here unless you are using another interface to start the playback.

Is this reproducible for you with the following:
1. Start streaming some media from the app
2. Turn off phone screen and let play for a bit
3. Turn screen back on and check app player time

**Comment by Skitals** [comment]
I can check later, but I think specifically the playback session needs to
end while the app is in the background. That could be either through the
book/podcast ending, or stopping playback from the Bluetooth player. It
happens to me constantly because I open the app on my phone and begin
playing an episode. I lock my phone and don't touch it again. My playback
session ends either when I turn off my car (Bluetooth ends), or stop
playback from my car head unit. If I repopen the app while playback is
ongoing, it immediately shows the correct playback position. If playback
session ends while the app is in the background, it does not update
progress until the app is restarted.

**Comment by Skitals** [comment]
> 

Okay, I just did some testing and couldn't reproduce it without bluetooth. 

Then on bluetooth (connected to my car) I reproduced it on the first try. From the app I resumed playback with 34 minutes remaining on a podcast. I navigated away from the app so it was in the background. I actually paused/resumed a few times from my infotainment screen, unlocked and used the phone a few times while it played in the background over bluetooth. When the episode ended I unlocked my phone and opened the app and this is what it looks like. The player on the bottom of the screen shows playback was complete, but you can see in the episode list it still shows 34 minutes remaining. I can navigate away from that screen and come back and it still shows 34 minutes remaining. I need to fully close the app (swipe the app away from the multitasking screen), relaunch the app and it properly shows the episode was completed.

![Screenshot_20221210-172832](https://user-images.githubusercontent.com/11912474/206877766-0473d64d-1cd8-4972-936f-076b66304532.png)

**Comment by advplyr** [comment]
I'm on Android 12 with a Pixel 6 and unable to reproduce this.
Maybe something about Android 13 but seems unlikely. As of now I have no idea.

**Comment by Skitals** [comment]
I will do more testing without Bluetooth. I did those tests with shorter play sessions. In these real world scenarios it always involves longer playback sessions which I'm always doing over Android Auto or straight Bluetooth. I think the screenshot I posted proves this isn't just in my head, you can see the mini player on the bottom and the episode list are out of sync with each other. I open the app and start playing the next episode, and I end up with a long list of episodes that show they were partially played until I force close the app.

**Comment by advplyr** [comment]
Yeah I can see there is an issue here but will need to reproduce it somehow.

**Comment by hobesman** [comment]
I see this a lot with books when I finish them. They show as orange with time remaining still. They even drop to the Listen again list but show orange. Then eventually it updates. I haven't noticed when.

I listen almost exclusively on Bluetooth headphones in case that does turn out to be relevant.

**Comment by advplyr** [comment]
Can you check this again on the latest app `0.9.62-beta` and server `2.2.15`?

**Comment by advplyr** [comment]
There have been strange issues happening for Android 12/13 with some device battery optimization settings.
For anyone coming across this try going into the app settings and disabling battery optimization.

**Comment by JReming85** [comment]
Same issue with my setup on Android 13.

The podcast episode ends, but it still shows 20-30% in the list view.  It also breaks Play Next as it will either do nothing, or replay the same episode from the beginning.

I will have to manually start the next episode causing me to generally have 3-5 semi finished (but really finished) episodes in the list view as the mark as complete is not clearing them all the time.
