### ISSUE TITLE
[IOS & Android] Orientation lock toggle does not work when clicking directly on the button.

### ISSUE THREAD

**Issue by lerndmina** [advplyr/audiobookshelf-app#465]
### Steps to reproduce

1. Open ABS App on the latest version.
2. Open the settings.
3. Click the switch for lock orientation. 

### Expected behaviour
- the button should work.
### Actual behaviour
- The button glitches and switches on then off immediately 

### Environment data

Audiobookshelf Version:

- [X] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 0.9.60-beta

iPhone model: 14 Pro

Below is a video showing me clicking the switch and the switch glitching. But when I click on the text for the setting it toggles correctly. 
https://user-images.githubusercontent.com/10632157/206990116-d92dc26d-e49d-4796-a8ef-27d19dfdd74c.MOV

**Comment by lerndmina** [comment]
Here is a YouTube video as I'm not sure the video uploaded to GitHub properly

https://youtube.com/shorts/iT5TYFCwtZc

**Comment by hobesman** [comment]
Seeing the same behavior on Android 10.

**Comment by advplyr** [comment]
Fixed in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
