### ISSUE TITLE
Items misaligned with labels in book detail page

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf-app#467]
### Steps to reproduce

1. Open book detail page
2. Look at publish year, narrators and genres
3. Secretly cringe a little

### Expected behaviour
- Things should be lined up

### Actual behaviour
- They aren't

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 10

Device model: Galaxy S9+

Stock or customized system: Stock 

#### iOS Issue
iOS Version:

iPhone model:

![Screenshot_20221213-093145_audiobookshelf](https://user-images.githubusercontent.com/29721765/207404665-9e9db71d-0aa7-4d86-ac9d-a06163907b39.jpg)

![Screenshot_20221213-093124_audiobookshelf](https://user-images.githubusercontent.com/29721765/207404853-2a0bd8f0-a103-4b2c-acc0-c04b030c553e.jpg)

**Comment by advplyr** [comment]
This is fixed in #499 for next release

**Comment by advplyr** [comment]
Updated in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
