### ISSUE TITLE
Add a "default play speed" to playback settings. 

### ISSUE THREAD

**Issue by Roskott** [advplyr/audiobookshelf-app#468]
When switching books or opening a new book, one has to change the playback speed each time, this can be frustrating. A simple checkbox on the speed selection to set default, or a selection box in the general player settings would work wonderfully.

**Comment by advplyr** [comment]
On Android your playback speed is saved. Are you using Android or iOS?

**Comment by Roskott** [comment]
I'm on Android 13 on a Google Pixel 7, my experience is it not preserving the playback speed. I suspect it may have to do with switching audio source, I will try to make better observations to see when this specifically happens and report back.

Just as some more info, I do use Android Auto and 2 separate wireless headphone devices on a regular basis.

**Comment by advplyr** [comment]
I'll have to test Android Auto again but in the meantime you could set the playback speed for a book, completely close the app out, then open again and see if it persisted.

**Comment by Roskott** [comment]
Yep, that's all it took. Closing and reopenong app reset playspeed to 0.

**Comment by advplyr** [comment]
What version of the mobile app and what version of the server are you using?

By 0 I assume you mean 1.

**Comment by Roskott** [comment]
Yes, sorry, play speed one.

Current version reports 0.960-beta

**Comment by advplyr** [comment]
And the version of your server? Are you connected to the server when you are doing this test?

**Comment by Roskott** [comment]
I'll check server version when I get home, but it should be the Truecharts Truenas Scale latest train. Normally I download to device rather than streaming.

**Comment by Roskott** [comment]
Sorry, totally forgot to get that.

Server version is V2.2.8

**Comment by advplyr** [comment]
This should be working in the latest versions. There is a bug #532 but not always reproducible

**Comment by raviwarrier** [comment]
I couldn't find the default playback speed setting in the settings. Using 0.9.63-beta. Am I missing something?
