### ISSUE TITLE
Arrange books vertiycaly when the player is offline

### ISSUE THREAD

**Issue by Blindie92** [advplyr/audiobookshelf-app#469]
currently, when the app is offline and only shows downloaded books, it shows one vertiycaly scrollable row of books, it would be nice if this can be switched to a vertiycaly grid like in online mode.

![Screenshot_20221214_011538_audiobookshelf](https://user-images.githubusercontent.com/94938390/207473801-b471ab17-f220-4977-858e-24ba1ae7eddd.jpg)
Offline mode

**Comment by advplyr** [comment]
Duplicate of #542
