### ISSUE TITLE
Android Auto and Android 13 Audio widget show incorrect progress  

### ISSUE THREAD

**Issue by dacmcbibs** [advplyr/audiobookshelf-app#470]
### Steps to reproduce

1. Start playing file and look at widget or android auto display

### Expected behaviour
- Progress should be correctly displayed 

### Actual behaviour
- Progress bar barely moves from the left

### Environment data

Audiobookshelf Version:

- [ ] Android App version 0.9.60

#### Android Issue
Android version: 13

Device model: pixel 6 pro 

Stock or customized system: Stock

This one may be audio file specific, but I thought I would share since the experience is inconsistent:
- Viewing book in ABS  - Book shows  length 23 hrs 13 minutes and 59% - 9 hours 26 minutes remaining
- Viewing in the ABS app player - book shows length of 19 hours 40 minutes ~70% complete - 13 hours 46 minutes complete  - 5 hours 54 minutes remaining
- Viewing the widget the dot is all the way to the far left
- viewing in android auto in the Download book list the status bar shows to be a little more than 50%
- Viewing in the android auto player the bar has barely progressed on the left, and the book shows 13 hours 46 minutes complete out of a total 514 hours and 5 minutes 

based on the chapters the book should be ~23 hours 13 minutes

**Comment by advplyr** [comment]
I believe this is because the Android Auto progress bar is not being updated in real-time. Just adding this note for when it gets worked on.

**Comment by advplyr** [comment]
I don't think this had to do with what I originally thought. This may be fixed now in 0.9.62-beta if you can test again

**Comment by dacmcbibs** [comment]
I think it's more of a file specific issue... I just tried 2 books , one of them displays the correct progress ( as long as my playback speed is set to 1). The other book shows the incorrect progress with a total time of over 500 hours.  Oddly the time in the app itself looks fine, Android auto is weird.  If I can catch anything to debug let me know , I can easily recreate with this file, or if we want to just close this out as a file related issue that's cool too

**Comment by advplyr** [comment]
If it's a single file then we can close this but if you decide to dig into it more let me know.
