### ISSUE TITLE
Configurable Haptic Feedback

### ISSUE THREAD

**Issue by benonymity** [advplyr/audiobookshelf-app#472]
### Is your feature request related to a problem? Please describe.
Different devices and operating systems have different levels of haptic feedback.

### Describe the solution you'd like
User-configurable haptic feedback intensity, or an option to disable it entirely.

**Comment by adiso06** [comment]
Bump - use the app at night and it's a bit disturbing to have haptic feedback for every action :)

**Comment by advplyr** [comment]
Updated in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
