### ISSUE TITLE
Inconsistent cover sizes

### ISSUE THREAD

**Issue by kaldigo** [advplyr/audiobookshelf-app#474]
### Steps to reproduce

- Minimised Player
- List view on library
- Everywhere when app offline

### Expected behaviour
- The book covers to match the server setting.

### Actual behaviour
- I am getting a mixture of visual bugs that seem to be related to square covers
![Screenshot_20221214_183714_audiobookshelf](https://user-images.githubusercontent.com/6437691/207685166-10eb16fb-4de2-43a4-a964-dfd96cafbc78.jpg)
![Screenshot_20221214_183741_audiobookshelf](https://user-images.githubusercontent.com/6437691/207685171-aaa54968-a49c-48e6-a30a-9578de792b4f.jpg)

### Environment data

Audiobookshelf Version:

- [ X ] Android App?

#### Android Issue
Android version:
Android 12

Device model:
Samsung Galaxy Fold 4

Stock or customized system:
Stock

**Comment by advplyr** [comment]
Fixed in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
