### ISSUE TITLE
Excessive Battery Usage

### ISSUE THREAD

**Issue by benonymity** [advplyr/audiobookshelf-app#476]
The iOS app somehow manages to use more power when playing audiobooks in the background than other apps do with the screen on. Some of this is probably due to background sync and progress saving, but maybe if the device is in low power mode the frequency of server syncing could be significantly reduced to preserve battery life?
![image](https://user-images.githubusercontent.com/62854267/208480495-6f6bb077-0e48-4f28-b1ea-851ed7134099.jpeg)

### Environment data

Audiobookshelf Version: 2.2.10

#### iOS Issue
iOS Version: 16.2

iPhone model: iPhone SE (2020)

**Comment by advplyr** [comment]
Server update v2.2.12 may help with this. The sync API endpoint was returning the entire library item payload each sync. Now it is returning nothing.
