### ISSUE TITLE
IOS Sleep Timer stops after player interaction

### ISSUE THREAD

**Issue by TheMaxik** [advplyr/audiobookshelf-app#477]
Any Interaction after sleep timer is set, cancels the sleep timer

### Steps to reproduce

1. Start Listening
2. Set Sleeptimer
3. Interact with the player

### Expected behaviour
- The sleep timer should continue to run

### Actual behaviour
- Timer gets disabled

Audiobookshelf Version:

- [ ] Android App?
- [X] iOS App?

#### iOS Issue
iOS Version: 16.2
App-Version: 0.9.60-beta

If this is actually wanted behavior, then i would suggest a option to disable this :)

**Comment by benonymity** [comment]
Can reproduce, will look for a fix!

**Comment by WillGunn** [comment]
For me (iOS), this only occurs while pausing and unpausing.  Easy reproduction, have the file paused, set a new timer, hit play, the timer disappears

**Comment by advplyr** [comment]
Fixed in [v0.9.67-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.67-beta)
