### ISSUE TITLE
BUG: Libraries - search function?

### ISSUE THREAD

**Issue by FlamingoDaBird** [advplyr/audiobookshelf-app#48]
Hi
First, I'm not entirely sure  on how the Libraries are meant to work?

I thought "MAIN" was the 'parent' and included everything. It seems like so when it shows the amount of objects (here it is called audiobooks, even if it contains ebooks) My "MAIN" library clearly states both other libraries total amount of objects.

When I select my "audiobook" library containing only audiobooks, it still shows searches from the the other library I've created: "ebooks" (I have both audiobook and the ebook for the same title)

All libraries have their own set of ongoing audiobooks/ebooks, that's fine I guess, just noticed it :)

On the other hand, the server application is only directed to one folder where all media should be located.
Mine is pointing to \media\

![image](https://user-images.githubusercontent.com/47981216/143886387-51aa686d-d38e-4501-8d05-5b89da16cecc.png)

Here's my filestructure
![image](https://user-images.githubusercontent.com/47981216/143886120-b657086e-7b9e-47e1-8fe1-a41216871521.png)

Thank you.

**Comment by advplyr** [comment]
Libraries should all be mapped to different folders. What folders did you select for each library in config -> libraries?

**Comment by advplyr** [comment]
If you meant searches from the mobile app, then yeah the mobile app still needs to be updated to search only the selected library.

**Comment by FlamingoDaBird** [comment]
Right! Didn't try the web-application, that one works fine. The android app is the one with the issue. 
Ok so its just a matter of implementing then.
All in due time :)
Thanks. I guess we can close this then if its already within your scope?
