### ISSUE TITLE
Can’t dismiss playback position

### ISSUE THREAD

**Issue by genebean** [advplyr/audiobookshelf-app#482]
### Steps to reproduce

1. Download book (m4b in my case)
2. Play partially 
3. Go away 
4. Click to discard current position so that it will start again 
5. Watch confirmation pop up 
6. Observe that nothing has actually changed 

### Expected behaviour

I expect the book to start over 

### Actual behaviour

The book plays from the saved position 

### Environment data

Audiobookshelf Version: v2.2.11

- iOS App 0.9.60-beta

#### iOS Issue
iOS Version: 16.1.1

iPhone model: iPhone 12

**Comment by advplyr** [comment]
I've just tested this on the latest server `v2.2.15` and latest iOS app `0.9.62-beta`. It is working well, I think this bug was fixed but let me know if you still have the problem and we can re-open.
