### ISSUE TITLE
Play Button in Android App broken?

### ISSUE THREAD

**Issue by tknorris** [advplyr/audiobookshelf-app#487]
I've noticed in the more recent server versions that the "Play" button in the book details page of the Android App doesn't seem to be working properly. Is this another problem related to the internationalization of fields? I *think* it used to switch to "Playing..." when a book was played, but now it just always says "Play". 

Server version: docker 2.2.11
Android app version: 0.9.60-beta

It also seems like the android app more recently is not always resuming from the correct resume point. It seems like sometimes when I restart playback from the android app, the last listening session has been "lost". Perhaps related?

**Comment by advplyr** [comment]
Fixed in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
