### ISSUE TITLE
Bookmark/notes button is sticky.

### ISSUE THREAD

**Issue by Travillion** [advplyr/audiobookshelf-app#488]
### Steps to reproduce

1. When playing a book, press the bookmark/note button to add a bookmark.
2. After the bookmark is added, the hollow icon is now filled in, looking like it can't be pressed again (although it can).
3.

### Expected behaviour
- Tell us what should happen
To me, it seems like the icon either shouldn't change, or should only change temporarily to indicate it can't be pressed again.
### Actual behaviour
- Tell us what happens
Once you add the first bookmark, the icon remains in it's changed, "active" state.
### Environment data

Audiobookshelf Version:

- [ X ] Android App 0.9.60-beta
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: Google Pixel 4a

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
When the bookmark icon is filled in it means that the book has bookmarks. If it is hollow it means the book has no bookmarks.

The layout has changed a bit in this screenshot but you can clearly see the difference between an icon that is disabled and the filled in bookmark icon.

![image](https://user-images.githubusercontent.com/67830747/211940438-5054b1f6-7b3c-4137-96a9-5fc89911f3b0.png)
