### ISSUE TITLE
Feature Request: Cover size/aspect options (audiobooks vs ebooks)

### ISSUE THREAD

**Issue by FlamingoDaBird** [advplyr/audiobookshelf-app#49]
Hi
Will there be any possibility to choose your cover size aspect?
Most audiobooks seem to have a very square sized aspect while ebooks tends to have the rectangular approach.
Since almost all audiobooks are inherited from audible(?) it seems like they have that format...

Every audiobook I've scraped information from (about 600-ish) tends to have that format.

Is there any possibility you could implement a choice for the different libraries we might add? 

Thank you.

**Comment by advplyr** [comment]
This is becoming highly requested so I think I will make this a server setting.
There is an issue open for this on the server github, so I will post updates for this on that issue. https://github.com/advplyr/audiobookshelf/issues/210
