### ISSUE TITLE
Silly request - would it be possible to make the cover larger ?

### ISSUE THREAD

**Issue by filviu** [advplyr/audiobookshelf-app#491]
### Is your feature request related to a problem? Please describe.
I would like to have the empty space around the cover used by it.

### Describe the solution you'd like
Make the cover larger to ocupy what is now empty space

### Describe alternatives you've considered
n/a

### Additional context
I added screenshots of audiobookshelf, a beautiful mockup using my awesome paint skills 😄  and an example of pocket casts making use of a big cover to show what I mean.

P.S. thank you for the absolute awesome app !

![audiobookshelf_now](https://user-images.githubusercontent.com/2470335/210732625-a71fc84e-9570-48f1-aeae-6c45aea833ca.jpg)
![audiobookshelf_proposal](https://user-images.githubusercontent.com/2470335/210732623-079cc3e3-3b14-426a-8d82-3392002be5ab.jpg)
![Pocket Casts](https://user-images.githubusercontent.com/2470335/210732618-4148d64a-8a2d-4818-919f-6a780a2fe671.jpg)

**Comment by lkiesow** [comment]
I don't think it's a silly request and I like the idea.

I would like to see your suggestions. I would also use the free space to give the control elements a bit more room. In particular when seeking right below the play button, I have accidentally hit that button in the past. Here is a mockup based on your ideas with a bit more space for the controls and a slightly larger margin at the endge of the phone:

<img src="https://user-images.githubusercontent.com/1008395/210885606-98ccc1d5-e595-4c25-88b3-af34b9f71ae8.jpg" width="300px" />

We could even offer the option to not have the overall progress bar. Something like this:

<img src="https://user-images.githubusercontent.com/1008395/210885980-5c73e4d7-f7ca-416c-b92a-852ab21b0719.jpg" width="300px" />

**Comment by advplyr** [comment]
I agree with these and plan on doing a few things with the audio player in addition to increasing the cover size.
One of them is moving the progress track so it isn't on the bottom. https://github.com/advplyr/audiobookshelf-app/issues/408
Another one I'm thinking is forcing you to grab the cursor if you want to seek, instead of allowing you to press anywhere on the track.

**Comment by advplyr** [comment]
Covers much larger in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
