### ISSUE TITLE
Special Characters in Filename Issues

### ISSUE THREAD

**Issue by fidoriel** [advplyr/audiobookshelf-app#492]
### Steps to reproduce

1. put a file like `207 - Outtake Köln 2- „Und da sind sie- Die Drei“.flac` in a dir
2. play/download the Audiobook

### Expected behaviour
- Play Audiobook
- Download Audiobook

### Actual behaviour
- Audiobook throws Playback error
- Download succeded but only some kb of non audio data is loaded

### Environment data

Audiobookshelf Version:

- [?] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version:

iPhone model:
13 Mini

**Comment by advplyr** [comment]
I just tested this and was unable to reproduce in the latest app `0.9.62-beta` and server `2.2.15`.

I believe this was fixed and had to do with the CD subfolder I see in your title change.

Let me know if this is still an issue though.
