### ISSUE TITLE
Enhancement: Downloader Place Files Into Subfolder Named Per Book Title and/or Subtitle

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf-app#5]
Currently the downloads go into the Audiobooks folder in my phone, which I guess is just a funny coincidence that I already had it there to manually download to with X-plore. But most (if not all) audiobook players need the files to be separated into subfolders, otherwise the player app will shove them all together into one "book".

Can the downloader in the mobile app please create a subfolder with the book name and/or subtitle for the files to be placed into?  Perhaps the app can internally link the download path to the server ID for the book?

**Comment by advplyr** [comment]
`v0.9.0-beta` is live now with ability to select your download location. It saves audiobooks in directories using the audiobook title, no more internal id as filename.

It would be best if you delete your downloaded audiobooks from the previous version and re-download with this version, since the system changed completely. The update won't pick up those stray files.

**Comment by Budlyte** [comment]
Perfect, as always.
This update also fixed the app not being able to delete the created subfolder. 

This will allow the use of other player apps, no offense they've just been around for years and focus on doing that one thing. Your app is still a fabulous companion to a must have server and this update really helps it all shine brighter.

**Comment by advplyr** [comment]
I think one big improvement to the app interface will be showing the books in a list rather than the bookshelf. The bookshelf looks nice and should remain an available view to use, but it is not as practical on mobile. These small improvements will help the app compete with other players.

**Comment by Budlyte** [comment]
That sounds good. It will reduce caching on mobile and load faster over the web.
