### ISSUE TITLE
[Bug]: Can't add podcast via Android app, buttons hidden.

### ISSUE THREAD

**Issue by revilo951** [advplyr/audiobookshelf-app#502]
### Steps to reproduce

1. Open app
2. Have existing book/podcast playing/paused
3. Search for podcast
4. Select podcast
5. ??? No add button visible

![Screenshot_20230111_083652_audiobookshelf](https://user-images.githubusercontent.com/13210587/211668609-52e52d61-1642-4eb7-a67f-1ca8df1b151d.jpg)
### Expected behaviour

- Should be buttons

### Actual behaviour
- There are no buttons visible

### Environment data

Audiobookshelf Version: 2.2.12

- [0.9.60-beta ] Android App?
- [ ] iOS App?

Device model: Samsung Galaxy S20 Plus

Stock or customized system: Stock

**Comment by hobesman** [comment]
Not to say this isn't a bug, but did you try closing the player at the bottom and see if the buttons are behind it?

**Comment by revilo951** [comment]
> Not to say this isn't a bug, but did you try closing the player at the bottom and see if the buttons are behind it?

I thought about that, but couldn't see a way to close the player. If you can enlighten me, I'll give it a shot.

**Comment by advplyr** [comment]
Fixed in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
