### ISSUE TITLE
When Siri's notification announcement stops, Audiobookshelf resumes from a point further in the past than where Siri interrupted

### ISSUE THREAD

**Issue by Piste** [advplyr/audiobookshelf-app#503]
### Steps to reproduce

1. Start streaming a book (haven't tested when book is downloaded)
2. Receive a notification on iOS that Siri announces
3. Siri halts playback and makes the announcement
4. When Siri stops and playback resumes, the playback starts from a past milestones, not where Siri halted the playback. It is possible that the milestone is where playback was started for this session.

### Expected behaviour
- Playback should resume from the point where Siri paused playback

### Environment data

Audiobookshelf Version: 2.2.12 (docker)

- [ ] Android App?
- [x] iOS App? 

#### iOS Issue
iOS Version: 0.9.60-beta

iPhone model: 14 Pro

**Comment by Piste** [comment]
This could be related to #191 but my playback resumed, just not in the right spot.

**Comment by advplyr** [comment]
How far back does it jump?
There is some logic that automatically rewinds a bit after a pause. We can tweak that logic but I want to make sure that is what you are experiencing first.

**Comment by Piste** [comment]
The one time this happened to me, it jumped back to the point I had hit "play".
However, I received a Siri announcement recently and the playback pause and resume handled it perfectly.
I'll keep an hear out. This might have been a one-off.

**Comment by Piste** [comment]
This has been happening more frequently. For example, a multiparty Signal (messaging) channel got busy and people were replying to each other while I was listening to a book and the playback would always resume to that same point in the past after Siri was done announcing. That resume point was maybe 15-30 seconds in the past(?)

**Comment by benonymity** [comment]
Are you still experiencing this issue on 0.9.61-beta? While the play/pause takes a second or so, it resumes at the proper place.

**Comment by advplyr** [comment]
Thanks, we can re-open this if it continues to be an issue on the latest release.
