### ISSUE TITLE
Cannot start playback if trackers under multi-disc folder structure

### ISSUE THREAD

**Issue by rosystain** [advplyr/audiobookshelf-app#508]
### Steps to reproduce

1. Put some audio file into a folder named with "CD01"
2. Start playback with iOS App

### Actual behaviour
- Nothing will be played and the play button turns into a circle then spins endlessly

### Environment data

Audiobookshelf Version:

- iOS App

#### iOS Issue
iOS Version:
16.1.1 (iPhone 12 Mini)
16.3 (iPad Pro 2021)

**Comment by B0rax** [comment]
Hi, I have the same issue (see #483)

**Comment by advplyr** [comment]
Duplicate of #483
