### ISSUE TITLE
[Bug] Progress made in app is not saved to server

### ISSUE THREAD

**Issue by juriroemer** [advplyr/audiobookshelf-app#51]
E.g. 
- When I listen to an audiobook in the app and then continue it in the web version the progress is still the same as before I listened to it in the app.
- When I finish something in the app it isn't marked as read either.
- When I make progress in app, close the app and continue in app later, the progress will also be gone.

There seems to be a problem in the communication from the app back to the server.
I haven't noticed this before, so i think it is a new bug introduced in a fairly recent version.

App version: v0.9.31-beta
Server version: v1.6.30

**Comment by FlamingoDaBird** [comment]
@juriroemer 

Addon to your issues and another potential bug in the APP calculating 100% progress

Tried out your issues, I have the same version on my server and app.
Seems like there's some sort of "refresh" issue in the web server and app

- I was able to sync between app and server.
At first my firefox refused to play, disabled adblocker, heh :) , still not playing. Used a chrome based browser, could play and sync worked, after a while firefox was working fine again. But not always did it display the correct time from app <> server. 
But a page refresh on the server web site did the trick. So it kind of works, should be more refreshes entering an audiobook perhaps  (both web and app)

- marked as read in the app and browser as well. My audiobook seems to have synced.
firefox, and also placed into the shelf, READ AGAIN:
![image](https://user-images.githubusercontent.com/47981216/144248668-9095b366-91fe-4d1f-99ac-8e1ff2da21a9.png)
![image](https://user-images.githubusercontent.com/47981216/144248828-9cdc64dd-3601-4ba9-b0f9-62fb89a17c5c.png)

In my APP it is also placed into the READ AGAIN shelf, with a full green bar as the web picture above.
But selecting the audiobook itself shows a YELLOW bar and also progress 100% but -1 min remaining

But before displaying completed, I completed it on the APP some fast forw then listnening to the last minute or less to reach completion, it then displayed some time left like 17 minutes and the percentage left... weird.. 
When I exited the APP and "killed" the APP running in the background, it got a new refresh and then displayed correctly 100%

here's the pic showing 1% left after APP-restart
![image](https://user-images.githubusercontent.com/47981216/144249659-b6dda36c-76c3-4be0-9c15-096d7a5e1600.png)


Could be a bug when completion occurs or some bug connected to fast forwarding to the end... ?

**Comment by zombiehoffa** [comment]
Are you guys still seeing this? This problem has pretty much gone away for me on the latest app release.

**Comment by feerlessleadr** [comment]
Fingers crossed, but I too am not really seeing this behavior anymore after the latest updates to the app.

**Comment by advplyr** [comment]
This should be fixed with latest mobile app and server
