### ISSUE TITLE
Download of book with a lot of mp3s not working 

### ISSUE THREAD

**Issue by stiefelus** [advplyr/audiobookshelf-app#515]
Trying to download a book consisting of a huge number of mp3s (over 500 in my Case) is actually killing the Download function entirely right now. The phones download notifications go crazy, but the (Android) app itself shuts down and never starts showing that a download is in Progress after reopening. In fact only about 370 of the 500+ parts really get downloaded in the end and never really arive in the destination folder nor is the finished but incomplete download linked anywhere. 
The only way to then remove this partial Download is to go into the apps preferences, deleting all app data. 
Would bei great If there could be an fix for this one. 

Thank you!

**Comment by gh0sti** [comment]
Would it make sense at this point to use the convert to m4b which merges all the tracks into one file?

**Comment by advplyr** [comment]
I'm working on a new download manager that should hopefully handle this. It is a big rewrite so I can't give an ETA.

**Comment by stiefelus** [comment]
> Would it make sense at this point to use the convert to m4b which merges all the tracks into one file?

Tried this also, strangely did not finish the Job. There was a correct m4b file consisting of all the content, but the book was now displayed as empty in the shelf. Rescan of the folder did not solve the issue. 
In this case had to remove and then re-deploy the folder and it then was fine. 
Maybe I try this again, cant definetly say If there was a shutdown of the Server at the end of this Task which would explain the result on this end

**Comment by stiefelus** [comment]
> I'm working on a new download manager that should hopefully handle this. It is a big rewrite so I can't give an ETA.

Thank you! Great Work by the way. Love audiobookshelf so far despite some little hickups!

**Comment by gh0sti** [comment]
> > Would it make sense at this point to use the convert to m4b which merges all the tracks into one file?
> 
> Tried this also, strangely did not finish the Job. There was a correct m4b file consisting of all the content, but the book was now displayed as empty in the shelf. Rescan of the folder did not solve the issue. In this case had to remove and then re-deploy the folder and it then was fine. Maybe I try this again, cant definetly say If there was a shutdown of the Server at the end of this Task which would explain the result on this end

There's a windows/mac app called Audiobookconverter that is a local app that can merge all the tracks into a .m4b

I have used this to convert multi-track mp3 books into one file. https://github.com/yermak/AudioBookConverter

**Comment by advplyr** [comment]
Downloader has been re-done. I've tested with hundreds of files and it is working well. Also, it will only download 1 audio file at a time so there will be only 1 notification. The notification will automatically go away once the download is finished.

A currently downloading files page is added by pressing the download icon in the app bar.

**Comment by advplyr** [comment]
This should be fixed now in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta) but let me know how it goes.

**Comment by stiefelus** [comment]
@advplyr The new release is a great improvement in terms of reliability! Thanks for that. In a perfect scenario I would like to have the option of activating simultaneous downloads of 3 mp3s or something similar. This would increase the download speed a bit, which is much slower with only one simultaneous mp3 download.

**Comment by ooii** [comment]
Has this been implemented? I'm on the iOS version and it's still downloading all the files at the same time.
Also, downloaded percentage of files may decrease a lot, like from 70 to 9.
