### ISSUE TITLE
Playback stopping intermittently

### ISSUE THREAD

**Issue by NAL100** [advplyr/audiobookshelf-app#516]
### Steps to reproduce

1. Play audiobook on iOS (press green play button)
2. Wait, or minimize app and wait

### Expected behaviour

Play should happen continuously (no sleep timer is set).

### Actual behaviour

Play will either stop after a few seconds in which case you need to re-start playback and then it will play for a while, or it will stop randomly, around 10-15 minutes in.

### Environment data

Audiobookshelf Version: 0.9.60-beta

- [ X ] iOS App?

#### iOS Issue
iOS Version: 16.1.1

iPhone model: iPhone 8

**Comment by benonymity** [comment]
Should be fixed in 0.9.61-beta, are you still experiencing this issue?

**Comment by NAL100** [comment]
> Should be fixed in 0.9.61-beta, are you still experiencing this issue?

It was happening intermittently but I can't replicate it, so closing this issue. Will repost if it reoccurs.
