### ISSUE TITLE
Bug?: Android  soft key "back"  ALWAYS exits application

### ISSUE THREAD

**Issue by FlamingoDaBird** [advplyr/audiobookshelf-app#52]
Hi.

Seems like the android back key exits the application. I'm so used that the back soft key on android always gets you only one step back in the application, not exiting. Several apps also asks if EXIT is desired...

For example, a audiobook/ebook search gives me some results, I then want to go back quickly I press the back key, which immediately
exits the app.

Not sure if it is by design or a bug/ unintentional?  But I find it very distracting :)
Not sure if this is a personal problem or if others have the same issue,

Thank you.

**Comment by advplyr** [comment]
This is fixed in `0.9.34-beta`

**Comment by FlamingoDaBird** [comment]
Nice! tried it works fine. The back button takes you back to the HOME tab.

The only step it is not return back from is when you have the audio book playing in full screen. It then asks you if you want to exit the app, it doesn't return to the HOME tab, not sure if it is intentional or seen as a feature to be able to exit from there?

![image](https://user-images.githubusercontent.com/47981216/146215813-9c64cc75-7a7e-423d-bafb-83fa7126298e.png)

thnx

**Comment by advplyr** [comment]
The fullscreen audio player is not a page that is why. It is more of an overlay on the current page.
