### ISSUE TITLE
[iOS] Forward/Backward controls on BT headphone not working

### ISSUE THREAD

**Issue by gilgwath** [advplyr/audiobookshelf-app#521]
I'm not sure whether this is a bug, or just not implemented yet. When I use the forward/backward functionality on my BT headphones, the playback does not skip forwards/backards. If I use the buttons on my Apple Watch it works fine. 

It might be an issue specific to the Sony WH-1000X M3 but I doubt that, since the backward/forward functionality via the BT headphones works fine in all other apps.

Thanks for the amazing work!

### Steps to reproduce

1. Connect BT headphones
2. Start listening to an Audiobook
3. Use backward/forward controls

### Expected behaviour
- The playback skips forward or backwards

### Actual behaviour
- Nothing happens

### Environment data

Audiobookshelf Version: Server: 2.2.8, iOS App: 0.9.60-beta 

- [ ] Android App?
- [ x ] iOS App?

#### iOS Issue
iOS Version: 16.2

iPhone model: 12 Pro

**Comment by blampe** [comment]
@gilgwath when you use these controls in the Music app do they skip to the next track? We might have the same issue, and I've suggested a fix here https://github.com/advplyr/audiobookshelf-app/pull/528

**Comment by mym0T** [comment]
This may have been fixed in version 0.9.61

I was experiencing the same issue with version 0.9.60 on iOS using AirPod Pros, but it is working correctly for me now in version 0.9.61

**Comment by advplyr** [comment]
This was fixed in v0.9.61. Didn't see this issue.
