### ISSUE TITLE
Android App Unknown Error when Connecting via Reverse Proxy

### ISSUE THREAD

**Issue by hevel86** [advplyr/audiobookshelf-app#522]
### Steps to reproduce

1. Enter URL into app: https://audiobookshelf.example.com
2. Enter credentials
3. See "Unknown Error"
4.  The web URL works via regular browser

### Expected behaviour
- Login and see the library

### Actual behaviour
- Unknown error is shown

### Environment data

Audiobookshelf Version:
0.9.60-beta

- [✅ ] Android App?
- [ ] iOS App?

#### Android Issue
Android version:
Android 13

Device model:
Google Pixel 6

Stock or customized system:
Stock

**Comment by advplyr** [comment]
Please join the discord or matrix server for troubleshooting connections. Reverse proxy connections are working in 0.9.60-beta
