### ISSUE TITLE
Download starts at 50%

### ISSUE THREAD

**Issue by lkiesow** [advplyr/audiobookshelf-app#523]
I've seen several times that as soon as you click download, the progress bar appears and starts at 50% from where it will then slowly go to 100%. That can't be right. It may be related to 1-file audiobooks. I've at least noticed that some books I've seen this on are single-file books. But I'm not yet sure if this happens on all single-file books.

<img width="300px" src="https://user-images.githubusercontent.com/1008395/215295348-538538b2-86d9-4540-b15f-6e5d7b4e5abf.jpg" />

### Steps to reproduce

1. Open app
2. Go to book
3. Click download
4. Look at progress bar

#### Android Issue

App version: 0.9.60-beta
Android version: 12
Device model: OnePlus Nord 2

**Comment by advplyr** [comment]
This is updated for the next release. It was calculating percentage in a weird way but now it will calculate percentage based on total bytes and bytes downloaded.

**Comment by hobesman** [comment]
Yeah, it was counting the cover art and the audio file as equal parts. Finishing downloading the cover image was calculated as half the download.

**Comment by advplyr** [comment]
Fixed in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
