### ISSUE TITLE
Podcasts "Latest" list should look like the web-version

### ISSUE THREAD

**Issue by hoggatt** [advplyr/audiobookshelf-app#529]
### Is your feature request related to a problem? Please describe.
The podcast latest tab in the app is not designed very well. I can't even tell who made the latest podcast. There's no picture or name of the author. 

### Describe the solution you'd like
The podcast latest tab in the web version is exactly what I'm looking for. Show the pictures, author, and title. You can click on the card to read the description if you want. You can start playing the podcast from there. 

Further, it would be nice if I could set the latest tab as the default when starting the app up since that's the view I'd think most podcast listeners would want to see. 

### Describe alternatives you've considered
Don't use the app (not ideal)

**Comment by advplyr** [comment]
Updated in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
