### ISSUE TITLE
Better padding at bottom of the screen iOS

### ISSUE THREAD

**Issue by gh0sti** [advplyr/audiobookshelf-app#531]
![image](https://user-images.githubusercontent.com/4202657/215652622-a6880ba0-d6cd-4870-a0c7-7fd114e93996.png)

Thank you for the latest update in fixing up the UI and crash issue when playing offline. I'm wondering if the bottom of the UI in the miniplayer could have some better padding to not be so close to the app switcher home button on iPhone 13 pro max display size.

**Comment by gh0sti** [comment]
Screen shot doesnt show it but the bezel curves which make it really tight at the bottom.

**Comment by gh0sti** [comment]
I'm pretty sure in app review they would deny your submission with it being so close to the bottom.

**Comment by meichthys** [comment]
I'm seeing this as well.
A similar issue was address in #408

**Comment by gh0sti** [comment]
Now looking at the player there should be some better separation. 

![image](https://user-images.githubusercontent.com/4202657/216127711-b9f06cdf-cffb-46be-b836-82a4af0ef299.png)

**Comment by benonymity** [comment]
Do you mean padding between some of the player elements, or on the bottom row of buttons? (Also, great book!)

**Comment by gh0sti** [comment]
@benonymity Yes that was what I am referencing. It's a great book so far, really calling out my screen addictions and how we distract ourselves so much.

**Comment by benonymity** [comment]
Gotcha, and agree it could use a bit more padding between elements. Same here, it made me realize all the completely unnecessary things I do, especially on devices, that only consume valuable time and feed this constant drive to get to the _next_ thing. I need to read the paper book and take notes next, I don't take away enough from audiobooks lol

**Comment by advplyr** [comment]
Updated in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)
