### ISSUE TITLE
Back no longer works in player view

### ISSUE THREAD

**Issue by lkiesow** [advplyr/audiobookshelf-app#535]
Until now, when opening the full screen player in the app, you could use the back button or gesture on Android to close the player again. This no longer works. Nothing happens if you click “back”.

### Steps to reproduce

1. Open app
2. Go to book details
3. Click play
4. Click on minimized player to open full screen player
5. Hit back gesture/button
    - Nothing happens
    - The player should close
    - This did work before

### Environment data

- Audiobookshelf version: v2.2.12
- Android App version: 0.9.61-beta
- Android version: 12 and 13

**Comment by lkiesow** [comment]
This seems to be a problem with other views as well. Although, it's probably less annoying there:

- Open the main menu
  - Hitting back will either go to a completely different view or (if you are on the home page) ask if you want to close the app.
  - I expect the menu to close
- Open a modal dialog (e.g. click ⋮ in boob details)
  - Clicking back, nothing will happen

**Comment by advplyr** [comment]
Fixed in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)
