### ISSUE TITLE
Player view missing when re-opening app

### ISSUE THREAD

**Issue by JakobTischler** [advplyr/audiobookshelf-app#536]
### Steps to reproduce

1. Start playing an audiobook → the player view is visible
2. Switch to a different app, or go to the Android homescreen
3. (Maybe do some other stuff, or wait some time - this is unclear to me as of now)
4. Re-open the ABS app 

### Expected behaviour
- When something is playing, the player should be either in view or accessible from the minimized view at all times.

### Actual behaviour
- When returning to the ABS app, we're in the app's home view, and the player view is not only not visible, but also the minimized view at the bottom of the screen isn't there. 

#### Audiobookshelf Version
- [x] Android App: 0.9.61-beta (but this also happened in the previous version)
- [ ] iOS App?

#### Android Issue
* Android version: 13
* Device model: Pixel 7
* Stock or customized system: Android 13 stock

**Comment by advplyr** [comment]
Is the audio still playing in the background?

**Comment by JakobTischler** [comment]
Yeah, the audio is still playing. I can pause/unpause it from the media notification panel. The library book view's action button says "Play" (instead of "Playing" or "Streaming" etc.). When I press it, it restarts the playback from just about the current position, though with the default speed of 1 instead of whatever I was actually using.

**Comment by advplyr** [comment]
Can you try disabling battery optimization for the app? These battery optimization changes made in Android are causing some unexpected behavior

**Comment by JakobTischler** [comment]
I've turned it off and will keep a lookout for any improvements. Thanks.

**Comment by advplyr** [comment]
I'm assuming this is fixed when disabling battery optimizations but let me know. Also try with the latest update 0.9.62-beta

**Comment by JakobTischler** [comment]
I can confirm (as sure as one can be with those things) this hasn't happened again after disabling the battery optimizations (in addition to using .62).
