### ISSUE TITLE
IOS: unable to play/download file on new phone

### ISSUE THREAD

**Issue by stones314** [advplyr/audiobookshelf-app#537]
I recently got a new phone, and have had some problems with audiobookshelf.

1) after installing app on new phone i was able to download the file, but when i tried to play i got a playback error msg.

2) I deleted book and app, and reinstalled app again. Now I am unable to download the book. I got a download error first time, something about unable to create file i think, not sure, it dissapeared. After that nothing happens when i click download on any book (also when i try on those I never tried to download before). 

I am however able to stream the books, but I would like to be able to download them.

My feeling is that there is some configuration in my user that is messed up after I switched phones, maybe it try to download to old phone, or something?

**Comment by benonymity** [comment]
Nope, something broke with iOS downloads in last night's update, it probably isn't an issue on your end. My guess is there will be a patch soon, so either downgrade the app version in Testflight or stream books until a fix is found.

**Comment by DrBazUK** [comment]
Glad it's not just me... I've only installed the app in the last 24 hours so have never had downloads work so seeing the comments on the backlog, I assumed that they were still not a feature. Will wait for an update to Testflight.

Thanks to the maintainer for investigating.

**Comment by advplyr** [comment]
Please upgrade to the latest server release `v2.2.13`.

I didn't realize that I introduced a breaking change there.

**Comment by benonymity** [comment]
The app still downloads in the latest version, it just doesn't report the download progress to the UI on iOS. The issue got introduced [here](https://github.com/advplyr/audiobookshelf-app/commit/8bab4ae383dd429405bd412c8226d77bfb0825ef#diff-709d8f22a127d7633fd15a79fd4420f806d2c0403afc4a645b141d595d6d26c1L41), so it should be a straightforward to resolve. Until there's a new release you can click the button once and wait for the download to complete, you just won't see the progress (or downgrade to the last version like you seem to have done).

**Comment by advplyr** [comment]
Fixed in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)
