### ISSUE TITLE
UI: Change version number in settings

### ISSUE THREAD

**Issue by gh0sti** [advplyr/audiobookshelf-app#539]
![image](https://user-images.githubusercontent.com/4202657/216075646-829accbb-ade3-43a0-8c73-701b6f0bca0e.jpeg)

I'd figure you would want to keep the version number updates and consistent throughout the app. I'm on 0.9.61 and the app settings says the previous build. 

Audiobookshelf Version: 0.9.61

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 16.3

iPhone model:13 Pro Max

**Comment by gh0sti** [comment]
I wonder if it's easier to make version number a variable that can be updated and a string calls out for that variable throughout the app where you want version numbers to be shown. Would that make it easier to keep the version number consistant throughout the app?

**Comment by advplyr** [comment]
Yeah I just forgot to re-generate the frontend after updating the version number.

**Comment by advplyr** [comment]
Fixed in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)
