### ISSUE TITLE
[Bug] Server details are sometimes not stored and app asks for URL on start

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#54]
I haven't really been able to figure out when this happens, but in the past 10 times I have opened the app, I have faced this 3-4 times Sorry, I couldn't screen capture, but the screen it shows is the one where we have to enter the server IP address/URL.

**Comment by andilee7** [comment]
I had the same issue once before it started crashing

**Comment by advplyr** [comment]
There were a lot of updates made on the new version. Let me know if this persists on the newest version.

**Comment by raviwarrier** [comment]
will test it in a day or two. Cheers.
