### ISSUE TITLE
Auto sleep timer broken

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#545]
### Steps to reproduce

See attached screen recording.
https://user-images.githubusercontent.com/42061703/216403812-a3e2b385-0106-477c-8e26-e2ab027865a0.mp4

### Expected behaviour
- Tell us what should happen

When one manually cancels the timer, the timer should remain cancelled and not turn back on, and definitely not within seconds of turning it off.

If it needs to be turned on automatically, then at least wait for the duration set as the default timer duration (in the video: 15m) before turning it back on.

### Actual behaviour
- Tell us what happens

In the video, i turned off the timer, but it turned back on in a few seconds.

### Environment data

Audiobookshelf Version: 0.9.61

- [yes ] Android App?
- [ ] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by MrBearedJoe** [comment]
Android: For me when I used the sleep timer this morning, I paused with around 8s left then I canceled the timer. When i went to play it again the volume was still low. I checked the volume on my device and it was fine. I had to close the app and reopen.

**Comment by advplyr** [comment]
I mentioned this here in point 5 https://github.com/advplyr/audiobookshelf-app/issues/260#issuecomment-1407752168

I just wasn't sure what the correct behavior should be. There are a lot of possibilities

**Comment by advplyr** [comment]
For next release when you go to cancel the sleep timer that has been enabled automatically the button will say "Disable Auto Timer".
So now canceling the auto sleep timer will disable the auto sleep timer settings. When pressing that button you will also have to confirm an alert message letting you know that the setting will have to be re-enabled in settings.

**Comment by advplyr** [comment]
@MrBearedJoe I wasn't able to reproduce this. Let me know if this is something you can reproduce.

**Comment by raviwarrier** [comment]
> For next release when you go to cancel the sleep timer that has been enabled automatically the button will say "Disable Auto Timer".
> So now canceling the auto sleep timer will disable the auto sleep timer settings. When pressing that button you will also have to confirm an alert message letting you know that the setting will have to be re-enabled in settings.

Here's what I would suggest:

Solution 1 - When auto sleep timer is cancelled, disable it just temporarily (reset it at the end of the auto sleep timer period, example: if set from 11p - 6a, enable it back at 6a automatically instead of making the user turn it back on manually).

Solution 2 - same as above, but instead of disabling it until next period (eg, 6a), disable it for just 30/60m extra. So, if the timer period is set for 11p-6a and duration is set for 15m [turning playback off at 11:15p automatically], if cancelled, the duration can be extended to 45m (original 15m + 30m extra) thus turning playback off at 12a.

This problem, in my guess, affects only those users who set short durations (10-30m). So, solution 2 should work for them well.

**Comment by revilo951** [comment]
I agree, there should be at least an option for just "Disable the sleep timer for tonight", and not only  one option that disables it altogether.

**Comment by advplyr** [comment]
Updated in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)

This was originally a bug and I solved it the same way that I saw another popular audiobook app doing it. Feel free to open a feature request on enhancing it further.

**Comment by calebj** [comment]
> Android: For me when I used the sleep timer this morning, I paused with around 8s left then I canceled the timer. When i went to play it again the volume was still low. I checked the volume on my device and it was fine. I had to close the app and reopen.

> @MrBearedJoe I wasn't able to reproduce this. Let me know if this is something you can reproduce.

I can reproduce this (on Android, using 0.9.62-beta). Neither resetting the timer nor canceling it restores the volume during the last minute of the sleep countdown. But instead of having to restart the app like Joe reported, I just have to pause and resume the playback (which also resets the timer). Adjusting the timer also restores the volume. After poking at the code a bit, this looks like a case of missing calls to `setVolume()` in SleepTimerManager.kt. I'm curious how you're not experiencing the issue yourself.

**Comment by advplyr** [comment]
@calebj I wasn't able to reproduce because I was pausing and resuming as per the original comment. I was able to reproduce it by just canceling the sleep timer without pausing. Just fixed it for next release in #605. Thanks!
