### ISSUE TITLE
No files are shown in library -Offline mode (downloaded items)

### ISSUE THREAD

**Issue by Pwnz74** [advplyr/audiobookshelf-app#546]
### Steps to reproduce

1. Click to download books to device for offline storage.
2. Go to offline - now audiobooks are not shown at all
3.

### Expected behaviour
- Audiobooks should be visible in offline mode aswell. Without saying to connect to server, if downloaded to device.

### Actual behaviour
- . Go to offline - now audiobooks are not shown at all and it is just show error: "bookshelf empoty audiobookshelf server not connected"

### Environment data

Audiobookshelf Version:

- [X ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: Android 12

Device model: Zenfone 8

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
On the home page when you are not connected to the internet you are still not seeing your downloaded books?

When you connect to the server can you see the downloaded book?

**Comment by Pwnz74** [comment]
yeah exactly.

If I enable air-plane mode (so no connections). All audio books even downloaded are gone.

If I disable air plane mode I see library back in place.

**Comment by advplyr** [comment]
Are you sure they are actually downloaded?
