### ISSUE TITLE
Unable to log into remote server since update

### ISSUE THREAD

**Issue by miseree** [advplyr/audiobookshelf-app#547]
Using nginx proxy for remote access. I was able to connect no problem for months. The last update now only says 'failed to ping' and won't connect. I am still able to access the server in a browser with the same address.

**Comment by advplyr** [comment]
Are you connecting over http or https?

**Comment by miseree** [comment]
http

**Comment by miseree** [comment]
Interesting. The only other app I'm running through nginx is overseerr, however I connect to it through a browser and not an iOS app. I wondered if it wasn't http/https. Thank you for looking into it. Not sure how you and the team will proceed. I'd appreciate a workaround, but that's only because I'm lazy and don't want to go back and implement https.

On a side note I have another issue and have wondered if http/https wasn't a cause. On a fresh load, I can access bookmarks. However if I resume listening some hours later, my bookmark icon completely disappears. The way I fix it is to stream another book for a few seconds, then reload the first book and my bookmarks icon is back. Let me know if I should start this on a different thread.

Again, really appreciate the team and your work.

**Comment by miseree** [comment]
btw, my current work around is to VPN my phone into my network and direct connect.

**Comment by advplyr** [comment]
I'm making #538 the main issue for this.

We're also discussing this in Discord and trying to get to the bottom of it. At the moment the latest iOS app is restricted to HTTPS for external connections.
