### ISSUE TITLE
Android app crashing

### ISSUE THREAD

**Issue by andilee7** [advplyr/audiobookshelf-app#55]
I just tried out setting up a audiobookshelf server and installed the android app. Looks quite promising to me. Unfortunately the android app is crashing when I want to play a downloaded file. It went so far, that the app crashed immediatly after I tried opening it. I tried to clear everything (delete appdata and cache) and it worked again. But then the crashing started again when playing a downloaded file.

While writing this I wanted to verify if a stream is working. But it crashed too and now it is again in the state that it crashes direct after opening the app.

Is there any log file or debug information I can provide? 

Phone: Samsung S21+
Server: v1.6.36
App: 0.9.31

**Comment by advplyr** [comment]
Are you having the same issue as in #35 ?
There is some percentage of users that the download is unusable, I've not yet heard of streaming crashing. The crashing has something to do with the app attempting to access files in the filesystem, so this should not effect streaming.

This week I will be looking into the file system issue and rewriting the downloader.

**Comment by andilee7** [comment]
I've read #35 but my issue is different. It just crashes also when trying to stream another audiobook. Not quite sure yet if it really has something todo with the download. After I clear appdata/cache it works again (stream and download). I'll try if it happens aswell when only streaming.
The download itself seems to be correct because I can play it successfully with e.g. Smart AudioBook Player.

I'm not not an android app developer but 15 years in the business as full stack developer (c#, JS, etc). So if there is anything I can help you with, I'm here :)

**Comment by advplyr** [comment]
I think may have come across this issue last night when running on an emulator, but I haven't narrowed it down yet. The mobile app is on v0.9.33-beta, and v0.9.32-beta was a big rewrite. The server is on v1.6.39. Let's see if updating to the latest solves your issue.

The mobile app has been more challenging then I anticipated, but that's what keeps it interesting. It has also been interesting how different the experience is when developing software used primarily by technically-minded people.

**Comment by FlamingoDaBird** [comment]
Hi
I tried my OnePlus Nord2 today:
with app: 0.9.34-beta
and server: v1.6.49

I still have the same issue as in #35. Sound plays and the phone locks up and is flashing between an empty desktop and a black frame. The phone is totally locked.. :)
Hard reset is needed.

**Comment by advplyr** [comment]
I'm directing all related issues to #35 
If your issue is still happening and is different than #35 please re-open this
