### ISSUE TITLE
Bookmark in Offline mode

### ISSUE THREAD

**Issue by zcharley** [advplyr/audiobookshelf-app#556]
### Is your feature request related to a problem? Please describe.
I'd like to use bookmarks in Offline mode.

### Describe the solution you'd like
Adding bookmarks locally would imply stocking them locally and then syncing them when back online.

Maybe I'm missing something since I just glanced at the codebase.

**Comment by advplyr** [comment]
Duplicate of #163 

You aren't missing anything. We would need to store them locally and sync.
