### ISSUE TITLE
pause/resume headset button not working on Android

### ISSUE THREAD

**Issue by zcharley** [advplyr/audiobookshelf-app#557]
### Steps to reproduce

1. using wired headphones with media playback buttons (I used wired Apple EarPods)
2. starting an audiobook with Audiobookshelf app play button
3. pressing pause/resume headphones button

### Expected behaviour
- Playback pausing

### Actual behaviour
- Playback is still playing

### Environment data

Audiobookshelf Version: 0.9.60-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Pixel 3a

Stock or customized system:
stock

**Comment by advplyr** [comment]
Duplicate of #429

**Comment by advplyr** [comment]
I'm pretty confident I found the fix for this that will be in the next release

**Comment by zcharley** [comment]
Good thanks! My bad, I didn't find the existing issue 🙄.
