### ISSUE TITLE
[bug] playing a book from android auto starts at beginning instead of saved location

### ISSUE THREAD

**Issue by zombiehoffa** [advplyr/audiobookshelf-app#56]
I haven't been able to test this with the app connected to the server because android auto won't work if I have my vpn connected on my phone and it's using wifi to send the screen info wirelessly to the car. In an unconnected state I see my local downloaded books in the android auto interface and if I start one playing it starts at the beginning. If I access the app on the phone directly I can see the saved location and start it playing on the phone, which then  updates the auto interface to show the correct location.

**Comment by advplyr** [comment]
This is not implemented yet. When launching the app from within android auto the only way it gets current progress is from the server starting a stream. AA doesn't read any local user progress data yet.
I'll follow up here with updates

**Comment by feerlessleadr** [comment]
My experience is that in addition to the issue the OP raised, when stopping a book played by AA, the position on the server is not updated, so when the book is started again sometime later (either with or without AA), the progress that was made while listening via AA is lost.

My temp workaround for this is to just play my book for 5 - 10 seconds once I'm out of my car, which seems to trigger a server update of my reading position.

**Comment by advplyr** [comment]
`v0.9.35-beta` was just released and will keep your progress when streaming from AA. Progress already worked but only when you had the app open on your device already. This is a fix for when opening the app from your cars AA.
