### ISSUE TITLE
Pressing the hardware button on headset causes system to recognize a double press

### ISSUE THREAD

**Issue by yuuzhan** [advplyr/audiobookshelf-app#573]
### Steps to reproduce

1. Open app / play audio book
2. press middle button on headset
3. Does not play / pause.  Looking at history logs can see a pause and a play event for the same time stamp.

### Expected behaviour
-  should play or pause the audiobook

### Actual behaviour
- does not play or pause the audio book

### Environment data

Audiobookshelf Version:

- [ 0.9.61] Android App?

#### Android Issue
Android version: 12

Device model: pixel 3

Stock or customized system: stock

**Comment by tehniemer** [comment]
Same issue here in Android Auto

**Comment by MikeBishop** [comment]
Noticed this as well. Works from my car controls, oddly, but not my BT headset.

**Comment by advplyr** [comment]
This is fixed for the next release already. Same issue as #429

**Comment by advplyr** [comment]
Fixed in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)
