### ISSUE TITLE
Resuming playback sometimes jumps to wrong time

### ISSUE THREAD

**Issue by JakobTischler** [advplyr/audiobookshelf-app#578]
### Steps to reproduce

1. Play and pause (via Bluetooth)
2. Some time later, resume (via Bluetooth)

### Expected behaviour
- Resume from time that was paused at.

### Actual behaviour
- Sometimes (not always) ABS seeks to wrong time, sometimes multiple times directly after another (see screenshot)
  ![image](https://user-images.githubusercontent.com/748857/218310994-25007202-dd09-4669-9ddf-91d8562242fc.png)
  1. At 13:11, I resume playback at position 09:40:23
  2. It immediately jumps to 06:37:10, then again to 04:35:47, then again to 04:14:46
- I _think_ that has only happened when pausing/resuming via Bluetooth, but I can't be certain, and I'm also not sure this would have anything to do with the problem.

### Environment data

Audiobookshelf Version:

- [x] Android App? v0.9.61-beta
- [ ] iOS App?

#### Android Issue
- Android version: 13
- Device model: Pixel 7
- Stock or customized system: Stock

**Comment by hobesman** [comment]
Just to narrow down, is it streaming or a downloaded book?

**Comment by JakobTischler** [comment]
It's a downloaded book.

**Comment by milesian01** [comment]
Same problem here.  Just as OP reported, this also happens to me when pause/resume via Bluetooth on stock Android, Pixel 6 Pro.

**Comment by tvaupo** [comment]
Noticed the issue when playback is stopped for a while (5mins or more). I'm using 1.2x speed increase, downloaded book.

**Comment by skronenwerth** [comment]
Same problem here on iOS without Bluethooth, with and without AirPlay. It always happens to me with audiobooks that are downloaded and sometimes with audiobooks that I stream.

**Comment by advplyr** [comment]
I think this is fixed for Android in the latest release 0.9.62-beta

Let me know if you can still reproduce this.

**Comment by lkiesow** [comment]
Still seems to happen sometimes with the latest release. With both streaming and downloaded books.

**Comment by advplyr** [comment]
Let me know if you can find reproducible steps. I'm not sure I've had this happen on the latest

**Comment by externl** [comment]
This happens to me all the time on iOS as well. With both downloaded and streamed books. Not sure of a good way to reproduce it reliably, but it's it's still an issue.

**Comment by skronenwerth** [comment]
I also have the problem under iOS, use here the version 0.9.63. With me there is also no way to make this reproducible, it happens sometimes when I want to start an audiobook. However, not every time.

**Comment by Mega-Volti** [comment]
I just found this one and reading through it, it does sound very much like the one I opened recently: https://github.com/advplyr/audiobookshelf-app/issues/638

Might it be the same root cause? "Rounding errors" in the playback position would explain the weird jumps when seeking or pausing/resuming.

**Comment by JakobTischler** [comment]
I encountered this again, and I have a clue that _might_ be connected.

![image](https://user-images.githubusercontent.com/748857/227779013-225672b8-a1c5-4f52-9fa8-60d8763693a2.png)

1. I listened on the phone and paused.
2. I resumed on the desktop.
3. Tried to resume on phone, sync seems successful.
4. Phone still tries to play from its last save point.

**Comment by rightaditya** [comment]
@JakobTischler nailed it, at least in terms of what I've experienced. I use both the web interface and the Android app (updated to 0.9.63 as per the Play Store) on a Pixel 7. The Web interface always resumes at the right spot, but the Android interface frequently (if not always) doesn't resume from the correct spot if I've listened to it in the meanwhile via the Web interface. Exactly as in @JakobTischler's screenshot, I see from the Android app that it syncs and sees the new time, but then the player resumes wherever it was originally paused from. Without looking at the code myself it kinda seems as though the player's timestamp isn't getting updated, even if the app is noting the the new timestamp somewhere else internally.

This is for a downloaded book. Not sure if this is relevant, but the Web interface shows me the "canonical" timestamp (i.e., according to the audiobook length when played at 1x) while the Android app shows me my "actual" timestamp (i.e., according to how much time has passed/is left for my listening to it at my usual 1.5x).

**Comment by Alistair1231** [comment]
> The Web interface always resumes at the right spot, but the Android interface frequently (if not always) doesn't resume from the correct spot if I've listened to it in the meanwhile via the Web interface. Exactly as in @JakobTischler's screenshot, I see from the Android app that it syncs and sees the new time, but then the player resumes wherever it was originally paused from. Without looking at the code myself it kinda seems as though the player's timestamp isn't getting updated, even if the app is noting the the new timestamp somewhere else internally.
> 
> This is for a downloaded book. Not sure if this is relevant, but the
 
I have exactly this issue on v2.2.23 with docker and 0.9.65-beta. I am using downloaded book.

![image](https://github.com/advplyr/audiobookshelf-app/assets/26165288/a4509def-6c51-4741-b139-23009cb073fb)
![image](https://github.com/advplyr/audiobookshelf-app/assets/26165288/a9c15cca-85a1-4ef8-9b3a-b44b570fc34b)
![image](https://github.com/advplyr/audiobookshelf-app/assets/26165288/2f1e6c73-ccd1-46dc-bc58-7ff9e1fe3680)
