### ISSUE TITLE
Recent sessions list items not aligned

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf-app#587]
### Steps to reproduce

1. Navigate to user stats page on mobile (at least Android, maybe iOS?)
2. Observe the numbers lined up but not the titles.
3.
![Screenshot_20230217-092749_audiobookshelf](https://user-images.githubusercontent.com/29721765/219752324-9bb3e5c5-413f-4093-bc51-505c0cf873d5.jpg)
![Screenshot_20230217-092943_audiobookshelf](https://user-images.githubusercontent.com/29721765/219752336-4f1c57c2-e37f-4130-b316-8bbe1bde2441.jpg)

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.61

Device model:

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Fixed in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)
