### ISSUE TITLE
Podcasts Latest Page Should Not Show Entire Description 

### ISSUE THREAD

**Issue by hoggatt** [advplyr/audiobookshelf-app#588]
### Is your feature request related to a problem? Please describe.
Many podcasts stuff a million links and tags in the description, so when I go on the "latest" page sometimes I have to scroll a lot and it's hard to even remember which podcast was even two up. Makes the latest page very cluttered, unlike the web app. 

### Describe the solution you'd like
Something just like the web app. Show the thumbnail, podcast name, podcast title, and play button (with duration, or spot left off at) just like today, but either don't include the description, or have a severely truncated version (ex. the first  2-3 lines of the description). 

Then for the description, either have a pop-up like the web app (if no description shown), or an expand/contract button for the description (if truncated description is shown). 

I think this improvement would be the last thing needed to make the mobile app have great basic podcast support for people who are subscribed to many podcasts!

**Comment by hoggatt** [comment]
I suppose pull to refresh on the latest page would be a nice feature too, but not nearly as important!

**Comment by advplyr** [comment]
Added in [v0.9.63-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.63-beta)
