### ISSUE TITLE
downloads do not appear/disappear in Android app

### ISSUE THREAD

**Issue by felix-wa** [advplyr/audiobookshelf-app#589]
### Steps to reproduce

1. Download audiobook to Android device
2. Wait till notification "Item 'XXX' download finished" appears
3. Search for media in app

### Expected behaviour
- I expec to see the audiobook in the Local Media folder as well as in the local media shelf.

### Actual behaviour
- Books do not appear or appear only for short time. Data is only availanble in local folder when I search in Android directly. If I download the book multiple times I can see in Android that the book was downloaded multiple times. Some books appear in the app but dissapear after minutes. If I do a 'Scan' it says 'Folder Scan complete - 2 books up-to-date' but I can not see any local book in the app

### Environment data

Audiobookshelf Version: v2.2.15

- Android App: Version 0.9.61-beta

#### Android Issue
Android version: 13

Device model: Samsung Galaxy A52

Stock or customized system: Stock system

sees screenshot:

![audiobookshelf](https://user-images.githubusercontent.com/62806811/219947630-a5ebb1f5-249e-4e24-816a-b8790f2daa49.jpg)

**Comment by advplyr** [comment]
I fixed the scanner yesterday and another download issue. Hopefully get to release it later today.

**Comment by advplyr** [comment]
Fixed in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)
