### ISSUE TITLE
Listening sessions getting lost

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf-app#591]
### Steps to reproduce

1. Listen on Android mobile (downloaded book and streaming book both same symptom)
2. Watch it say that progress is being saved
3. Server stats say 0 minutes for that day.

### Expected behaviour
- Tell us what should happen
There should be a record of listening minutes reflecting the progress that the app is syncing.

### Actual behaviour
- Tell us what happens
Somehow that session is lost.

Notice that the "Friday" referenced was 2/17/23. I had listened throughout the day, starting in the morning and continuing until midnight.

I half suspected that it was treated as one big session and so didn't show up under Friday. But I closed the player and it didn't show up under _any_ day.

![Screenshot_20230219-170100_One UI Home](https://user-images.githubusercontent.com/29721765/219987523-89fc12fc-ce44-42c6-9433-02e39a71d9f2.jpg)
![Screenshot_20230219-170252_audiobookshelf](https://user-images.githubusercontent.com/29721765/219987538-8e4f96e2-17f2-4e08-892f-91c24ed783ef.jpg)

The other suspect is the "auto load" feature on the testing version. I'm wondering if it's somehow messing with the sessions when it opens and tries to start a session even though I'm listening on the store version of the app.

### Environment data

Audiobookshelf Version: 2.2.15 server
Android version 0.9.61 (and the "nightly" build installed in parallel, but the listening was done on the play store version.)

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 10

Device model: Galaxy s9+

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
I fixed something in server v2.5.0 related to this https://github.com/advplyr/audiobookshelf/issues/2168

Let me know if you are still having this issue
