### ISSUE TITLE
"Now playing" bar covers local media list items

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf-app#592]
### Steps to reproduce

1. Download enough books to the device to reach the now playing bar across the bottom.
2. Watch the list continue behind the bar 
3. Fail to be able to scroll up enough to uncover the last items in the list.

### Expected behaviour
- Tell us what should happen
The list should allow scrolling enough to bring the bottom of the list above the now playing bar
### Actual behaviour
- Tell us what happens
![Screenshot_20230219-171548_audiobookshelf](https://user-images.githubusercontent.com/29721765/219988054-aaad5afa-e0b8-402d-bac7-b922fa0e2858.jpg)

You can't reach the bottom of the list.

### Environment data

Audiobookshelf Version: 0.9.61 and 0.9.62

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
The container should be scrollable. Are you not able to scroll? It's not a great UI though and those arrows are all misaligned.

**Comment by hobesman** [comment]
It does scroll but not enough. You can see in the screenshot that I've scrolled down some as the top book is cut off. It's only showing about 10 of the 17 items downloaded because I've scrolled down. 

You can see the top of the 16th item, and the 17th is completely covered by the now playing bar.

**Comment by advplyr** [comment]
Fixed in [v0.9.63-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.63-beta)
