### ISSUE TITLE
Download failed from second book of a series. "download complete but failed to create library item"

### ISSUE THREAD

**Issue by SeriousPat** [advplyr/audiobookshelf-app#598]
### Folder structure on server
Author
(Subfolder) Book 1
(Sub-Subfolder) Files
(Subfolder) Book 2
(Subfolder) Book 3

### Steps to reproduce

1. Download first book from a series. (OK)
2. Download second book drom a series. ("download complete but failed to create library item")

### Expected behaviour
- Both dowloads are complete and fine

### Actual behaviour
Local Folder is Empty.
At first Download Folders are createt local:

Author
.Book 1
..Files

After Download and Error Message "download complete but failed to create library item" Local Folders are.

Author
.Book 1
..Files
Author (1)
.Book 2
..File 1
Author (2)
.Book 2
..File 2
 ...etc

If i delete the Book 1 via App. The Folder Author will stay.
Whenn in repeat download Book 1, the Error occours aswell. 
After Download and Error Message "download complete but failed to create library item" Local Folders are.
Author
.Book 1
..(no Files)
Author (1)
.Book 1
..File 1
 Author (2)
.Book 1
..File 2
 ...etc

When i delete the whole Author Folder and the others. The first Download will succeess.

### Environment data

Audiobookshelf Version:
v0.9.62-beta
- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version:
12 SKQ1.211019.001
Device model:
Redmi Note 9 Pro
Stock or customized system:
Stock (MIUI Global 13.0.4)

**Comment by advplyr** [comment]
I'm not sure I understand but I just downloaded a 5 book series and I was not able to reproduce this issue.

Is this happening with a specific audiobook? Or is this only happening once you download a second book to the same author folder?

**Comment by SeriousPat** [comment]
This only happening once you download a second book to the same author folder?
- Yes, not at every series from the same author. Current problem Series.
Cody Mcfadyen\Smoky Barrett\1 - Die Blutlinie
Cody Mcfadyen\Smoky Barrett\2 - Der Todeskünstler
Cody Mcfadyen\Smoky Barrett\3 - Das Böse in uns
Cody Mcfadyen\Smoky Barrett\4 - Ausgelöscht
Cody Mcfadyen\Smoky Barrett\5 - Die Stille vor dem Tod

Book 1 and 2 are fine.
Book 3 - 5 occours the error. If i clean the local folders, i can dowload just one of them. If i download the next one the error occurs. "download complete but failed to create library item"
I tried to merge the mp3 files to ine file, also transcoding to m4b. Same error.

**Comment by SeriousPat** [comment]
Yes, space is enough.

Same Problem on:

Android Issue
Android version:
11 RKQ1.200826.002
Device model:
Mi 9t Pro
Stock or customized system:
Stock (MIUI Global 12.5.2)

I can try to capture my screen and send a video.

**Comment by stefanoschrs** [comment]
I have a similar issue, but for me it doesn't let me download any audiobook at all! I've tried a few different ones. The books on the server are in folders and I can confirm that I can download them from the Web.

Android: 0.9.63 (beta)
Server: 2.2.19 (docker)

![image](https://user-images.githubusercontent.com/4215699/232679976-68f6a0c6-01ec-44ee-b2a3-5f21abcd96e8.png)

**Comment by MI3Guy** [comment]
I've found on android that this happens when downloading a book with a "?" in the name. (The ? is in the filename on ths server as well.) My guess is that it is trying to save a file locally with a "?" but the underlying file system doesn't support it.

**Comment by MI3Guy** [comment]
I'm able to download other files that don't have the question mark.

**Comment by EichFlo** [comment]
I'm also no longer able to download any audio-books since the last update. I definitely have enough storage, so that's not the issue. 

When using 'download to Audiobooks', I get the error that item has been downloaded but failed to be added to library. I can't find the file  on my device though.

'Internal App storage' claims to download the item and the book now appears to be downloaded, but trying to play the book gives me an error and the download finishes instantly, too fast to actually download the file.

I don't think it's related file names, I can no longer download books I have previously downloaded. A work around I have found is manually copying the audiobook files into the correct directory and then choosing 'download to Audiobooks'. The book is then playable locally

**Comment by advplyr** [comment]
@EichFlo The latest app version requires server v2.2.23

**Comment by EichFlo** [comment]
@advplyr That did the trick, thanks! All working now

**Comment by advplyr** [comment]
Thanks for following up. I think this can be solved on the latest release by choosing to use internal storage instead of selecting a folder. You will see the option when pressing download on the latest release.

Let me know if this persists for anyone using internal storage
