### ISSUE TITLE
Sleep timer running while casting not stopping playback

### ISSUE THREAD

**Issue by justinwoodland** [advplyr/audiobookshelf-app#599]
### Steps to reproduce
1. Timer is set. 
2. Audio is cast to google cast device.
3. Timer counts down to zero

### Expected behavior
1. Playback on cast device stops when timer ends.
2. Cast session ends.
3. Future playback continues from last stopped spot.

### Actual behavior
1. Playback continues on the google cast device after the timer ends.
2. The server seems to think that playback has stopped when the timer reaches zero. 
3. This causes future playback to start behind where the cast device was eventually stopped.

### Environment data
Server version: v2.2.15 (docker)
Android App version: 0.9.61-beta

**Comment by justinwoodland** [comment]
Order of timer setting and casting doesn't seem to matter.

**Comment by advplyr** [comment]
I just tested this on the current release and I'm not able to reproduce. Can you try this again with 0.9.62?
