### ISSUE TITLE
Series layout not adapting ro screen resize

### ISSUE THREAD

**Issue by lkiesow** [advplyr/audiobookshelf-app#602]
In the series view, if you resize the screen (e.g. by rotating the device), the layout does not adapt and series may be hidden or half cut off.

### Steps to reproduce

1. Rotate device to be in landscape mode
2. Go to series
3. Rotate device to be in portrait mode

Some series will be cut off or even completely hidden.

### Environment data

Audiobookshelf Android 0.9.62-beta

**Comment by advplyr** [comment]
Fixed in [v0.9.63-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.63-beta)
