### ISSUE TITLE
cant use hamburger menu and cant see mini player while playing in app and cant see all series on that tab

### ISSUE THREAD

**Issue by ChrisAust1n** [advplyr/audiobookshelf-app#604]
### Steps to reproduce

1.not really sure 
2. it happened all of a sudden 
3.

### Expected behaviour
- Tell us what should happen
- should be able to use the hamburger menu on top right to change server info and see profiles and stats 

### Actual behaviour
- Tell us what happens
- doesnt show all the series that i added on the series tab only shows first two and nothing else it scrolls down but doesnt show anything
- and i cant see the mini player view when playing it shows streaming/playing but cant see it 
- videos showing the issue on gdrive- https://drive.google.com/drive/folders/1uXFh7-_wDpx31YN0Ojj3098HwgtXcY9j?usp=share_link

### Environment data

Audiobookshelf Version:

- [yes latest from playstore] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 7.1

Device model: Redmi 4a

Stock or customized system: stock with hyperion launcher

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Please still provide the version of the app you have installed.

In the videos I don't think I saw you press the hamburger menu.

My suspicion is this has to do with Android 7.1 since I haven't tested that and very few users are using it. My suggestion is to go to the play store and search "Android System WebView". Update that app and restart your device.

**Comment by ChrisAust1n** [comment]
> Please still provide the version of the app you have installed.
> 
> In the videos I don't think I saw you press the hamburger menu.
> 
> My suspicion is this has to do with Android 7.1 since I haven't tested that and very few users are using it. My suggestion is to go to the play store and search "Android System WebView". Update that app and restart your device.

i did press it but for some reason the video doesnt show the show taps option and the doesnt even allow me to press the menu button but i will do that thanks

**Comment by ChrisAust1n** [comment]
> Please still provide the version of the app you have installed.
> 
> In the videos I don't think I saw you press the hamburger menu.
> 
> My suspicion is this has to do with Android 7.1 since I haven't tested that and very few users are using it. My suggestion is to go to the play store and search "Android System WebView". Update that app and restart your device.

Well mate that did all the work and its fixed now thanks alot ❤
