### ISSUE TITLE
Sort in library no longer functions after choosing an author from the home screen

### ISSUE THREAD

**Issue by bcmross** [advplyr/audiobookshelf-app#607]
### Steps to reproduce

1. Select an author from the "Newest Authors" section on the home screen.
2. Press the "Sort" button, and select any sort method. 
3. Keep trying different sort methods.

### Expected behaviour
- Selecting an author should bring you to the library with the filter Author: 'Selected Author' with their books visible. 
- Choosing a sort option should resort that author's books accordingly. 
- Clearing the filter should show your whole library again, and choosing sort methods should resort accordingly. 

### Actual behaviour
- **Selecting an author** brings you to the library and shows their books, but the filter button shows that no filter is set. 
- ~~Pressing the "Sort" button shows that it's currently sorted to "Added At (down)", which is true for the author's books.~~ (Not true with further testing)
- **Selecting a different sort option** refreshes the library to show all of your books instead of the specific author's, and the library becomes unresponsive to any attempt to resort it. It doesn't seem to be sorted in any particular order, yet this semi-random order is consistent between reproductions of the bug and doesn't change with what sort button you choose first.
- Filtering still works, but sorting doesn't regain function. The currently played book along the bottom also changes to show the times "NaN" and no longer plays.

Audiobookshelf Version: 0.9.62-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Pixel 3

Stock or customized system: Stock

**Comment by hobesman** [comment]
This also happens if you open a book and tap on an author or narrator name from there.

**Comment by advplyr** [comment]
There was a bug in setting the filter from links.

**Comment by advplyr** [comment]
Fixed in [v0.9.63-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.63-beta)
