### ISSUE TITLE
REQUEST:  Mark Unread

### ISSUE THREAD

**Issue by dietrichmd** [advplyr/audiobookshelf-app#61]
A way to mark a book as unread would be helpful for those accidental click plays.

**Comment by advplyr** [comment]
The read/unread still needs to get added, but you should still be able to click the small X in the progress box that will reset the progress.

**Comment by proteus077** [comment]
To add to this, a mark complete on a book would be handy, as there are a couple books that I've finished but they still show as incomplete and when I click play on them they start playing and the beginning of the last chapter in the m4b file. At the moment I fix this by just going to the web version, marking as complete, then going back to the app and it now shows as complete but a button in the app would be awesome.

**Comment by Strider27** [comment]
+1 for the Mark as Finished, I see a pull request above but doesn't look like it is going to be merged as not complete.
