### ISSUE TITLE
(Podcasts) Newest Episodes/Continue Listening carousel on Home tab should display Episode Titles, not Show Name

### ISSUE THREAD

**Issue by copey02** [advplyr/audiobookshelf-app#616]
### Is your feature request related to a problem? Please describe.

On the web version, the Home tab for Podcasts displays Newest Episodes carousel with the Episode Titles of new podcasts. 
On the App (iOS), this same carousel displays the Podcast Show name, not the episode. 

### Describe the solution you'd like

Newest Episodes carousel on mobile app should display the new episodes the same way the web server displays them, with the Title of the episode shown. This is more useful information to have. 
This should also be updated for the Continue Listening carousel on mobile, both show the Podcast Show name, not the episode title.

**Comment by advplyr** [comment]
Fixed in [v0.9.63-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.63-beta)
