### ISSUE TITLE
REQUEST: Sync button

### ISSUE THREAD

**Issue by itschrisonline** [advplyr/audiobookshelf-app#62]
Hi
Is it possible for a sync progress button I do some driving in areas with no reception. I know where they are and would be able to push it when close to keep progress.
I have found that when you come back into reception you have to log in again, you lose your progress.
Also what is the sync interval?

Cheers

**Comment by advplyr** [comment]
Are you listening on android auto? Android auto doesn't sync yet, I'm hoping to get that working today.
For regular listening on both the mobile & web app is 5s.

I'm guessing you are using android auto because worst case would be 5s of progress lost.

**Comment by itschrisonline** [comment]
Sorry have been away,
Using a device with android auto but have been using the main app for all functions including play pause
