### ISSUE TITLE
Download breaks with CD folders

### ISSUE THREAD

**Issue by KaiStarkk** [advplyr/audiobookshelf-app#620]
### Steps to reproduce

1. Try to download a book which is using CD sub folders

### Expected behaviour
- Book downloads and is playable
- Folder size matches the files downloaded

### Actual behaviour
- Book “download” extremely quickly
- The folder size is only several kilobytes (the size of the cover)
- Book can’t be played

### Environment data

- [ X ] iOS 

iOS Version: 
16.3.1

iPhone model:
11

**Comment by KaiStarkk** [comment]
@advplyr you’re awesome

**Comment by advplyr** [comment]
Fixed in [0.9.63-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.63-beta)
