### ISSUE TITLE
An 'Auto-Rewind' feature under the 'Auto-Sleep' settings

### ISSUE THREAD

**Issue by HStep20** [advplyr/audiobookshelf-app#623]
### Is your feature request related to a problem? Please describe.
I have a sleep mask I used with bluetooth headphones built into it. Since I wake up often in the middle of the night, I have to restart my playback to fall back asleep with. This involves me:

1. Turning the mask on
2. taking it off
3. opening ABS
4. skipping back 10-15 minutes to find where I fell asleep at
5. putting the mask back on
6. falling asleep again

### Describe the solution you'd like
Ive raised this issue before with #311, but I think the new auto-sleep settings give the perfect opportunity to add a new setting to 'auto rewind' for the user when the auto sleep is triggered. It could be as simple as a toggle to enable 'auto rewind', and a numerical input for the amount of time to rewind. 

This would cut out all the steps of taking off the mask as the user could just:
1. Turn the mask on
2. ABS Starts, Rewinds, Starts a sleep timer all on its own
3. Fall back asleep

The only problem I could see coming up is how it may handle books that finish in the last 'period' of sleep. If my auto timer runs for 20 minutes when it starts, and my book only has 17 minutes left, will ABS be able to handle resuming playback in a book that is completed?

**Comment by YodaDaCoda** [comment]
Not sure how long the auto-rewind duration is right now, but IMO the auto-rewind duration being equal to the sleep timer is a perfect default👌.

Having the auto-rewind duration user-customisable would be ideal, and would bring some certainty to the process where currently I am uncertain how far it's going to auto-rewind.

**Comment by Dr-Blank** [comment]
Just some thoughts.

Auto rewind could also depend on the time since the last playback.

This is not just for auto sleep, but in general and could be a separate feature.

How it would work:

if the playback for a book has been paused for 1 min: rewind 15 seconds
⏸ 5 mins => ⏪ 30 seconds
⏸ 30 mins => ⏪ 1 min 30 seconds
⏸ > 2 hours => ⏪ 2 min

of course all these settings sould be customized.

attached a Screenshot from mAbook app.

**Comment by tehniemer** [comment]
I support this, I'm finding myself rewinding considerably after more than a couple hours.

**Comment by HStep20** [comment]
For clarification, this request is not an addition or change to the current 'auto rewind' system. Im suggesting an Auto-Rewind system for the Auto Sleep timer. 

You go to bed, and put on an audiobook -> you fall asleep while the sleep timer finishes

I want to streamline the experience of finding where I approximately was when I fell asleep. Since Im constantly waking up throughout the night, its a pain to open my phone, adjust my eyes, scrobble around, and set a new sleep timer. Id love for it to 'auto rewind "halfway"' when the Auto Sleep Timer triggers so that I can just hit play and let it go. 

No scrobbling or trying to find where I was because the app would approximate where I fell asleep by auto rewinding

**Comment by Dr-Blank** [comment]
> For clarification, this request is not an addition or change to the current 'auto rewind' system. Im suggesting an Auto-Rewind system for the Auto Sleep timer. 


Your feature could be included in the comment I made by putting a logic on how the book was paused.

If ⏸️ by auto sleep timer => ⏪ 50% of current auto timer setting

so if auto sleep is set to 10 min, rewind 5 min on next play.

**Comment by advplyr** [comment]
Added in [v0.9.64-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.64-beta)
