### ISSUE TITLE
Podcast Library empty on iOS (0.9.63)

### ISSUE THREAD

**Issue by cybergurke** [advplyr/audiobookshelf-app#625]
### Steps to reproduce

1. Select a Podcast Library
2. Press Library Button

### Expected behaviour
See all Podcasts

### Actual behaviour
Library is empty. Worked before last update. Works in Browser.
Home and latest Tabs are working normal.
Audiobook Library is still working. 
![image](https://user-images.githubusercontent.com/12197823/224439525-821203a9-805f-4725-9656-eb4e0ed8ec6d.jpeg)

### Environment data

Audiobookshelf Version: 0.9.63

- [ ] Android App?
- [X] iOS App?

#### iOS Issue
iOS Version: 16.3
iPhone model: 12 Pro

**Comment by advplyr** [comment]
I'm not able to reproduce this. Does this happen even if you close and re-open the app?

**Comment by advplyr** [comment]
Maybe a filter got leftover. Can you click the filter button and see?

**Comment by cybergurke** [comment]
Filter to all didn't helped. I restarted the App and Updated the Server. 
Re-Adding the Server didn't helped.

**Comment by cybergurke** [comment]
After reinstalling the App, it is working again. 
Sorry for the inconvenience. Should have tried first.
Thanks for the great software.
