### ISSUE TITLE
REQUEST: Buffer

### ISSUE THREAD

**Issue by itschrisonline** [advplyr/audiobookshelf-app#63]
Hi,

Is it possible to have a buffer?

**Comment by advplyr** [comment]
Right now the player is using the defaults that come with Exoplayer android media player.
2.5s must be loaded before playing, then it will maintain a buffer of 5s.

I think we can increase this because we are only streaming audio. What do you think a reasonable default is?
This can be something customizable in the future.

**Comment by advplyr** [comment]
I've been testing out various buffer durations and landed on:
5s required to begin playing
buffer will remain between 23s and 45s

I also added a buffer highlight on the tracks, which will be easier to see if you have chapter tracks enabled.

![image](https://user-images.githubusercontent.com/67830747/146686782-c79ba280-8ce3-4f7d-a4db-d229b38ac6e4.png)

This will be in the next release

**Comment by advplyr** [comment]
This is live on the play store now in `v0.9.35-beta`

**Comment by itschrisonline** [comment]
Is there any chance for a overwrite time 45s when playing at 3x is still pretty small and for people go country have a longer buffer would be would be beneficial. There is about a 15 mintue area where I dont recieve any cell coverage

**Comment by advplyr** [comment]
It sounds like you should be playing downloaded audiobooks in that case. Are you asking for increased buffer because you are having an issue playing downloaded audiobooks like in other threads?

**Comment by itschrisonline** [comment]
I have tried that keeps saying invalid bytes and won't play

**Comment by advplyr** [comment]
Invalid bytes? Where is it saying that?

**Comment by itschrisonline** [comment]
When you click downloads on the book.

**Comment by advplyr** [comment]
Can you take a screenshot of that? I've never heard that before

**Comment by itschrisonline** [comment]
![Screenshot_20220101-150402_AudioBookshelf](https://user-images.githubusercontent.com/13555496/147860485-611675a0-a2b6-46ae-af16-26c0ee59cb7c.jpg)
![Screenshot_20220101-155728_AudioBookshelf](https://user-images.githubusercontent.com/13555496/147860487-e48d95dc-3093-4a6a-93cf-66c82aa6275b.jpg)


![Screenshot_20220101-062454_AudioBookshelf](https://user-images.githubusercontent.com/13555496/147860488-f495632f-93ba-40fb-93b2-c696d42bbe38.jpg)
![Screenshot_20220101-150334_AudioBookshelf](https://user-images.githubusercontent.com/13555496/147860489-773214a5-844b-482c-b5b5-2f14c6581d8f.jpg)

**Comment by advplyr** [comment]
I don't understand the screenshots. It looks like 2 of the downloads didn't complete or failed in which case you would need to delete it and download again.
The other downloads look okay and should play.

**Comment by itschrisonline** [comment]
I have not been able to get a local play
Most of the time it fails on both cellular and on the same network as the server
If it succeeds and I close the app then it changes status to invalid bytes
and if that somehow work and I download multiple books they start changing to invalid bytes

**Comment by advplyr** [comment]
What phone do you have?
You should also try downloading a book without a cover from your server. There was a problem with that on Oneplus

**Comment by itschrisonline** [comment]
Samsung fold 3 will try when I get home

**Comment by 2fst4u** [comment]
> What phone do you have?
> You should also try downloading a book without a cover from your server. There was a problem with that on Oneplus

What is the issue here? I have a OnePlus and I experience the same issue with downloads not working. It just says "preparing" and stays on 0% and if I restart my phone is shows what the images above show, with "invalid bytes".

I can't seem to download at all.

**Comment by advplyr** [comment]
> > What phone do you have?
> > You should also try downloading a book without a cover from your server. There was a problem with that on Oneplus
> 
> What is the issue here? I have a OnePlus and I experience the same issue with downloads not working. It just says "preparing" and stays on 0% and if I restart my phone is shows what the images above show, with "invalid bytes".
> 
> I can't seem to download at all.

The issue had to do with already downloaded covers. When downloading don't navigate away from the audiobook page. If you navigate away before it's done it will freeze. Known bug also.
