### ISSUE TITLE
[Bug]: Syncing of "place" in book?

### ISSUE THREAD

**Issue by isuee94** [advplyr/audiobookshelf-app#632]
### Describe the issue

I'm not clear how your "place" in a book is synchronized, but I've been having major issues with this.  I'll listen to a book during the day and then the next day start again and it looses my place.  Most commonly it jumps ahead considerable when I restart the next day.  I'm running audiobookshelf in a docker container on Proxmox and using the iOS app.

If the iOS app pings the server for the "place", it's possible this is a connectivity issue.  As I leave my house, I have an area with poor cell coverage.  Is it possible that the app isn't picking up the "place" from the server?

### Steps to reproduce the issue

1. Using the iOS app, listen to a book and then stop.
2. The next day, open the iOS app again and start listening again by hitting the play button.
3. Seems to start in a different spot than where i left off.

### Audiobookshelf version

2.2.15

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Is this a downloaded audiobook?

**Comment by isuee94** [comment]
Yes

**Comment by advplyr** [comment]
Have you reproduced this issue with streaming an audiobook?

**Comment by isuee94** [comment]
I take that back. I’m streaming this one. I’ll have to try it with a downloaded book and see if it happens there too.

**Comment by advplyr** [comment]
Another thing to take note of is whether you are using other clients in between, like using the web.
Also, if you are leaving the app open in the background is notable.

**Comment by Mega-Volti** [comment]
Might be the same as this one? https://github.com/advplyr/audiobookshelf-app/issues/486

**Comment by skronenwerth** [comment]
Maybe also the same as this #578

**Comment by Danathar** [comment]
I've also experienced this problem with downloaded books.

**Comment by Danathar** [comment]
> Another thing to take note of is whether you are using other clients in between, like using the web. Also, if you are leaving the app open in the background is notable.

Thank you for the suggestions. I have been switching between the web and mobile app versions. Often I will listen to a book on my computer via the web, then leave my desk at work with a downloaded book ready to go in the mobile app. In those cases, the sync progress sometimes gets completely reset on the server, so that my place is totally lost on both platforms after launching the app again. I'll try to pay closer attention to exactly when this sync issue occurs to help troubleshoot further.

**Comment by benonymity** [comment]
Is this still an issue?
