### ISSUE TITLE
High Res Cover

### ISSUE THREAD

**Issue by Dr-Blank** [advplyr/audiobookshelf-app#634]
I consume my media on my phone and the recent updates to player ui looks nice. However, the low resolution downscaled cover images kind of spoil the feel.

solution I like to propose: Use low res images when browsing through the library, but high resolution images when viewing the library item or in player.

Also while downloading the book offline, I'm downloading hundreds of Mb of books, surely I can afford the data and storage for a couple of Mb of cover images.

**Comment by hobesman** [comment]
I believe the mobile player uses the full res cover currently. But the item details page shows the downscaled version unless you tap the cover to expand.

**Comment by advplyr** [comment]
The player was already using the raw cover image. I updated the item page to use it and the download to use it.

**Comment by Dr-Blank** [comment]
> I believe the mobile player uses the full res cover currently. 

Never occurred to me that I should click on the image 😀.

**Comment by Dr-Blank** [comment]
> The player was already using the raw cover image.

Never noticed it since I didn't stream, mostly downloaded.

> I updated the item page to use it and the download to use it.

You are awesome 😎. The background gradients and the buttos look so pretty btw with the images, loving it!

**Comment by advplyr** [comment]
Updated in [v0.9.64-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.64-beta)
