### ISSUE TITLE
[Android] Support for mp3 index seeking

### ISSUE THREAD

**Issue by Mega-Volti** [advplyr/audiobookshelf-app#638]
### Steps to reproduce

1. Listen to audiobook with a single, large mp3 file
2. Seek or pause playback and start it up again

### Expected behaviour
- Playback should re-start where it was paused or +- 10 seconds from the seek position

### Actual behaviour
- The playback position is off a little bit, sometimes only a couple of seconds, sometimes even a few minutes, time discrepancy seems to increase depending on length of listening session (it might be a rounding error when saving the playback time?)
- I haven't observed this issue when playing books split into multiple, smaller audio files
- The issue only occurs when playing with the Android app, not when using the web interface.
- The issue occurs regardless of playing an audiobook stored locally, or when using the app and streaming.
- Weirdly, after seeking back and forth a bit, a particular section in the audiobook I use for testing settled on 1:10:05 for the exact sentence I was using for the test. Then, switching to the web interface and searching the same position, the very same sentence was spoken at 1:09:35 instead.

### Environment data

Audiobookshelf Version: v2.2.17

- [x] Android App? v0.9.63-beta
- [ ] iOS App?

**Comment by hobesman** [comment]
Is this happening with all of your mp3 files? Or just certain ones?

I experienced a sort of similar issue with an audiobook that was encoded weirdly. I reencoded it with VLC and it worked better after that.

**Comment by Mega-Volti** [comment]
This is still happening in the latest version. Not with all files, it seems to only occur when playing an audiobook with a single, long mp3 file.
Started a new one the other day and the issue persists: The playback position in the Android player is off regularly when seeking or pausing and resuming. On the other hand, when using the web interface (either on PC or the Android phone), everything works perfectly and there is no issue with the playback position whatsoever.
Which means the mp3 file can't be to blame, somehow the Android app is determining the playback position differently than the web interface and the former is having some sort of bug.

**Comment by DebrodeD** [comment]
This issue is happening to me as well across all of my mp3 files, on multiple android devices using the android app. It does not happen in the webplayer and I'm testing whether it happens with m4b files or not, but I'm guessing not.

**Comment by Mega-Volti** [comment]
Update:

This seems to occur with pretty much all mp3 files when using the Android app. I have noticed it with audiobooks split into smaller files, although it is very hard to pinpoint there since the offset is usually only a few seconds - but it does exist and it is reproducible once I knew what I was looking for.

The longer the mp3 file is, the more pronounced (and easier to find) the offset, which is why at first I only noticed it with single file mp3 audiobooks.

I also loaded up the very same audiobook (local file as downloaded by the ABS Android app) into AntennaPod and it plays perfectly fine there. No issues with seeking and offsets at all.

So whatever ABS' mp3 player does, AntennaPod's mp3 player doesn't seem to have the same issue. Maybe that helps with pinpointing the bug.

**Comment by advplyr** [comment]
I was able to get the sample mp3 file seeking correctly by setting `FLAG_ENABLE_INDEX_SEEKING` in exoplayer: https://developer.android.com/guide/topics/media/exoplayer/customization#customizing-extractor-flags

Until I understand this better or some other solution comes along we can add a device setting to use this flag.

**Comment by advplyr** [comment]
Setting is added for next release.

![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/29100cfc-e19f-4efc-bb28-cc7685b96739)

The view more links to https://exoplayer.dev/troubleshooting.html#why-is-seeking-inaccurate-in-some-mp3-files

**Comment by advplyr** [comment]
Added in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)

**Comment by Mega-Volti** [comment]
Sadly, this is still not fixed.

The app setting does not seem to take: I can activate it in the settings, but when closing the app and opening the settings again, it is deactivated again.

Additionally, the seek issue described above is still occuring (which makes sense since the new setting doesn't seem to work).

**Comment by advplyr** [comment]
The setting is fixed in 0.9.66 in that it will show that it is applied. It was getting applied before it just wasn't showing that it was. Let me know how it goes
