### ISSUE TITLE
Transferred phone - audiobooks not playing / cover art gone

### ISSUE THREAD

**Issue by NAL100** [advplyr/audiobookshelf-app#640]
I recently upgraded my iPhone and transferred the phone (a backed up copy) to the new phone, as a result some things have stopped working. 

### Steps to reproduce
1. Transfer iOS between phones
2. Reinstall Audiobookshelf iOS app from Testflight
3. Try to play **Downloaded** Audiobook

### Expected behaviour
- Downloaded audiobook should play
- Cover icons should show up

### Actual behaviour
- Cover icons all gone (this got partially fixed once I logged out and back in - however they are still gone for previously downloaded books in the "Local Books" list)
- When I try to press "Play" after downloaded audiobook is selected, an error pops up in app "Playback Failed: Playback Error"
- In Downloads section all audiobooks are listed as downloaded but I can't play them (same behavior).
- Streaming works fine

### Environment data

Audiobookshelf Version: 0.9.63-beta

- [ X ] iOS App?

#### iOS Issue
iOS Version: 16.2

iPhone model: iPhone 13 mini

### Other Info
This seems to be mostly on downloaded audiobooks. - I logged out, deleted the audiobook, and then logged in and re-downloaded it, and it worked fine. The cover art refreshed for all books once I logged back in in the "continue listening" and "recently added" lists, but the "local books" list (some of the same books) do not have covers, except for the one that I re-downloaded, that one has a cover. Also streaming seems to work fine.

**Comment by benonymity** [comment]
I don't think this is an issue that can be fixed on our end; since the app itself isn't installed automatically there is a desync with the DB and local files since you have to re-download the app from Testflight. Once the app is published on the App Store I imagine this wouldn't be an issue, until then just redownload the books. I just got a new phone and had to do the same thing—it's annoying, but I'm guessing it's just the fact this is through Testflight and can't be copied directly through the App Store.

**Comment by NAL100** [comment]
> I don't think this is an issue that can be fixed on our end; since the app itself isn't installed automatically there is a desync with the DB and local files since you have to re-download the app from Testflight. Once the app is published on the App Store I imagine this wouldn't be an issue, until then just redownload the books. I just got a new phone and had to do the same thing—it's annoying, but I'm guessing it's just the fact this is through Testflight and can't be copied directly through the App Store.

Alright - that's annoying but I guess it's just something to live with until it is on the app store.
