### ISSUE TITLE
iPad does not sync playback position

### ISSUE THREAD

**Issue by Hackmodford** [advplyr/audiobookshelf-app#647]
### Steps to reproduce

1. Play streaming content on iPad.
2. Pause on iPad and note the time
3. Try to resume on iPhone

### Expected behaviour
- iPhone continues where iPad left off

### Actual behaviour
- iPhone continues from last position it knew about.

### Environment data

Audiobookshelf Version: 0.9.63

- [ ] Android App?
- [x] iOS App?

### Notes

I found that it does work the other way round. If I play something on my phone, the ipad will pick up where the phone left off.

**Comment by skronenwerth** [comment]
Maybe also the same as this #578

**Comment by brandonocasey** [comment]
This is also happening on 0.9.65-beta. Seems like the player needs to sync progress when it starts to read or opens an item?

**Comment by advplyr** [comment]
I think this has been fixed on 0.9.66 and server v2.5.0 but let me know if not.

**Comment by Hackmodford** [comment]
Confirmed it is syncing for me now.

If I have the player open while doing the test the position doesn’t update, but that seems reasonable to me.

If I play on one device, pause. Then switch to the other and open the file (in other words something else was playing first) it goes to the correct position 😀
