### ISSUE TITLE
Open in player mode by default (or remember last mode)

### ISSUE THREAD

**Issue by gazpachoking** [advplyr/audiobookshelf-app#650]
### Is your feature request related to a problem? Please describe.
After listening to a (downloaded) book, when I come back to the app after some time, the app loads in library mode. I then have to:
- Wait for it to connect to the server
- Click on the book I was reading
- Click the play button to start the player minimized
- Click on the player to expand it to full screen

To continue my listening session in player mode.

### Describe the solution you'd like
When in player mode, the app always remembers, and opens directly in that mode. Usually I pick a book much less often than I resume playing the last book, so defaulting to always opening in library mode isn't so convenient.

### Describe alternatives you've considered
- Remembering the last mode the app was in, and resuming in that mode
- An option to always default to opening up in player mode

### Additional context
Ideally it would open the player to the last book and position that the user was playing on any client.

**Comment by advplyr** [comment]
This should already be happening on Android and iOS.
Are you on iOS or Android and what version of the app and server are you using?

**Comment by gazpachoking** [comment]
I'm on Android, server 2.2.17, client 0.9.63-beta

**Comment by advplyr** [comment]
Once the server connects, the most recent book on the continue listening shelf should automatically open. Is this not happening for you?

**Comment by gazpachoking** [comment]
~~No, when I open the app, it takes a second to connect, then just shows the home screen,  where I have to select the book, (which does show first in the continue listening section,) then press play,~~
Well, while I was repeatedly testing this, I realized that it does open up the latest book in the player (minimized at the bottom of the screen,) but it normally takes longer than it does for me to press the book manually then press the play button, so I didn't realize it was doing it automatically (5+ seconds after it connects to the server.)
I guess this is good. It would be nice if it was quicker, but then we'd have to compromise on resuming from the last position on the _device_ vs server (server book/position is clearly preferred but inherently will have more delay.) I'd also prefer if it opened with the player interface full screen, but that would also be bad if it takes too long, because it would pop a new interface over the library, potentially right as (or before) you were clicking on stuff in the library. I guess I'm good with the current behavior then. I think there is room for improvement, but it's not as simple as I imagined when I made the ticket.
The one related area that I think could use improvement is when the interface opens on android auto I often have to select my current book (which is listed first) before I get the media controls.

**Comment by gazpachoking** [comment]
Did this behavior change recently? The player hasn't been opening anymore when I open the ABS app, no matter how long I wait.

**Comment by advplyr** [comment]
Yeah it was removed because there were issues with how it was implemented and the solution is a bigger project right now. I think this will get added back in with a setting to control it.

Is this feature request still relevant? I'm not sure what to do here

**Comment by gazpachoking** [comment]
We can certainly close out this issue if this feature is already part of a bigger project I think.

**Comment by flboy1758** [comment]
Is there another issue to track or an ETA for when this feature will be reimplemented?
