### ISSUE TITLE
BUG: Playback Speed not correct when using Android Auto

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf-app#66]
Hi - I've noticed a strange bug where when I plug my phone into Android Auto to listen to a book on the app, if the app itself isn't open (or at least the last music app I used on my phone), the book will play at 1x speed, rather than the 1.3x speed I have it set on my phone. As soon as I open the app and book on my phone (with it still plugged into AA), the book will start playing the book at the correct playback speed. 

If the app and book are already open on my phone when I open the app through AA, the book with play with the correct playback speed through AA without issue. 

My head unit is stock Sync 3 with a 22 Ford explorer, and my phone is a OnePlus 8T running Android 11. 

Thanks!

**Comment by advplyr** [comment]
This is the trouble I came across when I began implementing AA. When AA is launched from your car without opening the app on your device, then the core logic the app was built on never gets ran. So I've had to re-write that code again for just native android.
I have an update pending on the play store now that will send updates to your server with the current progress when you have  launched the app from your car AA only. Before this update progress was not kept in sync if you did not have the app open on your device also.
This is still missing for downloaded audiobooks, and as you pointed out here the audiobook speed is also missing.

**Comment by feerlessleadr** [comment]
Thanks! Any thoughts on doing dual releases through the play store as well as directly through GitHub, since I know the play store approval process takes a while.

**Comment by advplyr** [comment]
Yeah I can start putting the binaries in github releases.

**Comment by advplyr** [comment]
Just put up the APK pending review on the play store: https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.35-beta

I'll try to remember to do this for each one.

**Comment by advplyr** [comment]
That version is live on the play store now

**Comment by feerlessleadr** [comment]
One thing that I didn't consider when installing the apk directly from github, is that AA doesn't allow sideloaded apps to show up in the AA dashboard. Doh!

**Comment by advplyr** [comment]
Version `v0.9.36-beta` will use the current playback speed when you start playing on Android Auto.
If you change the playback rate you will need to restart the AA playback.
