### ISSUE TITLE
Bookmark icon disappears after app inactivity

### ISSUE THREAD

**Issue by miseree** [advplyr/audiobookshelf-app#660]
First, thank you so much for the work you do on this app. I love it! I have had this issue for months across several versions of audiobookshelf and the audiobookshelf ios app. After some time of inactivity, I lose the ability to select/create chapters. See video:

https://youtube.com/shorts/-K9vGtw6MQk

### Steps to reproduce

1. Start Audiobookshelf, functions normally. 
2. Do a few other things on your phone
3. Return to Audiobookshelf a few hours later and the bookmarks icon disappears.
4. I can get the icon back by playing another book briefly and returning to the first book and voila the bookmarksicon is back

### Expected behavior
- chapter icon should persist

### Actual behavior
- see above

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [ x] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 16.3.1

iPhone model: 13 pro max

**Comment by miseree** [comment]
Not sure if this could be related or not. If I have a book downloaded, I don't have access to bookmarks...is that normal?

**Comment by advplyr** [comment]
Bookmarks are not yet supported when offline. However, when you are connected to your server you should see the bookmark icon on downloaded books.

I tried to reproduce your issue but was not able to

**Comment by raviwarrier** [comment]
![Screenshot_2025-05-17-00-38-11-40_e9782661401ed6f222682e1e02b74bd4.jpg](https://github.com/user-attachments/assets/efdfab6d-d357-45fc-a8de-41c32e4c2360)

Please reopen this bug for fix.

**Comment by advplyr** [comment]
Can you reproduce it or was that a one-off?

**Comment by raviwarrier** [comment]
> Can you reproduce it or was that a one-off?

It's happened quite a few times. Until I read the OP's post, I thought it was a font-icon rendering problem. But after reading it, I reproduced it as shown in the images above.
