### ISSUE TITLE
A way to start playing a specific podcast from a playlist

### ISSUE THREAD

**Issue by mightypanders** [advplyr/audiobookshelf-app#666]
### Is your feature request related to a problem? Please describe.
When viewing the playlist in the app it is currently (to my knowledge) not possible to start the playback of a specific podcast from the list, only for the whole list. Tapping a podcast in the list only links to the Detail View of the podcast, showing Shownotes and other details.

### Describe the solution you'd like
I would like a button for each entry in the playlist which starts the playback of the specified podcast. Maybe it could be styled in the same way as the playback button in the podcast view (showing the remaining time if nothing is playing, showing 'Playing' if the podcast is playing and 'Finished' if the podcast is completed)

### Describe alternatives you've considered
- The cover of the podcast could serve as a (hidden) play button, superimposing a 'Pause' Icon if the podcast is playing.
- The whole row of the podcast could serve as a button to start the playback of a podcast with the cover serving as a link to the Detail View

### Additional context
This is a screenshot of something I have cobbled together myself.  
I am not sure if this aligns with the vision of the project, if it is alright I could fix up any dangling issues in my fork and create a PR for this
![image](https://user-images.githubusercontent.com/11777733/231233368-e270ee2b-9354-4f80-b308-9ed44d1272b8.png)

**Comment by advplyr** [comment]
I think adding a play button makes sense but maybe just a round play/pause aligned right? The design would need to be played around with a bit to see what makes sense. The design from your screenshot looks a bit cramped.
Playlists are also available for audiobooks, so we would want to make sure this looks good with books also

**Comment by advplyr** [comment]
Added in [v0.9.64-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.64-beta)
