### ISSUE TITLE
[Android] Chapter Order Differs Between Website and Mobile when downloaded

### ISSUE THREAD

**Issue by valdearg** [advplyr/audiobookshelf-app#670]
### Steps to reproduce

I have an audiobook in parts and chapters, which is typical of Graphic Audio books, when on the ABS website these seem to be named in the correct order:

MISTBORN0101P01.mp3
MISTBORN0101P02.mp3
MISTBORN0101P03.mp3
MISTBORN0101P04.mp3
MISTBORN0101P05.mp3
MISTBORN0101P06.mp3
MISTBORN0102P01.mp3
MISTBORN0102P02.mp3
MISTBORN0102P03.mp3
MISTBORN0102P04.mp3
MISTBORN0102P05.mp3
MISTBORN0102P06.mp3
MISTBORN0103P01.mp3
MISTBORN0103P02.mp3
MISTBORN0103P03.mp3
MISTBORN0103P04.mp3
MISTBORN0103P05.mp3
MISTBORN0103P06.mp3
MISTBORN0103P07.mp3

This basically means: Mistborn book 01, part 01-03, chapter 01-07.

Displaying this in Windows and in the website view, this looks great:

![image](https://user-images.githubusercontent.com/2789033/232101684-eab16e70-a15e-476c-b6fa-223c7f1e18fc.png)

If I then view this in the app however the order may be based on the final numbers?

![image](https://user-images.githubusercontent.com/2789033/232102279-ef029144-f799-49fd-86ef-6ea71f82dd56.png)

This means the playback is skipping between various different parts, leads to very confused listening!

### Expected behaviour
Playback should follow the same order the website provides.

### Actual behaviour
Follows a different order, perhaps based on the final number in the files?

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: Android version 13

Device model: Samsung Galaxy S23 Ultra

Stock or customized system: Stock

**Comment by advplyr** [comment]
Did you update the tracks AFTER downloading the book on your device?
There is an issue open #525 to update chapters for downloaded books if they are updated on the server.

Can you test this again?
