### ISSUE TITLE
Two progress bars are displayed on Android

### ISSUE THREAD

**Issue by ameyp** [advplyr/audiobookshelf-app#672]
### Steps to reproduce
I don't know how I got into this state, but every audiobook on my Android phone exhibits this problem. Both bars advance as I listen or seek.

![Screenshot_20230415_141701_audiobookshelf](https://user-images.githubusercontent.com/83116/232253640-c9dcb784-d74e-4ee8-ac5b-e56d0fae91f5.jpg)

### Expected behaviour
- Only one progress bar should be deployed

### Actual behaviour
- Two progress bars are displayed

### Environment data

Audiobookshelf Version:

- [x] Android App? 0.9.63-beta
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: Samsung Galaxy S3

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by hobesman** [comment]
One is for the chapter and one is for the entire book. If there are no chapters, then those will be the same.

You can change this by tapping the three dots in the top right and selecting which others bar(s) to display. Or by adding chapters to the book from the web UI.

**Comment by ameyp** [comment]
An, thank you!
