### ISSUE TITLE
Support offline podcast episode chapters

### ISSUE THREAD

**Issue by mmBesar** [advplyr/audiobookshelf-app#675]
This app is a Must-have for the server, and I have a couple of requests:
- I need to use the new [chapters feature](https://github.com/advplyr/audiobookshelf/issues/1646) in the app.
- Adding a couple of features from [AntennaPod](https://github.com/AntennaPod/AntennaPod)'s player would be nice, like: 
   - Pausing and resuming by clicking on the thumbnail/poster.
   - Easy access to show notes and chapters.
- ~~Adding the app to F-Droid.~~
I love this project, thank you.

Edit: F-Droid has been requested before.

**Comment by advplyr** [comment]
There is a feature request open for f-droid #58

**Comment by mmBesar** [comment]
> There is a feature request open for f-droid #58

Sorry, I missed it!

**Comment by advplyr** [comment]
This will be available in the next server release

**Comment by mmBesar** [comment]
> This will be available in the next server release

So it's all in the server, no updates needed for the app, nice.
Just a few app enhancements, and the project will be the one-stop solution.
Thank you.

**Comment by mmBesar** [comment]
I like where this project is going, so I will ask for more minor tweaks:
- Chapters to be accessible offline.
- Deactivate the download button for the downloaded episodes.
- An option to sort episodes by release date in the offline mode.
Thank you.

**Comment by advplyr** [comment]
Added in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
