### ISSUE TITLE
Show episode numbers in the lists besides the titles

### ISSUE THREAD

**Issue by dnlmlr** [advplyr/audiobookshelf-app#677]
### Is your feature request related to a problem? Please describe.
In the mobile app (android) only the podcast episode titles are shown, not the episode numbers. This makes it really hard to find specific episodes if you only know the episode number. The web application shows the episode number below the title.

### Describe the solution you'd like
The episode numbers for episodes should be shown *somewhere* in the list. Possibly below like in the web app, or maybe on the far right side next to the title.

**Comment by advplyr** [comment]
Updated in [v0.9.64-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.64-beta)
