### ISSUE TITLE
[Enhancement/RFC] iOS screen swipe back should be disabled on "now playing" screen

### ISSUE THREAD

**Issue by ajaxbits** [advplyr/audiobookshelf-app#681]
### Issue overview
When I am on the "now playing" screen, a swipe right from the left edge of the screen (generally indicating "go back" in iOS UX) causes unexpected behavior. 

https://user-images.githubusercontent.com/45179933/233757822-f9a7b6dc-ad26-4ff1-abf5-9dd7fae702ca.MOV

These are the aspects that make it feel especially unexpected from a UX standpoint:

- As a user of other apps in the iOS ecosystem, I don't expect the "now playing" screen to even accept a "go back" input because (A) there is a downward pointing arrow at the top left, meaning that this tile slides up and down, not side to side -- and because (B) the "now playing" screen feels like it operates "on top of" or "in a higher priority" than the other screens of the app. As a user, I expect it to not interact with the history of my previous windows. 
- It seems like the app is processing the back swipe the same as the browser would (which makes sense given the codebase). This sometimes feels glitchy. For example in the video above, I'm on my collections page, visit authors, bring up the now playing screen, but when I swipe back, I'm taken to the collections page instead of the screen that I was just on. This does not make sense with iOS UX.  

### Proposed solution
I feel like the best and easiest solution is to disable back-swipes on the now playing screen entirely. That way the user only interacts with it through vertical swipes or taps. 

I'd love to hear thoughts on this proposal, or any suggestions others have. 

Thanks for an amazing project! Use this every day.

**Comment by benonymity** [comment]
@advplyr maybe something like this could be added to the now playing UI?
```javascript
document.addEventListener('touchstart', function(e) {
    if (e.pageX > 10 && e.pageX < window.innerWidth - 10) return;

    e.preventDefault();
});
```
