### ISSUE TITLE
Enhanced back and forward buttons, with adjustable times (i.e. 10 Seconds, 15 Seconds, 30 Seconds etc)

### ISSUE THREAD

**Issue by projx** [advplyr/audiobookshelf-app#682]
### Is your feature request related to a problem? Please describe.

Sometimes navigating for skip forward and back can be difficult or time consuming, especially with single-file books, it can take many presses of the back and forward buttons find a position.

### Describe the solution you'd like
Allow the back and forward buttons to be customised, i.e. rather than just 10 seconds, add a setting than allows this to be changed, with options for 15, 20, 30 and 60 seconds.

### Describe alternatives you've considered
A couple of options, but I'm not sure if they are feasible with the UI kit it uses:
1) Adding additional back and forward buttons, each with a different speed, or
2) Keeping the current button pressed, will repeat the back and forth, rather than having to re-tap it.

Thanks

**Comment by c-hri-s** [comment]
You are already able to configure this in the IOS app

**Comment by advplyr** [comment]
This is already supported in Android and iOS. Maybe you have some really old version?
