### ISSUE TITLE
iOS app won't stream or download audiobooks from server

### ISSUE THREAD

**Issue by andrewakessler** [advplyr/audiobookshelf-app#688]
Local server runs without issue from 2014 Mac Mini (audiobooks play fine on server). iPhone connects to local server and shows library, but refuses to stream or download audiobooks. tried restarting server, app, and phone. Worked prior to most recent iOS app update. Clicking on "stream" or "download" provides haptic feedback but no actual action. 

#### iOS Issue
 iOS App 0.9.63(20)

iPhone model:
iPhone XR

iOS version:
16.3.1

**Comment by advplyr** [comment]
What version of the server are you running?

Are you using a reverse proxy or local ip address? Connecting over https?

**Comment by andrewakessler** [comment]
Connecting though HTTP (not HTTPS) using local address (192.168.....)

Current server version is 2.2.17 though Docker. OS version is 12.6

**Comment by advplyr** [comment]
Try updating to the latest server version 2.2.19

Also check if this is limited to certain audiobooks

**Comment by andrewakessler** [comment]
Appreciate the responses and assistance. Additional steps taken for possible debugging:

Updated to version 2.2.19 — Same issue occurred as before. 
Updated Docker Desktop to 4.18.0 and rebooted computer (server) — Same issue
Deleted iPhone app and re-downloaded version 0.9.63 (20) from TestFlight. reentered server address — This appears to have worked as the books that previously wound not stream or download are now working. My guess is something occurred during the update that corrupted the iOS app.

**Comment by advplyr** [comment]
I can't think of anything changing that could cause this unless maybe you had a really old version. Glad it's working for you again.
