### ISSUE TITLE
Easier way to delete local files 

### ISSUE THREAD

**Issue by HappyPants9999** [advplyr/audiobookshelf-app#690]
### A delete from device button on the book page by the listen button would be awesome. Currently it's a lot of menus to dive through to figure out how to delete a title. Might be hard for new users to figure out.
Also clear text that you are deleting from the device and not the actual library.

**Comment by advplyr** [comment]
Added in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
