### ISSUE TITLE
"shake to reset" needs a lot of shake even on "Very Low" sensitivity

### ISSUE THREAD

**Issue by vb0** [advplyr/audiobookshelf-app#696]
### Steps to reproduce

1. Set a sleep timer (be it automatically by time of day or while playing)
2. Try to reset it by moving the phone

### Expected behaviour
The timer should get reset even by lifting the phone a little, when on "Very Low" sensitivity

### Actual behaviour
The timer almost never gets reset (verified by looking at the countdown - with the display on and the player in the foreground) or with the vibration. With a VERY vigorous shake the timer does get reset so the functionality itself works.

### Environment data

Audiobookshelf Version: 0.9.63-beta (Play Store)

- [ x] Android App?

#### Android Issue
Android version: 10 and 13 

Device model: S9+ Snapdragon and Pixel 7 Pro

Stock or customized system: stock

Smart AudioBook Player works as expected so the hardware is fine.
Also read the sensors via AndroSensor and the movement - the intent here is to distinguish between the phone sitting anywhere like on a (not vibrating ...) bed or nightstand or table as opposed to being handled and in any way. The linear acceleration sensor has a bit of noise and the "stand still" versus lifting it readings are "only" 2 orders of magnitude apart ( 0.0x versus x.  m/s^2) but the gyroscope ones are really good as they are in very low 0.000x rad/s versus single digit rad/s even when slightly lifted (like you keep the phone on the table face up and you lift it a little towards you). That's 4 orders of magnitude, should be easily discernible (not sure what the interface is on the Android side but I'm sure there is some way to just make it more sensitive).

**Comment by bluenote73** [comment]
I think you want 'very high' sensitivity.

**Comment by vb0** [comment]
Ouch, you can imagine how dumb I feel. Good lesson: no matter how good the product is users will pick the wrong option and then open a bug report even if it fully works as expected and documented :-)
