### ISSUE TITLE
[Bug] Incorrect playback status

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#697]
![tempFileForShare_20230504-005455.jpg](https://user-images.githubusercontent.com/42061703/236023477-e31f17bb-03c3-4377-a805-0acb30592eb6.jpg)

The book's not playing, but this is what it shows.

**Comment by hobesman** [comment]
I suspect fixing this will fix https://github.com/advplyr/audiobookshelf-app/issues/601 and a similar problem I encountered with playlists. I want able to tell it to play the next item without manually closing the player window first. I think the fix you put in for this request will address my issues as well. Or did I misunderstand the commit?

**Comment by advplyr** [comment]
@hobesman I think so

**Comment by advplyr** [comment]
Updated in [v0.9.64-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.64-beta)
