### ISSUE TITLE
[iOS] Track progress not reset when changing tracks after sleep timer ends

### ISSUE THREAD

**Issue by higbee4** [advplyr/audiobookshelf-app#699]
### Steps to reproduce

1. Listen to a multi-track audiobook. 
2. Set a sleep timer with a long enough duration that it will end on a subsequent track.
3. After the timer ends, use the track/chapter selector to go to the previous track.
4. Skip until you are close to the end of the track and start listening.
5. When it gets to the next track, instead of starting at the beginning of that track, it will start at the point where the sleep timer stopped.

### Expected behaviour
- Once I select a previous point in the book, all track positions in later tracks should be forgotten.

### Environment data
I didn't test on Android. This bug didn't happen on the web version. And it only happened when I used the sleep timer on iOS.

Audiobookshelf Version:

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 16.4.1 (a)

iPhone model: iPhone 13 Max Pro,

**Comment by nichwall** [comment]
Is this fixed in 0.9.69? It should be fixed by the same fix for #686

**Comment by higbee4** [comment]
It appears fixed in my initial test. I’ve been waiting for some bug fixes before using this app as my daily driver. I’ll try it out again and see if I run into this or any other sync issues. Thanks.
