### ISSUE TITLE
Progress from Android app to server/web app appears to be synced on resume and not on pause

### ISSUE THREAD

**Issue by tzw9373** [advplyr/audiobookshelf-app#70]
Basically what the title says. This has minimal impact with quick pause/play scenarios, but leads to loss of progress when playback is paused for an extended period. This is my only real complaint, thanks so much for all the work you've put in!

**Comment by advplyr** [comment]
Can you share which version of the app and server you are using and some basic steps to reproduce the issue on my end?
I want to make sure I'm understanding correctly.

**Comment by tzw9373** [comment]
App version: 0.9.34-beta
Server version: 1.6.46
Reproduction steps:  
When playing an audiobook, current playback progress shows in full media view as well as minimized media view. Once paused, percentage progress does not update in book info view until playback is resumed. I would expect to see percentage progress updated in book info view when playback is paused.

**Comment by advplyr** [comment]
I'm testing this now and I cannot reproduce. Here is what I'm doing:
1. click an audiobook and go to the audiobook page
2. press play & audiobook starts streaming
3. watch as the progress is updated on the audiobook page every 5 seconds

Are you playing a downloaded audiobook, or are you streaming from your server?

**Comment by tzw9373** [comment]
I only stream currently, I haven't attempted downloading books locally yet. When I follow the steps you listed, percentage completed/time remaining do not update every five seconds, only when paused/resumed. The issue of only updating when resumed appears to occur more often when remaining in other parts of the app (home screen, media view, etc.).

**Comment by advplyr** [comment]
Does the yellow progress bar on the cover image update when playing?
You are referring to the progress percent and the time remaining on the audiobook page correct?

**Comment by tzw9373** [comment]
The progress bar similarly does not appear to update every five seconds. And yes, those are the ones I refer to.

**Comment by advplyr** [comment]
Are you seeing any errors in the server log? Is this the same for every audiobook?

**Comment by tzw9373** [comment]
This behavior does appear to be consistent across multiple books of varying filetypes. I am seeing multiple "socket disconnected", "socket connected", and "API called without a token" messages in the logs, is there anything in particular I should keep an eye out for?

**Comment by advplyr** [comment]
The progress updates are sent via the web socket, so if the web socket is disconnecting then that is the issue. However, you also must have a socket connection to start the audiobook stream, so it is disconnecting some time after starting the stream.

You can try:
1. In the web app go to the config page -> logs and select debug logs
2. Close any open stream and make sure you dont have the web app open
3. Open a new stream
4. Watch the server logs for when the socket is disconnecting

Making sure you are only using the mobile app for this test will help us to know the socket connection is from the mobile app.

**Comment by tzw9373** [comment]
When following those steps, the debug logs indicate the client current time being sent to the server on both pause and resume and I'm not seeing any socket related messages. I'll continue to keep an eye on this, thanks for your guidance!
