### ISSUE TITLE
Deleting/removing the books leaves behind the folder

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#701]
![tempFileForShare_20230510-142837.jpg](https://github.com/advplyr/audiobookshelf-app/assets/42061703/34ad2d66-e943-462f-b37b-bb822bbde690)

All the empty folders in the screenshot are books I've read and then removed using the app. Apparently, it leaves the folder after it deletes the files.

App version: 0.9.63-beta

**Comment by advplyr** [comment]
Fixed in [v0.9.64-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.64-beta)
