### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by captainbadass2** [advplyr/audiobookshelf-app#703]
May 11 12:04:09  audiobookshelf[742]: [2023-05-11 12:04:09] ERROR: [DB] Update entity user Failed: Error: ENOSPC: no space left on device, mkdir '/usr/share/audiobookshelf/config/users/data/data.0.json.lock'
May 11 12:04:09  audiobookshelf[742]: [DailyLog] Append log failed [Error: ENOSPC: no space left on device, write] {
May 11 12:04:09  audiobookshelf[742]:   errno: -28,
May 11 12:04:09 audiobookshelf[742]:   code: 'ENOSPC',
May 11 12:04:09 audiobookshelf[742]:   syscall: 'write'

i had it installed on ubuntu server with android client. working ok for ages then tried to download a book to the client.
It said downloaded ok but had no covers, then every time tried to play it crashed the android app

So i restarted server and now it wont restart. Tried reinstalling server. same issue. 
There is about 20gig of free space on the drive.

**Comment by advplyr** [comment]
It says no space is left on device to create that folder. Is there space left on the device?
Since this is happening on the server this would be a server issue and not related to the mobile app.
