### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#705]
![Screenshot_2023-05-13-11-10-27-33_3d9111e2d3171bf4882369f490c087b4.jpg](https://github.com/advplyr/audiobookshelf-app/assets/42061703/dfa1f83e-4b3d-4566-a058-1ae68f45af37)

Is it possible to have ABS be considered as a media app by Google Maps? It would be nice to be able to control ABS playback while navigating.

**Comment by advplyr** [comment]
I don't think this is possible. Google maps has set that list
