### ISSUE TITLE
"Source Error" after downloading m4b audiobook (Android)

### ISSUE THREAD

**Issue by stiefelus** [advplyr/audiobookshelf-app#707]
### Steps to reproduce

1. Imported this m4b file as audiobook to audiobookshelf.
<img width="647" alt="image" src="https://github.com/advplyr/audiobookshelf-app/assets/114739505/f2fe55ae-ce97-4a2a-9aee-10b58833b79b">
2. Downloaded on Android App. Download itself seems fine. It finished and also linked the local file via an ID.
3. When I try to play the audio book I get an error: "Source Error". (When playing file without downloading it, playback works fine. Playback type ist "transcode" and not direct as in all the other m4b files I own.)

### Expected behaviour
- Complete download, then local playback with the linked local m4b file. 

### Actual behaviour
- Playback does not start at all. Just get a "Source Error" information, no more informations visible on app or inside the container. When playing file without downloading it, playback works fine. Playback type ist "transcode" and not direct as in all the other m4b files I own. 

### Environment data

Audiobookshelf Version:

- Android App

#### Android Issue
Android version: 11

Device model: Xiaomi Mi9T

Stock or customized system: MIUI 12.1.1

**Comment by stiefelus** [comment]
> There must be some encoding issue with the m4b file or it is using a codec not supported on your device. At the moment if you can't direct play the audio file then you won't be able to play the downloaded file.

@advplyr hmm, thats odd. The file ist coming fromm the same source and seems to have the exact Same Codec as all the other m4bs that are working perfectly fine. Also, offline Playback works with alternative Audiobook Players locally on my device. 

Maybe this ist Not the same issued, but the other day I was encoding a big Audiobook that consisted of a Lot of mp3s directly in Audiobookshelf. After encoding was done there was a Problem with this Audiobook, with a Error Message that there was no Media File even though a complete m4b was located in the expected directory

**Comment by advplyr** [comment]
I think that all the audio player apps use the same media player, exoplayer, so that would be strange. The m4b that you downloaded using the Abs app is the same m4b file you have tested with other players?

**Comment by stiefelus** [comment]
My issue is fixed with the new android app version! This seemed to be the problem: "(Android) Out of memory causing fallback to transcode"

Now its not transcoding anymore and local playback is working fine also. :)
