### ISSUE TITLE
Offline books available while trying to connect to server. 

### ISSUE THREAD

**Issue by jimski427** [advplyr/audiobookshelf-app#708]
### Is your feature request related to a problem? Please describe.

When opening the abs app in poor cell conditions on Android, there is a delay playing offline books. It can take up to 30 seconds at times to have a book downloaded to the phone available to click on to play off line. 

### Describe the solution you'd like

Offline books available right away while it tries to connect to the server in the background. 

### Additional context

Screen cap of it happening. 
https://imgur.com/a/gKnz7SB

**Comment by hobesman** [comment]
Just to add, based on the video that was shared in discord, the period of unavailability of local books might be _after_ the app concludes the server is reachable but before the app receives enough data to load the full home page (which might never happen).

**Comment by advplyr** [comment]
@hobesman is correct. What was happening is the server connected successfully but the network connection going in and out causes the home page to reload the items on the server. Or there might be a case where one server request goes through to connect, but the server request to get the items times out.

The solution I put in place for this will be to show text at the top of the screen if server items are being fetched. If there are no local items and no server items then you will see the regular loading indicator.

![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/ca29a615-0928-49d3-8a1d-c0af26b42eea)

**Comment by advplyr** [comment]
Updated in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
