### ISSUE TITLE
Android: Universal back button/gesture does not go back when reading Ebook

### ISSUE THREAD

**Issue by lerndmina** [advplyr/audiobookshelf-app#709]
### Steps to reproduce

1. Open the app
2. Open an Ebook
3. Use the back button
4. Observe the loading popup
5. Observe nothing else happens
6. Use the back button again
7. Observe dialogue asking to close the app.

### Expected behaviour
- The back button should close the book and return to the previous screen.

### Actual behaviour
- Unexpected behaviour, from what I can tell the book overlay stays open while the things behind it go back.

### Environment data

Audiobookshelf Version: [v0.9.64-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.64-beta)

- [X] Android App?

#### Android Issue
Android version: 13

Device model: Pixel 7 A

Stock or customized system: Stock

Video showing the issue.  

https://github.com/advplyr/audiobookshelf-app/assets/10632157/fd5996af-1a46-45fa-af71-cab2b2b78e97

**Comment by advplyr** [comment]
Fixed in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
