### ISSUE TITLE
Problem with rClone

### ISSUE THREAD

**Issue by phampyk** [advplyr/audiobookshelf-app#71]
I've got an issue with the app and rClone. I've got a bunch of other apps accessing the rClone folder without issue (radarr, sonarr... Everything on docker) but since I installed audiobookshelf  sometimes when I scan the library it dismounts the rClone folder and the only workaround is reboot the whole raspberry pi. Sometimes it works without issues, but specially when I force re-scan is when it happens. 
Is there anything I can do to fix that?

**Comment by advplyr** [comment]
This may be related to: https://github.com/advplyr/audiobookshelf/issues/188

I'm not convinced this is an audiobookshelf problem, still need more data.
