### ISSUE TITLE
Save scroll position on item page

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf-app#717]
### Steps to reproduce

1. Open up a list of a podcast episodes
2. Select the filter "Show all"
3. Scroll down in the list and open up the description of an individual podcast episode
4. Click the Back-arrow in the top left

### Expected behaviour
- I should be positioned in the list where I left and with the filter I set

### Actual behaviour
- I am kicked back to the top of the episode list with the filter reset to "Incomplete"

### Environment data

Audiobookshelf Version: 2.2.20

- [ ] Android App?
- [X] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 16.3.1

iPhone model:
14 Plus

**Comment by advplyr** [comment]
Updated in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
