### ISSUE TITLE
Do not show toast for items marked as finished/unfinished

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf-app#718]
### Steps to reproduce

1. See attached screenshot
![image](https://github.com/advplyr/audiobookshelf-app/assets/4344284/281ddf74-fca4-40e0-a26a-0de22f08c526)

### Expected behaviour
- The popups shouldn't be there at all in an ideal world

### Actual behaviour
- The popups cover up the player

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [X] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 16.3.1

iPhone model:
14 Plus

**Comment by advplyr** [comment]
Updated in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
