### ISSUE TITLE
[iOS] Can't play "Finisheed" podcasts in offline mode

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf-app#719]
### Steps to reproduce

1. Mark a podcast episode as "Finished"
2. Download that same episode
3. Go ofline. I disabled Wifi and enabled flight mode
4. Try to play the just downloaded episode.

### Expected behaviour
- The episode should start playing from 0:00

### Actual behaviour
- Even if I go back online, the ep is now in a perpetual "Finished" mode and is unplayable in the app. The progress is immediately set to whatever the length of the ep is.

### Environment data

Audiobookshelf Version: 2.2.20

- [ ] Android App?
- [X] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 16.3.1

iPhone model:
14 Plus

**Comment by advplyr** [comment]
Fixed in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
