### ISSUE TITLE
BUG: Playing downloaded file crashes android launcher (OnePlus)

### ISSUE THREAD

**Issue by TheBinaryLoop** [advplyr/audiobookshelf-app#72]
### Steps to reproduce

1. Open App
2. Download file (.flac)
3. Press play on the downloaded file

### Expected behaviour
- The app should play the file like it does with the stream

### Actual behaviour
- The app crashes the android launcher

### Environment data

Audiobookshelf Version:

- [x] Android App? 0.9.35-beta
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model: OnePlus 8 Pro (IN2023)

Stock or customized system: Stock (OnePlus)

#### iOS Issue
iOS Version:

iPhone model:

**Comment by rubbo898** [comment]
Same here, my oneplus 8 crash and I have to reboot the whole device!

**Comment by advplyr** [comment]
Yeah this seems to be about 10% of users and because I can't reproduce the problem on any of my devices it is difficult to debug. For most people it seems if they choose a different folder to download to it can work that way.
That could be a temporary solution to try

**Comment by rubbo898** [comment]
I've just tried to switch folder but same results, phone crashed

**Comment by advplyr** [comment]
I thought I had finally replicated this when I tested on a Nexus 6 playing the downloaded audiobook was causing the phone to lock up and flicker for a few seconds before crashing. It was also showing "System UI is not responding".
Then it started working normally, so I think that was just an emulator hardware issue.

Is there any information shown about the crash? Does it crash instantly when pressing play? What is happening that is forcing you to restart the device?

**Comment by rubbo898** [comment]
The device become unresponsive with display blinking and I'm only able to press the power button to reboot. Starting it stop at the recovery with logs of the crash but I can't understand how to collect and share them with you

**Comment by TheBinaryLoop** [comment]
I'm going to try and use adb to collect some logs. I'll post them here if I find something
  

  

  

  
  
  
  
  
>

**Comment by TheBinaryLoop** [comment]
I found these two lines, but i don't know what they mean:

12-31 22:53:23.391  1725  5235 E ScreenModeService: getAppToken ActivityRecord{9c75691 u0 com.audiobookshelf.app/.MainActivity t32416}
12-31 22:53:23.391  1725  5235 E ScreenModeService: setRefreshRate token ActivityRecord{9c75691 u0 com.audiobookshelf.app/.MainActivity t32416} rate 0 tmpRate 0

@advplyr I captured the complete crash via logcat but i cant seem to find any important information. If you want i can send you the full trace privately.

**Comment by advplyr** [comment]
I'm not sure what that means either. It would be great if you can send it to me via email advplyr@protonmail.com

**Comment by advplyr** [comment]
When looking through the logs the error I'm seeing has to do with reading the locally downloaded cover image. 

If you can remove a cover on one of your audiobooks on the server and download it in the mobile app, that would help us see if it is just the cover images.

That log is very useful, thanks for sending that.

**Comment by TheBinaryLoop** [comment]
Without the cover, it works like a charm.

**Comment by advplyr** [comment]
That is great news, finally some progress on this issue.
Now to see if @rubbo898 has the same issue

**Comment by TheBinaryLoop** [comment]
How hard is it to fix this issue?

**Comment by advplyr** [comment]
Anywhere from "just needed to put a space there" to "we have to start from scratch to fix it".

**Comment by TheBinaryLoop** [comment]
It looks like the path, that was build by the app is wrong: 
content://com.android.externalstorage.documents/tree/primary%3AAudiobooks/document/primary%3AAudiobooks
instead of:
content://com.android.externalstorage.documents/tree/primary/Audiobooks/...

**Comment by advplyr** [comment]
I don't think so. When the uri is decoded it becomes:
content://com.android.externalstorage.documents/tree/primary:Audiobooks/document/primary:Audiobooks

Although it might be wrong, I don't think there should be a / there

**Comment by TheBinaryLoop** [comment]
I meant the primary:Audiobooks part... I don't think that part should be in there multiple times

**Comment by advplyr** [comment]
The main thread for this issue will be #35
