### ISSUE TITLE
mka file is neither playable nor downloadable in android-app

### ISSUE THREAD

**Issue by dunjii** [advplyr/audiobookshelf-app#722]
### Steps to reproduce

1. add audiobook (mka format) in audiobookshelf library
2. try to play or download in android app

### Expected behaviour
- files should be playable

### Actual behaviour
- it seems like the file is ignored

### Environment data
- other apps like voice play mka files without problems. so it should not be a problem of android per se

Audiobookshelf Version:

- [x] Android App

#### Android Issue
Android version: app-version 0.9.64-beta on android 13

Device model:
FP4

Stock or customized system: iodé 4.1

**Comment by advplyr** [comment]
I just tested an MKA file on Android 13 using a Pixel 6. It was able to direct play, download and play locally without a problem.

Using sample file https://software-download.name/sample-mka-audio-file/download.html

Let me know if you have something I can reproduce.

**Comment by dunjii** [comment]
I tried the testfile. It's working. Hm. 
All the mp3-based books, i merged to mka files with MKVToolNix, before i got to know your awesome software, are not playable on my android phone.
Try this one: https://next.dezentrale.cloud/s/KWqZmemH6bdiaAf to reproduce.

**Comment by advplyr** [comment]
Just tested that and it is working for me. I could stream direct, download and play local.

**Comment by dunjii** [comment]
Hm. Okay, strange. So i will search for my own or use the m4b-converter. :) Thx so much for this wonderfull software!
