### ISSUE TITLE
Menu colors inconsistent

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf-app#723]
### Steps to reproduce

When switching library, the currently active library is a lighter tone and other libraries are a darker tone. Everywhere else in the app the "current page" is the one with the darker tone. See attached screenshots

This is the library selector. The currently open library is Audiobooks
![image](https://github.com/advplyr/audiobookshelf-app/assets/4344284/1292edf3-8c26-4719-8155-1e1d9abb26d9)

This is the menubar in the app. The currently open page is the Home page
![image](https://github.com/advplyr/audiobookshelf-app/assets/4344284/f7fccbe3-b887-414b-b378-7c30faefa63d)

Audiobookshelf Version: 2.2.21

- [X] iOS App?

iOS Version: 16.3.1

iPhone model:
14 Plus

**Comment by advplyr** [comment]
Updated in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
