### ISSUE TITLE
closeSession / Removed session

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf-app#724]
### Steps to reproduce

1. start play on mobile
2. stop play and close app
3. open app again and start listened book again

### Expected behaviour
- Tell us what should happen
play after last saved time 

### Actual behaviour
- Tell us what happens
closeSession / Removed session > start from 0

> 2023-05-28 20:24:25

> DEBUG

> [PlaybackSessionManager] syncSession "play_4p6ptroevd4nksgg1b" (Device: SM-T725 SDK 30 / v0.9.64-beta) | Total Time Listened: 1186

> 2023-05-28 20:24:25

> DEBUG

> [DB] Updated user: 1

> 2023-05-28 20:24:27

> DEBUG

> [DB] Updated session: 1

> 2023-05-28 20:24:35

> DEBUG

> [Server] User Offline Skyzuma

> 2023-05-28 20:24:35

> INFO

> [Server] Socket RlEvmyMiJw-vl2gfAAA4 disconnected from client "Skyzuma" after 12807ms (Reason: transport close)

> 2023-05-28 20:24:47

> INFO

> [Server] Socket Connected FqP1aKTR9v8kELQrAAA6

> 2023-05-28 20:24:47

> DEBUG

> [Server] User Online Skyzuma

> 2023-05-28 20:24:47

> DEBUG

> [DB] Updated user: 1

> 2023-05-28 20:25:01

> DEBUG

> [PlaybackSessionManager] startSessionRequest for device SM-T725 SDK 30 / v0.9.64-beta

> 2023-05-28 20:25:01

> INFO

> [PlaybackSessionManager] startSession: Closing open session "Das Herz der Zwerge 1" for user "Skyzuma" (Device: SM-T725 SDK 30 / v0.9.64-beta)

> 2023-05-28 20:25:01

> DEBUG

> [DB] Updated session: 1

> 2023-05-28 20:25:01

> DEBUG

> [PlaybackSessionManager] closeSession "play_4p6ptroevd4nksgg1b"

> 2023-05-28 20:25:01

> DEBUG

> [PlaybackSessionManager] Removed session "play_4p6ptroevd4nksgg1b"

> 2023-05-28 20:25:01

> DEBUG

> [PlaybackSessionManager] "Skyzuma" starting direct play session for item "li_8m0skslpl2r7h0xpiq" with id play_0onousiacpzl0ay7b5 (Device: SM-T725 SDK 30 / v0.9.64-beta)

> 2023-05-28 20:25:06

> DEBUG

> [PlaybackSessionManager] syncSession "play_0onousiacpzl0ay7b5" (Device: SM-T725 SDK 30 / v0.9.64-beta) | Total Time Listened: 2

### Environment data
v0.9.64-beta

Audiobookshelf Version: 2.2.21

- [x] Android App?

#### Android Issue
Android version: 11

Device model: SM-T725 SDK 30

Stock or customized system: stock

**Comment by advplyr** [comment]
I don't understand. The opening/closing of sessions doesn't have to do with your progress.

**Comment by skyzuma** [comment]
if i play any book and stop it after maybe 30 min, close and reopen the app and play the book again it should be start from saved 30 min and go on ... but its resets the progress and starts with 0 sec. as u can see in the log ...

**Comment by advplyr** [comment]
The log doesn't show the start time. Are you able to see the updated progress in the UI before you press play again?

**Comment by skyzuma** [comment]
if i reopen the app ...

your progress: 2%
NaN hr remaining

i think this is only for this book i played befor update server and app ... i tested an other but cant see the same issue ...

**Comment by skyzuma** [comment]
update: i tryed "discard progress" and start again ... now i can see the progress and all is ok ...
