### ISSUE TITLE
App crashes when I try to use chromecast

### ISSUE THREAD

**Issue by peterandreasrothe** [advplyr/audiobookshelf-app#727]
### Steps to reproduce

1. Connect to chromecast device
2.
3.

### Expected behaviour
- the app should connect to my chromecast device and start playing. I've tried several devices

### Actual behaviour
- the app crashes. No error messages or anything

### Environment data

Audiobookshelf Version:

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: pixel 7 pro

Stock or customized system: stock 

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Have you installed from the google play store?

Have you tested with different audiobooks? Maybe different audio formats (mp3 vs m4b)?

Is the chromecast device audio only?

Are you able to cast using the web app?

**Comment by peterandreasrothe** [comment]
Thanks for the swift reply. It seems to be related to the particular
audiobook (in m4b) which doesn't cast via the web interface either. I'm
sorry I didn't think to check that out before filing a bug report. Sorry
for the inconvenience.

Best Regards,

Peter Andreas Rothe


Den ons. 31. maj 2023 kl. 20.43 skrev advplyr ***@***.***>:
