### ISSUE TITLE
[Feature request] High contrast mode for android ereaders/visually impaired

### ISSUE THREAD

**Issue by last-available-username** [advplyr/audiobookshelf-app#728]
The android app is pretty usable on my android based e-ink reader, but it's difficult to read the title-text due to the lack of contrast between the grey background and the text.  The mode with the wood-grain bookshelf is slightly harder to read.

I'd love switch in settings to make the backgrounds globally white for better contrast OR force all text to be bright white,  even if it's ugly when enabled on color devices.

A high contrast mode might also help some people with poor vision.

**Comment by advplyr** [comment]
The next release will include a light theme option. I shared a screenshot of what it will look like here: https://github.com/advplyr/audiobookshelf-app/issues/916#issuecomment-1851099647

Will this be suitable?
