### ISSUE TITLE
BUG: ProgressSync switches progress between 100% and the real progress repeatedly

### ISSUE THREAD

**Issue by TheBinaryLoop** [advplyr/audiobookshelf-app#73]
The progress gets set to an extremely big negativ number (which is then 100% completion) and the again to the normal (real) progress.

**Comment by tzw9373** [comment]
I'm seeing this issue as well!

**Comment by TheBinaryLoop** [comment]
I noticed that the negativ number increases every time

**Comment by TheBinaryLoop** [comment]
![WhatsApp Image 2022-01-03 at 23 42 15](https://user-images.githubusercontent.com/13447164/147988443-3471a9ea-af6c-4bde-8666-e024e279f6e1.jpeg)
![WhatsApp Image 2022-01-03 at 23 42 25](https://user-images.githubusercontent.com/13447164/147988460-9907cf19-f229-4d50-a2f8-3ed25e9a52dd.jpeg)

**Comment by MidnightSnowleopard** [comment]
I haven't seen it hit the real progress on mine but I have started experiencing this exact issue on the mobile client with it displaying a large negative number and the progress set to 100%.

Client version is 0.9.35-beta and server is v1.6.49.  Unsure when it started manifesting like this or if it was present in previous versions.  Book being played with this behavior so far is a m4b with aac audio.  Haven't tested with different format/books on mobile client at this point.

**Comment by advplyr** [comment]
This will be fixed in the next release, the time remaining won't show when progress 100%.

**Comment by advplyr** [comment]
`v0.9.36-beta` is available now and should fix this issue
