### ISSUE TITLE
Full Screen For Ebooks

### ISSUE THREAD

**Issue by darthrater78** [advplyr/audiobookshelf-app#731]
Option to full screen ebooks, as well as a black color scheme.

**Comment by advplyr** [comment]
What type of ebook? Epub is already fullscreen. Are you using iOS or Android?

**Comment by darthrater78** [comment]
Android. Is not fullscreen, title of book is at the top as well as Android info bar. 
![Screenshot_20230604-182605](https://github.com/advplyr/audiobookshelf-app/assets/94141126/b57f9716-6b71-4570-8646-79d3af36e801)

**Comment by advplyr** [comment]
Is there an ereader app that you use with the fullscreen I can look at?

**Comment by darthrater78** [comment]
The only e-reader I used before this is Kindle, which is completely fullscreen.

**Comment by advplyr** [comment]
Updated in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)

**Comment by darthrater78** [comment]
Excellent! Thanks very much.
