### ISSUE TITLE
Playlists play from server, not downloaded files

### ISSUE THREAD

**Issue by revilo951** [advplyr/audiobookshelf-app#734]
### Steps to reproduce

1. Create playlist of podcasts
2. have those podcasts downloaded locally
3. Play from playlist

### Expected behaviour
- Local files would be played, not streamed from server

### Actual behaviour
- Files are streamed from server instead

### Environment data

Audiobookshelf Version: 2.2.22

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.64-beta

Device model: Samsung Galaxy S20+

Stock or customized system: Stock

**Comment by advplyr** [comment]
I have also added the downloaded icon
![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/a938f095-26fc-4d79-8b05-10acac946f1e)

**Comment by advplyr** [comment]
Fixed in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
