### ISSUE TITLE
[Feature Request] Book details and chapter name scrolling

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#740]
![Screenshot_2023-06-13-19-56-05-28_e9782661401ed6f222682e1e02b74bd4.jpg](https://github.com/advplyr/audiobookshelf-app/assets/42061703/4cf99fe6-3b27-4ac4-b34b-96873d6bd741)

I know that the functionality of viewing the book details was added a while back - tapping on the chapter name takes the user to the book details page. This was useful and important.

I'm suggesting a slight change to this functionality. 

1. Tapping the book cover takes the user to the book details
2. Tapping the chapter name scrolls the name so that the user can see the full chapter title.

Currently, there's no way to see the full title in any of the views - the player screen, the chapter list from the player screen or the ~~chapter list from the book details~~.

For non-fiction books, knowing the chapter name helps at times to understand the context of the chapter content. Especially, if someone plays the book at 2x+ speeds where the name might just slip by before the user/listener acknowledges it.

**Comment by lwobniar** [comment]
Positing here because I think it's related to this request. 

Re point #2 chapter title, when the title is too long, right now it just gets cut off on the screen. It would be nice if the title is displayed as scrolling text, so eventually you can read the full name if you wait 1-2 more seconds.

**Comment by advplyr** [comment]
For the next release (0.9.72-beta) scrolling is added. Scrolling is automatic after a short delay.

The minimized player is updated to show the title and chapter title in the format of "Title | Chapter" (previously only the title was shown on the minimized player).
![miniplayer_marquee](https://github.com/advplyr/audiobookshelf-app/assets/67830747/6a61c678-2eb6-4661-ad9f-b6684d5f15d8)

The fullscreen player will only show the chapter title the same as it has.
![fullplayer_marquee](https://github.com/advplyr/audiobookshelf-app/assets/67830747/ea9e1874-382f-4168-820e-767bd198d053)

**Comment by advplyr** [comment]
Added in [v0.9.72-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.72-beta)
