### ISSUE TITLE
Podcasts - Auto next episode

### ISSUE THREAD

**Issue by JReming85** [advplyr/audiobookshelf-app#742]
### Is your feature request related to a problem? Please describe.
I have a large amount of podcasts on my server, when listening to an episode when it ends it just stops playing and I have to manually wake my phone and play the next episode.

### Describe the solution you'd like
I would like it to automatically play the next unplayed episode for that podcast

**Comment by jacky9246** [comment]
me too

**Comment by ljy920325** [comment]
Has it been resolved yet？

**Comment by JReming85** [comment]
> Has it been resolved yet？

No

**Comment by advplyr** [comment]
Duplicate of #416

**Comment by ktfcaptain** [comment]
I can't take silence, and lose track of my phone all the time. 

I love this app and really hope this is coming. 🤞
