### ISSUE TITLE
Font size change in e-read

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf-app#745]
### Discussed in https://github.com/advplyr/audiobookshelf-app/discussions/744

<div type='discussions-op-text'>

<sup>Originally posted by **JotiGj** June 14, 2023</sup>
Hi,
I would like to thank for this amazing application.
One small feature, maybe a request or I am not able to find it. Is a possibility to change the size of font in fly, in e-read mode? Could be useful, for older people eyes... Thanks</div>

**Comment by advplyr** [comment]
Added in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)

**Comment by frollard** [comment]
Running v2.3.3 in Docker
Web-view, Chrome 115.0.57
Window scaling 100%

both font size and line spacing only affect line spacing
Default: 
![Default](https://github.com/advplyr/audiobookshelf-app/assets/1535306/32685809-cc63-4692-b8d2-5d95eb4fbf0e)
Font 200%
![Font size](https://github.com/advplyr/audiobookshelf-app/assets/1535306/ebf0b4fb-dce6-4040-bf02-f635ff1e42e5)
Spacing 200%
![Spacing](https://github.com/advplyr/audiobookshelf-app/assets/1535306/a31caf6b-4b5e-4f86-b779-3a57d1027a93)
Both 200%
![Both](https://github.com/advplyr/audiobookshelf-app/assets/1535306/a407a3e0-b801-41f9-92f9-71ce349bc139)

If I change chrome scaling it affects the page, but also all the UI elements, and they start to stack badly.

Inspecting the text element, it seems the sliders are both affecting relative row height, but not font size.
![image](https://github.com/advplyr/audiobookshelf-app/assets/1535306/31bd0f82-c569-4380-a273-9a46b3b5c507)
