### ISSUE TITLE
[iOS] UI form partially obscured by currently playing podcast when adding new podcast

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf-app#750]
### Steps to reproduce

1. Search for a new podcast and add it

### Expected behaviour
- The UI should be obscured by a currently playing podcast

### Actual behaviour
- The UI is obscured by a currently playing podcast

![image](https://github.com/advplyr/audiobookshelf-app/assets/4344284/7ff37722-3312-4568-9b8e-4bad8df6b18a)

### Environment data

Audiobookshelf Version:

- [x] iOS App?

#### iOS Issue
iOS Version:
16.5

iPhone model:
14 Plus

**Comment by advplyr** [comment]
Fixed in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
