### ISSUE TITLE
iOS epub "x" to close book nearly impossible to tap

### ISSUE THREAD

**Issue by Jmanko16** [advplyr/audiobookshelf-app#752]
### Steps to reproduce

1. Open epub book
2. Try to click close "x" on top right
3. Have to click multiple times to get it to close

### Expected behaviour
- Tell us what should happen
- "tap zone" for x needs to be bigger, shouldn't take multiple taps to close
- 
### Actual behaviour
- Tell us what happens

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [x] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 16

iPhone model: iPhone 12 (same on iPad Pro 11")

**Comment by advplyr** [comment]
Fixed in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
