### ISSUE TITLE
Hope to adjust the playback preview display of the iOS app.

### ISSUE THREAD

**Issue by Alano-i** [advplyr/audiobookshelf-app#756]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when playing audio.Hope to adjust the iOS preview information. 
Currently, the display content of the preview information cannot see the title of the chapter that is playing the audio

### Describe the solution you'd like
- Hope to be able to display the chapter title of the audio being played.
- Hope to be able to display the title of the audio being played.

<img width="1091" alt="image" src="https://github.com/advplyr/audiobookshelf-app/assets/68833595/2ccfbd7e-9a31-4a96-9767-bb36d7ac0e7e">

Thanks!

**Comment by advplyr** [comment]
Related #239 for android

**Comment by Alano-i** [comment]
> Related #239 for android

I saw that this issue seems to show that the chapter title has been developed, is it not released yet? The latest version of the test I am running does not yet have this feature.

**Comment by Alano-i** [comment]
https://github.com/advplyr/audiobookshelf-app/pull/372 This pr seems to have solved this problem, but it has not been merged. Can it be merged?
Thanks!

**Comment by benonymity** [comment]
This has been implemented in #1002

**Comment by advplyr** [comment]
Added in [v0.9.71-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.71-beta)
