### ISSUE TITLE
[Android] Downloaded audiobooks putting tracks out of order

### ISSUE THREAD

**Issue by wtanksleyjr** [advplyr/audiobookshelf-app#759]
### Steps to reproduce

I highly doubt this is reproducible, although once it happens I can find no way to make it stop. I've had it happen with Steakley's "Armor" and the following book, so let's go with the one I have loaded now. I'll keep it where it is for now so I can hopefully answer questions.

1. Borrow "Journey of the Mind: How Thinking Emerged from Chaos" by Ogi Ogas, Sai Gaddam from Overdrive, load into media library temporarily. Match against Audible.
2. ffwd to chapter 10, "Fish Mind."
3. Confirm that web player reads the chapter title "chapter 10, fish mind." Rewind a minute or so.
4. Download to app (I'm using Android).
5. Play, listen ... at chapter change, it will read the chapter title "chapter 13, rat mind," and go from there. The amount of audio played and remaining will be exactly the same as on the web player, but it's playing a different chapter.

### Expected behaviour
- Web player is correct; the app seems to do ... something with the chapters.

### Actual behaviour
- Missing chapters, apparently moved to some other place in the audio (the total length is the same, and the last few chapters are correct, but the third chapter from the last is probably the wrong one).

### Environment data

Audiobookshelf Version: 2.2.23

#### Android Issue

Android version: 0.9.65-beta

Device model: Moto g stylus g5 (2022), Android 12

**Comment by wtanksleyjr** [comment]
Oh, I forgot to say  that the audio before the chapter break is the same on both web player and app player; it's clear that it has the correct end-chapter and begin-chapter and smoothly skips over all the audio in between.

**Comment by advplyr** [comment]
When downloading the audiobook the file tracks are probably getting out of order. I think there is a bug report for this but I haven't reproduced it yet.

Check the file order of the downloaded book on the local media page

**Comment by wtanksleyjr** [comment]
Good question, all of the filenames look right, numbered in the same order
as their sort order should be... the sizes are all correct too (that is,
the same across both desktop and app). Just for fun I checked the ODM
chapter tags, they're all in the right place too.

-Wm

**Comment by advplyr** [comment]
Did you check the file order when you go to "Manage Local Files"?

**Comment by wtanksleyjr** [comment]
Yes, exactly, based on your description. It has a very conspicuous ordering
number in front of each title. I was very much expecting to see a
difference!

-Wm

**Comment by advplyr** [comment]
I don't understand what you mean. Are the tracks out of order?

**Comment by wtanksleyjr** [comment]
Unfortunately they're in perfect order, same for web and app. I checked the
file size too, they're all correct.

-Wm

**Comment by advplyr** [comment]
Just to double check you are looking at the audio files in the local media section of the app and not on the audiobook page in the app?

There are 2 places tracks are listed and one could come from the web and the other is the actual order that will be used for the downloaded media.

**Comment by wtanksleyjr** [comment]
Yes, the local media section of the app. I tried to describe it to you by
saying "it has  a very conspicuous ordering number in front of each title".
Oops, I should have said "file name" instead of "title." The ordering
number is in a bigger font than the filename, and then there's a duration
after each filename. The durations are all in the correct order.

I'm trying to manually move them around right now...

-Wm

**Comment by wtanksleyjr** [comment]
Is there a way to force it to reload? I can't seem to make it play the
tracks in the new order, it just sticks with the order I started with.

**Comment by advplyr** [comment]
I just tested and was able to change the order. I moved the first track below the second track. Then pressed saved.
Then you have to open the audio player again. If you have the audio player open to that book already then it will use the same order.

**Comment by advplyr** [comment]
I'm pretty sure there is a bug report open for this already but I couldn't find it so until then will use this as the out of order bug report.

**Comment by wtanksleyjr** [comment]
Perfect, all I have to do is close and reopen.

**Comment by wtanksleyjr** [comment]
Um... hard crash. HARD. Let me try to recreate that.

**Comment by wtanksleyjr** [comment]
Swapping two tracks where one of the tracks is what I'm currently playing
(and then closing and reopening the player) damages (something about) the
underlying book so that the player cannot even display anymore; it starts
playing without displaying the player, and then a couple seconds later the
app shuts down. I've tried playing a different book (works) and then
switching back to the old one (doesn't work).

**Comment by wtanksleyjr** [comment]
Oh, wow, my phone rebooted while I had it set down. That's odd.

**Comment by wtanksleyjr** [comment]
After reordering the files (to try to find if the missing chapter is in a
different file), I found that moving a file that the player is currently
reading, then closing and opening the player, results in a hard crash
that's apparently permanent.

I am only able to play this book by streaming now; local downloads 100%
break when I press play even if I delete everything, reboot, and download
to a new place. (Fortunately streaming works -- and since I work from home
I can stream without using data.)

-Wm

**Comment by wtanksleyjr** [comment]
Quick update: the files have the correct contents, they play correctly in other local players when I download with ABS (and of course I can stream fine). But the crash is permanent, I can no longer play downloaded no matter what I try.

**Comment by gazpachoking** [comment]
> it starts playing without displaying the player, and then a couple seconds later the app shuts down.

Is this maybe the same as #773? This has been happening to me recently (although not the order problem.)

**Comment by advplyr** [comment]
This may have been an issue with the scan feature that was in Android and removed as of v0.9.67-beta.
Can you confirm if you are still getting out of order audio tracks on the latest release from new downloads?

**Comment by wtanksleyjr** [comment]
Quick comment: a fix for me was to use AudioBookShelf's feature to convert
to m4b (the last tab when editing the book, "Tools" I think). The problem
only ever was in the mp3 player.

-Wm

**Comment by advplyr** [comment]
Sounds good we'll consider this closed until it is reproduced again
