### ISSUE TITLE
Series Tab in App is Not Sorted Alphabetically (sort-of)

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf-app#76]
### Steps to reproduce

1. Open App
2. Navigate to 'Series' tab
3. Series are not completely sorted alphabetically (see below for description)

### Expected behaviour
- When I go to the series tab, all of the book series should all be listed in alphabetical order from A to Z. 

### Actual behaviour
- Instead of every series being listed in alphabetical order, groups of 10 - 15 book series are listed in alphabetical order, and then the next 10 - 15 book series are then listed in a separate alphabetical order, and so on. So instead of one big alphebetized list, the list has multiple alphebetized lists (hopefully that makes sense). 
- The server shows the correct alphabetical order for series. 

### Environment data

Audiobookshelf Version: 1.6.50

- [X] Android App

#### Android Issue
Android version: 11 - app version 0.9.35-beta

Device model: OnePlus 8T

Stock or customized system: Stock

**Comment by advplyr** [comment]
This should be fixed with the latest server update.
Also noted in this issue: https://github.com/advplyr/audiobookshelf/issues/295

**Comment by feerlessleadr** [comment]
Thanks - can confirm this is fixed.
