### ISSUE TITLE
Android Notification Pulldown Interface Enhancement

### ISSUE THREAD

**Issue by truthsword** [advplyr/audiobookshelf-app#762]
### Is your feature request related to a problem? Please describe.
When using the Android notification pulldown to manager the player, the playbutton is quite small and close to other interface features that may be accidentally triggered. This is particulalry frustration when using the player in a vehicle.

### Describe the solution you'd like
I recommend an alternative layout. As an example, of a layout I find quite helpful is this:

![](https://i.imgur.com/R48jNtm.png)

Please note the enlarged play/pause button, and the spacing of the advance, and rewind controls.

I would love to see this design for the Android app.

Here is another app that has taken a similar approach:

![](https://i.imgur.com/QI3r3uH.png)

**Comment by advplyr** [comment]
This is how the latest version looks v0.9.65-beta

Not sure which version you are on but let me know if for some reason yours doesn't look like that on the latest version.

**Comment by truthsword** [comment]
Amazing what an update will do. Thanks!

Jun 27, 2023 4:03:47 PM advplyr ***@***.***>:
