### ISSUE TITLE
Show progress while reading ebooks

### ISSUE THREAD

**Issue by FuzzyWereBeast** [advplyr/audiobookshelf-app#766]
### Describe the solution you'd like

I would like to see the progress of where I am in the chapter or book at the bottom of the screen similar to other ereaders. A simple (4/23) would suffice.

**Comment by advplyr** [comment]
The percent progress is already shown. Epubs don't really have a page number. Are you talking about epub ebook?

**Comment by FuzzyWereBeast** [comment]
I'm speaking about when you are in the ereader, not when you are looking at the book overview.  When you are viewing an epub on a Kindle or in Calibre, you get a progress update in the bottom right of the screen that shows what "page" you are on vs. how many "pages" you have left in that section.

**Comment by advplyr** [comment]
For me on kindle the bottom right is a percentage (same as Abs) and the bottom left is a location. I'm not sure how the location is useful since it changes based on the screen size.

I don't know what the calibre mobile app looks like but the calibre desktop ereader shows a percentage in the bottom right the same as Abs.

Can you share screenshots of the page number you are seeing?

**Comment by FuzzyWereBeast** [comment]
It's just a nice visual as to where you are in relation to the end of the chapter.

![Screenshot_20230701-140821_Moon+ Reader Pro.jpg](https://github.com/advplyr/audiobookshelf-app/assets/32906753/669058fd-b677-447a-b8b0-5609ca29cd99)

**Comment by advplyr** [comment]
What part is showing your relative position in the chapter?

**Comment by FuzzyWereBeast** [comment]
middle bottom.  "Chapter 1 (1/78)"

**Comment by advplyr** [comment]
Are there 78 chapters?

**Comment by FuzzyWereBeast** [comment]
No. There are 78 pages in the 1st chapter based on the current view settings.

**Comment by advplyr** [comment]
Added a location in the bottom left of the book. I think this is the best we're going to get with this library.
