### ISSUE TITLE
Andorid App Book Postion Lost

### ISSUE THREAD

**Issue by brianalsum** [advplyr/audiobookshelf-app#77]
I've been using ABS for a few weeks now. I love it! However there is one issue that keeps bugging me.

I consume Audio books at a prodigious rate. 1-2 a day.... every day of the work week. I'm constantly pausing my books and coming back to them. for the most part ABS doesn't have a problem it may rewind a few seconds but that's more of a feature than an issue. However at the end of the day when i get out of my truck for the night to go to bed and come back to the book the next morning... I'm hours behind in the book. I do not know if this issues is just android or also in iOS.

**Comment by brianalsum** [comment]
No android auto
0.9.35-Beta

It happens regardless of being in the car or head phone

**Comment by advplyr** [comment]
Are you listening to downloaded audiobooks?
I just found a bug with the progress sync for downloaded audiobooks that I'm fixing.

**Comment by brianalsum** [comment]
Yeah, downloaded books. I'll see if I can narrow it down with some of the variables. It does seams that the long a I'm away tye farther back the book goes.

**Comment by advplyr** [comment]
A big part of it was a server side issue that I just pushed a release for `v1.6.53`. That may solve it, then there will be an app release that may take a week to be available.

**Comment by tvories** [comment]
I mentioned it in my issue, but `v1.6.53` doesn't seem to have solved the issue for me on my phone.  Obviously I haven't tried the updated app yet.

**Comment by FlamingoDaBird** [comment]
Hi.

I've noticed this behavior in my downloaded audiobook about a week ago. When I've  not listened for a while, say a few hours it has re-winded about 20 minutes. I've noticed this in two occasions.

**Comment by advplyr** [comment]
I believe I resolved this issue in the latest release (v0.9.39-beta) for downloaded audiobooks while you are connected to your server.

The issue had to do with the progress sync not happening for downloaded audiobooks while your phone was asleep.

Also explained here #74
