### ISSUE TITLE
iOS App constantly closing

### ISSUE THREAD

**Issue by kirsch33** [advplyr/audiobookshelf-app#770]
### Steps to reproduce

I listen on my AirPods or car head unit over CarPlay mostly, and I've noticed specifically with the latest update that after pausing a book that the entire app is auto-closing. I'm not sure what  specifically needs to be done to reproduce but its happening 5-10 times a day (i listen frequently). Not sure if it matters but this is with books ive downloaded locally.

i dont remember this happening with the previous version but i havent tried downgrading to test if it goes away.

### Environment data

Audiobookshelf Version:

0.9.65

server version 2.2.23

#### iOS Issue
iOS Version: 16.5.1

iPhone model: 13

**Comment by gh0sti** [comment]
I'm wondering if it has to do with this bug coming up again. https://github.com/advplyr/audiobookshelf-app/issues/471

**Comment by kirsch33** [comment]
@gh0sti  i think so for sure because after further testing it does not happen if I'm tunneled into my VPN or on my local network. Only with local files while operating the app off-network.

**Comment by gh0sti** [comment]
So I deleted the downloaded books and redownloaded them and the app is working again.

**Comment by kirsch33** [comment]
so im still dealing with this and actually I think it doesnt have anything to do with downloaded vs streaming. 

it seems to happen when Im listening to a book over airpods/carplay/bluetooth and when I either get out of range or when I pause the audiobook from outside of the actual app. for example, phone locked and listening to audiobook and I double tap an airpod to pause, app closes. or, listening on carplay and turn off truck (which tells ABS to pause but not directly interfacing with the app physically)

very frustrating.

**Comment by KaiStarkk** [comment]
Having this problem also. It seems like it might be an iOS limitation. Also happens with the YouTube app. Whenever you pause (talk to someone, think about a scene, just have to do something else for a couple minutes) it’s a dice roll whether the app will be closed by the system to save memory. And when you reopen, it starts at the home page as if it was force quit. 

Not sure if there is a way to prevent this like keeping the app live somehow.

**Comment by kirsch33** [comment]
agreed with @KaiStarkk 

there seems to be a lot of randomness on when it decides to quit, thats why the few week lag between when I initiated this issue and replied above this week. I was trying to pinpoint exactly when it was happening but couldnt.

regardless, this is happening multiple times daily, and really the only issue I have with the app at all.

**Comment by KaiStarkk** [comment]
Can also confirm that this doesn’t happen on Android phone, only iPhone. 

I’m shocked that this problem as well as #686 and #622 exists even for YouTube (meaning it’s an iOS problem). How are iPhones still so popular… forced to use this one for work.

**Comment by kirsch33** [comment]
@KaiStarkk upgrading to the latest audiobookshelf server version has pretty much solved this issue for me. therefore I am going to close this issue for now unless it comes back.

**Comment by kirsch33** [comment]
relating also to #844 i think, im reopening this because im all the sudden having this issue again quite often

**Comment by aweb-01** [comment]
Also having this issue. I primarily use downloaded local copies of the audiobooks which seems to align with the conversation here so far.

**Comment by kirsch33** [comment]
Yeah this is still constantly an issue for me as well

**Comment by gh0sti** [comment]
Been happening since iOS 17 for me even on iOS 17.1

**Comment by nichwall** [comment]
There are several open issues regarding this bug, which makes it hard to track. For many people, completely reinstalling the iOS app has fixed the issue (probably something hanging around from previous versions, like an erroneous listening session or item id).

Can you try reinstalling the app and see if it fixes the issue? This is regardless of when you first installed, since some people who installed 2.4.4 and 0.9.66 as their first version had the issue fixed by reinstalling.

https://github.com/advplyr/audiobookshelf-app/issues/910#issuecomment-1773891343

**Comment by gh0sti** [comment]
> There are several open issues regarding this bug, which makes it hard to track. For many people, completely reinstalling the iOS app has fixed the issue (probably something hanging around from previous versions, like an erroneous listening session or item id).
> 
> Can you try reinstalling the app and see if it fixes the issue? This is regardless of when you first installed, since some people who installed 2.4.4 and 0.9.66 as their first version had the issue fixed by reinstalling the iOS app.
> 
> [#910 (comment)](https://github.com/advplyr/audiobookshelf-app/issues/910#issuecomment-1773891343)

reinstalling the app seemed to fix it for the time being. What was odd was getting a new iPhone which would have had a fresh install of ABS from testflight which would still cause this issue. 15 PM on iOS 17.1

**Comment by kirsch33** [comment]
reinstalling fixed for me as well, so I am closing this issue

**Comment by aweb-01** [comment]
Probably fine to close this since it’s a duplicate with this other bug, but as I commented there yesterday, the issue returned for me a week after reinstalling the app (possibly when my phone upgraded to 17.1). 

Ref: https://github.com/advplyr/audiobookshelf-app/issues/910#issuecomment-1786600081
