### ISSUE TITLE
[Bug] Incorrect spacing around commas

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#777]
![Screenshot_2023-07-07-19-58-10-84_e9782661401ed6f222682e1e02b74bd4.jpg](https://github.com/advplyr/audiobookshelf-app/assets/42061703/8ff8ed12-bad5-48b1-b73e-f11d98fb92ff)

As seen from the screenshot above, the comma delimiter between narrators and tags uses incorrect spacing.

It's supposed to be item 1, item 2, item 3 and not item 1 ,item 2 ,item 3

Not a big problem, just an aesthetics issue, but still reporting.

**Comment by advplyr** [comment]
Fixed in [v0.9.66-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.66-beta)
