### ISSUE TITLE
Android app jumps to the end of the book. 

### ISSUE THREAD

**Issue by ChiefMedicalOfficer** [advplyr/audiobookshelf-app#78]
### Steps to reproduce

1. Play a book
2. Pause for more than 30 minutes (possibly longer)
3. Open app. 

### Expected behaviour
- Tell us what should happen

Book should be at the position it was paused at. 

### Actual behaviour
- Tell us what happens

When opening the app after a period of time the book will be at the very end. Just before this happens the current position and end times will be huge numbers, usually in the thousands. 

### Environment data

Audiobookshelf Version: 1.6.35 (docker install) 

- [x] Android App? 0.9.35-beta
- [ ] iOS App?

#### Android Issue
Android version: 8

Device model: Samsung Galaxy S7

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

This is also happening to a friend on Android version 11.

Server logs from the last time I paused to the issue occurring.

```
{"timestamp":"2022-01-07T16:02:19.416Z","message":"[Stream] Update client current time 6392:19:37.0","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-07T16:02:19.416Z","message":"[Server] clientEmitter - no clients found for user root","levelName":"ERROR","level":4}
{"timestamp":"2022-01-07T16:02:19.421Z","message":"[DB] Updated user: 1","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-07T16:02:19.798Z","message":"[ApiController] syncStream for root - ","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-07T16:02:19.798Z","message":"[StreamManager] streamSyncFromApi stream not found ","levelName":"ERROR","level":4}
{"timestamp":"2022-01-07T18:30:13.487Z","message":"[SOCKET] Socket Connected -3y0H_Sn6_4moQ6VAADP","levelName":"INFO","level":2}
{"timestamp":"2022-01-07T18:30:13.496Z","message":"User has stream open already str_pe012d6qgc5gpaxndc","levelName":"INFO","level":2}
{"timestamp":"2022-01-07T18:30:13.496Z","message":"[Server] User Online root","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-07T18:30:13.502Z","message":"[DB] Updated user: 1","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-07T18:30:52.738Z","message":"[Stream] Update client current time 9:09:01.0","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-07T18:30:52.757Z","message":"[DB] Updated user: 1","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-07T18:30:52.830Z","message":"[ApiController] syncStream for root - ","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-07T18:30:52.830Z","message":"[StreamManager] streamSyncFromApi stream not found ","levelName":"ERROR","level":4}
```

Further logs after it occurred again. 

```
"timestamp":"2022-01-09T16:25:36.632Z","message":"[Stream] Update client current time 3237:18:08.0","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:25:36.640Z","message":"[DB] Updated user: 1","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:25:36.676Z","message":"[Stream] Update client current time 3:14:13.0 | Add listening time 1s, Total time listened 8940s","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:25:36.689Z","message":"[DB] Updated session: 1","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:25:36.689Z","message":"[DB] Updated user: 1","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:27:05.908Z","message":"[ApiController] syncStream for root - str_62tov55633sq9ei2uw","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:27:05.910Z","message":"[Stream] Update client current time 7496:35:05.0","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:27:05.922Z","message":"[DB] Updated user: 1","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:27:05.958Z","message":"[Stream] Update client current time 7:29:47.0","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:27:05.963Z","message":"[DB] Updated user: 1","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:27:08.458Z","message":"[ApiController] syncStream for root - str_62tov55633sq9ei2uw","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:27:08.458Z","message":"[Stream] Update client current time 0:00.0","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:27:08.464Z","message":"[DB] Updated user: 1","levelName":"DEBUG","level":1}
{"timestamp":"2022-01-09T16:27:13.449Z","message":"[ApiController] syncStream for root - str_62tov55633sq9ei2uw","levelName":"DEBUG","level":1}
```

**Comment by ChiefMedicalOfficer** [comment]
I've also noticed that whilst playing this on the android app the webui shows the book to be at the end.

**Comment by advplyr** [comment]
Please try again with the latest version

**Comment by ChiefMedicalOfficer** [comment]
Still happening on 1.6.55 & 0.9.36-beta.

Thanks.

**Comment by advplyr** [comment]
Is this happening with all of your audiobooks? Or are there any audiobooks this is not happening with?

At first thought it seems like the audio player may not be reporting back the duration of the audio track properly, which may be an issue with the audio files.

Does the web app handle progress correctly?

**Comment by ChiefMedicalOfficer** [comment]
Oh I should have mentioned I thought this was only happning with large m4b files but it's happening with mp3 too.

I've only used the web app briefly but what I noticed earlier on was that while listening on the Android app my book was at 4hrs 20mins but on the web app it was at 100% and 7hrs 29mins.

I've tried to replicate it and at first it seemed like it would happen after a certain amount of time (I listened to a book in work and it didn't happen one time with the longest pause being about 35 minutes) but now that doesn't seem to be the case. I can pause, lock my phone, open up 1 minute later and it's happened. 

If there's anything I can try just let me know.

Thanks again.

**Comment by ChiefMedicalOfficer** [comment]
Hasn't happened yet on web app. I've paused, started, closed browser, closed tabs. I'll pause for a while and go back to it.

I've noticed the log doesn't have errors since using web app.

**Comment by ChiefMedicalOfficer** [comment]
Seems the web app handles progress fine.

**Comment by tzw9373** [comment]
I'm seeing this issue as well: streaming only, multiple file types.

**Comment by shotgun2197** [comment]
I've noticed the same thing as well. Android 12.
The issue  occurs mostly after disconnecting from a Bluetooth source.

Ex.  If I'm listening in my car, shut it off, and then go to back to the player, most of the time it displays the end of the book. Of the book. In this scenario, I also noticed the player in the notification bar displaying 'null'.

One of the ways I combat this issue, is to pause it prior to shutting down. My car. Car. Seems to save progress more often that way. I'm not sure if it's because the app is loaded back into  the foreground, or if pause is sending the location back to the server

**Comment by advplyr** [comment]
Pausing does send the progress update to the server, but it should also be getting sent every 5 seconds anyway. I think disconnecting bluetooth triggers a pause also though.

Where were you seeing 'null'?

**Comment by tzw9373** [comment]
I have seen "null" in similar circumstances, like this. 
![Screenshot_20220110-112725](https://user-images.githubusercontent.com/50788362/148811090-10344427-2dac-4903-bfa1-039e5c73374a.png)

**Comment by shotgun2197** [comment]
> I have seen "null" in similar circumstances, like this. ![Screenshot_20220110-112725](https://user-images.githubusercontent.com/50788362/148811090-10344427-2dac-4903-bfa1-039e5c73374a.png)

Yeah, I've seen it exactly like this. Just in the drop-down player that hangs in the notification area. When I see it say null, I know I have to try to find my spot in the book again.

**Comment by advplyr** [comment]
Can you give step by step on how I can reproduce this? I've never had this

**Comment by shotgun2197** [comment]
I just tried to reproduce it, but it may be only after a longer duration of listening. 30-60 minutes.
It occurs for me when I'm listening on Bluetooth. Headset or my car. 
Start book from app > minimize app > listen for a while > turn off Bluetooth device without having app open. Turning my headphones or my car off does it 70% of the time. 
I'll try disabling battery optimization and see if that helps

**Comment by ChiefMedicalOfficer** [comment]
Reproduced this by closing the app while the audiobook was playing. The current position and total duration was 4439:27:34 / 3329:09:76. Had to close and re-open a couple of times for the duration to return to normal then the audiobook moved to 100% complete.

**Comment by ChiefMedicalOfficer** [comment]
Ok I tried the same thing with my bluetooth earphones disconnected 5 times and it didn't happen once.

Connected bluetooth earphones and it happened first time.

**Comment by feerlessleadr** [comment]
I'm seeing similar situations to both @shotgun2197 & @ChiefMedicalOfficer

**Comment by jaymarvels** [comment]
I have had this a couple of times now too. Streaming only.

This happened once when using the sleep timer and another time just normally playing/pausing and then returning to it.

Not sure if the track position is stored locally or server side to tell if it's an issue with the device storage handling or on the server

**Comment by ChiefMedicalOfficer** [comment]
Not sure if helpful but I've found that if I open the app initially to start a book then only use the drop down controls it will always keep its place but checking progress on the web app will still show 100% progress.

**Comment by jaymarvels** [comment]
I'm not sure if it also helps but when I open the app up initially it says "Not connected to server" before connecting and showing my books, I get a notification of the last book I was listening too once it connects, as well as the book completed.

**Comment by jaymarvels** [comment]
Also, was listening via Android Auto, when I pulled over I opened the app up on my phone, hit pause, which it did do, but then it went to the end of the book

**Comment by shotgun2197** [comment]
Disabling battery optimization did not help the situation. I've still had a few occurrences the past couple days

**Comment by feerlessleadr** [comment]
Not to pile on here, but in my use case, it seems like this is now happening 95% of the time I stop a book, regardless of whether I listen via Android Auto (majority of the time), bluetooth, wait to re-open the app (30 - 60 minutes), wait to open the app (5-10 minutes), etc. 

I can't find a discernable pattern, since it is happening more and more each time I use the app. I've had to resort to taking screenshots evey time I stop a book.

It definitely only happens with books that I'm actively listening to, since I have 2 other books "in progress" that I'm not actively listening to and they have not lost position.

**Comment by darkzero-sdz** [comment]
This seems to be the issue that prevents me from using this app as a daily driver for my audiobooks. Falling asleep to audiobooks with 100% finished in the morning isn't fun.

**Comment by advplyr** [comment]
This is fixed and live on the play store in [v0.9.37-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.37-beta)

---

For those interested, and future me, here is what happened.

The mobile app uses webview for most of the logic, leaving the android/ios specific features to be written in their native tongue. 
Webview gets closed when the app is in the background, which will stop the progress sync interval.

To solve for this I wrote [AudiobookProgressSyncer](https://github.com/advplyr/audiobookshelf-app/blob/master/android/app/src/main/java/com/audiobookshelf/app/AudiobookProgressSyncer.kt) for android native that also runs an interval timer and handles the progress sync when webview is closed.

That progress sync was sending milliseconds instead of seconds to the server, causing the audiobook to get set to 100% complete. Also, when webview was opened back up both progress syncs were running, so I updated the android sync to stop when webview is re-opened.

Pshew

**Comment by jaymarvels** [comment]
Glad you were able to find the issue, I was starting to suspect it was something to do with the app losing state in the stack, and I had noticed that the time bar was jumping up to a massive number on reopen and then being 100% which points to the millisecond issue you mentioned.

I guess you will have to add in a syncer for the native ios section too, this is one of the things when using hybrid tools like reactjs etc

**Comment by advplyr** [comment]
Yeah, I didn't even consider the implications of webview for a media app when starting this project. It will probably make more sense to move the progress sync entirely native at some point.

**Comment by tvories** [comment]
I wonder if this solves #74 as well

**Comment by ChiefMedicalOfficer** [comment]
Amazing. Thanks again.

**Comment by feerlessleadr** [comment]
Just to echo others, this bug appears to be fixed for me after extensive testing tonight. Thanks!

**Comment by ChiefMedicalOfficer** [comment]
This seems to have fixed another small issue I had. When my phone connection changed from data to wifi and vice versa the book would pause and I'd have to restart the app. Now it's working seemlessly.
