### ISSUE TITLE
[Enhancement]: Allow podcast to be queued to device before playing (ie: not streaming to device)

### ISSUE THREAD

**Issue by wanderling** [advplyr/audiobookshelf-app#782]
A setting on the UI to allow a podcast episode to be fully queued to device before starting to play. I have had numerous instances where I have asked for a podcast to play but the stream can't keep up. instead of waiting for the buffer to refill, the player stops playing and declares the playback 'finished'. Manual retries result in the same behavior. I am making a similar ask for the web UI as well.

**Comment by advplyr** [comment]
In the mobile app it should not get marked as finished when it is waiting for buffering. I haven't tested this yet on the web client.

Are you sure this is marking it as finished in the mobile app? Are you on a slow network connection when this is happening? Is the podcast episodes direct playing or are they transcoding?

You didn't mention what versions you are using and whether you are using iOS or android. I know the buffer can be adjusted on android but most users download when they are traveling without a good connection.

**Comment by wanderling** [comment]
Positve it is marking the podcast as finished and stopping playback. If there are other items in the queue it will move on to them.
It is possible this is due to a slow connection but still should not be the intended behavior at any connection speed. 

Hosted AudioBookshelf version: v2.2.23 (docker)
App version: Android 0.9.65-beta from Google Play Store

**Comment by advplyr** [comment]
The mobile app doesn't queue episodes. Are you sure this is happening in the mobile app?

**Comment by wanderling** [comment]
Sorry you are right the queue was on the webui. The app behaves similarly as it stops plaing the podcast requested. An additional note. The audiobook side works flawlessly in the app.

**Comment by advplyr** [comment]
Something may be going on with the podcast then because the audiobook and podcast episodes are using the same audio player. 

If this is happening only for podcasts on the mobile app and the web client then the audio files being played should be looked at.

**Comment by advplyr** [comment]
I think in cases where your network connection is very slow and the audio player is pausing to wait for buffering then you will be best off downloading the podcast episode. In your request you mentioned fully buffering the podcast episode which would be the same as downloading the episode.

We could tweak the buffer rate in some way but it doesn't sound like that's what you are requesting here so I'm going to close this one out.
