### ISSUE TITLE
UI Regression: Missing functionality in audiobook detail view

### ISSUE THREAD

**Issue by hyyyjinx** [advplyr/audiobookshelf-app#788]
### Steps to reproduce

A recent iOS app update seems to have introduced some UI changes which I assume were unintentional. 

1. You can no longer easily start or resume an in progress audiobook. The only way to start a new audiobook is to select a chapter via chapter view and kick of playbook this way.
2. Downloads to local device are no longer possible. The button is missing.

This is how the UI looks for me at the moment: 

![image](https://github.com/advplyr/audiobookshelf-app/assets/131786551/e6fe60d6-f07c-4821-b90e-b968c4c95b35)

If we compare this to the screenshot on the readme.md 

![image](https://github.com/advplyr/audiobookshelf-app/assets/131786551/0a4b32ee-9526-4875-ae95-2b6899fd2b45)

It is missing a row of buttons to stream/download below the cover above the progress indicator. 

**Versions**

app: 0.9.65 (iOS)
backend:  v2.3.0

**Comment by mateusz-bak** [comment]
Download button is missing as well on Android, app version 0.9.65-beta, backend v2.3.1.

**Comment by Schabernack** [comment]
somehow this automatically resolved for me last night without having applied an app or backend update. 

buttons are back, functionality restored.

**Comment by hyyyjinx** [comment]
Somehow this fixed itself for me without applying an app or backend update. 

Not sure what happened or if the fix is permanent but for now, functionality for me is restored.

**Comment by mateusz-bak** [comment]
Android issue still present, even after resinstalling the app.

**Comment by mateusz-bak** [comment]
Is anyone else experiencing this issue?
