### ISSUE TITLE
App does not give meaningful errormessage when changing password

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf-app#789]
### Steps to reproduce

1. Log in to the mobile app
2. Change password using the web ui
3. Try to access content in the app

### Expected behaviour
- The app should tell me my credentials needs updating or similar

### Actual behaviour
- Odd behavior and unclear errormessages, seen in the screenshot below
![image](https://github.com/advplyr/audiobookshelf-app/assets/4344284/ec3a4416-6ffd-43c0-8915-d9d8e01338cb)
- Also, according tho the app, I am still synced to the server, see the green cloud icon

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 16.5.1 (c)

iPhone model: 14 Plus

**Comment by ScuttleSE** [comment]
Hm, interestingly enough... after actually restarting the app I am still logged on, and with full access to the libraries and all the media, without having to update the password in the app.

**Comment by ScuttleSE** [comment]
Actually, wrong again, it seems like I can browse all the libraries, but actually opening a book or similar doesn't work

**Comment by advplyr** [comment]
Is this working now? I tested and cannot seem to reproduce this

**Comment by ScuttleSE** [comment]
Yeah, I think there was something else going on. I did change the password at the same time I upgraded to 2.3.0

What I am a bit confused about is that I am still logged in in the app, even though I changed password...

**Comment by advplyr** [comment]
I'm not sure. Let me know if you can reproduce this
