### ISSUE TITLE
Opening a book series gives an empty page

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf-app#790]
### Steps to reproduce

1. Open any book series

### Expected behaviour
- The books in the series should open

### Actual behaviour
![image](https://github.com/advplyr/audiobookshelf-app/assets/4344284/cbd40f53-451d-473b-b975-d486bab9e039)

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [x] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 16.5.1 (c)

iPhone model: 14 Plus

**Comment by CrowMash** [comment]
Same problem on Android after updating audiobookshelf server from 2.2.23 to 2.3.0.

**Comment by advplyr** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1914

**Comment by advplyr** [comment]
This will be fixed in the server patch coming soon
