### ISSUE TITLE
Fails to mark as finished

### ISSUE THREAD

**Issue by tyvsmith** [advplyr/audiobookshelf-app#794]
### Steps to reproduce

1. Using the latest Android app (.9.65-beta) 
2. Click overflow menu in book details page
3. Click mark as finished

Note that it successfully works from the same account on the web.

### Expected behaviour
- Should mark as finished succesfully

### Actual behaviour
- Red snackbar appears noting failed to mark as finished 

### Environment data

Audiobookshelf Version:

- [X ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: .9.65-beta

Device model: Pixel 7 Pro

Stock or customized system:
Stock (latest Android 13)

**Comment by advplyr** [comment]
I just tested this on 0.9.65-beta and the latest server version v2.3.2 and it is working correctly for me.

Are you using the latest server version?

Are you doing this on a downloaded book?

Is this happening for other books you have tried?

**Comment by tyvsmith** [comment]
Server is 2.3.2.
All books that are on server and not locally downloaded mark done as failed.
If I have a downloaded book locally, I can mark as done, but it's not reflected on the server.

**Comment by advplyr** [comment]
Can you check the server logs?

**Comment by tyvsmith** [comment]
Traefik logs show with access logs enabled show normal API requests for my library and when I click into a detail view, but show no API requests when I click mark as finished.


audiobookshelf server Logs has nothing related to the connection failure (just normal socket connection when device first syncs) when on debug on info:

```
2023-07-21 12:36:11

INFO

[Server] Socket Connected L1lglimtjXiFHpsnAAAT

2023-07-21 12:36:16

INFO

Received ping

DEBUG

Set Log Level to DEBUG
```

ADB Logs:

```
07-21 12:37:56.701  1235  4777 D ConnectivityService: requestNetwork for uid/pid:10495/22529 activeRequest: null callbackRequest: 39982 [NetworkRequest [ REQUEST id=39983, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10495 RequestorUid: 10495 RequestorPkg: com.audiobookshelf.app UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
07-21 12:37:56.705  1235  1680 D UntrustedWifiNetworkFactory: got request NetworkRequest [ REQUEST id=39983, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10495 RequestorUid: 10495 RequestorPkg: com.audiobookshelf.app UnderlyingNetworks: Null] ]
07-21 12:37:56.706  1235  1680 D OemPaidWifiNetworkFactory: got request NetworkRequest [ REQUEST id=39983, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10495 RequestorUid: 10495 RequestorPkg: com.audiobookshelf.app UnderlyingNetworks: Null] ]
07-21 12:37:56.706  1235  1680 D MultiInternetWifiNetworkFactory: got request NetworkRequest [ REQUEST id=39983, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10495 RequestorUid: 10495 RequestorPkg: com.audiobookshelf.app UnderlyingNetworks: Null] ]
```

**Comment by advplyr** [comment]
Are you able to test this using a local IP address to make sure the request isn't being intercepted by some middleware?

You could also try creating a bookmark or opening an RSS feed to see if other API requests are reaching the server.

**Comment by tyvsmith** [comment]
I can verify that in a bit, by exposing the port directly to the outside. I did check the debug webserver access logs sitting at the edge (traefik), and didn't see any entries for that request. Making me think it's entirely client side and not hitting the server.

 In the meantime, I'll note that if I stream a book from the server and jump into the middle, then that progress is tracked on the server.

I also asked in the Truecharts discord and someone else saw the same issue.

**Comment by tyvsmith** [comment]
Update. If I connect to the server by IP:port, then I can mark as finished.

As noted, that's the only client API that seems broken if running in a proxy and not hitting the server at all.

**Comment by advplyr** [comment]
This may be related to https://github.com/advplyr/audiobookshelf-app/issues/781#issuecomment-1633281274

Although, if you are able to create a bookmark then that would rule that out. 

Updating progress is happening natively, but marking as finished, creating bookmarks, & playlists are some things happening in webview. The next release all API calls will be made natively.
