### ISSUE TITLE
Android App Library tab in Podcast library is empty

### ISSUE THREAD

**Issue by awochna** [advplyr/audiobookshelf-app#795]
### Steps to reproduce

1. Create a Podcast library (media type = Podcast). This was not my first or "default" library, so that might be significant.
2. Populate Podcast library with some podcasts so that they show up in the web app's Library tab.
3. Browse to Podcast library in Android app (0.9.65-beta) and select the Library tab. Results say "0 Podcasts" and "No Books" instead of expected list of podcasts matching web app.

### Expected behaviour
- I should see a nice listing of the podcasts I've added to my server

### Actual behaviour
- I see "0 Podcasts" and "No Books" as if I don't have any podcasts added to my server

### Environment data

Audiobookshelf Version: 2.3.2

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.65-beta

Device model: Pixel 4a

Stock or customized system: Stock, Android 13

May be related to https://github.com/advplyr/audiobookshelf-app/issues/625

Unfortunately, I was unable to resolve this by:

* unselecting filters (none were selected)
* closing and reopening the app
* signing out and back in
* uninstalling and reinstalling the app

Screenshot from app showing "Library" tab with "0 Podcasts": 
![Screenshot_20230719-121156](https://github.com/advplyr/audiobookshelf-app/assets/3280320/232c59dc-2e2b-4b85-903a-916ab7c46469)

Screenshot from app showing "Latest" tab, populated with podcasts: 
![Screenshot_20230719-122006](https://github.com/advplyr/audiobookshelf-app/assets/3280320/d0495fd4-3a2e-4df5-a96f-5d9ea1c93ddb)

Thank you for all of your hard work! I can still reach target podcast episodes through other navigation means, so I'd definitely call this an inconvenience rather than broken :smile: 

Edit: formatting

**Comment by advplyr** [comment]
I'm not able to reproduce this but I'm testing on the latest server version 2.4.1. Are you still getting this on the latest server?

**Comment by awochna** [comment]
After updating my server to 2.4.1, I'm no longer seeing this issue in my Android mobile app. I now get a list of podcasts, a proper numbered label in the filter bar, and I can navigate to the podcast's details screen and back without issue!

Thanks for all your hard work!
