### ISSUE TITLE
on iOS in an audiobook library if you hit the collapse series checkbox it doesn't work correctly

### ISSUE THREAD

**Issue by brandonocasey** [advplyr/audiobookshelf-app#797]
### Steps to reproduce

1. Go to the audiobook library
2. Select the 3 dot menu
3. Select collapse series
4. Notice that series books are not collapsed. 
5. In my case I have 222 books and it moves to 55 books. In the webui it lists the series stacks and single books like I would expect. In the app it seems to be a random assortment of 55 books.

### Expected behaviour
- The series should be collapsed and non-series books should still be show 

### Actual behaviour
- A random assortment of books is shown according to the number of books that would be in your library with series entries collapsed.

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [X] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version:
0.9.65-beta
iPhone model:
iPhone 14 Pro Max

**Comment by advplyr** [comment]
This may have been an issue with one of the server releases you were on. Are you able to reproduce this with the latest server version 2.4.2?

**Comment by brandonocasey** [comment]
I cannot reproduce this anymore with new server/app versions.
