### ISSUE TITLE
[iOS] playback speed lost when closing the player or app

### ISSUE THREAD

**Issue by brandonocasey** [advplyr/audiobookshelf-app#799]
### Steps to reproduce

1. Start audiobook plackback and set a playback speed
2. continue playback
3. close the app
4. Open the app and start the book again, note that the playback speed is lost

### Expected behaviour
- playback speed should be maintained between app sessions. Possibly even synced between the app and web?

### Actual behaviour
- playback speed is lost

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [x] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 0.9.65-beta

iPhone model: Iphone 14 Pro Max

**Comment by advplyr** [comment]
Is this for a downloaded book or streaming or both?

**Comment by brandonocasey** [comment]
I think it happens for both after testing.

**Comment by holazit** [comment]
I have this same annoying problem too for a few days, I didn't have this issue with the previous version of Audiobookshelf.

**Comment by Drudoo** [comment]
Same issue here (on iOS)

**Comment by benonymity** [comment]
I think this has been solved and was a duplicate of #543

**Comment by advplyr** [comment]
Is this still an issue on v0.9.66?
