### ISSUE TITLE
Downloading audiobook crashes the Android system

### ISSUE THREAD

**Issue by scorpio862** [advplyr/audiobookshelf-app#8]
Recently I was pre-downloading every audiobook which I was listening. Today I noticed that my downloaded books disappeared so I wanted to download an audiobook again. 

When downloading finished my smartphone became unstable and I coudn't do anything on it so I had to force restart it.
After Android restarted it went straight to Recovery Mode. I reboted the phone again and Android was working fine until I started the Audiobookshelf app and Android crashed again like previously. 

I had to remove the downloaded book with file browser app and when I started the Audiobookshelf app it was working fine again.
I already had that problem before, when the downloading feature was added.

**Comment by advplyr** [comment]
Did you just update and this happened, or just the first time you downloaded on the new version?

What is your phone model and android version?

Side note:
If you had downloads on the previous version you may want to open the file system on your phone and delete those old downloads so they don't take up unnecessary space.

**Comment by scorpio862** [comment]
I've been using version 0.9.1-beta for couple of days with no problem. Until I tried to download an audiobook localy. 
I'm using Oneplus 8 Pro with android 11. 

When I noticed that my downloaded books are not showing up in the application, I checked the folder and it was empty.

**Comment by advplyr** [comment]
The app would not have deleted your old downloads, after the update it just wouldn't have detected them any longer, but they should still exist in your phones `/Audiobooks` directory.

When you select a folder to download too, were you selecting an SD card?

When you had this problem before, did it just resolve itself? Or maybe it was a specific audiobook that was breaking it?

**Comment by scorpio862** [comment]
Missing books is not the problem. Maybe I removed it somehow. 

I selected the folder called /Audiobookshelf as I already use /Audiobooks folder for another app that I used to play audiobooks. 
This folder is in my main storage, not on the SD card. 

I don't know how was this problem solved last time. I just didn't use Downloading option for some time and after few updates I tried again and it just worked. Until now. Last time it was a different audiobook.

**Comment by blueboysthlm** [comment]
I have the same issue on a Oneplus 9 Pro running OxygenOS 11.

If I download an audiobook and start playing it locally, the Android UI flickers and crashes completely. Have to do a hard reboot of the phone.

If I stream the audiobook I have no issues.

**Comment by advplyr** [comment]
#35 will be the main thread for this issue. It is a Oneplus permission issue with the cover image.
