### ISSUE TITLE
Progress bar difficult to use due to book duration

### ISSUE THREAD

**Issue by ThasLegendary** [advplyr/audiobookshelf-app#80]
### Is your feature request related to a problem? Please describe.
It is difficult to browse the audiobook because the progress bar represent the whole book. I'm used to another app where the progress bar represent the current chapter only. If I fall asleep while listening to a book it's hard to manually browser to the point I last remember listening.

### Describe the solution you'd like
The progress bar should allow browsing in the current chapter only and browsing between chapter is already present.

### Describe alternatives you've considered
None

### Additional context
None, just wanted to end with a thumb up for your work. I'm trying to migrate my current audiobook setup to audiobookshelf. I encounter some difficulties but overall your project feels very enjoyable. I hope you'll keep working on it and make it evolve. Thanks !

**Comment by advplyr** [comment]
In the dropdown menu at the top right of the fullscreen player there is a checkbox for "Chapter Track".

This will use the chapter as the main track and show the full track above. This setting gets saved so you only need to do it once.

**Comment by advplyr** [comment]
The original request for this is #46

**Comment by ThasLegendary** [comment]
Sorry didn't spot this option. Thanks for the quick reply (and not blaming me for my poor research before posting !).
