### ISSUE TITLE
[Bug] Epub ereader swiping moves two pages

### ISSUE THREAD

**Issue by brandonocasey** [advplyr/audiobookshelf-app#802]
### Steps to reproduce

1. Sometimes swiping to the next page will move two pages forward
2. Sometimes swiping to the next page will fail and the next swipe does two pages

### Expected behaviour
- it should only move one page

### Actual behaviour
- sometimes it will move two pages

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [x] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: iOS 16.5.1 (20F75)

iPhone model: iPhone 14 pro max

**Comment by insaneriot** [comment]
This is also an issue on the android version of the app.

**Comment by nichwall** [comment]
This is due to the third party library used to display epubs. I don't think a better one has been found

**Comment by advplyr** [comment]
This seems to be ebook dependent in my testing. I resolved one issue where this could have happened but did notice in one of the ebooks I tested there is still some weird behavior when swiping.
Let me know if this is reproducible on v0.9.66 for your ebooks

**Comment by insaneriot** [comment]
> This seems to be ebook dependent in my testing. I resolved one issue where this could have happened but did notice in one of the ebooks I tested there is still some weird behavior when swiping. Let me know if this is reproducible on v0.9.66 for your ebooks

Tested by multiple family members using my server, different devices, different epubs, seems the issue hasn't been replicated since the app update. 👍

**Comment by advplyr** [comment]
Awesome, thanks for helping to test
