### ISSUE TITLE
[Bug] Clicking title on fullscreen audio player navigates to the item page but doesn't switch library

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf-app#803]
### Steps to reproduce

1. Open library A with audiobooks and start playing a book
2. Switch to library B that has podcasts
3. Open up the currently playing book in fullscreen
4. Click on Author, Series, Narrator or Genre

### Expected behaviour
- The app should switch to library A and show any other books in the category clicked

### Actual behaviour
- The app shows an empty result

It was kinda hard to describe the error, so I'm attaching a video

https://github.com/advplyr/audiobookshelf-app/assets/4344284/25b13931-1eb0-4cb6-9226-2d5aa0099a5d

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 16.5.1 (c)

iPhone model: 14 Plus

**Comment by advplyr** [comment]
Fixed in [v0.9.66-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.66-beta)
