### ISSUE TITLE
Audiobookshelf problems when opening a downloaded audiobook in android

### ISSUE THREAD

**Issue by Rilith** [advplyr/audiobookshelf-app#805]
### Steps to reproduce

1. Click on a audiobook
2. Press the download button
3. Click play

### Expected behaviour
- The app should not crash and the audiobook should be reproduced
- The downloaded green popup should be displayed once

### Actual behaviour
- The app with some  audiobooks crashes when the play buttons is played for downloaded audiobooks
- The other downloaded audiobooks cannot be played offline for "Playback Failed" Source Error
- The download popup shows 2 times one on top of the other
- All the audiobooks are saved in .m4b

![photo_2023-07-24_19-01-17](https://github.com/advplyr/audiobookshelf-app/assets/50102080/db13b78a-fabb-4978-a09a-827678e8ecd3)

### Environment data

Audiobookshelf Version: 2.2.20

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model:  Samsung Galaxy note 10

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
You did not specify the mobile app version. I think the latest app version requires server v2.2.23 and up so I'm assuming you are not on the latest app?

**Comment by advplyr** [comment]
I believe you just need to update your server but let me know if you update your server and are on the latest mobile app version and this is still happening.
