### ISSUE TITLE
Problems with local audiobooks

### ISSUE THREAD

**Issue by plague-doctor** [advplyr/audiobookshelf-app#810]
Audiobooks stored on mobile in local directory are unable to be properly discovered and/or played using ABS app:

- If discovered, then the order of chapters is messed up and/or time is wrong:

![image](https://github.com/advplyr/audiobookshelf-app/assets/10541916/913ea136-088d-49fd-be95-ce6799f4feea)

- Audiobooks image is not recognised properly:

![image](https://github.com/advplyr/audiobookshelf-app/assets/10541916/7887d5ee-dc34-46df-b94e-a39752664a26)

I have no problems with those books with any other application.

Android Issue

Android version: 0.9.65-beta
Device model: OnePlus 9-PRO
Stock or customized system: LineageOS

**Comment by advplyr** [comment]
Are these downloaded to internal storage or shared storage?

If they are in shared storage, do the files actually exist? I see the cover is broken so I'm wondering if the cover downloaded.

Can you specify what your server version is?

When you say they are unable to play, what do you mean by that?

**Comment by plague-doctor** [comment]
The files are put to the shared storage manually (uploaded through USB).
Every directory consists of a bunch of mp3 files, cover.jpg and metadata.opf:

![image](https://github.com/advplyr/audiobookshelf-app/assets/10541916/c7baf07d-b787-4d06-bb2f-17a3bfc4d278)

The server 2.3.3 is running in Docker.

When I press the green play button (from Menu --> Local Media --> Local Folders --> Audiobook) then the ABS app is crashing.

**Comment by advplyr** [comment]
Oh I see. While the app does support scanning in media from your phone, there will be limited support (opf file won't be used) & it won't communicate with your server at all. 

That being said there are clearly some bugs here.

**Comment by advplyr** [comment]
Scanning in audio files has been removed from the android app as of v0.9.67-beta. This was too difficult to maintain and was buggy. All local downloads have to be made from the server.
