### ISSUE TITLE
[Bug]: Inconsistent Podcast Playback %

### ISSUE THREAD

**Issue by alfureu** [advplyr/audiobookshelf-app#815]
### Describe the issue

The issue I have on the Android version of the app is that the podcast section on the server on an episode shows (incorrectly) that an episode is played - for example - 13%, while the bottom player shows that I finished (100%) the episode already. Shouldn't these be synced somehow?

### Steps to reproduce the issue

1. just play any podcast to the end and observe

### Audiobookshelf version

2.3.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you share the version of the mobile app you are using and a screenshot of this issue

**Comment by alfureu** [comment]
Will try to make a screenshot in the morning, the mobile app version is 0.9.65-beta

**Comment by alfureu** [comment]
Finally I was able to create a screenshot:

![image](https://github.com/advplyr/audiobookshelf-app/assets/10846169/7911c466-6962-46ea-b975-86dbe8f03e96)

You can see that for ~20 seconds the progress bars are not synced. It is not due to the slowness of the server or bad connection, as I am on a gigabit line and there is no stuttering/caching. Also, not very clear why these progress indicators are not synced at all times....

**Comment by advplyr** [comment]
Progress is synced to the server every 15s or 60s depending on the network connection, this is when timestamps are updated on the page.
