### ISSUE TITLE
[Enhancement]: iOS: Make playbar a little narrower

### ISSUE THREAD

**Issue by mdeeter** [advplyr/audiobookshelf-app#818]
### Describe the feature/enhancement

It would be nice to make the play/time-bar on iOS a little narrower so it's easy to grab the playhead when starting a chapter... it's close to the edge, so it's pretty easy to accidentally start a swipe-right instead of moving the playhead.

![image](https://github.com/advplyr/audiobookshelf/assets/136902/e2feacf9-d2c8-47cb-b392-14a836588a5d)
![image](https://github.com/advplyr/audiobookshelf/assets/136902/ab4433e8-900c-462e-b9ab-219f55b578a1)

**Comment by sizzleweet** [comment]
I think this is 100% needed. Personally I don’t really see the benefit in the swipe right functionality on that screen as a whole!

**Comment by advplyr** [comment]
@sizzleweet Agreed. I couldn't figure out a way to disable it though

**Comment by benonymity** [comment]
Yeah, the swipe back/forward gestures are universal among all the pages, which is annoying, but probably exceedingly difficult to implement in pure javascript and disable in the webView.

**Comment by KaiStarkk** [comment]
This may be addressed in the recent merge @advplyr

**Comment by advplyr** [comment]
It's not perfect but @benonymity was able to figure out a way to stop the accidental swipe right. This is in v0.9.71
