### ISSUE TITLE
Files downloaded incorrectly to cache after moving on server

### ISSUE THREAD

**Issue by coldshouldermedia** [advplyr/audiobookshelf-app#823]
### Steps to reproduce

1. Audiobook originally stored at `/audiobooks/J.K. Rowling/1 - Harry Potter and the Philosophers Stone/01 Chapter 01 - The Boy Who Lived.mp3` or similar, I don't remember the exact structure.
2. File cached and played properly on android.
3. Audiobook moved to `/audiobooks/J.K. Rowling/Harry Potter - Stephen Fry/1 - Harry Potter and the Philosophers Stone/01 Chapter 01 - The Boy Who Lived.mp3` and library rescanned.
4. When file is cached in the android app, the file is put in `Download/Audiobook/J.K. Rowling/Harry Potter and the Philosophers Stone, Book 1/01 Chapter 01 - The Boy Who Lived.mp3`
5. One android device attempts to play the cache and crashes after 2-3 seconds, another android device throws an error `Item download complete but failed to create library item`

### Expected behaviour
- I expect the file to cache in the same new directory structure as the server.

### Actual behaviour
- The file appears to be cached in the wrong location which might be the source of the error/crash?

### Environment data

Audiobookshelf Version: v2.3.2
Android App

#### Android Issue
Android version: 0.9.65-beta

Device model: Moto G7 Power

Stock or customized system: LineageOS 20

**Comment by coldshouldermedia** [comment]
Forcing a re-scan of the full audiobook library did not fix the issue.

**Comment by advplyr** [comment]
The file structure on the device is not going to match the file structure on the server. This seems like unnecessary extra work. I'll most likely remove the scan options to avoid confusion in the future

**Comment by advplyr** [comment]
You'll have to delete the item from inside the app local downloads page. Or clear data from the app and delete the downloads from your file system and re-download.

**Comment by coldshouldermedia** [comment]
Yes, I have done that.  After re-downloading the file from the new structure, the crash persists.

**Comment by advplyr** [comment]
Re-downloading from what structure? I don't recommend using the "Scan" feature at all. After it downloads it shouldn't be moved on the file system.

**Comment by coldshouldermedia** [comment]
I'm sorry the the confusion, I'm not familiar with the terminology you use on this project.  

I just deleted the cached audiobook from my android device, then redownloaded them.  When I go to play the cached file on my android device it plays ~1 second of audio and crashes.

This is the only book for which this happens, and it only started happening after I re-arranged files on the server end.  if streaming the audio (not cached), it does not crash.

**Comment by coldshouldermedia** [comment]
Is there a way I can provide logs from the app to help?

**Comment by advplyr** [comment]
There is no good way to get logs for the app. I'm not sure what the problem could be. I would recommend copying the audio files on your server to create a new book to test with. Try downloading the new book and narrowing down what is going on.

**Comment by advplyr** [comment]
What about if you replace those audio files with audio files from another book that you know are already working

**Comment by coldshouldermedia** [comment]
I deleted the audio files in the new test folder, replaced them with audio files from another audiobook, then when I went to cache the audiofiles from my android device I got "Item download complete but failed to create library item".  So I ssume there's a metadata mixup?

Did I miss a step in that test?

**Comment by coldshouldermedia** [comment]
On the non-test version of the book, I cached again and tried playing a file for a later chapter in the book, and the crash happened as well.  In case you were thinking there was a problem with the file/s.

**Comment by coldshouldermedia** [comment]
I'm not sure if this is relevant, but I have noticed since enabling "Store metadata with item", that there are plenty of directories without an .abs file in them.
