### ISSUE TITLE
Downloading an audiobook after making progress causes progress to be reset

### ISSUE THREAD

**Issue by brandonocasey** [advplyr/audiobookshelf-app#825]
### Steps to reproduce

1. Start a book via streaming and get to 20% or something
2. Download the book 
3. The next time you play the book it will start at 0%

### Expected behaviour 
- Progress should be maintained

### Actual behaviour
- Progerss is lost

### Environment data

Audiobookshelf Server Version: server v2.3.3
Audiobookshelf App Version: 0.9.65-beta

- [ ] Android App?
- [x] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 16.5.1 (c)

iPhone model: Iphone 14 pro max

**Comment by m4gr4th34** [comment]
Thx!  Same here!

Audiobookshelf Server Version: server v2.4.4
ios app: 0.9.66-beta

iphone 11 pro max
ios 17.0.3

**Comment by Keavon** [comment]
Similarly, when I completely finished a book that started as streaming but where I switched to downloaded halfway through, upon finishing the book and closing the player, it showed the book's progress at halfway through instead of as being completed. I had to manually mark the book as read.

**Comment by helio4k** [comment]
Same issue, annoying bug. Got caught several times by starting the streaming then I like the book so I have download it and my progress reset. 😩

**Comment by advplyr** [comment]
Fixed in [v0.9.67-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.67-beta)
