### ISSUE TITLE
support external player

### ISSUE THREAD

**Issue by toxic0berliner** [advplyr/audiobookshelf-app#829]
### Is your feature request related to a problem?

 I'm frustrated with the player being quite good (except a few bugs hopefully being worked on) but not being able to use some external player, some have spent very significant time and effort to be great.

### Describe the solution you'd like
Allow for downloaded books to use Smart Audiobook Player (https://play.google.com/store/apps/details?id=ak.alizandro.smartaudiobookplayer) instead 9f the integrated player. Use the position.sabp.dat file after the play ends to sync the reading state back to the server 

### Describe alternatives you've considered
Manually "sync" playback state between the external player and audiobookshelf

**Comment by advplyr** [comment]
This is not going to be supported since focus should be spent on improving the app but Abs does expose the API so that other projects can integrate and sync progress.
