### ISSUE TITLE
Play controls not visible! 

### ISSUE THREAD

**Issue by Farru19** [advplyr/audiobookshelf-app#83]
[Screenshot_20220113-224316.jpg](https://user-images.githubusercontent.com/54806674/149377004-96ea1d83-5afd-43c0-b37b-92abff81a58d.jpg)

What can I do get them ?

**Comment by advplyr** [comment]
Yeah I noticed this yesterday and haven't found a fix yet. I think I will push a fix tonight.

I don't have a good solution for now

**Comment by advplyr** [comment]
This is fixed and live on the play store in [v0.9.37-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.37-beta)

**Comment by jcrmit** [comment]
Appreciated @advplyr - I was experiencing this too as a new user and wasn't sure if was a issue at my end.

**Comment by Farru19** [comment]
Dev, thanks for taking note of this soon and pushing an update. Will continue to support you. 🙏
