### ISSUE TITLE
Sleep timer resets when opening app

### ISSUE THREAD

**Issue by ryanwalder** [advplyr/audiobookshelf-app#833]
### Steps to reproduce

1. Open App / Start Playing Audiobook
2. Set Sleep Timer
3. Leave App in foreground
4. Lock Phone
5. Wait a few minutes
6. Unlock Phone
7. App is shown and Sleep Timer resets to whatever it was set as (eg: 60m)

### Expected behaviour

- Sleep Timer does not reset

### Actual behaviour

- Sleep Timer resets

### Environment data

Audiobookshelf Version: 0.9.65-beta

- [X] Android App?
- [ ] iOS App?

#### Android Issue

Android version: 12  
Device model: Fairphone 4  
Stock or customized system: Stock

**Comment by nichwall** [comment]
The sleep timer is configured to restart when the phone shakes so users can easily restart the timer when going to sleep.

If you don't want the sleep timer to reset, you can disable the shake to reset in the app settings (near the bottom of the list on 0.9.65)

Or, have you already done this and still having it reset? I'm not 100% sure what constitutes a "shake"

**Comment by ryanwalder** [comment]
Ah, I was not aware of that feature. I've retested with this disabled in the options and it seems it is the shake to reset that was triggering it.

Thanks for your help!
