### ISSUE TITLE
Provide .ipa for sideloading on iOS

### ISSUE THREAD

**Issue by fuchs234** [advplyr/audiobookshelf-app#837]
This is not a feature request for the app but rather a request for a compiled installer for iOS

### Is your feature request related to a problem? Please describe.

- A recent update of TestFlight broke the UI for older iOS versions (e.g. iOS15.0). It is not possible to accept the terms and conditions. This means Audiobookshelf is not installable on these devices. The Problem has been known [for some time](https://www.reddit.com/r/TestFlight/comments/11tf0xz/tester_cant_accept_terms_and_conditions/) without fix
- I, and some other users, prefer to stay on lower iOS versions(easier Sideloading, Jailbreak). 
- I like to think that the type of people with a self hosted audiobooks app tend to be the people who like to stay on a lower iOS version. This means I might not be the only one with an issue (althow it seems like i am the first to open one)

### Describe the solution you'd like

As this issue will only affect users who intentionally stay on low iOS versions, the most likely fix is to provide an .ipa for every release. Users with trollstore or jailbreak can install the ipa. All other users can update their system to use TestFlight

### Describe alternatives you've considered

- While there might be some users like me, this is an edge case and I understand if there are more pressing issues
- I, and other users with the problem could compile an ipa ourselves. However you need a mac for that as far as i know
- The RSS feed option can be used in combination with any podcast app for an okay replacement- just create a feed for every book and you are good to go (Can only be done as admin user, a setting to allow non-admins to open (their personal) rss feed might be good but also might be overkill/a security risk)

I know this is one user with a very specific problem. I understand if you do nothing about it. Thanks for the app and software, its great!

**Comment by PulsarFTW** [comment]
This would allow people to test the app via side-loading whilst the testflight is full and would allow people on apple silicon macs to sideload the file.

**Comment by Unlearned6688** [comment]
https://github.com/Unlearned6688/audiobookshelf-app-ipa/releases

I compiled the most recent code and uploaded the .ipa. It works fine on my devices.

I’m mostly doing this due to Apple’s restrictions regarding TestFlight.

**Comment by advplyr** [comment]
Added in [v0.9.66-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.66-beta)

**Comment by ideal2545** [comment]
> Added in [v0.9.66-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.66-beta)

thank you very much

**Comment by UnixNight** [comment]
> Added in [v0.9.66-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.66-beta)

Awesome! Would it be possible to host an altstore.json file in the repo to allow for direct installation and updates via an altstore source?

https://faq.altstore.io/distirubute-your-apps/make-a-source

**Comment by advplyr** [comment]
@UnixNight Do you know if this is against apples terms of service? I did a quick lookup and it seems like things are changing but in the past distributing ipa could get your apple developer account banned.

**Comment by UnixNight** [comment]
> @UnixNight Do you know if this is against apples terms of service? I did a quick lookup and it seems like things are changing but in the past distributing ipa could get your apple developer account banned.

I know that Paperback has been doing this and have been fine. They have their app in the App Store, a public and Patreon TestFlight, as well as instructions on how to side load. If you don't want to risk any trouble with a source then that's understandable and I guess discord announcements would be more than enough for update notifications

**Comment by nivepl** [comment]
Any chance for a more up to date ipa to download? Thanks

**Comment by binyaminyblatt** [comment]
I made a repo it should auto update 
https://raw.githubusercontent.com/binyaminyblatt/audiobookshelf-altstore-repo/refs/heads/pages/apps.json
