### ISSUE TITLE
Shared Playlists

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#841]
It would be nice if a playlist could be shared with specific users on the server.

The playlists could also be marked collaborative, where not only is the playlist shared, but other users can add books to it. 

'Allow deletion' could be a toggle setting if the playlist is marked collaborative.

**Comment by raviwarrier** [comment]
Sorry, meant to post it in abs repo instead of here, but since I can't delete it, there's a modification I'd like to suggest:

Allow sharing from the app if the shared playlist feature is implemented on the server (making a new request shortly)

**Comment by advplyr** [comment]
Let's re-open this if it gets implemented on the server to keep this list a bit cleaner

Ref https://github.com/advplyr/audiobookshelf/issues/2005
