### ISSUE TITLE
Flac doesn’t work on iOS

### ISSUE THREAD

**Issue by higbee4** [advplyr/audiobookshelf-app#85]
### Steps to reproduce

1. Stream a flac file using iOS safari or the iOS app. It never starts playing. It does work on Android. 

Audiobookshelf Version:

- [ ] Android App?
- [X] iOS App?

iOS Version: 15.2.1

**Comment by advplyr** [comment]
I am wondering if this is a bug they introduced in 15.2
https://developer.apple.com/forums/thread/695917

If anyone can test this on an earlier iOS version that would be helpful.

**Notable**: FLAC is the only audio format that uses fMP4 ([specs](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices))

> 2.25. The container format for xHE-AAC, Apple Lossless, and FLAC audio MUST be fMP4.

**Comment by higbee4** [comment]
I think I found the problem. The server transcodes the .flac files to aac. However, it also changes the segment to use fMP4. Since the file has been transcoded to aac it doesn't need fMP4. It only needs fMP4 if it is not transcoded.
I tested with the following change, and it worked for me. (Force aac transcode, but keep mpegts segment type).
```
get hlsSegmentType() {
    var hasFlac = this.tracks.find(t => t.ext.toLowerCase() === '.flac')
    if (hasFlac) this.transcodeOptions.forceAAC = true
    return 'mpegts'
}
```
I tried to get it to work without transcoding and with fMP4 which I think would be preferable. But I haven't been able to figure out how to get that to work yet.

**Comment by advplyr** [comment]
Thanks for digging into that, that makes sense. Were you able to replicate the crash with the flac transcodes?

**Comment by higbee4** [comment]
I'm not sure which crash you are referring to.

Before I tried changing the transcode on the server, I noticed the app was always returning 0 for getCurrentTime(). I think `audioPlayer.currentItem` was nil. Anyway, because that always returned 0, playback would stop with the error `Audio current time has not increased - cancel interval and pause player`.

**Comment by advplyr** [comment]
I'm not sure why I said crash, I meant to say replicate the issue. The temp fix I guess will be to just transcode with mpegts segment type.

**Comment by advplyr** [comment]
Just pushed a server update `v1.6.65` that will use mpegts for FLAC files and AAC transcode.

Tested on iphone X and was working.
