### ISSUE TITLE
Save Metatdata into files

### ISSUE THREAD

**Issue by frugglehost** [advplyr/audiobookshelf-app#853]
### Is your feature request related to a problem? Please describe.
When matching audio book to local media meta information is not saved to the file.

### Describe the solution you'd like
Option to also save to the AudiobookShelf Database and or update meta data in file. (*When possible)

### Describe alternatives you've considered
Manually using mp3 Tag to update data. 

### Additional context
Would be useful for cases when copying an individual file and using it outside of AudioBookShelf

**Comment by nichwall** [comment]
This is already supported using "embed metadata", but does not automatically update the metadata in the file during a match in case something goes wrong. Some file formats have more problems than others (such as m4b with covers)

**Comment by frugglehost** [comment]
Hey Nichwall, you are correct I see there was a toggle in settings to allow for the meta data to be saved.

Thank you.
