### ISSUE TITLE
Unable to click on the hamburger menu icon

### ISSUE THREAD

**Issue by cherifad** [advplyr/audiobookshelf-app#855]
### Steps to reproduce

1. Have an Android 7 Huawei phone
2. Download the app from the PlayStore

### Expected behaviour
- When I click on the hamburger icon at the top right of the screen, it should open a menu with "Home", "Account", ... "Settings". 

### Actual behaviour
- Nothing is happening. I cannot access the settings (and therefore add a server).  

### Environment data

Audiobookshelf Version: 0.9.65-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 7.0

Device model: Honor 6x

Stock or customized system: Stock (EMUI 5.0.3)

**Comment by advplyr** [comment]
I know someone brought this up before but I couldn't find the original issue or discussion. I was never able to find out why this happens and I don't have a Huawei phone.

**Comment by advplyr** [comment]
Is this still an issue for you?

**Comment by cherifad** [comment]
I don't have the phone anymore 😅. Anyway thank you for coming back to me and congratulations on your great work! Keep up the good work!

**Comment by advplyr** [comment]
Thanks! We'll call this good until it resurfaces
