### ISSUE TITLE
Wrong comma position in multi genre

### ISSUE THREAD

**Issue by update-freak** [advplyr/audiobookshelf-app#856]
### Steps to reproduce
1. Check the genre for podcasts when there are more than one genre

### Expected behaviour
- comma and than space --> for my example: "Health & Fitness, Health & Fitness: Mental" instead of "Health & Fitness ,Health & Fitness: Mental"

### Actual behaviour
-  space and than commafor --> my example: "Health & Fitness, Health & Fitness: Mental"

Audiobookshelf Version:

- [v0.9.65-beta] Android App?

#### Android Issue
Android version: 13
Device model: Samsung S23
Stock or customized system: Stock
![audiobookshelf](https://github.com/advplyr/audiobookshelf-app/assets/40196995/55b92b67-eae6-49ed-b20d-52dceb2d5e3e)

**Comment by CLHatch** [comment]
I'm not sure on the 2.3.x versions, but on 2.2.23 this seems to be the behavior on any comma separated list, showing ` ,` instead of `, `.

**Comment by nichwall** [comment]
This has been fixed and is awaiting release, but the original issue was closed which is probably why it didn't come up in search
#777

**Comment by advplyr** [comment]
Thanks I re-opened #777
