### ISSUE TITLE
Progress percentage not shown correctly / only updated on app restart

### ISSUE THREAD

**Issue by 0verEngineer** [advplyr/audiobookshelf-app#857]
### Steps to reproduce

1. Listen to an audiobook on the app (i listened to a downloaded one)
2. Check the progress percentage
3. Jump an hour in the audiobook progress
4. Check the progress percentage again, same as before
5. Restart the app to see the new progress percentage

### Expected behaviour
- The progress percentage should always be up to date

### Actual behaviour
- The progress percentage shows a wrong number

### Environment data

Audiobookshelf Version:

- [ x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: Google Pixel 7 Pro

Stock or customized system: CalyxOS 4.12.0

**Comment by nichwall** [comment]
Are you referring to the progress percentage here? (There's a few places you could be referring to)

![Screenshot_20230903-193200.png](https://github.com/advplyr/audiobookshelf-app/assets/5686638/3dc33428-7bd5-4a2b-8434-2d7ca0e6f308)

The percentage and time remaining both update in this view without requiring an app restart, but it may only update if you are listening to the book or refresh the page (such as from restarting the app)

Did you resume playing the book after seeking an hour, or only seek? Did the time remaining change but the percentage didn't, or did neither change?

**Comment by 0verEngineer** [comment]
Yea i mean this one, both time and percentage are not updating if i randomly select (and of course play) chapters in a book.

**Comment by advplyr** [comment]
This is intentional as it updates when the progress sync happens

**Comment by 0verEngineer** [comment]
@advplyr i pressed play and pause multiple times and it did not update, this is intentional?!? :D lol

**Comment by 0verEngineer** [comment]
And even if intentional, wrong information is shown to the user, so this is a bug, why do you close this? It affects multiple users as well.

**Comment by advplyr** [comment]
Have you pressed play and listened for at least 15 seconds?
If you are on a metered network you would need to listen for 60 seconds since it syncs less on metered connections.

**Comment by 0verEngineer** [comment]
I can't remember, but i think i listened long enough because i wanted to continue with the book.

But imho this is irrelevant, wrong data should never be shown.

How does this happen, is this the old timestamp that is saved locally on the phone bcs then it would make sense to me.

**Comment by advplyr** [comment]
It's relevant because that progress represents where you will pick up at if you force closed the app before the next sync happens. We don't save progress every second to prevent making many requests to the server. Progress is saved every 15 seconds for unmetered connections.

**Comment by 0verEngineer** [comment]
Ok, as i said i think i played longer then 60 seconds because i found this bug/problem as i started to listen to an audiobook.

I understand the reasoning behind this, but when we start playing, we already hit the server for the audio stream (idk how this is implemented). But why does the app/web interface not load the progress after starting the stream?

And the app/web could also query the audiobook info when i click on it to show the details/play page. I think this way wrong info is never shown.

Btw: does a way to sponsor the project exist? I use it almost daily and i love it...
