### ISSUE TITLE
Progress lost after pausing from home sceen widget

### ISSUE THREAD

**Issue by 0verEngineer** [advplyr/audiobookshelf-app#863]
### Steps to reproduce

1. Pause a local downloaded audiobook (no idea if it also happens with non local audiobooks) in the home screen widget
2. Go into the app and press play there

### Expected behaviour
- The progress should never be lost, every time we press pause the progress should be updated locally in the app as well as on the server

### Actual behaviour
- Some progress was lost

### Environment data

Audiobookshelf Version: v2.3.3

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12
MIUI version: 13.0.9

App version: 0.9.65-beta

Device model: Xiaomi Redmi Note 10 Pro

Stock or customized system: Rooted

**Comment by nichwall** [comment]
Is the behavior you experienced the same as #808 or #828?

**Comment by 0verEngineer** [comment]
No, it is different from both Issues, see my steps, i pause in the home screen widget and go to the app without restarting the app.

**Comment by nichwall** [comment]
Ah, there's been a number of sync related issues and the behavior you described is similar (you are correct the steps are different). I also meant to tag #804 , including the comments because the original comment didn't include everything

**Comment by advplyr** [comment]
The fix made for #828 will fix this one also in the next release

**Comment by advplyr** [comment]
Fixed in [v0.9.66-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.66-beta)
