### ISSUE TITLE
Get unknown error on android login

### ISSUE THREAD

**Issue by The-Ducktor** [advplyr/audiobookshelf-app#868]
### Steps to reproduce

1.click add server on android
2. Put in ip:port 
3.enter username and password

### Expected behaviour
- Tell us what should happen
Login like it does on browser or like on ios

### Actual behaviour
- Tell us what happens
I get (unknown error) when I click submit

### Environment data

Audiobookshelf Version:

- [version 0.9.65-beta

com.audiobookshelf.app
versionCode 96

targetSdk 33
minSdk 24

Installed: Sep 11, 2023; 11:41 AM] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: coral / pixel 4 xl

Stock or customized system: GraphineOS

**Comment by nichwall** [comment]
What server version?

**Comment by The-Ducktor** [comment]
2.4.1 running in docker

**Comment by jw2804** [comment]
@nichwall - I1m getting the same issue. I Installed and set the server (ver V2.4.2) on my Synology NAS, created library, added some MP3`s, and setup two users. I can log in as either user on my PC no issues, also works with the browser on my phone (Android OS). Installed the app from the app store, pointed to the same url I have in the browser, i`m prompted for user ID and password ( the same as I am when accessing it from the browser) enter the same credentials - Unknown error.

**Comment by advplyr** [comment]
Are you getting this issue on mobile app version 0.9.66?

**Comment by The-Ducktor** [comment]
no not recently seems to possibly be fixed
