### ISSUE TITLE
[Enhancement]: Bookmark Trash icon touch space bigger

### ISSUE THREAD

**Issue by mdeeter** [advplyr/audiobookshelf-app#876]
### Describe the feature/enhancement

When trying to delete a bookmark... it's very easy to miss the trash can icon... and if/when you do, it moves the playhead to the position of the bookmark you're trying to delete.  It seems like the icon itself is the only touchable area... but, imo, it should be the entire square area around the icons... like the highlighted areas displayed here:
![image](https://github.com/advplyr/audiobookshelf/assets/136902/f65845a2-c25b-4dd1-b22c-5aa6e276df71)

**Comment by advplyr** [comment]
![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/9f298025-0dbb-424e-b977-b1475fa4b0ec)

Design for upcoming release

**Comment by mdeeter** [comment]
I confirmed this UX is improved in the app after the release.  Edit and delete functionality works well.

Wondering if it's possible to not close the modal after editing or deleting a bookmark?  @advplyr

**Comment by advplyr** [comment]
Sure, can you open up another feature request for that?

Updated in [v0.9.66-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.66-beta)
