### ISSUE TITLE
[Bug] Android app doesn't stream audiobooks when using mobile data

### ISSUE THREAD

**Issue by luoabd** [advplyr/audiobookshelf-app#880]
### Steps to reproduce

1. Switch off Wifi
2. Enable mobile data
3. Stream any audiobook

### Expected behaviour
- The audiobook should stream normally.

### Actual behaviour
- The audiobook shows as infinitely loading.

### Note
- If I enable Wifi, stream an audiobook then turn it off and enable data, I can continue streaming normally (even further than what was initially buffered).

### Environment data

Audiobookshelf Version: 2.3.3

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 10

Device model: Samsung S9+

Stock or customized system: Rooted with no other changes.

**Comment by advplyr** [comment]
I'm not able to reproduce this. Just from your description this doesn't seem like it has to do with Abs app.

Can you share more info about your server? What version of the mobile app are you using?

**Comment by luoabd** [comment]
I'm using latest: v0.9.66-beta. As for the server, what kind of info would you like me to share?
For now, here are the logs when I reproduce the issue: https://pastebin.com/TtgRqzFT

**Comment by advplyr** [comment]
If you are using a reverse proxy
