### ISSUE TITLE
Testflight now reporting "this beta is full"

### ISSUE THREAD

**Issue by wtanksleyjr** [advplyr/audiobookshelf-app#883]
### Is your feature request related to a problem? Please describe.
Introduced someone to ABS, but they stopped due to them not being able to run the iOS app due to "this beta is full".

### Describe the solution you'd like
I don't know if it's solvable, but maybe some spots are being taken up by inactive users, or maybe the number of slots could be increased.

**Comment by nichwall** [comment]
The iOS beta has a hard limit on the number of users set by Apple. There should be open spots this weekend when users who didn't update to 0.9.66 are purged. This is the only way to know if someone isn't using the app anymore.

In the meantime they can use the mobile browser to access ABS or sideload the IPA themselves (not recommended if they don't have an Apple developer account)

**Comment by advplyr** [comment]
Spots have been opened up in test flight but like @nichwall it will be first come first serve on the 10k limit. I have asked if they would allow an exception and increase the limit but they said there are no exceptions.

**Comment by wtanksleyjr** [comment]
Thank you, and double thanks for the explanation because my sister had
missed the upgrade so I was able to help her get into the beta program
again, whew!!!

-Wm
