### ISSUE TITLE
Timer from the app

### ISSUE THREAD

**Issue by Daniel-PT** [advplyr/audiobookshelf-app#886]
Smart Audiobook Play (App for android) has a feature just to tab "Zzz" and the timer can be set to like 20 min.

Can we have that in the app? :)

Thanks!
![20230926_173442](https://github.com/advplyr/audiobookshelf-app/assets/20338866/c3e4be34-3864-45fa-85c5-7813ffdf3719)
![20230926_173446](https://github.com/advplyr/audiobookshelf-app/assets/20338866/32c37388-91ff-4f50-9065-bf0488d834ca)

**Comment by HStep20** [comment]
A Sleep Timer already exsits within the app. Press the Moon, and you can set a time. You can even set an 'auto sleep timer' in the settings so it sets a sleep timer if you start playing between the hours of _x_ and _y_

**Comment by Daniel-PT** [comment]
> A Sleep Timer already exists within the app. Press the Moon, and you can set a time. You can even set an 'auto sleep timer' in the settings so it sets a sleep timer if you start playing between the hours of _x_ and _y_

Ahh wow! I didnt know that! Meny thanks! :)

**Comment by Daniel-PT** [comment]
Is allready in the app.
