### ISSUE TITLE
Unable to stream/download two books in my library

### ISSUE THREAD

**Issue by sbstratos79** [advplyr/audiobookshelf-app#889]
### Steps to reproduce

No way to know which book will exhibit this issue, so not very reproducible. Simply pressing the `Stream`/`Download` buttons should show the described behavior.

### Expected behaviour
- Audiobook should stream or get downloaded.

### Actual behaviour
- On pressing the `Stream` button, Audiobookshelf log shows this message:
```
[PlaybackSessionManager] startSession: Closing open session "The Pariah" for user "sbstratos79" (Device: POCO F1 SDK 33 / v13)
```
- On pressing the `Download` button, no log message is shown.
### Environment data

Audiobookshelf Version:

- Android App

#### Android Issue
Android version: 0.9.66-beta

Device model: Poco F1, Moto G62

Stock or customized system: AwakenOS Custom ROM, unrooted

#### Note
The audiobook is in m4b format. I can stream the file from web version (on both PC and phone).
I can also stream the file from audiobookshelf by manually transferring the files to my phone and adding them to the local media directory.

**Comment by nichwall** [comment]
Do these two books have an ebook? If so, this is a known issue fixed for the next release.

https://github.com/advplyr/audiobookshelf-app/issues/865

**Comment by sbstratos79** [comment]
> Do these two books have an ebook? If so, this is a known issue fixed for the next release.
> 
> https://github.com/advplyr/audiobookshelf-app/issues/865

Yes. They have epub files. Thanks for the reply. I will close this issue.
