### ISSUE TITLE
ABS seems to keep seperate timestamps for offline and online use

### ISSUE THREAD

**Issue by Daemonias** [advplyr/audiobookshelf-app#890]
### Steps to reproduce

- 1. Start to listen to an audiobook and download it
2. Step outside of server reach an stop 
3. Go inside again and resume
4. Step outside again and resume

### Expected behaviour
- Synced timestamps that let me listen on from where I stopped the last time I stopped

### Actual behaviour
- It resumes from where I stopped in the environment I'm currently in. If I listened outside and then step inside it resumes from where I was inside.. so I have to manually find out where that was. Then when I step outside again it again resumes from where I stopped outside and I have to once again find out and jump to where I stopped.

### Environment data

Audiobookshelf Version: 0.9.66 beta

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: pixel 5

**Comment by Daemonias** [comment]
Just realised.. I can manually disconnect from the server to keep listening from where I stopped. So I guess a solution for now is to just never be online since it's no use anyway

**Comment by advplyr** [comment]
You may have downloaded the book on a separate IP address or connection in which case it wouldn't be syncing until you connect to that one again.
Syncing works perfectly fine for me and many others

**Comment by Daemonias** [comment]
I either download in my home or I download via wireguard.

Functionally wouldn't that mean I have the same IP?

It's the same server every time.

I'm not sure what exactly goes wrong

**Comment by advplyr** [comment]
Do you have a local ip and an external ip configured in the app?

**Comment by Daemonias** [comment]
> No.. didn't know that was a thing
> 
> Will take a look at that 

Where would I do that?
I just had a look at the app and can't find a place to do that.

Or do you mean on the server somewhere?

**Comment by advplyr** [comment]
The book is most likely no synced to the server. I recommend redownloading it on the server you are connected to

**Comment by TrevorBroderick** [comment]
I have this same problem with all of my books and it's pretty frustrating.

I download all of my audiobooks for offline listening because I mainly listen while I'm driving. I didn't know I could manually disconnected from the server, so I specifically have been turning off my phones wifi every morning before I open the app or it will think I have 0% progress on all my books.

This happens with freshly downloaded books too so I don't think redownloading would do anything for me.

**Comment by advplyr** [comment]
@TrevorBroderick Are you using the latest server v2.4.4 and app 0.9.66?

When you download books it has to be from the same server connection. That includes if you download on your local ip address but are connected over a reverse proxy.

**Comment by TrevorBroderick** [comment]
> @TrevorBroderick Are you using the latest server v2.4.4 and app 0.9.66?
> 
> When you download books it has to be from the same server connection. That includes if you download on your local ip address but are connected over a reverse proxy.

I'm on app version v0.9.66-beta (Android Pixel 6 Pro) and I was on v2.4.3 for the server, I can update that if you think it might help.
I always connect through my local IP address, and I am just running the standard docker image on an Unraid server.

**Comment by advplyr** [comment]
You should update the server. If you go to the local downloaded book page and it doesn't show "Connected" in green letters under the cover art, then the book is not linked to the server you are connected to.

**Comment by advplyr** [comment]
The latest release v0.9.67 added an alert on the downloaded book page that will show whether you are connected to the same server connection that downloaded the book.
Hopefully that should give you the info you need

**Comment by TrevorBroderick** [comment]
I believe updating my server has fixed the issue.

After I updated, all of my offline progress got wiped so I had to seek back to where I was. However, it now seems to stay synced whether I'm offline or online. The new connection alert will help if it ever pops up again.

Thank you!
