### ISSUE TITLE
[Bug]: iOS app sometimes does not show the 'Play' button

### ISSUE THREAD

**Issue by Aelmord** [advplyr/audiobookshelf-app#892]
### Steps to reproduce

1.  Open app
2. Tap on downloaded book
3. 'Play' button is missing, but progress is shown

### Expected behaviour
- The 'Play' button should appear right away and allow you to continue listening to the downloaded audiobook

### Actual behaviour
- 'Play' button does not appear. Have to try to open the book multiple times to get it to pop up

### Environment data

Audiobookshelf Version: 0.9.66-beta

- [ ] Android App?
- [X ] iOS App?

#### iOS Issue
iOS Version: 17.0.1

iPhone model: iPhone 13 Pro Max
![audiobookshelf_ios_screenshot](https://github.com/advplyr/audiobookshelf-app/assets/79537435/57285414-cae9-40a3-8f11-4f9a08bc80cc)

**Comment by advplyr** [comment]
What version of the server are you on?

**Comment by Aelmord** [comment]
2.4.4

**Comment by advplyr** [comment]
Are you still having this issue?

The only thing I can think of is the local copy of the book got corrupted in some way. Assuming this only happens with downloaded books.
