### ISSUE TITLE
Need a way to get the books I've read out of my sight

### ISSUE THREAD

**Issue by vsuh** [advplyr/audiobookshelf-app#893]
### Is your feature request related to a problem? Please describe.

Every time I put the next book I read as finished and try to select the next one, I see all the books I read in the lists: "Continue Listening", "Continue Series".

### Describe the solution you'd like

I believe that books marked as finished should not appear in these lists. And please make the "Listen again" list switchable in the app settings.

### Describe alternatives you've considered

A temporary solution might be the ability to move the books I read to another library, but I didn't find it.

**Comment by hobesman** [comment]
Books you mark as read should be disappearing from the continue listening list. Are you using the browser or the mobile app? Which operating system? Perhaps try refreshing when that happens and see if it gets removed from the list?

**Comment by advplyr** [comment]
Please share the mobile app version you are using and the server version you are using

**Comment by nichwall** [comment]
May be related to an issue with local files on iOS. The linked Discord channel is a discussion about how there were two local copies on an iPad, and after removing the local books from the iPad the finished book was able to be removed from the continue listening shelf. The main device was Android, so could be related to a local copy somewhere else.

(Link is the solution at the end, but additional information before)

https://discord.com/channels/942908292873723984/1158832039273971893/1158921548346970132

**Comment by vsuh** [comment]
Sorry for delay.
App version 0.9.66 beta
Srv version 2.4.4
After latest update app behaves as I wanted.
