### ISSUE TITLE
Android media control notification setPosition starts from beginning

### ISSUE THREAD

**Issue by lukeIam** [advplyr/audiobookshelf-app#894]
### Steps to reproduce

1. play an audio book with multiple tracks in android app
2. go the a later track
3. use the android media media control notification to set a new position inside the current track
(by clicking on the process bar)
4. this cause the app to start the book from the beginning (track 1)

(the progress bar shows the track process - which is correct)

### Expected behaviour
- seek inside the the current track of the audio book 

### Actual behaviour
- seek to the new position inside the track

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.66-beta

Device model: Pixel 7

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
I was able to reproduce this

**Comment by advplyr** [comment]
Fixed in [v0.9.67-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.67-beta)
