### ISSUE TITLE
Request: Add option to sync local Copy with the server

### ISSUE THREAD

**Issue by Hyperion923** [advplyr/audiobookshelf-app#9]
Please add the function to sync the local copy with the server so you can download a audiobook to your phone and also listen at the last point on the webclient.

**Comment by advplyr** [comment]
This should already be the case.

When you are connected to the server and listening to a downloaded audiobook on your phone, the server will be receiving updates every few seconds with your progress.

Whenever you connect to the server on your phone the progress should be getting synced.

**Comment by Hyperion923** [comment]
ahh i found the error, if i select the book normally from the shelf then it is synced but if i select it from the download folder then it is not
