### ISSUE TITLE
Bookmarks not being saved on downloaded books

### ISSUE THREAD

**Issue by igorkaldowski** [advplyr/audiobookshelf-app#90]
### Steps to reproduce

1. Save book for offline
2. Listen to book and add bookmark while online

### Expected behaviour
- The bookmark to be added

### Actual behaviour
- The bookmark looks like it was added but when I open the bookmark window again its not there

### Environment data

Audiobookshelf Version: v1.6.50

- [ x ] Android App

#### Android Issue
Android version:

Device model: Pixel 6 Pro

Stock or customized system: Stock

**Comment by advplyr** [comment]
I just tested this and cannot replicate the issue. Can you double check this?
You must be connected to the server to use bookmarks for now.

**Comment by igorkaldowski** [comment]
It seems to be working now. I do wander if it has something to do with the 2 settings files as that is the only thing that has changed.
