### ISSUE TITLE
[Bug]: Skip or Stops Playing on Android Auto

### ISSUE THREAD

**Issue by madcar86** [advplyr/audiobookshelf-app#901]
### Describe the issue

When played through the app on Android Auto, it skips or stops playing. App is forced closed, but usually works the second time. Files have been downloaded to local storage.

### Steps to reproduce the issue

1. Play book from Android Auto

### Audiobookshelf version

2.2.23

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
What version of the mobile app?

**Comment by madcar86** [comment]
0.9.66-beta

**Comment by gazpachoking** [comment]
I've been having this problem since 0.9.64. I have similar problems outside android auto as well, but usually the phone can catch up before the app gets force closed there.

**Comment by advplyr** [comment]
Is this still an issue for you?

**Comment by gazpachoking** [comment]
I've been checking periodically, but I'll check again and report back definitively. I've switched to playing with smart audiobook player until we can figure this out because the ABS player stutters and crashes a lot since 0.9.64 with downloaded media (both with and without android auto, but worse with android auto.)

**Comment by nichwall** [comment]
> I've been checking periodically, but I'll check again and report back definitively. I've switched to playing with smart audiobook player until we can figure this out because the ABS player stutters and crashes a lot since 0.9.64 with downloaded media (both with and without android auto, but worse with android auto.)

Do you have a connection to the server when listening to downloaded audio and encountering stuttering? I haven't ever experienced stuttering with downloaded media on Android and I rarely stream. I do usually have a connection to the server, but not always.

**Comment by gazpachoking** [comment]
I have the same issue both with and without connection to the server. I'm wondering if it's something to do with either the encoding of my files, or that there are a large number of separate files per book. Most of my books are in the same format though, so it's not so easy for me to test that.
