### ISSUE TITLE
[Bug] Local copy of book is not marked as completed when completed on server

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf-app#903]
If a book is downloaded, the local copy is not marked as "finished". This is related to the local copy not having ever from the server (#842). This is a slight annoyance, but probably shouldn't be addressed until the offline library overhaul.

### Describe the solution you'd like
If a local copy is completed, show as completed in the offline row (green bar instead of yellow bar).

### Describe alternatives you've considered
Nothing specific.

### Additional context
"The Captain" is completed (visible in first row), but the local copy is not (last row)
![Screenshot_20231008-025357.png](https://github.com/advplyr/audiobookshelf-app/assets/5686638/fc6a0aa5-148d-4289-85cf-d6666431fe2b)

**Comment by advplyr** [comment]
Fixed in [v0.9.67-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.67-beta)
