### ISSUE TITLE
Downloaded audiobook won't play with error 

### ISSUE THREAD

**Issue by MI3Guy** [advplyr/audiobookshelf-app#904]
### Steps to reproduce

1. Download an audiobook that causes this issue to internal storage. The audiobook I am having the issue with is a retagged version of https://librivox.org/the-chessmen-of-mars-version-3-by-edgar-rice-burroughs/
2. Play the audiobook.

### Expected behaviour
- The audiobook plays.

### Actual behaviour
- An error message pops up: `Playback Failed: Source error`

Note that this audiobook plays as expected when streaming from the server.

### Environment data

Audiobookshelf Version: 2.4.4, app version 0.9.66-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13
Device model: Pixel 5a
Stock or customized system: GrapheneOS

**Comment by Grzy7316** [comment]
Running into the same issue with Pixel 6  & android app, as well as Cat S42 & android app.  The Cat S42 is on android 10  , & the pixel 6 is on android 13

**Comment by nichwall** [comment]
May be related to an issue with the file.

https://github.com/advplyr/audiobookshelf-app/issues/865

**Comment by advplyr** [comment]
Yeah most likely the same m4b encoding issue. I haven't tested that sample file yet but every time this comes up re-encoding the file fixes it.

**Comment by advplyr** [comment]
I just got around to testing that audiobook you linked and this works fine for me. It direct streams from the server and plays when downloaded on a Pixel 6 Android 13.

This may have been an issue when you tagged the audio file. I would suggest re-encoding the audio file or downloading it again and testing.
