### ISSUE TITLE
Chapter Level Seek Bar

### ISSUE THREAD

**Issue by Ev1dentFir3** [advplyr/audiobookshelf-app#905]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I try to use the seek bar and I accidently skip an entire chapter because the seek bar covers the entire book... 

### Describe the solution you'd like

Please add an option or make it so the bar only covers a single chapter, bit the entire book. 

### Describe alternatives you've considered

Please make the seek bar only cover a single chapter. If chapter 5 is from 10:30 to 17:00 then dragging the bar from left to right should only cover that frame, making it easier to go back just a little. 

### Additional context
It's extremely hard to seek for just a few minutes, and the longer the book the harder it is. Narrowing it down to one chapter at a time would make it a ton easier.

**Comment by advplyr** [comment]
This is already supported for the audio player in the app. When the audio player is full screen click the menu in the top right.

For m4b audiobooks this is not yet supported for the lock screen notification player #239
