### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lukethehawk** [advplyr/audiobookshelf-app#908]
### Describe the issue

After the upgrade to iOS 17 I experienced a problem, when I push the play button the stream wont start, it remain stuck. I'm connected, I tried with wifi and 4G but it wont start the stream. No prob with the web app through safari I tried to reinstall completely the app,  app v. 0.9.66 srv. v 2.4.3 (docker)

### Steps to reproduce the issue

1. After upgrade to iOS 17. Press play doesn’t work

### Audiobookshelf version

app v. 0.9.66 srv. v 2.4.3 (docker)

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you check if this is transcoding or direct play? You will see that at the top of the audio player when you open it up full screen.

Is this only happening with that one audiobook or others?

Can you update your server to v2.4.4 so we can be sure this wasn't fixed on the server-side?

**Comment by advplyr** [comment]
Also, that audio file just may not play on iOS. You can test that by downloading it and trying to play it with another app (not VLC).

**Comment by lukethehawk** [comment]
Updated to 2.4.4 nothing changed.
After some test I found that the problem is only with that book.
At the top of the audio player I see DIRECT
thanks

**Comment by advplyr** [comment]
Can you share the ffprobe output of that audio file?
You can find that by using the web client here
![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/ae1b8d16-c96c-4439-b3f9-0f442634e9a9)

Then in the top right

**Comment by lukethehawk** [comment]
[ffprobe.txt](https://github.com/advplyr/audiobookshelf-app/files/12904198/ffprobe.txt)

**Comment by advplyr** [comment]
I'm not seeing anything unusual. I'm guessing it's some encoding issue that I could only confirm if I had the audio file.
You can try re-encoding it

**Comment by lukethehawk** [comment]
> I'm not seeing anything unusual. I'm guessing it's some encoding issue that I could only confirm if I had the audio file. You can try re-encoding it

Ok, I'll try re-encoding.
Thanks for your help
