### ISSUE TITLE
Send to device context menu option for ebooks

### ISSUE THREAD

**Issue by ScyllPoesis** [advplyr/audiobookshelf-app#909]
### Is your feature request related to a problem? Please describe.
A pretty simple (hopefully!) request to have the context menu option for ebooks "Send Ebook to..." from the desktop app available on the mobile app. Would save me a trip or pinching with desktop mode mobile browsing!

### Describe the solution you'd like
Parity of options with the desktop app for sending ebooks. 

### Describe alternatives you've considered
I can always just get my chromebook or go to my desktop, but that's not ideal.

**Comment by SpartacusIam** [comment]
I second this!  Pretty much the last piece for me so that my users never have to use anything but the browser.

**Comment by advplyr** [comment]
Added in [v0.9.67-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.67-beta)
