### ISSUE TITLE
Android Auto - Still having issues resuming at the right point

### ISSUE THREAD

**Issue by danmed** [advplyr/audiobookshelf-app#91]
So i'm still having problems with Android Auto resuming playback at the point i left it at.

It *seems* regardless of what client i was using prior to using android auto, it reverts to some time stamp quite a way back..

i havn't yet managed to track down when that timestamp was saved.. but what i don't understand is if i get out of the car, then go look at the web gui.. the time stamp is right.. so why would AA then start from a different point?

**Comment by danmed** [comment]
Sorry, UK speak :)

I mean i sit in the car on my driveway and make sure playback is at the
right point before i drive off :)

**Comment by danmed** [comment]
In all honesty i'm now having a hard time replicating it (it's late and i can't go to the car).. but i've opened AA in "driving mode" and i can't replicate the problem..

I've now closed ABS and AA and i know the time stamp.. so i will test it on the school run tomorrow and come back to you!

**Comment by advplyr** [comment]
Got it. I will try to replicate it, but in the meantime if you could try opening up the mobile app on your device at the end of your trip while it is playing in AA.
Let it play for 5 seconds with the mobile app open in your car then close it down. When you next get in your car I am curious if AA will start back up on the right time.

**Comment by danmed** [comment]
OK will do.. i'll try that in the morning!

**Comment by danmed** [comment]
so now ive got no clue whats going on..

i got in the car with everything closed, tried to open ABS in the car and it jsut kept loading..

Had to open the app on my phone before it would load in the car.. then an app update came through so i did that.. The book played from the right place.

Got out at my daughters school... app was still open on my phone.. got back in starting playing and it went back to where it was when i first got in the car :(

**Comment by advplyr** [comment]
When you get back in your car if you can open the app up first and check to see if the progress is correct for your audiobook before launching android auto.
Is the mobile app showing the correct progress then android auto not playing at the right position?

Another helpful test would be to fully close out of the application before connecting to android auto, this would clear out any initial start position stored in memory.

**Comment by danmed** [comment]
So this morning i got in the car with the app not open on my phone, opened
it in AA and it started the book from scratch..

I then opened the app on my phone and it stopped playing and jumped forward
to almost where i left it....

I'm so confused by all of this lol

**Comment by danmed** [comment]
Some screenshots for you..

Web Interface time stamp : 
![image](https://user-images.githubusercontent.com/3878490/152000047-593de309-8725-4fe0-8be5-101de907fa88.png)

Android App time stamp : 
![image](https://user-images.githubusercontent.com/3878490/152000295-4026f5b3-3d18-46b1-b170-70b709f6f82e.png)

**Comment by advplyr** [comment]
> I'm so confused by all of this lol

You and me both!

I'm curious about those 2 tests I mentioned above still. If closing out of the app completely and re-opening it before launching AA solves the problem, then that will give me something to go off of.

**Comment by danmed** [comment]
Sorry it's taken a while to get back to you.. So this is almost certainly
something happening when AA is involved..

I went for a long walk the other day and listened.. When i got in the car
it resumed at the right place! Fantastic! (starting it on my phone whilst
plugged in to the car).. When i got out, i hit pause on the car screen..

Now when i go back to it on my phone, it's rolled back 15 minutes or so..

So it seems to me like this is happening when i get out of the car rather
than getting in.. if that helps at all?

**Comment by advplyr** [comment]
I can only think that you are using the version before I added progress sync to android auto. Can you check what version you are currently on by going to the account page?

**Comment by danmed** [comment]
Android : 0.9.39-beta
Server : 1.6.44

**Comment by advplyr** [comment]
The code to allow syncing streams from android auto required a server update to 1.6.45, so that is the problem.
The latest server version is 1.6.64

**Comment by danmed** [comment]
Hmm my bad, i thought i'd added your repo to my docker notify list.. but obviously not..

Apologies! I've just updated it and i'm going to add you to the notify list now!

I'll update in a few days!

**Comment by advplyr** [comment]
The newest app releases 0.9.41-beta and server v2 and up handle syncing differently.
Let me know if this still persists.
