### ISSUE TITLE
Disclaimer about needing to have a server when connecting

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf-app#912]
### Is your feature request related to a problem? Please describe.
First time users are confused about the server setup when they find the app, not realizing they also need a server.

### Describe the solution you'd like
Having a note beneath the server address box like "This app is designed to work with an ABS server you or someone you know is running on another device. Use the IP or domain name of where the server is running."

This message could also be in an "info" bubble.

### Describe alternatives you've considered
Making it more clear on the website/GH/app stores, but it already says the server is required so it doesn't help when people just install the app.

**Comment by advplyr** [comment]
Earlier versions of the app had this message at the bottom displayed at all times. It can be revised and only shown when there are no server connections.

![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/35419123-42d4-40f3-9ad9-e28c257cc8d3)

**Comment by advplyr** [comment]
The main reason I put that was for the app store reviewers

**Comment by advplyr** [comment]
![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/803039ed-454c-462b-97c9-9d59e399fbd5)

**Comment by advplyr** [comment]
Does the "This app does not provide any content" make sense? Or is it unnecessary

**Comment by nichwall** [comment]
It doesn't add any information to someone who has found the website already, but will help handle the case of when someone stumbles upon it in an app store (and hasn't seen anything else about ABS yet). I think it should stay in.

**Comment by advplyr** [comment]
Updated in [v0.9.67-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.67-beta)
