### ISSUE TITLE
Better control of playlists on mobile

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf-app#914]
Im pretty sure it used to show the finished item icons in playlist on mobile, now it no longer does. Knowing / seeing what has been listened to in a playlist is a pretty essential feature to be able to go on to things you havent listened to yet without having to try and remember each item

### Describe the solution you'd like
Bring back the 'Finished' icons in playlist, or even better the option to remove something from a playlist as well from mobile

**Comment by advplyr** [comment]
Updated in [v0.9.67-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.67-beta)

**Comment by barelylit** [comment]
That's a massive improvement, thank you.

One slight comment is that having to click three dots, then add to playlist
(even though im not adding) then click on a remove button is a bit long
winded. You're already working within the context of the playlist you are
viewing, so just three dots and a remove from this playlist should do the
job surely?

**Comment by advplyr** [comment]
Yeah for sure, didn't think about it
