### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by schwartzaher** [advplyr/audiobookshelf-app#916]
I was trying to use the app on my Onyx Boox Poke 4 Lite. Love how the reader portion of the app looks. Navigation throughout reading a book looks and functions very amazing. It is the first app and server that I found that can replace the built in book reader on my e-reader. The only problem I have is the dark mode. When you navigate the main page of the bookshelf, the screen becomes very dark and is very hard to navigate and see. Having a light mode would make that so much easier to navigate and make the app worth it. I was using it for a week to see if I could work around it, having to stop just because of not being able to navigate my books in the bookshelf mode. Adding a light mode would make this look and work a lot nicer on any device that uses an e-ink screen. Using the app and dark mode on my tablet looks fine as it is an IPS LCD display that looks just fine with dark mode.

**Comment by advplyr** [comment]
Can you share a picture of what this looks like for you on that device?

**Comment by schwartzaher** [comment]
![Uploading IMG_20231018_233204_575.jpg…]()

**Comment by schwartzaher** [comment]
![IMG_20231018_233239_002](https://github.com/advplyr/audiobookshelf-app/assets/35978962/012e9e89-13cd-4be0-8af0-a677c9cbb989)
![IMG_20231018_233204_575](https://github.com/advplyr/audiobookshelf-app/assets/35978962/09c13872-5485-42de-8514-f330e37abbad)

**Comment by schwartzaher** [comment]
This is with a manual screen refresh to give it the best possible look. With dark mode it seems to kill the bookshelf but book itself looks good.

**Comment by KaiStarkk** [comment]
Same on the Boox Air 3 C with colour epaper. Seems like dark apps cause more refreshes


The other things that would be amazing for e-readers:
- option to hide the player bar at bottom of screen but keep playing
- Tap to turn page option
- Vertical scroll option

@advplyr I thought I recall there used to be a tap option - apologies if I’m missing it

![IMG_0794](https://github.com/advplyr/audiobookshelf-app/assets/1722064/77c7c4a0-5dee-4b70-8044-eaf7fea17e0d)
![IMG_0793](https://github.com/advplyr/audiobookshelf-app/assets/1722064/6e4378cf-0500-4f6a-9115-4e304c224719)

**Comment by advplyr** [comment]
Next release will include the first pass at light theme. I'm still going through and finding things I missed but it will be setup so that we can change the colors easily.

![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/c332dd62-2312-46b6-9878-b8b01c2e3019)

The track bar is still using the dark theme, need to update that.

**Comment by benonymity** [comment]
This looks awesome, love the color selection!

**Comment by advplyr** [comment]
Added in [0.9.69-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.69-beta)

**Comment by advplyr** [comment]
If you test this out on your ereader please share a screenshot of what it looks like now

**Comment by schwartzaher** [comment]
![IMG_20231219_202738_362](https://github.com/advplyr/audiobookshelf-app/assets/35978962/ae8a6ff3-82f1-4e3c-b1b0-ae551b706dca)
![IMG_20231219_202835_417](https://github.com/advplyr/audiobookshelf-app/assets/35978962/0f5bbfe0-1ebf-4162-bcb0-6e5be063cb49)
![IMG_20231219_202920_808](https://github.com/advplyr/audiobookshelf-app/assets/35978962/3ce51bc0-f86a-4e8f-a6dc-235557f71931)
![IMG_20231219_202925_118](https://github.com/advplyr/audiobookshelf-app/assets/35978962/cd21c567-cc06-4eba-9ec7-741d6057ae15)
![IMG_20231219_202936_813](https://github.com/advplyr/audiobookshelf-app/assets/35978962/ef3cd2c2-afc2-4d14-8799-7d8e50f79dd2)

So it looks good. Haven't used it since I posted this issue. It looks resolved, not being able to use bookshelf view which is to be expected. I still need to customize the font and other things. Otherwise it looks good.

**Comment by schwartzaher** [comment]
> ![IMG_20231219_202738_362](https://private-user-images.githubusercontent.com/35978962/291680749-ae8a6ff3-82f1-4e3c-b1b0-ae551b706dca.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTEwNDAsIm5iZiI6MTcwMzAxMDc0MCwicGF0aCI6Ii8zNTk3ODk2Mi8yOTE2ODA3NDktYWU4YTZmZjMtODJmMS00ZTNjLWIxYjAtYWU1NTFiNzA2ZGNhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE4MzIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZWMyZGU5NDM5YTA2MmM2NmE2ODc5NWIwYmU5M2RhOTZiZDc4NGZiZTdmODQ4ZmJlY2U0NjcwMWNmZmRkNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XzIyqHj0eQzBlhjPXZhCnahS6y4ksd6Fbeyz6f6oq-A) ![IMG_20231219_202835_417](https://private-user-images.githubusercontent.com/35978962/291680763-0f5bbfe0-1ebf-4162-bcb0-6e5be063cb49.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTEwNDAsIm5iZiI6MTcwMzAxMDc0MCwicGF0aCI6Ii8zNTk3ODk2Mi8yOTE2ODA3NjMtMGY1YmJmZTAtMWViZi00MTYyLWJjYjAtNmU1YmUwNjNjYjQ5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE4MzIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMGViYTVmYmJhMWRjNjdiNWIyODcxM2MzNjEzZjU0YmNkMDM5YjhlMWJhYzUxM2M2YjNkMjNmYzYzN2MyNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wSpFkxob3ijA8WT0qgA2N72VJDlv661Nuy2BCPhUrEA) ![IMG_20231219_202920_808](https://private-user-images.githubusercontent.com/35978962/291680975-3ce51bc0-f86a-4e8f-a6dc-235557f71931.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTEwNDAsIm5iZiI6MTcwMzAxMDc0MCwicGF0aCI6Ii8zNTk3ODk2Mi8yOTE2ODA5NzUtM2NlNTFiYzAtZjg2YS00ZThmLWE2ZGMtMjM1NTU3ZjcxOTMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE4MzIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZjY5NGI2NDM4ODdiODQ5NzE0NWVlYjUwM2MwZmYwZDU0ODAyYzliZmZjMThlODhiOWJhNjQwZmUzNTg0YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z4Lqyy9Vxq24E_JgLlonotJjJT2Sxj7OvM5P6C7m8Co) ![IMG_20231219_202925_118](https://private-user-images.githubusercontent.com/35978962/291680983-cd21c567-cc06-4eba-9ec7-741d6057ae15.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTEwNDAsIm5iZiI6MTcwMzAxMDc0MCwicGF0aCI6Ii8zNTk3ODk2Mi8yOTE2ODA5ODMtY2QyMWM1NjctY2MwNi00ZWJhLTllYzctNzQxZDYwNTdhZTE1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE4MzIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNmQ4Yjg2N2VmZWQ4ZDIyOGZlMWQzMjRlZTJlZGQwMGQwMmFiNTFkNmFjN2VmYjAzM2I2NGNkOGMwYzhkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Frw589iIwF_1NgnL2Sik8f1_T1phT4KkOEOxXBS6qOw) ![IMG_20231219_202936_813](https://private-user-images.githubusercontent.com/35978962/291680999-ef3cd2c2-afc2-4d14-8799-7d8e50f79dd2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTEwNDAsIm5iZiI6MTcwMzAxMDc0MCwicGF0aCI6Ii8zNTk3ODk2Mi8yOTE2ODA5OTktZWYzY2QyYzItYWZjMi00ZDE0LTg3OTktN2Q4ZTUwZjc5ZGQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE4MzIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZjY5YjViZTJlOTM4MTZkZTY5ZWVlYzc1MWEwM2ZjMGJkZDIyYTg4MDI4ZjRmYTFkNjg1ZTdlMzUwZmUyN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IUrHRYb31DkxX-EX9SojM48aW71_94LrdQ-j7LHVrSI)
> 
> So it looks good. Haven't used it since I posted this issue. It looks resolved, not being able to use bookshelf view which is to be expected. I still need to customize the font and other things. Otherwise it looks good.

At this point it looks good. I'm not sure how easy it is to program a toggle that asks if you want to switch off of bookshelf mode when you turn on light mode. Otherwise thank you for fixing things
