### ISSUE TITLE
Slow Audiobook downloads

### ISSUE THREAD

**Issue by CunningSquirrel** [advplyr/audiobookshelf-app#919]
Downloading books from my server is extremely slow. I’m not sure if it’s just me or if this is expected?

I have my server installed on an HP Micro Server with the following specs:
- Intel® Xeon® CPU E3-1265L V2 @ 2.50GHz
- 16 Gigs Ram
- 5x SSD
- unRAID OS 
- 2x 1Gig ports configured in bonded mode for load balancing

CPU isles at around 10% and Ram at 8%

However downloading a 1 gig audiobook from Audiobookshelf on my UniFi Wi-Fi 6 AP takes +- 10 - 15 mins. It seems a bit slower than I would have expected? Any suggestions?

I’m using a UniFi Dream Machine as my router and I have the two network cables connected directly into the back of it and I have the two ports bonded in the interface there as well.

**Comment by advplyr** [comment]
This is definitely unexpected. The server and the client isn't throttling speed in any way so I suspect this is something with your device or network. Are you using a local ip address or a reverse proxy?

**Comment by CunningSquirrel** [comment]
Thanks for the quick response, I’m using Swag as my reverse proxy for ssl certification on my unRAID containers

**Comment by advplyr** [comment]
Have you checked the download speed when not going through the reverse proxy?

**Comment by CunningSquirrel** [comment]
Just got home, I will check that now and report back


Sent from Yahoo Mail for iPhone


On Sunday, October 22, 2023, 6:58 PM, advplyr ***@***.***> wrote:




Have you checked the download speed when not going through the reverse proxy?

**Comment by mcfrojd** [comment]
I experience the same problem with slow / never completed download when connected through a cloudflare tunnel, if i connect to the local ip the speed is fine.

**Comment by CunningSquirrel** [comment]
I’m currently connected locally and it’s about the same speed unfortunately. Could possibly be because I’m hosting it in unRAID. I’ll have to spin up a test server running from its own VM and rest to see if there is a difference.
Here is a clip of my download speed.


Sent from Yahoo Mail for iPhone


On Saturday, October 28, 2023, 5:00 PM, mcfrojd ***@***.***> wrote:




I experience the same problem with slow / never completed download when connected through a cloudflare tunnel, if i connect to the local ip the speed is fine.

**Comment by advplyr** [comment]
I'm not able to see the clip of your download speed if you shared one.

I also host in unraid without speed issues on downloads.

**Comment by Eideen** [comment]
I seeing very slow speeds (<180kB/s), when using HAproxy, on PFsense.

I see normal speed when going direct.
