### ISSUE TITLE
Series tab lists items out of order.

### ISSUE THREAD

**Issue by chyron8472** [advplyr/audiobookshelf-app#925]
### Steps to reproduce

1. Assign books to series
2. Multiple series exist
3. Open Series tab

### Expected behaviour
- Series should be sorted alphabetically, while ignoring prefixes.

### Actual behaviour
- Series sort seemingly randomly

![image](https://github.com/advplyr/audiobookshelf-app/assets/12549803/cece8b25-b644-4260-86c6-aefc1201f883)

### Environment data

Audiobookshelf Version: 2.4.4

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.66-beta

Device model: Moto G Power XT2041-7

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by hobesman** [comment]
Could it be during by the title of the first book in the series?

**Comment by chyron8472** [comment]
> Could it be sorting by the title of the first book in the series?

Nope.
Case in point:
- Colour of Magic
- Sword in the Stone
- Pirates of the Caribbean
- Twilight
- Life Reset
- Princess is Black
- White Queen
- Ender's Game

**Comment by advplyr** [comment]
Fixed in [v0.9.67-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.67-beta)
