### ISSUE TITLE
NGINX - Subdomain from DYNDNS - Adding Server Address - nothing happens

### ISSUE THREAD

**Issue by fendle** [advplyr/audiobookshelf-app#928]
Hi,

I configured my audiobookshelf behind a reverse proxy as a subdomain and I can access the webfronend without issues.
The url looks like:
{subdomain}.{myDDNSDomain}.duckDns.org
When I now enter the url into the AudioBookshelf and save it, nothing happens.

I tried to connect directly with the IP of my Server in the LAN and there it's working without any issues.

Br

**Comment by advplyr** [comment]
Can you expand on what you mean by "nothing happens"? Also, what makes you think this is a bug with Abs?

**Comment by hobesman** [comment]
At one point the ABS mobile app wasn't handling http->https redirects and you had to type https if you were using that. 

I'm not sure if that's what you're dealing with though until you describe more what does/doesn't happen.
