### ISSUE TITLE
Jumps ahead after pausing

### ISSUE THREAD

**Issue by Daemonias** [advplyr/audiobookshelf-app#929]
This happened on an Google Pixel 5 with the newest updates

Since a few days I have a really weird bug.
When I pause it jumps ahead half a minute or so.
But not always.. sometimes it does it when I skip back. Sometimes it's directly after unpausing.

It also seems as if the media player on my phone and the media player in the opened app don't always show the same time stamps.

The audiobook is downloaded to my phone and I haven't left my Wlan in the past week while listening.

**Comment by advplyr** [comment]
If it is an mp3 file they may be variable bitrate in which case you can try enabling the mp3 index seeking setting.
https://exoplayer.dev/troubleshooting.html#why-is-seeking-inaccurate-in-some-mp3-files

If you can share more information about what mobile app you are using, what the file format is, if it is happening with other audiobooks, if the same issue is happening while streaming, or anything else you can think of that will help debug.
