### ISSUE TITLE
iOS TestFlight beta is full

### ISSUE THREAD

**Issue by ruoti** [advplyr/audiobookshelf-app#930]
The iOS test flight beta is full, so new users can't get the app on their devices. Is there a way to increase the size of the beta or to publish this to the actual app store?

**Comment by nichwall** [comment]
No, there is a hard limit set by Apple for how many people can be in the testflight. You can sideload the IPA yourself, but this is not recommended if you don't have an Apple developer account (without a developer account you have to reinstall the app every 7 days).

Whenever the next version of the app is released, users who do not update within about a week are removed from the beta to make room for new users.

https://www.audiobookshelf.org/faq#app-faq

**Comment by chengnieisu** [comment]
Other than buying an Android phone, are there other alternatives to use the app?

**Comment by nichwall** [comment]
You can sideload the IPA, use your mobile browser, or wait for spots to be cleared after the next app release.

**Comment by ruoti** [comment]
What is the reason this can't get published in the app store? Is it financial, technical, or something else? If technical, I'm happy to try and help out. If it is financial, I know I would be happy paying a one-time fee to gain access to the app, and I'm sure there are many others in that boat.

**Comment by nichwall** [comment]
Mostly technical. There are a lot more bugs on iOS than on Android because many of the contributors only use Android.

https://github.com/advplyr/audiobookshelf-app/issues/541

**Comment by maodelg** [comment]
Thanks for the hard work. Any way you can release some beta slots? Thanks!

**Comment by vdrover** [comment]
What bugs are the blockers for full iOS release? It seems that if you release officially, you will get a lot more users/testers for iOS, which will solve the problem you have of "most users being android".

**Comment by ruoti** [comment]
Closed, pending https://github.com/advplyr/audiobookshelf-app/issues/541

**Comment by arjur831** [comment]
Minecraft preview

**Comment by smccomics5-cyber** [comment]
Why😭🤞
