### ISSUE TITLE
Finished book stuck in continue listening

### ISSUE THREAD

**Issue by philhagger** [advplyr/audiobookshelf-app#931]
### Steps to reproduce

1. Finished book. 
2. Showing 100% and finished. 
3. Still showing in continue listening.  

### Expected behaviour
- When a book is finished it should drop off the continue listening quite. 

### Actual behaviour
- Completed book, showing finished and 100% stuck in continue listening. 

### Environment data

Audiobookshelf Version:
0.9.66-beta
- [x] iOS App?

Device model:
iPhone 14 Pro Max 
Stock or customized system:

#### iOS Issue
iOS Version: 17.0.3

![IMG_1842](https://github.com/advplyr/audiobookshelf-app/assets/739206/f2e3f277-76f3-42ec-b540-30297cdf247c)
![IMG_1841](https://github.com/advplyr/audiobookshelf-app/assets/739206/66924762-3148-47ae-9eb8-70501e5d9358)

**Comment by nichwall** [comment]
This is a bug with the iOS app incorrectly creating extra listening sessions. Have you downloaded the book for local listening on iOS or did you download this book before an update? The extra listening session can still happen on streamed books, but seems to be more common with downloaded books.

The below issue goes more in depth on what is happening, but reinstalling the iOS app may fix the bug for you.

You can also try to "Discard Progress" and then "Mark as Finished"

https://github.com/advplyr/audiobookshelf/issues/1983

**Comment by philhagger** [comment]
Ah that makes sense. 

I just discarded process then marked as complete and that kicked it out the continue list. 

Thanks for the solution.
