### ISSUE TITLE
Restore Android 6 support (seems to work fine w/ two line change)

### ISSUE THREAD

**Issue by spieden** [advplyr/audiobookshelf-app#934]
### Is your feature request related to a problem? Please describe.
I want to use cheap old Android phones as dedicated audiobook players

### Describe the solution you'd like
Android 6 support was dropped about a year back, seemingly when taking on an ffmpeg dep that supports it in an LTS version. Can we just use that version to get it back?

### Describe alternatives you've considered
Paying more for an Android 7 phone

**Comment by spieden** [comment]
Here's a PR: #935

**Comment by advplyr** [comment]
I've been thinking of moving in the opposite direction because ~99% of the active users are on Android 9 or up and we have to test these older android versions

**Comment by spieden** [comment]
Ahh too bad but makes sense I guess. It's nice for kids to be able to give them cheap single purpose devices like dedicated audio book players from old Android phones. That's what I'm doing and it's working really nicely from a build I did of the PR branch.

**Comment by spieden** [comment]
Maybe official support and testing could be dropped but the minimum API version could be lowered to allow installing official builds on Android 6? Anybody on an operating system that old has to expect some potential issues anyway.

I can try to keep the unofficial support going with PRs for as long as it makes sense.

**Comment by advplyr** [comment]
This isn't going to be supported, also commented in #935
