### ISSUE TITLE
Rename "Search" in podcast library

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf-app#936]
### Is your feature request related to a problem? Please describe.
Users are confused by the "Search" tab on the web client. https://github.com/advplyr/audiobookshelf/issues/2301
If that is changed, it should also be changed in the mobile apps since the "Search" tab does not search podcasts on the server.

### Describe the solution you'd like
Change the text to match the web app (if it is updated).

### Additional context
![image](https://github.com/advplyr/audiobookshelf-app/assets/5686638/48b184ba-45ec-4f15-8715-f7d5e03ea063)

**Comment by advplyr** [comment]
Updated in [v0.9.67-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.67-beta)
