### ISSUE TITLE
Opus title from OpenAI TTS won't play via the app

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf-app#938]
### Steps to reproduce

1. The title is in the library
2. I go and try to play the version created by the OpenAI "alloy" TTS voice
3. It refuses to play

### Expected behaviour
It should play

### Actual behaviour
Errors out but it does work if i go to the website via chrome desktop

### Environment data

ABS Log: https://pastebin.com/1PKgevDp

Audiobookshelf Version: 2.5.x

- [ ] Android App

#### Android Issue
Android version:

Device model:

Stock or customized system:

**Comment by advplyr** [comment]
I'm not seeing anything helpful in the logs. The actual audio file would have to be shared to debug this.

**Comment by iconoclasthero** [comment]
https://mega.nz/folder/AEQBQLZB#BitAgFQRIkO67JkBkv1QTA
the .2.opus is one I ran through ffmpeg with the sole option -acodec copy; it works in both the web client and the android client.
