### ISSUE TITLE
iOS 17.0.3 notch pushes icons and covers up UI - iPhone 12

### ISSUE THREAD

**Issue by mdeeter** [advplyr/audiobookshelf-app#939]
iPhone 12 Pro - iOS 17.0.3

Audiobookshelf Version:  0.9.66

- [ ] Android App?
- [x] iOS App?

![image](https://github.com/advplyr/audiobookshelf-app/assets/136902/f22db758-6a8e-4a74-b572-508954ee0d40)

![image](https://github.com/advplyr/audiobookshelf-app/assets/136902/e73b610a-1127-460e-ba29-d6ef4557de5a)

**Comment by mdeeter** [comment]
So..... after a hard-close of the app and re-opening... the app looks correct now.

**Comment by advplyr** [comment]
I think someone mentioned an issue with the ereader and the status bar at the top. Don't remember exactly but something to look out for if you see this again.
