### ISSUE TITLE
Tags are missing from search

### ISSUE THREAD

**Issue by danielbeaver** [advplyr/audiobookshelf-app#940]
Tags are currently missing from searches in the Android app:
![Screenshot_20231115_112638_audiobookshelf](https://github.com/advplyr/audiobookshelf-app/assets/844664/3f94ede5-2599-4ad6-a5ff-31d769701e17)

The web server browser version does currently seamlessly search for tags when doing a search:
![image](https://github.com/advplyr/audiobookshelf-app/assets/844664/d6cc3fd6-e231-42cd-850d-0e8ca4be3e87)

It would be useful to see to see tags in searches in the apps

**Comment by advplyr** [comment]
Added in [v0.9.67-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.67-beta)
