### ISSUE TITLE
Android Playback laggs if Phone is locked

### ISSUE THREAD

**Issue by PercyJW-2** [advplyr/audiobookshelf-app#941]
### Steps to reproduce

1. Start playback
2. lock phone

### Expected behaviour
- Normal playback

### Actual behaviour
- Laggy playback

### Environment data

Audiobookshelf Version: 0.9.66-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 10

Device model: OnePlus 5T

Stock or customized system: Stock

(Energy optimization is already deactivated)

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Are you streaming or playing a downloaded book?

Can you test on both a download and stream?

**Comment by PercyJW-2** [comment]
I tried both, and it laggs every time. I'll try reinstalling

**Comment by advplyr** [comment]
I think I have seen this mentioned before and it was specific to streaming or downloaded I can't remember. If you can double check that

**Comment by PercyJW-2** [comment]
After reinstallation it works again
