### ISSUE TITLE
[Bug]: iOS App loses position

### ISSUE THREAD

**Issue by woolmonkey** [advplyr/audiobookshelf-app#942]
### Describe the issue

The iOS app has completly lost all position of the book, ig goes back to having nothing being listened to.  I have also have had it go back to a previous random listening point. 

### Steps to reproduce the issue

1. I believe this has happened when listening offline. But I am not sure what caused it as it seems random.

### Audiobookshelf version

2.5.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Make sure to update to the latest iOS released today v0.9.67-beta. Some info was added to the book page for downloaded books that will tell you if you are linked to the correct server
