### ISSUE TITLE
Android - Google Maps Driving Mode - Skip forward/Back 10s buttons changes tracks instead

### ISSUE THREAD

**Issue by mr-ransel** [advplyr/audiobookshelf-app#943]
### Steps to reproduce

Note, this is running locally on the phone screen, not a separate android auto head unit.

0. Have the current progress in a book, currently somewhere in track 2 or greater
1. Launch google maps, and start driving directions going somewhere
2. Go to the app selection in the bottom right (grid of 4 squares)
3. Select Audiobookshelf
4. Select the book from step #0.
5. Use the skip forward/back 10/30 seconds buttons

### Expected behaviour
- Skip ahead or back by 10 seconds on the current audio track

### Actual behaviour
- Sometimes (I'm not sure what the deciding circumstance is) instead of skipping back 10 seconds, it will set the current track to track 1, and the current timestamp to "10 seconds earlier than the timestamp you were at" on whatever track you were listening to before it changed tracks
- It may correlate to when you are connected/not connected to the upstream server and listening to local content, I'll update this report if I can isolate the circumstances further

### Environment data

Audiobookshelf Version: 0.9.67-beta

Android App

#### Android Issue
Android version: 14

Device model: Pixel 6

Stock or customized system: Stock

**Comment by nichwall** [comment]
Sounds like https://github.com/advplyr/audiobookshelf-app/issues/894
The fix may have not made it to Android Auto if it's the same thing

**Comment by mr-ransel** [comment]
Minor correction, this is specifically "Driving mode" in Google maps/Google Assistant, locally on the phone, not Android Auto (no car connected to the phone), but that logic tracks generally. I'll work on a more detailed repro next time I'm driving and it comes up.

**Comment by mr-ransel** [comment]
Google has deprecated this functionality in the Google Maps Driving mode, so this is no longer worth investigating.
