### ISSUE TITLE
Downloaded audiobook says progress will not be synced

### ISSUE THREAD

**Issue by YodaDaCoda** [advplyr/audiobookshelf-app#945]
### Steps to reproduce

1. Download an audiobook and start listening 
3. Note that the page for the book says progress will not be synced
4. Login to the web application via browser and note that progress is still synced as the book continues playing

### Expected behaviour
- Progress should be synced, and there should not be a message saying progress will not be synced.

### Actual behaviour
- There is a message saying progress will not be synced, but progress is still synced.

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: OnePlus 9 5G

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

![Screenshot_2023-11-19-12-49-35-41_e9782661401ed6f222682e1e02b74bd4](https://github.com/advplyr/audiobookshelf-app/assets/365349/5d7a921b-89eb-4a02-b45a-9ca1e36e9643)

**Comment by nichwall** [comment]
Was this book downloaded before 0.9.67? Does redownloading the book fix the message?

**Comment by YodaDaCoda** [comment]
This book was downloaded with v0.9.66 but the issue persists with a book freshly downloaded with v0.9.67

![Screenshot_2023-11-19-14-04-11-33_e9782661401ed6f222682e1e02b74bd4](https://github.com/advplyr/audiobookshelf-app/assets/365349/638084c4-5545-4e2d-90a4-d9c487b18511)

**Comment by kucksdorfs** [comment]
I am on 0.9.6.7-beta (2.5.0 server) and I am getting that prompt on previously downloaded books and newly downloaded books. Progress appears to be retained.

Stock Android (motorola edge, android 11, security updates August 1 2022, Play System Updates October 1 2023), no root, app from Play Store.

**Comment by advplyr** [comment]
I just realized what this probably is. You setup your connection on server v2.2.23 or below before we switched to UUIDs. So the user id stored on your device is the old user id and no longer matches the new one on your server.

To fix this I suggest you logout on the device, delete your existing connection and create a new one. New downloads should show that they are correctly linked.

**Comment by kucksdorfs** [comment]
> To fix this I suggest you logout on the device, delete your existing connection and create a new one. New downloads should show that they are correctly linked.

So I am fine doing this, but will I think this is unrealistic if people have a lot of books downloaded. Or its "expensive" to download books (in terms of time for example).

**Comment by advplyr** [comment]
I can push up a fix in the next update. Progress will still be synced properly for all of those items because the server knows how to handle the old user ids. The main issue is that the alert is confusing and misleading.
I still recommend updating the server connection so you have the new UUIDs stored locally.

**Comment by advplyr** [comment]
Fixed in [v0.9.68-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.68-beta)

**Comment by bojtalepenye** [comment]
> I just realized what this probably is. You setup your connection on server v2.2.23 or below before we switched to UUIDs. So the user id stored on your device is the old user id and no longer matches the new one on your server.
> 
> To fix this I suggest you logout on the device, delete your existing connection and create a new one. New downloads should show that they are correctly linked.

Thank you, it is solved now
