### ISSUE TITLE
Cannot create property... error on switching server

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#947]
![Screenshot_2023-11-19-23-54-26-75_e9782661401ed6f222682e1e02b74bd4.jpg](https://github.com/advplyr/audiobookshelf-app/assets/42061703/f9ba0de4-67a0-484c-85ef-661d49e68724)

Following up from the previous issue.

I switched the server to internal and now I get this page.

**Comment by advplyr** [comment]
Is this for a downloaded book? Was the book downloaded a long time ago? What server version are you running?

**Comment by raviwarrier** [comment]
Yes, it's for a downloaded book. 
And I think your assumption is correct. It was a book I downloaded a while back and then did a clean install of the server to move to the latest image (via docker/portainer). It might be because of that.
I'll keep a look out for any other books that I have recently downloaded that throw a similar error. Until then, I realize that this issue is invalid. You can close it if you want.
