### ISSUE TITLE
@advplyr The download stucks, I have to kill the app and try again to make it work.

### ISSUE THREAD

**Issue by p6002** [advplyr/audiobookshelf-app#948]
### Describe the issue

              @advplyr The download stucks, I have to kill the app and try again to make it work. 
I looked in the logs now and it just says user requested download, there is no error. 
I would prefer, for example, the ability to mark several episodes for download, because there are often days that several episodes appear. The best if there was an option to automatically download files when they appear on the server.

<img width="520" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/74392057/12324d38-d32a-498e-8a73-fcf8cc1a769d">

_Originally posted by @p6002 in https://github.com/advplyr/audiobookshelf/issues/2303#issuecomment-1819646592_
            

### Steps to reproduce the issue

1. Open app.
2. Start downloading file

### Audiobookshelf version

latest

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you share the mobile app version you are using, the server version you are using, what device you are using and android/ios version

**Comment by p6002** [comment]
Mobile: 0.9.67-beta
Server:  v2.4.4
Device:  Unihertz Titan, Android 10

**Comment by advplyr** [comment]
Android 10 will most likely only work with internal storage. When you download are you selecting internal storage?

**Comment by p6002** [comment]
Yes, only internal, I do not use sd card.
For example, services like Navidrome and Symfonium apk work without problems. In general, I have never had problems with downloading on this device.

**Comment by advplyr** [comment]
Can you explain in more detail what is happening? Is the app crashing and closing out completely? Is it just staying stuck at a certain percentage?

**Comment by p6002** [comment]
It varies. Sometimes I turn on the download and it stops at 0%, and sometimes at a few %. When downloading several episodes at once, it always stops working, in the sense that the first file has, for example, 3% and the rest stalls.
https://streamable.com/n2m6z5

**Comment by advplyr** [comment]
Are you using a reverse proxy or are you connecting to your local ip address?

Have you tried leaving the device open for a few minutes without the percent changing? In the video you are only waiting a few seconds so I just want to make sure.

**Comment by p6002** [comment]
The download is interrupted after some time automatically, as you can see in the first screenshot (timeout).
Yes I use Nginx Proxy Manager as a reverse proxy.

**Comment by advplyr** [comment]
Can you test this without using your reverse proxy and connecting to Abs using your local ip addresss?
