### ISSUE TITLE
SSO broken in mobile

### ISSUE THREAD

**Issue by igor47** [advplyr/audiobookshelf-app#949]
### Steps to reproduce

1. set up a audiobookshelf server with SSO enabled
2. confirm you can log in with SSO into the web UI
3. add server to mobile app
4. use your "log in with SSO" button

### Expected behaviour
- I should log into the app

### Actual behaviour
- I get an error, like in this screenshot:
- 
![Screenshot_20231120-143211_audiobookshelf](https://github.com/advplyr/audiobookshelf-app/assets/200575/3f20b9ae-7528-4339-8347-86451e7a3436)

there seem to be two problems here:
- missing a `/` between my domain name `*.org` and the `auth` endpoint, so it looks like `orgauth` instead of `org/auth`
- that looks like an IP address in the error, but it doesn't seem to be any ip address i recognize -- not for any of my audiobookshelf server, my mobile device, or my openid auth server (i'm using authentik)

### Environment data

Audiobookshelf Version:

- [X] Android App?
- [ ] iOS App?

#### Android Issue

Device model: Asus Zenfone 8

Stock or customized system: Lineage

I am in the "early access" group via the play store, and using app version from nov 17th (looks like `0.9.67-beta`)

**Comment by igor47** [comment]
fyi @Sapd 

i tried adding a `/` at the end of my server name, but it seems stripped out automatically

i can log in using my username/password, bypassing SSO, and the app works fine then.

**Comment by advplyr** [comment]
I fixed this yesterday https://github.com/advplyr/audiobookshelf-app/commit/ef4d7ba1bf7f4bbd799af56c7599fb10dae4036a
It will only work if you build from source. Since that feature isn't available yet in the server release I'm going to close this out. Thanks for testing
