### ISSUE TITLE
Add option to delete local download when episode completed

### ISSUE THREAD

**Issue by jurgenhaas** [advplyr/audiobookshelf-app#952]
I'm downloading podcast episodes and audiobooks to my Android device, when chances are that I will be listening to them while on the road. That's to safe bandwidth while not on my local network.

Now, when I completely listened to a track, there is no need to still have a local copy of it. Cleaning up such episodes manually is time-consuming. Having an option in the settings such that the app cleans up automatically, would be much appreciated.

**Comment by advplyr** [comment]
Duplicate of #293
