### ISSUE TITLE
All podcasts displayed after selecting a local podcast

### ISSUE THREAD

**Issue by tonyedwardspz** [advplyr/audiobookshelf-app#954]
When connected to the server, clickling one of the local podcasts from a podcast library's home page takes me to the full list of podcasts episodes . . instead of limited to just the local ones. Disconnected works as expected.

### Steps to reproduce

1. Download podcasts to the Android app
2. Stay connected to the server
3. Open a local podcast series from from a podcasts library home page

### Expected behaviour
- Podcast series page opens with only downloaded episodes shown

### Actual behaviour
- Podcast series page opens with all episodes shown

### Environment data

Audiobookshelf Version:

- [x] Android App - v0.9.67-beta
- [ ] iOS App?

#### Android Issue
Android version: 14 (5th Nov Release)

Device model: Pixel 5

**Comment by advplyr** [comment]
This is intentional since there has been a lot of confusion over there being 2 different pages for the same media item. As long as you are connected to the same server that the item was downloaded from then that should show all episodes.
One possible solution is we could add a filter on that page to show only downloaded episodes.

**Comment by tonyedwardspz** [comment]
I can see that. A filter would be really useful 🙏, with being auto filtered from the local podcasts section ideal. 

I've been using the app to support an offline first consumption pattern with the server only availible on my home network. The local podcasts / books sections are where I listen to content from on mobile. I'm away from a connection to the server enough to warrent downloading items ahead of time, usually in bulk, and listening from there. But connected enough and listening directly to make toggling between the two connectivity states fairly inconvienient.

With the local podcasts section, this consumption pattern was super convienient and required zero extra effort.

**Comment by tonyedwardspz** [comment]
Added feature request #958
