### ISSUE TITLE
[bug] autopause rewinds a bit every pause which makes the app unusable with other apps that cause a lot of short pauses (i.e. google maps)

### ISSUE THREAD

**Issue by zombiehoffa** [advplyr/audiobookshelf-app#96]
### Steps to reproduce

1. Start an audio book playing over android auto
2. start google maps with a destination  that has a lot of turns/other reasons to pause audiobookshelf
3. arrive at your destination  and note you h ave made no progress, or in some cases actually gone backwards on your book progress

### Expected behaviour
- audiobookshelf should be much  more restricted in when it rewinds (i.e. only rewinding if the book has been paused for longer than a set amount of time, say 15 minutes). I don't need it to rewind whenever google maps interrupts for a few seconds to tell me to make a turn

### Actual behaviour
- Tell us what happens

### Environment data
android auto
Audiobookshelf Version: all of them, I am currently on 0.9.39-beta and it is doing it.

- [X ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 11 and 12

Device model: xiaomi redmi note 10, oneplus 8, but probably every single device.

Stock or customized system: both.

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
`v0.9.40-beta` is live on the play store where I extended the seek back time to 1 minute.
If the pause is less than 1 minute than seek back should not happen. Let me know how that goes.

**Comment by zombiehoffa** [comment]
That was a lot better. So far I haven't hit any spots where it rewinds in the car but I have only tested it for about a half hour.
