### ISSUE TITLE
[Enhancement]: Add a low feedback / notificaition setting

### ISSUE THREAD

**Issue by tonyedwardspz** [advplyr/audiobookshelf-app#966]
### Is your feature request related to a problem? Please describe.

I love this software. I've built an offline first content consumption pattern around it, and it was the starting point for my meandering through the world of self-hosted open source.

However I do have one gripe. 

It's always trying to tell me stuff. Lot's of stuff. It's great hearing about how awesome ABS is at getting things perfect every time. Well. Almost every time :)

For example, the toasts and confirmation dialogs can be a bit much when downloading lots of short podcast episodes in quick succession. The downloaded media link status is irrelevant, personally speaking. I can completely see why these things are in the app and are hugely useful to lot's of people.

Kinda an extension of #718.

### Describe the solution you'd like

Introduce a low feedback mode. 

After toggling the mode on through the "user interface settings" section of the settings menu, the following would happen:

- Download confirmation dialog for podcasts are skipped
- Download success toasts for podcast are disabled
- Ditto both the above for audiobooks
- Downloaded media link status on podcast pages are hidden

A [pull request](https://github.com/advplyr/audiobookshelf-app/pull/967) will be made shortly for a starter implementation of the above for Android. 

I can think of other things to add to the list, but wanted to get some input from others before going any further.

After using a more hacky version of the implementation (just delete all the things) for a few days, I'd describe my experience of using the app as calmer.

### Describe alternatives you've considered

Maintaining my own fork and getting stuck on an outdated version of everything at some point in the future.

I mean. I probably won't tbf.

### Additional context

In some ways, this is a great accessibility feature to have in the app.  Kinda related reading - [https://www.smashingmagazine.com/2020/09/design-reduced-motion-sensitivities/](https://www.smashingmagazine.com/2020/09/design-reduced-motion-sensitivities/)

**Comment by advplyr** [comment]
Added in [0.9.69-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.69-beta)
