### ISSUE TITLE
Playback speed not remembered after app is restarted 

### ISSUE THREAD

**Issue by mikiher** [advplyr/audiobookshelf-app#976]
### Steps to reproduce

1. Download a book to local media folder
2. Set a non-default playback speed
3. Close the app from the app switcher
4. Open the app again and play the book

### Expected behaviour
- Book is played with the set playback speed

### Actual behaviour
- Book is played with the default playback speed

### Environment data

Audiobookshelf Version: 0.9.68-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: Galaxy S21 Ultra

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
I was able to reproduce this so long as the initial server connection is being attempted. Once that either succeeds or fails then the playback speed is set.

**Comment by mikiher** [comment]
Yeah, I failed to mention that this happened while my server was down, so it could not connect to it.
Thanks for the quick fix!

**Comment by advplyr** [comment]
Fixed in [0.9.69-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.69-beta)
