### ISSUE TITLE
Volume boost/equalizer 

### ISSUE THREAD

**Issue by jtechguru1** [advplyr/audiobookshelf-app#977]
### Describe the solution you'd like.
A volume boost built into the application. With pitch and a few equalizer channels.

### Describe alternatives you've considered
I installed several different volume boosters that effect all apps. While this works to some degree, this app is literally the only one needing the boost. So when I switch apps, get notifications, or an incoming call the sound is distorted enough that I just revert back and deal without the distorted sound coming from everything else 

### Additional context
This is a feature many audiobook players have, but those players aren't synced to Audiobookshelf. So my progress wouldn't be tracked across devices.

**Comment by advplyr** [comment]
Duplicate of #195

**Comment by LGM47200** [comment]
UP !!

**Comment by scgf** [comment]
> UP !!

Do you mean the volume boost is available? How do you access it? I've downloaded the latest version of Audiobookshelf from Google Play and I can't see it.

EDIT: Ahh, I think you were just bumping this topic. I absolutely can't use Audiobookshelf without a volume boost function. Now I realise it hasn't been enabled, I'll re-retire my docker container and go back to Smart AudioBook Player.
