### ISSUE TITLE
WMA format book can't play as offline on Androind phone

### ISSUE THREAD

**Issue by wbhinspector** [advplyr/audiobookshelf-app#979]
### Steps to reproduce

1.create a new folder (abook) to verify the app got the correct permission.
![f17a0449451e52793b1adbc1ebcff3c](https://github.com/advplyr/audiobookshelf-app/assets/39436441/e367568f-4ec6-47eb-8391-a819ca689d58)

2. the book played as online well.
3.download the book, after finished, check the files were stored in the abook folder.
![c1b33742d667c2510446f8cde3da01e](https://github.com/advplyr/audiobookshelf-app/assets/39436441/039fd03d-4817-4a72-835d-e26060df7e7b)
![d20fae88c20767e6401834319da84b3](https://github.com/advplyr/audiobookshelf-app/assets/39436441/2add514d-3fa3-42a8-bbe1-b4ba449f7a14)
4. play this book as offline, can't play it.
![ba123ceb585ccea2a2ffa1c8fc3eaa7](https://github.com/advplyr/audiobookshelf-app/assets/39436441/ff26d6c6-3f28-4ee4-adf9-ee0cd051b729)

6. try download another mp3 format book. it can play offline well.

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### enhancement
- can we choose a part of files in a book to download, such as download all un-played files? thanks.

Audiobookshelf Version: 0.9.68-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model:Redmi K30 Ultra

Stock or customized system: MIUI 13 22.10.26

#### iOS Issue
iOS Version:

iPhone model:

**Comment by hobesman** [comment]
It's there a way to make the server transcode before transferring for download?

**Comment by advplyr** [comment]
No I put in an issue to better handle these errors in the client before coming out of beta https://github.com/advplyr/audiobookshelf-app/issues/968

We get these a lot and some of them (like this one) can be prevented because we know WMA is not supported on Android so we could show an alert when initially downloading.

**Comment by Darkblizzard21** [comment]
> Is there a way to make the server transcode before transferring for download?

This would need to be implemented on the server side first.
