### ISSUE TITLE
Open Library Last Accessed Rather than Same Library Each Time When Starting App

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf-app#98]
### Is your feature request related to a problem? Please describe.
I currently have 2 libraries on my server, one for audiobooks and one for eBooks. My audiobook library is called 'Main', and my eBook library is called 'eBooks'. 

Each time I open the android app, it always opens to my eBooks library, rather than my 'Main' (Audiobooks) library, which is what I listen to 99.99% of the time I use the app. This means that I constantly need to select a different library every time I open the app. 

### Describe the solution you'd like
Have the app save the last library accessed and open that library when the app is opened (so if I close the app with the main library open, when I open the app, the main library is remebered and opens right to that). 

### Describe alternatives you've considered
None

### Additional context
I think that this may be because the libraries are opened in alphabetical order (hence the 'eBooks' library is higher in the pecking order, so to speak, rather than my 'Main' library. I have a separate bug that I opened as I'm unable to rename the 'Main' library to 'Audiobooks' ([see here](https://github.com/advplyr/audiobookshelf/issues/350)).

**Comment by advplyr** [comment]
I agree the last library should be saved, but what order do you have the libraries? 
It is not alphabetical, the libraries can be dragged into whatever order you would like. It should open up to the first library.

**Comment by feerlessleadr** [comment]
so on the web, my libraries are ordered 'Main' then 'eBooks' - however, in the app, eBooks is listed first (I don't see a way to re-order in the android app).

**Comment by advplyr** [comment]
Can you try dragging the eBooks library to the first spot, refreshing and make sure it is on top in the web app. Then dragging the Main back to the first spot.

**Comment by feerlessleadr** [comment]
So I dragged eBooks to the top, refreshed and it was still at the top. I also restarted the server and eBooks stayed at the top. I then switched Main back to the top, refreshed the server, and it was at the top. However, in the Android app, eBooks was still listed first (and was the library that opened first). 

I then restarted the server and the same thing happened in the app (eBooks listed first).

**Comment by jcrmit** [comment]
I can confirm this issue for me as well. I have three - all audiobook, but I am transitioning to a new consolidated collection - so have main; transition; old - in this order. It always defaults to the transition library - tried reording and refreshing but this didn't help.

**Comment by jcrmit** [comment]
I put the main library to the bottom - restarted the container - web defaults to Main - app defaults to 'Transition'. :)

**Comment by advplyr** [comment]
The latest release should handle libraries properly
