### ISSUE TITLE
Hide chapter counter for numbered chapters

### ISSUE THREAD

**Issue by SkippyTheMonkeyKeeper** [advplyr/audiobookshelf-app#981]
### Is your feature request related to a problem? Please describe.
I'm currently listening to a book with chapters named like this: 
```
Opening Credits
1. Intro
3. First Steps
etc... 
```

Now when I click to view the chapters when listening to this audiobook I'm seeing the following: 
```
1 - Opening Credits
2 - 1. Intro
3 - 2. First Steps
etc...
```

### Describe the solution you'd like
Would it be possible to add an option to hide the chapter counter (I think globally in app)? So when I open the chapter list I will only see:
```
Opening Credits
1. Intro
3. First Steps
etc... 
```
Alternatively it could be disabled conditionally, but I'm not sure how easy this would be to achieve since not all chapter names use the numerical form for chapter numbering plus it would also have to account for different languages.

**Comment by advplyr** [comment]
The chapter number was already removed in the web client so I removed it to match

**Comment by advplyr** [comment]
Updated in [0.9.69-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.69-beta)
