### ISSUE TITLE
(added but broken) Add ability to remove an item from playlist on the playlists page

### ISSUE THREAD

**Issue by mdeeter** [advplyr/audiobookshelf-app#987]
You can delete a book from a playlist on the web:
![image](https://github.com/advplyr/audiobookshelf-app/assets/136902/d560a75e-f1b4-43dc-a5d8-2f568e30a806)

it'd be nice to have this same functionality in the item menu on the apps...
here:
![image](https://github.com/advplyr/audiobookshelf-app/assets/136902/478731f4-03de-4d7d-8a0d-b72e48a66a8e)

**Comment by hobesman** [comment]
FYI the functionality is there. But the labels are misleading. If you tap add to playlist, you can also remove from a playlist on the screen that opens.

**Comment by advplyr** [comment]
I added it to the context menu in 0.9.73-beta but it only works in dev. I just fixed it for the next release

**Comment by advplyr** [comment]
Fixed in [v0.9.74-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.74-beta)
