### ISSUE TITLE
Collapse series in library

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf-app#99]
Collapse series as seen here [#322](https://github.com/advplyr/audiobookshelf/issues/322)

**Comment by Budlyte** [comment]
I like it, but lmao did this really just create a Series View that collapses into a single cover instead of the stacked view that the Series tab does?  It does work great, and adds yet another alternate view when using square cards.  Neat feature, even if I think it was a bit silly to do.    :P

**Comment by SeriousPat** [comment]
plz implement it :*

**Comment by advplyr** [comment]
Added in [v0.9.63-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.63-beta)
