### ISSUE TITLE
[Android 0.9.69-beta] Load indicator blocks playback for locally downloaded audiobooks if not connected to server

### ISSUE THREAD

**Issue by Salvoxia** [advplyr/audiobookshelf-app#990]
Just updated to 0.9.69-beta on Android and encountered this issue while not conntected to my server.

### Steps to reproduce

1. Update to 0.9.69-beta
2. Open Audiobookshelf while the ABS server is not reachable (server down, different network, ...)
2a. Optionally: Disconnect from server if connected after ABS startup by opening the menu, selecting "Switch Server/User", then selecting "back" on the server selection screen
3. Open a locally downloaded audiobook

### Expected behaviour
- Play button should be available, since the audiobook was downloaded locally

### Actual behaviour
- Loading indicator is shown on the "Play" button indefinitely, playback cannot be started
- The device seems to get warm to the touch when keeping this view open for a prolonged time
![image](https://github.com/advplyr/audiobookshelf-app/assets/6501566/7b4e68cb-19d8-468f-afeb-d3f2b4e31f57)

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: Samsung Galaxy S20 (SM-G980F/DS)

Stock or customized system: Stock Android

**Comment by advplyr** [comment]
Fixed in [0.9.70-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.70-beta)
