### ISSUE TITLE
Download progress stays at 0%

### ISSUE THREAD

**Issue by sarg3nt** [advplyr/audiobookshelf-app#992]
### Steps to reproduce

1. Download a book
2. Progress never changes from 0%

### Expected behaviour
- Progress should smoothly update as the download progresses.

### Actual behaviour
- Progress stays at 0% the entire time.

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [X] iOS App?  0.9.70

Server is 2.6.0 and is hosted in Docker behind a local reverse proxy and Cloudflare cache.  If this is a "me" thing then maybe it's a problem with my setup. Reverse proxy, etc.  Any idea what I may need to open?

#### iOS Issue
iOS Version: 
17.2
iPhone model:
15 Pro Max

My Audiobooks consist of a single file.

**Comment by advplyr** [comment]
Can you test this without your reverse proxy? That could eliminate that possibility.

You can also check the server logs that should show a request has been made to download a file.

**Comment by sarg3nt** [comment]
Apologies for the late reply. 
I remembered this bug today and had some time to figure it out, which I did, so I'm leaving this here in case others run into this.
I'm using Traefik as a reverse proxy for the Docker container and it was the gzip middleware that was causing the issue.  Turning off gzip fixed it for me. 
I don't know why that would only break the download percentage counter, but it did.
