### ISSUE TITLE
Downloaded marker overlaps with series part number

### ISSUE THREAD

**Issue by mxsrm** [advplyr/audiobookshelf-app#996]
### Steps to reproduce

1. Have series
2. Download one of the books in that series

### Actual behaviour

See screenshot attached. The marker for “downloaded audiobook” overlaps with the series part number (e.g. part 3, 3.5 or 4). Maybe place the marker on the top left instead of the top right?

### Environment data

Audiobookshelf Version:

Android v0.9.70-beta
Server v2.6.0

#### Android Issue
Android version: 14, December update

Device model: Pixel 8 Pro

![Screenshot_20231220-203354](https://github.com/advplyr/audiobookshelf-app/assets/7951225/e7e2d906-4019-48d4-a66d-bdbca43d702c)

**Comment by advplyr** [comment]
Fixed in [v0.9.71-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.71-beta)
