### ISSUE TITLE
[iOS] "Clear Filter" button intersecting the notch at the top of the screen

### ISSUE THREAD

**Issue by johnpyp** [advplyr/audiobookshelf-app#999]
### Steps to reproduce

1. Set a filter on the library page
2. Click the newly activated filter, which should now have a "Clear Filter" button

### Expected behaviour
- "Clear filter" button doesn't overlap the notch / dynamic island.

### Actual behaviour
- "Clear filter" button overlaps the notch / dynamic island. Looks very much out of place.

This screenshot doesn't contain the notch so it isn't apparent, but the corner of the button is hidden in reality. It's also just all the way at the top of the screen, needs some padding :)

![image](https://github.com/advplyr/audiobookshelf-app/assets/20625636/adf4408d-6505-4be5-9257-ad91066c106b)

### Environment data

Audiobookshelf Version: 0.9.70-beta

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 17.1.2

iPhone model: iPhone 15 Pro

**Comment by advplyr** [comment]
Fixed in [v0.9.71-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.71-beta)
